### ISSUE TITLE
Catppuccin Theme

### ISSUE THREAD

**Issue by Stetsed** [end-4/dots-hyprland#1]
Good evening,

I love your theme and specifically the bar and everything, if I where wanting to turn this into a catppuccin theme how would I do that? I'm not sure what I would want to modify to do this.

**Comment by Stetsed** [comment]
Also as I mentioned in my reddit comment I want to know if your accepting PR's for implementing features that might be nice, such as dynamic resolution as right now you have to configure that manually.

**Comment by Stetsed** [comment]
Okay so I don't know what I did... I changed the colors inside of css/_colors.scss, then I bricked something so I changed it back and now the calendar still has my colors

**Comment by end-4** [comment]
Hi there!
# Change theme
## Explanation
- For eww, if you take a look at `colormanage` in the `scripts` folder, for color profiles, they are _(painfully)_ stored in 3 files: `css/_iconcolor_THEMENAME.txt`, `css/_colorscheme_THEMENAME.scss`, `css/_material_THEMENAME.scss`. It then runs the `applycolor` scripts which copies all SVGs from `images/svg/dark/` `images/svg/` then `sed`s all the "white" in those icons to the colors defined in `css/_iconcolor_THEMENAME.txt`
## What you should do
- Manually change those 3 files
- open the overview, type `>save YOUR_THEME_NAME` 
- do that again, but this time type `>load YOUR_THEME_NAME`

**Comment by end-4** [comment]
I have to say sorry for how this system might be easy-to-code and unorganized

At first i just wanted to have something that works so the system sucks a bit

About PRs, sure! I'd be really happy if you could in any way improve stuff. The css currently uses pixels, so it might be a lot of work to make things friendly with different monitors other than 1920x1080.

**Comment by Stetsed** [comment]
I olready found that the bar situtation can be fixed very easily with using xrandr to get the resolution(olready have a prototype of this working), and I do see that some of the bars are pixel aligned so I need to find away around that. But no worries.. I've dealt with worse tbh

**Comment by Stetsed** [comment]
I'll make PR's in small bits btw to make it easier to say "This I do want this I don't"
