### ISSUE TITLE
windoes - not showing icons

### ISSUE THREAD

**Issue by D3vil0p3r** [end-4/dots-hyprland#10]
Hey mate. I'm testing Windoes branch. It seems all set in the right manner, the only problem is that I don't see the icons on the Windows bar and either when I click on Windows logo button on the Windows bar. I also rebooted. Is there something I'm missing?
![image](https://github.com/end-4/dots-hyprland/assets/83867734/1be28c30-327d-4662-ad60-578b062d9fc2)

**Comment by end-4** [comment]
Hi there,
- Make sure you copied the icon pack to `/usr/share/icons` (it **is** necessary to copy there, not your local icon folder)
- Delete all files in `~/.config/eww/scripts/cache/`
- Open the start menu and wait 10 seconds for it to generate cache
- Restart eww. now icons should show properly

**Comment by D3vil0p3r** [comment]
Where is the icon pack?

**Comment by end-4** [comment]
in the `.local/share/icons` folder of the repo
or you can google "win11 icons pling"

**Comment by D3vil0p3r** [comment]
In `.local/share/icons` folder of the Windoes branch there are only Bibata and candy-icons. I see the Win11 and Win11-dark are in the main branch. Maybe they should be replicated also on Windoes branch.

Btw now I test your suggestion and I see what happens.

**Comment by end-4** [comment]
alright...
https://github.com/end-4/dots-hyprland/commit/588458946958b21535048b87dc180f114c862b66

**Comment by D3vil0p3r** [comment]
Y, now the icons seem to work. I have just two last questions related to Windoes:
1- In the Win11 start button, if I click on any application (File Explorer, Notepad, and so on) nothing happens. Is it expected? Is it possible to connect each one of them to a real application (for example File Explorer to Thunar, Notepad to Gedit or Codium, and so on)?
2- Windoes is a dark theme, but it seems that the system-theme configured in your Hyprland configuration is light. Indeed, if you open an application like Firefox and go to Settings -> Addons & Themes, and set the theme as "System theme - auto", it recognizes that the environment uses light theme and apply this one instead of dark theme. Is there a way to set the dark theme at system-level in Hyprland config?

**Comment by end-4** [comment]
1. Yes, the taskbar is configured using a json. See [.config/eww/modules/taskbar.json](https://github.com/end-4/dots-hyprland/blob/windoes/.config/eww/modules/taskbar.json)
- Just ignore the "address" and "workspace" fields. 
- "count" should be 0
- "class" is the class name of the window of that app (check with `hyprctl clients`). Setting this field correctly will make the taskbar function properly without duplicate icons. (If you want the button to be a launcher, set that value wrong)
- "icon" and "exec" are self-explanatory
2. Do you mean GTK settings? I'll review that after this.
3. Nope. I tried to achieve that but Hypr has a lot of missing features so i quit lol.

**Comment by T-Crypt** [comment]
You could use g setting in the hyprland.conf to set the GTK theme and GTK icons. 

I can do a PR to this. 

I'm also having issues with getting the icons to work properly. I have them in /usr/share/icons and set them as the base GTK icon theme. They populate for the first open and then they go blank after closing and opening start again.

**Comment by end-4** [comment]
I'm closing this as I will no longer be supporting EWW-powered setups
