### ISSUE TITLE
[Issue] Transparency around drop-down menu edges

### ISSUE THREAD

**Issue by PlexILIghT** [end-4/dots-hyprland#1000]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro:  Endeavor Arch-based

---
## The issue
The blur, the opacity works fine in the whole desktop. But when it comes to right-clicks, damn. There are unblurred additional edges that i think are meant to be drawn as shadows after the app is rendered, but instead it's shadows over blurred desktop wallpaper. Didn't find the solution neither at github.io nor other issues. I don't know what and where went wrong. 

Image is from brave.
For another example, in Telegram, there's like one frame of it showing that the xray is happening and then telegram menu draws over it, covering the whole void.
<details>
No logs.
<summary>Images</summary>

![Brave](https://github.com/user-attachments/assets/3c2c42f7-18c2-45b4-912d-61ccb5d6112d)

</details>

**Comment by fern-end-o** [comment]
Have you tried adding application rules to your configuration?
https://wiki.hyprland.org/Configuring/Window-Rules/

You can find the application class using
`hyprctl clients`

Then add a windowrule to disable blur/border/shadow. 
I face the same problem regarding Xdg-desktop-portal-gtk

**Comment by PlexILIghT** [comment]
Trying this rn. What I've accomplished so far is filter those "windows" with windowrule
```windowrulev2 = noblur,floating:1```
But this means it will also apply to every floating. I managed to get description of this window with
```sleep 3; hyprctl clients``` 
But what I got is a bit depressing (part of output, to show parent window - Brave, and its child - the _____), because there's almost no info to distinct it from another windows:
```plain
Window 62ae55826d50 -> Window Rules – Hyprland Wiki - Brave:
	mapped: 1
	hidden: 0
	at: 3,43
	size: 730,2114
	workspace: 3 (3)
	floating: 0
	pseudo: 0
	monitor: 0
	class: Brave-browser
	title: Window Rules – Hyprland Wiki - Brave
	initialClass: Brave-browser
	initialTitle: Window Rules – Hyprland Wiki - Brave
	pid: 1571
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 0
	inhibitingIdle: 0

Window 62ae5384a910 -> :
	mapped: 1
	hidden: 0
	at: 581,1142
	size: 522,601
	workspace: 3 (3)
	floating: 1
	pseudo: 0
	monitor: 0
	class: 
	title: 
	initialClass: 
	initialTitle: 
	pid: 1571
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 8
	inhibitingIdle: 0
```
Well, maybe I could add a rule for Brave to add dynamic tag to every window it opens, but will it work as inteded first try - I don't know. I will continue working on this later.

**Comment by PlexILIghT** [comment]
Well, I realized I don't need to go further cuz I like the looks I got for transparent windows, so the solution for me was adding
```windowrulev2 = noblur,floating:1```
to rules.conf (~/.config/hypr/custom/rules.conf).
