### ISSUE TITLE
[Issue] Installing `illogical-impulse-microtex-git` fails. Missing module `gtksourceviewmm-3.0`.

### ISSUE THREAD

**Issue by sigurd4** [end-4/dots-hyprland#1001]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
   - (...except for the package that failed to install.)
- Linux distro: Arch Linux x86_64

---
## The issue

Installing `illogical-impulse-microtex-git` fails because it can't find module `gtksourceviewmm-3.0`.

I have `gtksourceviewmm` installed, but `gtksourceviewmm-3.0` does not exist in the package repos.

<details>

<summary>
Logs
</summary>

```plain
-- Checking for module 'gtksourceviewmm-3.0'
--   Package 'gtksourceviewmm-3.0' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - gtksourceviewmm-3.0

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  CMakeLists.txt:215 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
    Aborting...
```

</details>

**Comment by PlexILIghT** [comment]
Same thing. Despite that I was able to install the dots successfully on one machine. The other machine however is throwing errors while starting hyprland

**Comment by Artfill008** [comment]
[#955](https://github.com/end-4/dots-hyprland/issues/955#issuecomment-2486579754)

**Comment by sigurd4** [comment]
Thanks. installing it manually resolved the missing dependency.
