### ISSUE TITLE
powerview not showing icons and geticons reporting wrong theme

### ISSUE THREAD

**Issue by Dialgatrainer02** [end-4/dots-hyprland#101]
- **I have read the instructions** and I have a problem with branch: novelknock
---
## The issue
i installed a theme manually then i uninstalled it but geticons still reports it as the curent theme regardless of gtk/qt themes used or icons packs. i cant find much documentation on how to change it and i think its screwing up powerview icons

- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)

[geticons-L.txt](https://github.com/end-4/dots-hyprland/files/13186239/geticons-L.txt)

[geticons-U.txt](https://github.com/end-4/dots-hyprland/files/13186241/geticons-U.txt)

**Comment by end-4** [comment]
looks like a geticons problem
geticons -L just segfaults for me

**Comment by Dialgatrainer02** [comment]
i sent a message to the geticons dev asking for help on how to change the theme idk why its segfualting tho

**Comment by end-4** [comment]
I've switched to using AGS instead of EWW, and can no longer support configs that use the latter, so I'm closing this issue.
The new widget system is cleaner and doesn't have an icon problem like this.
