### ISSUE TITLE
[Issue] The colors.conf issue😮‍💨

### ISSUE THREAD

**Issue by PlexILIghT** [end-4/dots-hyprland#1013]
- Yes. I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- Yes. I have made sure that both my config and system packages are up to date
- And I already made sure that everything is installed.
- Linux distro: Arch

---
## The issue
Before the whole thing - can running update-dots.sh resolve the problem? bring it to the "factory settings"? If so, then the half-decent solution is present. To the issue:
Was on my chill non-error streak with these dotfiles, then pressed the "Transparency" setting for the third installation of the dotfiles. But! Now it DOESN'T fix with setting a wallpaper or changing in
```/home/u200b/.config/ags/scss/main.scss```
this line:
```@import 'material';```
to this:
```@import './fallback/material';```
Well. The bar is showing on the other display and everything else. But the colors are not passing to some variables in colors.conf so I have either an error or not working feature if I comment out the colors.
btw wallpaper on other display is now stretching and filling space below with one line of pixels from bottom of picture across the whole screen.

 I don't what's wrong here, either that the module is missing (well, obviously, but is this what's causing the whole problem), either it's the gradiance thing. Idk how the managing happens, sorry. 

<details>
<summary>Logs</summary>

```plain
Config error in file /hnome/u200b/.config/hypr/hyprland/colors.conf at line 4: Error parsing gradient rgba({{ $onSurface }}39): failed to parse }}39) as a color

Config error in file /hnome/u200b/.config/hypr/hyprland/colors.conf at line 5: Error parsing gradient rgba({{ $outline }}30): failed to parse }}30) as a color

Config error in file /hnome/u200b/.config/hypr/hyprland/colors.conf at line 9: rgba() expects length of 8 characters (4 bytes) or 4 comma separated values

Config error in file /hnome/u200b/.config/hypr/hyprland.conf at line 9: Config error in file /home/u200b/.config/hypr/hyprland/colors.conf at line 4: Error parsing gradient rgba({{ $onSurface }}39): failed to parse }}39) as a color
Config error in file /hnome/u200b/.config/hypr/hyprland/colors.conf at line 5: Error parsing gradient rgba({{ $outline }}30): failed to parse }}30) as a color

(1 more..))
```

```plain
pkill ags; ags
```
### skipped
```plain
Traceback (most recent call last):
  File "/home/u200b/.config/ags/scripts/color_generation/generate_colors_material.py", line 6, in <module>
    from materialyoucolor.quantize import QuantizeCelebi
ModuleNotFoundError: No module named 'materialyoucolor'
Traceback (most recent call last):
  File "/home/u200b/.config/ags/scripts/color_generation/generate_colors_material.py", line 6, in <module>
    from materialyoucolor.quantize import QuantizeCelebi
ModuleNotFoundError: No module named 'materialyoucolor'
Traceback (most recent call last):
  File "/home/u200b/.config/ags/scripts/color_generation/generate_colors_material.py", line 6, in <module>
    from materialyoucolor.quantize import QuantizeCelebi
ModuleNotFoundError: No module named 'materialyoucolor'
Traceback (most recent call last):
  File "/home/u200b/.config/ags/scripts/color_generation/generate_colors_material.py", line 6, in <module>
    from materialyoucolor.quantize import QuantizeCelebi
ModuleNotFoundError: No module named 'materialyoucolor'
```
```plain
yay materialyoucolor
1 aur/python-materialyoucolor-git 2.0.8.r1.g9780c78-3 (+2 0.57) (Installed: 2.0.9.r3.g85099ce-1)
    Material You color algorithms for Python!
```

</details>

**Comment by PlexILIghT** [comment]
I replaced variables with HEX for now. Didn't manage to get materialyoucolor to get seen by python running the scripts.

**Comment by PlexILIghT** [comment]
I MANAGED TO FIX THIS.
So. The deal is the python-materialcolor.
As I have two pythons installed on my system:
One is 3.12, I think it was preinstalled (Is not being detected by packages ¯\_(ツ)_/¯)
Second is 3.13.1, later installed with the pacman.

Next steps is for your system default python (consider checking with ```python --version````. (no need to do something specific, just check your pythons in usr/lib)
<Summary>The Solution</Summary>
What I did is downloaded the package with
```sh
yay -G python-materialyoucolor-git
```
Then
```cd python-materialyoucolor-git/```
Make package with:
```makepkg -si```
DONE.

Now set a wallpaper and everything should. Consider doing the steps before this comment for the whole setup to work. It will not work (work partially) if you don't edit the ```@import 'material';``` line.
I am now testing if everything now works flawlessly.

**Comment by PlexILIghT** [comment]
Closing the issue. Errors now fixed. Except now whole ags stuff is stuck at one theme. Damn it

**Comment by FixeQyt** [comment]
Just comment 3-10 line bro (Temporary fix), and don't change the wallpaper or this setting in effects

**Comment by PlexILIghT** [comment]
> Your solution didn't worked for me (This "reinstalling" material theme) Just comment 3-10 line and edit `@import 'material';` bro (Temporary fix), and don't change the wallpaper or this setting in effects

Yes, installing materialyoucolors don't help if you have only one python installed, so then the package gets into the same python as your dots are using, then my solution does nothing. But that helped me not get the error after changing settings related to gradience on both my machines. Except now ags doesn't change color scheme except for foot, but that is another topic.

**Comment by clsty** [comment]
Note: The fix here is outdated. We're using python virtual environment.

https://github.com/end-4/dots-hyprland/issues/1136#issuecomment-2688062789
