### ISSUE TITLE
where's the dashboard script? i am not able to find it, is it eww? if not where's it and if it is again where is it...

### ISSUE THREAD

**Issue by daUnknownCoder** [end-4/dots-hyprland#104]
- **I have read the instructions** and I have a problem with branch: hybrid [hyprland dotfiles]
---

## The issue
- (describe your problem here)
- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)
aaint able to find the dashboard

**Comment by end-4** [comment]
either hit Super+A or run [`~/.config/eww/scripts/toggle-dashfs.sh`](https://github.com/end-4/dots-hyprland/blob/hybrid/.config/eww/scripts/toggle-dashfs.sh)

**Comment by daUnknownCoder** [comment]
> either hit Super+A or run [`~/.config/eww/scripts/toggle-dashfs.sh`](https://github.com/end-4/dots-hyprland/blob/hybrid/.config/eww/scripts/toggle-dashfs.sh)

thanks...
