### ISSUE TITLE
Changes made in appearance tab do not take effect. Wallpaper change only possible with swww. Color scheme doesn't change.

### ISSUE THREAD

**Issue by r3quie** [end-4/dots-hyprland#105]
- **I have read the instructions** and I have a problem with branch: illogical_impulse
---
## The issue
- Installed about a day ago. Everything works more or less as expected except wallpaper changes and theme changes.
- Color scheme doesn't react to change in wallpaper (which is only possible using `swww img`).
- Appearance tab in setting doesn't work at all. Can't change theme from dark to light, nor the background. No wallpaper when I installed (black).
- Also can't change volume using fn; brightness works though.
- No errors thrown that I noticed

EDIT:
just noticed icons do not work either, Files is using icons from my previous KDE install. Wonder if KDE is the source of these problems.

**Comment by end-4** [comment]
- Press `Ctrl`+`Super`+`T` and pick a wallpaper. That's how you're supposed to generate a colorscheme.
- What appearance tab? I don't have such a thing. Do you mean in GNOME Control Center? That won't work.
- Can't change volume using Fn keys: I'm not sure about that.. Does running `wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+` work?
- Icons follow your icon theme, so yes, it is the same as what you used before. If you want squircle icons like in my screenshot, get this icon pack: [OneUI4](https://github.com/mjkim0727/OneUI4-Icons)

**Comment by r3quie** [comment]
- Oh my bad, must have missed that in the keybinds. Works perfectly.
- Right, never used gnome so I thought it was your thing, sorry hah.
- Running the command returns "Translate ID error: '-1' is not a valid ID (returned by default-nodes-api)."
- Alright, thanks.
