### ISSUE TITLE
um weird eww things idk why

### ISSUE THREAD

**Issue by daUnknownCoder** [end-4/dots-hyprland#106]
- **I have read the instructions** and I have a problem with branch: hybrid
---
## The issue
- (describe your problem here)
- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)

![image](https://github.com/end-4/dots-hyprland/assets/84800625/b502f19e-6961-47b9-801c-baf3400bfb30) --> eww open bar
![image](https://github.com/end-4/dots-hyprland/assets/84800625/d092ec64-506d-45e4-996a-f33e0f333c0d) --> toggledashfs.sh
![image](https://github.com/end-4/dots-hyprland/assets/84800625/7f4bd1fe-64c7-45fd-84c6-a47cd7c4ba21) --> eww open dashboard
after clicking outside of above img down comes...
![image](https://github.com/end-4/dots-hyprland/assets/84800625/145d3e2d-43e7-48b5-bb84-0de17db6dac8)
![image](https://github.com/end-4/dots-hyprland/assets/84800625/7a9f6a74-5a62-4c64-ad68-41e9e3e7780e) --> eww open wingamebar
![image](https://github.com/end-4/dots-hyprland/assets/84800625/424b7ffd-36ed-4942-9563-dec8e616f985) --> eww open calendar
![image](https://github.com/end-4/dots-hyprland/assets/84800625/4991fa0c-2d00-47b7-a887-0d0f4505f4e0) --> eww open winbar

tried decreasing the font size for general from `Torus` to `Fira Code` and `Material Rounded Icons` to `FontAwesome` but nothing works idk why, any help is appreciated...,

note: in branch hybrid, i downloaded only the eww folder if thats something...

idk why is this happening...

**Comment by end-4** [comment]
- the config will only work properly with 1920x1080 resolution
- install material symbols

**Comment by daUnknownCoder** [comment]
> * install material symbols rounded

how, arch package?,


> * the config will only work properly with 1920x1080 resolution
```bash
Screen 0: minimum 16 x 16, current 1366 x 768, maximum 32767 x 32767
eDP-1 connected 1366x768+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
```

so what edits do i hav to make?

**Comment by end-4** [comment]
- Package: It doesn't hurt searching a bit. Either use the Arch package or download the font manually from its repository and put in your fonts folder (`~/.local/share/fonts`)
- Screen: Your screen is smaller, so things won't fit on screen
  - If you *really* want it, you'll have to learn css and change every size value in `.config/eww/css` to make elements fit
  - That's a lot of work (8000 lines), and I don't have any plans to do this.
