### ISSUE TITLE
Can't change volume with Fn keys

### ISSUE THREAD

**Issue by r3quie** [end-4/dots-hyprland#107]
- **I have read the instructions** and I have a problem with branch: illogical_impulse
---
## The issue
- Fn + function keys do not change volume, brightness works though.
- Running `wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+` throws "Translate ID error: '-1' is not a valid ID (returned by default-nodes-api)."

**Comment by r3quie** [comment]
SOLUTION: reinstalled wireplumber

when I ran `wpctl status` it returned that no audio sinks are detected. Reinstalled wireplumber, works now idk

**Comment by bergentroll** [comment]
Or possibly just restart: `systemctl --user restart wireplumber.service`

**Comment by sellingsrud** [comment]
I have the same issue. I've tried reinstalling wireplumber as well as restarting the service to no avail.

Anyone have any other tips or tricks?
