### ISSUE TITLE
sideleft window not working in the illogical-impulse branch

### ISSUE THREAD

**Issue by akshitgaur2005** [end-4/dots-hyprland#109]
- **I have read the instructions** and I have a problem with branch: illogical-impulse
---
## The issue
As mentioned above, the sideleft window does not seem to work, neither by keybinding nor by running the command directly in the terminal.

Also thanks for making this beautiful rice. I was really enamored by the Windoes branch as I found it really beautiful but alas, it does not work. I am a beginner to ricing and have made only very minor modifications ever. Could you please tell how you learned to do it so well?

Also, why do you prefer ags over eww?

**Comment by end-4** [comment]
- oh, that sidebar is wip. i tried to make a clipboard widget but haven't figured out. 
- i learned by copying others' configs and modifying them. see the bottom of my main readme and you'll see two people with two configs which played a major role in my journey.
- ags vs eww? i'm lazy to type it all again so see [this comment](https://www.reddit.com/r/unixporn/comments/17j296c/comment/k72ohvp/?context=3) of mine on reddit
