### ISSUE TITLE
Spamming errors in logs

### ISSUE THREAD

**Issue by TheSunCat** [end-4/dots-hyprland#11]
Hi! I'm trying to use both the windoes and normal bar (toggle between both), and followed the installation guide. I noticed most of it works but some parts were broken, so I fixed what I could myself (happy to contribute back once I get it fully working). For example, the taskbar.cpp file segfaults if a window with an empty class is open, as it tries to open `./scripts/cache/` as a file and fails. Watching `eww logs`, I still see a ton of errors while the windoes bar is open. This is the most common one, which happens every time I change window focus:
```
 2023-06-09T17:54:43.015Z ERROR eww::error_handling_ctx > Error while updating UI after state change

Caused by:
    Couldn't upgrade reference, widget got deallocated
 2023-06-09T17:54:43.015Z ERROR eww::error_handling_ctx > Error while updating UI after state change

Caused by:
    Couldn't upgrade reference, widget got deallocated
 2023-06-09T17:54:43.015Z ERROR eww::error_handling_ctx > Error while updating UI after state change

Caused by:
    Couldn't upgrade reference, widget got deallocated
 2023-06-09T17:54:43.015Z ERROR eww::error_handling_ctx > Error while updating UI after state change

Caused by:
    Couldn't upgrade reference, widget got deallocated
error: Failed to turn `` into a value of type json-value
    ┌─ /home/apm/.config/eww/eww.yuck:172:62
    │
172 │           :style "margin-left: ${RES_WIDTH / 2 - 100 - (25 * arraylength(tasks))}px;"
    │                                                              ──────────────────


error: Failed to turn `` into a value of type json-value
   ┌─ ./modules/winstuff.yuck:90:21
   │
90 │     (box(for app in tasks
   │                     ───── `` is not of type `json-value`
   │
   → EOF while parsing a value at line 1 column 0
```
I'm a bit new to eww and have never seen the repeated error at the top before. If I open a submenu in an app such as Firefox or nheko, the error gets spammed constantly several times per second.

**Comment by end-4** [comment]
hyprland crashes immediately when i launched the bar 💀
it must be those random xwayland windows
![image](https://github.com/end-4/dots-hyprland/assets/97237370/6d0fdd21-0dbc-42ef-9901-c016f74ac07a)

**Comment by TheSunCat** [comment]
Yes... I wonder where they came from? I've never seen a window on workspace -1 and monitor -1.

**Comment by end-4** [comment]
https://github.com/end-4/dots-hyprland/commit/2130755c7206fe28cca4df69bb5ca111af518154 https://github.com/end-4/dots-hyprland/commit/dab09366027c5292abbead794a80f5c23cd696e9
these 2 commits fixed crashing for me

**Comment by end-4** [comment]
- This fixes spamming warnings https://github.com/end-4/dots-hyprland/commit/aadfdb9823564942c32552a1c548a1926896bfdb 
- About errors, idk if those "Failed to turn `` into a value of type json-value" errors can even be fixed. The value is of course empty at first, but will be updated by the deflisten, so things should function normally... if you don't mind having to delete eww cache once in a while

**Comment by TheSunCat** [comment]
Great, thank you! I need to find a better way of using these dotfiles with my own local changes than pulling in my cloned folder in `~/Downloads` and manually copying the changes in :thinking:

**Comment by end-4** [comment]
Alrighty

**Comment by end-4** [comment]
turns out the errors spam because the variables don't have initial values

**Comment by SpendIce** [comment]
Hi, I seem to have a similar issue, but when trying to open the top bar, it crashes immediately. Here are the error logs

```
[0m#[1m#[38;5;9merror#[0m#[1m: Failed to turn "{ "total": "16G", "used": "2,7G", "free": "13,0G", "swaptotal": "0B", "swapused": "0B", "swappercentage": 0,0, "swapfree": "0,0G", "percentage": 16,0 }" into a value of type json-value#[0m
   #[0m#[34m┌─#[0m ./modules/system.yuck:92:21
   #[0m#[34m│#[0m
#[0m#[34m92#[0m #[0m#[34m│#[0m             :value {#[0m#[31mmemory#[0m.swappercentage}
    #[0m#[34m│#[0m                     #[0m#[31m──────#[0m


thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "property 'value' of type 'CircProg' can't be set from given value, it is invalid or out of range", filename: "/home/spendice/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/object.rs", function: "glib::object", line: 3393 }', /home/spendice/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/object.rs:2238:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛
    
 2023-07-25T12:16:37.899Z #[0m#[32mINFO #[0m #[0m#[1meww::app   #[0m > Opening window bar
 2023-07-25T12:16:37.899Z #[0m#[32mINFO #[0m #[0m#[1meww::ipc_server#[0m > IPC server initialized
 2023-07-25T12:16:38.058Z #[0m#[31mERROR#[0m #[0m#[1meww::error_handling_ctx#[0m > Error while updating UI after state change

Caused by:
    Failed to open file “./images/icons/distros/"EndeavourOS"”: No such file or directory
 2023-07-25T12:16:38.058Z #[0m#[31mERROR#[0m #[0m#[1meww::error_handling_ctx#[0m > Error while updating UI after state change

Caused by:
    Failed to open file “./images/icons/distros/"EndeavourOS"”: No such file or directory
 2023-07-25T12:16:38.066Z #[0m#[33mWARN #[0m #[0m#[1meww::script_var_handler#[0m > stderr of `notifications`: Error: name already taken on the bus
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "property 'value' of type 'CircProg' can't be set from given value, it is invalid or out of range", filename: "/home/spendice/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/object.rs", function: "glib::object", line: 3393 }', /home/spendice/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/object.rs:2238:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 2023-07-25T12:16:38.120Z #[0m#[33mWARN #[0m #[0m#[1meww::script_var_handler#[0m > stderr of `memory`: scripts/memory: line 21: printf: 13.40200000000000000000: invalid number

┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛
    
 2023-07-25T12:17:24.357Z #[0m#[32mINFO #[0m #[0m#[1meww::ipc_server#[0m > IPC server initialized
```
 
 The EndeavorOs icon file does exist in eww's config file, but apparently it can't find it. Currently the app search and workspace viewer are the only things working. Everything else crashes, and even that takes it's time to appear.

**Comment by end-4** [comment]
I'm closing this as I will no longer be supporting EWW-powered setups
