### ISSUE TITLE
How to reset terminal keybidings to the default

### ISSUE THREAD

**Issue by SiwyKot41** [end-4/dots-hyprland#110]
- **I have read the instructions** and I have a problem with branch: illogical-impulse
---
## The issue
- (describe your problem here)
Hi,
I would like to ask about keybinding in the terminal, your config allows to paste text using only ctrl+v whithout using shift which has its advantages but for me it is quite problematic. It is because when i use vim for the config files sometime i like to use ctrl+v+I to write in many places at the same time and with this configuration my clickboard is pasting its text to the vim when i don't want to do that. I would like to change the keybindings but i don't know which file is responsible for this. 

Thanks for help

- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)

**Comment by end-4** [comment]
Hi, thanks for trying out my dotfiles
- The file you wanna modify is `~/.config/foot/foot.ini`, at line 108. Ctrl+C to copy is also there in case you need to modify that too. This should take effect when you start new `foot` instances
![image](https://github.com/end-4/dots-hyprland/assets/97237370/c913b931-e160-4872-b09b-152458770266)
- You might want to make the same change in `~/.config/ags/scripts/templates/foot/foot.ini` too - this is the template file for future color generations

**Comment by SiwyKot41** [comment]
Thanks!
