### ISSUE TITLE
New Installing Query

### ISSUE THREAD

**Issue by shukla-devansh** [end-4/dots-hyprland#112]
- **I have read the instructions** and I have a problem with branch: Illogical-Impulse
---
So I did a new EndeavorOS install and Base KDE installation I wanted to copy your stuff So i installed Hyprland and Just Copied your folders in my home folder after installing the dependencies So when i boot into Hyprland All i see is a grey wallpaper and nothing else am I doing anything wrong?

**Comment by end-4** [comment]
https://github.com/end-4/dots-hyprland/wiki/illogical_impulse#installation

**Comment by shukla-devansh** [comment]
I literally did everything from the wiki for installation and still it is showing the same thing

**Comment by end-4** [comment]
- Open terminal with Super+T, run and see if it gives errors
```
pkill ags
ags
```
- To change wallpaper, hit Ctrl+Super+T then pick one

**Comment by end-4** [comment]
install [libdbusmenu-gtk3](https://archlinux.org/packages/extra/x86_64/libdbusmenu-gtk3/) maybe

**Comment by shukla-devansh** [comment]
> install [libdbusmenu-gtk3](https://archlinux.org/packages/extra/x86_64/libdbusmenu-gtk3/) maybe

yeah it fixed that and the mouse things I got two more problems 

the Bluetooth thing is not working it shows no bluetooth found and some apps like emacs are very blurry is it because i use Nvidia and a 4k monitor? i scale to around 1.5

**Comment by end-4** [comment]
## Bluetooth
- Enable the system service maybe (`sudo systemctl enable bluetooth.service`)
## Nvidia
- You'll have to figure that out for yourself. I don't run Hyprland on Nvidia and I don't use Emacs
