### ISSUE TITLE
PSA: Keyboard layout is _not_ configured via `systemsettings5`

### ISSUE THREAD

**Issue by Syndace** [end-4/dots-hyprland#113]
Hi, I've set up the hybrid branch (on a completely fresh Manjaro), and upon starting Hyprland for the first time a notification appeared saying something along the lines of

```
Keyboard layouts are not supported in the usual way yet, use systemsettings5 to configure them.
```

(this is just roughly from memory, the notification never appeared again).

This is a LIE. The keyboard layout is configured in `~/.config/hypr/hyprland.conf`. That notification cost me a few hours and nerves.

I don't think you are responsible for that notification, it seems to stem from Plasma. This issue is just for future users who might have the same issue and search the repo for a solution like I did. You can go ahead and close it or maybe add a little warning to the README first.

Also thanks a lot for creating and sharing these amazing styles :)

**Comment by end-4** [comment]
I think that's ibus. If you don't need to input in different languages, comment anything related to ibus in `~/.config/hypr/execs.conf`.
This config was old, I didn't use fcitx5 at the time so ended up with a lot of ibus nonsense :skull:
