### ISSUE TITLE
freezing when eww open themer

### ISSUE THREAD

**Issue by kn5suzuki** [end-4/dots-hyprland#114]
- **I have read the instructions** and I have a problem with branch: **hybrid**
---
## The issue
- I installed this to archlinux and faced problem of freezing when I click the "beatbox" button. I figured out that when clicking this button, command` eww open themer` is executed and this is the cause of freezing.
- README.md says `eww-wayland-git` is required, but now I can install `eww-wayland` and using `eww-wayland 0.4.0-5` now. Maybe this is doing something with this problem.

**Comment by end-4** [comment]
#99
