### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Gufderald** [end-4/dots-hyprland#118]
- **I have read the instructions** and I have a problem with branch:  [illogical-impulse](https://github.com/end-4/dots-hyprland/tree/illogical-impulse)
---
## The issue
- Got 2 problems with icons:
1. Im using arch. Until I installed `ttf-material-symbols-variable-git` AUR package, I saw texts like `bluetooth_disabled`, `restart_alt`, etc. instead of icons everywhere AGS is used. Probably installation instructions should be updated with that package, as [ttf-material-symbols](https://aur.archlinux.org/packages/ttf-material-symbols-git) responds 404 for now.
2. Second problem is that I miss SOME (not all) apps icons on powerview. This may be related to https://github.com/end-4/dots-hyprland/issues/101 as `geticons -L` also segfaults for me. Hovewer, some apps have icons (I found kitty at least).
![image](https://github.com/end-4/dots-hyprland/assets/75615922/9ee15b48-2417-46a5-9fae-6c2c9c16c188)
 
Let me know if I can provide some extra information. Thanks!

**Comment by end-4** [comment]
## 1. symbols
- thanks for letting me know! i'll update that
## 2. app icons
- unrelated to that issue. this branch doesn't use geticons.
#### how app icons work:
  - get window class names provided by hyprland, which aren't exactly icon names
  - those names go through a 'substitute' function, which changes that to the icon name for known cases
  - then comes the icon display
#### what you should do
- add a new case to the `subs` array in the substitute function in `.config/ags/windows/overview/overview.js`
- tip: hover the window on the overview widget for a tooltip saying "(class): (window name)"
- for the icon name, maybe try to search your app name in your icon pack folder

**Comment by Gufderald** [comment]
That works great, thanks!
