### ISSUE TITLE
How to change to the summer gruvbox theme cant find the setting?

### ISSUE THREAD

**Issue by woshichuanqilz** [end-4/dots-hyprland#120]
I use this [link](https://github.com/end-4/dots-hyprland/tree/hybrid)

The default theme is ![this](https://github.com/end-4/dots-hyprland/raw/hybrid/assets/screenshot-reddit.png) 

How to chang to the summer gruvbox I cant find it. 

The summer gruvbox is like this:

![Summer](https://github.com/end-4/dots-hyprland/raw/hybrid/assets/screenshot-summer.png)

**Comment by end-4** [comment]
get stuff from [its release](https://github.com/end-4/dots-hyprland/releases/tag/hybrid-v0.1-summer)
in case you wanna change the wallpaper type `>img` in the search box

**Comment by woshichuanqilz** [comment]
> get stuff from [its release](https://github.com/end-4/dots-hyprland/releases/tag/hybrid-v0.1-summer) in case you wanna change the wallpaper type `>img` in the search box
>
Tks. If it is ok I just change the .theme folder from tokyo-night to gruvbox?
