### ISSUE TITLE
Ags windows not opening

### ISSUE THREAD

**Issue by Auonghada** [end-4/dots-hyprland#122]
- **I have read the instructions** and I have a problem with branch: illogical-impulse
---
## The issue
Ags wont show any windows and gives an error about the todo.js file when starting ags.
I have tried installing ags from the AUR and also manually. I haven't changed the ags configs.
Trying to open the bar with `ags -t 'bar'`  outputs "undefined"

The todo.js error:
`(com.github.Aylur.ags:21292): Gjs-Console-CRITICAL **: 09:05:42.506: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
TodoService@file:///home/joe/.config/ags/services/todo.js:74:35
@file:///home/joe/.config/ags/services/todo.js:80:17
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:3`

Errors for opening windows:
`(com.github.Aylur.ags:21292): Gjs-Console-CRITICAL **: 09:07:35.351: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:102:27
toggleWindow@resource:///com/github/Aylur/ags/app.js:77:24
ToggleWindow@resource:///com/github/Aylur/ags/app.js:189:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

`(com.github.Aylur.ags:24331): Gjs-Console-CRITICAL **: 09:29:53.061: Error: There is no window named bar
getWindow@resource:///com/github/Aylur/ags/app.js:102:27
ToggleWindow@resource:///com/github/Aylur/ags/app.js:190:24
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

`(com.github.Aylur.ags:21292): Gjs-Console-CRITICAL **: 09:08:22.462: Error: There is no window named sideright
getWindow@resource:///com/github/Aylur/ags/app.js:102:27
ToggleWindow@resource:///com/github/Aylur/ags/app.js:190:24
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

**Comment by end-4** [comment]
can you try deleting `~/.cache/ags/user/todo.json`

**Comment by Auonghada** [comment]
Thanks, that worked.
