### ISSUE TITLE
how to add a cpu usage and tempreture monitor widget to the ram and disk usage ones 

### ISSUE THREAD

**Issue by Mahgozar** [end-4/dots-hyprland#123]
- **I have read the instructions** and I have a problem with branch: 
---
## The issue
its not really an error just confusion going through the config file i just wanted to add a cpu temperature and usage monitor to the widgets on the desktop 
- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)

**Comment by end-4** [comment]
You should
- See the AGS wiki https://github.com/Aylur/ags/wiki/
  - Probably make a polling connection to a Variable. If this doesn't make sense to you, read the wiki.
- Not ask here
- Good luck!

**Comment by end-4** [comment]
`.config/ags/windows/desktopbackground/system.js` is the file you wanna make changes to

**Comment by Mahgozar** [comment]
thank you the wiki was kinda confusing but pointing out the file actually helped
