### ISSUE TITLE
Error: no property exclusivity on AgsWindow

### ISSUE THREAD

**Issue by jenkshields** [end-4/dots-hyprland#125]
- **I have read the instructions** and I have a problem with branch: illogical-impulse
---
## The issue

I've followed the installation instructions in the wiki but am running into an error when running ags:

```
(ags:33493): Gjs-WARNING **: 18:39:36.257: JS ERROR: ImportError: Unable to load file from: resource:///com/github/Aylur/ags/variable.js (The resource at “/com/github/Aylur/ags/variable.js” does not exist)
loadURI@resource:///org/gnome/gjs/modules/internal/loader.js:88:21
loadURI@resource:///org/gnome/gjs/modules/internal/loader.js:290:30
resolveModule@resource:///org/gnome/gjs/modules/internal/loader.js:179:33
moduleResolveHook@resource:///org/gnome/gjs/modules/internal/loader.js:338:29
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

Full disclosure, I may have fucked up trying to install this while ags was already running! Any idea what the best approach is to start from scratch if need be?

**Comment by jenkshields** [comment]
After reading some other issues, I guessed it might have been an update issue - I was on 1.0.0 of ags and now have 1.5.1 running, and have another issue:

```
(com.github.Aylur.ags:5726): Gjs-Console-CRITICAL **: 20:43:14.065: Error: No property exclusivity on AgsWindow
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:10:12
AgsWindow@resource:///com/github/Aylur/ags/widgets/window.js:28:9
createCtor/<@resource:///com/github/Aylur/ags/widget.js:22:26
CornerTopleft@file:///home/jennifer/.config/ags/windows/screencorners/main.js:4:43
@file:///home/jennifer/.config/ags/config.js:41:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by end-4** [comment]
update even more. you should clone and compile manually according to the instructions on [AGS wiki](https://github.com/Aylur/ags/wiki/installation#from-source)

**Comment by end-4** [comment]
that 1.5.1 was the aur package right?
my ags installed from source actually says 1.5.3 now

**Comment by jenkshields** [comment]
Thank you - I didn't realise there was anything newer, looking at their releases page!

ags is launching now, thanks - now I'm getting a `failed to open uinput device: Permission denied` - any clues?

**Comment by jenkshields** [comment]
Sick, thank you!
