### ISSUE TITLE
Windoes branch missing?

### ISSUE THREAD

**Issue by adocampo** [end-4/dots-hyprland#129]
Hi there!

I'm new to hyprland and I just see your work and I got impressed. I was going to try Windoes, but I see no trace of it anywhere.
Is there any chance to try it out?

Thank you!
Angel

**Comment by adocampo** [comment]
Oh, it's a pity, it seemed awesome on the video... :|

**Comment by end-4** [comment]
I will make another Windows rice with the new, non-hacky widget system once Windows 12 comes out
ping me brutally when that day comes

**Comment by adocampo** [comment]
I'm not a windows guy at all, but I found your Windoes theme very clean and tidy (not as bloated -IMO- as the others), besides, the black theme is quite well done. I didn't even know Windows 12 would be released (I left windows back on Windows 2000 SP4), but  I can ping you back in a year if you weren't joking about that :P
