### ISSUE TITLE
[Illogical Impulse] Powerview not showing all workspaces

### ISSUE THREAD

**Issue by OnlyCS** [end-4/dots-hyprland#140]
- **I have read the instructions** and I have a problem with branch: illogical_impulse
---
## The issue
- Powerview isn't showing all workspaces like it does in the screenshots

![image](https://github.com/end-4/dots-hyprland/assets/61358474/a2de25e2-d673-4630-83bf-fa7df651312d)

Also I'm not sure if it's still called powerview, I migrated from m3ww and it was the same thing and called powerview there.

**Comment by end-4** [comment]
- Now it's just "overview". The widget was called powerview earlier as a result of my laziness.
- Can you provide the logs? Run `pkill ags; ags` in the terminal and see if it prints anything. If yes, make sure you include everything (it's the beginning that matters, so don't just the last few messages).

**Comment by OnlyCS** [comment]
there are no logs

**Comment by end-4** [comment]
ughhhhhh
now that's hard since no log = no basis to debug
you just run `ags`, things launch and nothing is printed? even when you open the overview?

**Comment by end-4** [comment]
can you add this line then see if ags prints 1 to 10 when launched? this is in the file `.config/ags/widgets/overview/overview.js`
![image](https://github.com/end-4/dots-hyprland/assets/97237370/250e91b0-c248-4b6a-a0ec-a6074c1c913d)

**Comment by OnlyCS** [comment]
sorry for the late reply. i get numbers 1-10 in the output
![image](https://github.com/end-4/dots-hyprland/assets/61358474/c04296a4-e6a7-4ec7-b9e6-6308bd6ae937)

**Comment by end-4** [comment]
> show all workspaces with open windows but nothing else

what do you mean? in the first picture you sent only one workspace shows up

**Comment by OnlyCS** [comment]
right, but only one workspace had windows open. if i have workspaces 1 and 3 with windows open, overview will show 1 and 3 and no others.

**Comment by OnlyCS** [comment]
well, i spent some time debugging and figured it out
SCREEN_WIDTH and SCREEN_HEIGHT was NaN. I got an error when running the xrandr command you used. I manually set the values to 1920 and 1080. worked like a charm

**Comment by end-4** [comment]
looks like i have to add xorg-xrandr to dependency list then

**Comment by end-4** [comment]
huh it's already there
can you run the command you removed and check the output?
