### ISSUE TITLE
Lightmode problem

### ISSUE THREAD

**Issue by 4Gettt25** [end-4/dots-hyprland#141]
- **I have read the instructions** and I have a problem with branch: illogical Impulse
---
### Lightmode 
- I am not able to switch to lightmode (I even tried a completely white bnackground and it still recognized it as dark

### Doesn't recognize LAN
- the sideright does have a LAN switch at least in the js but it still just shows me a wifi symbol with a questionmark.

### Errors
I've also seen the #111 issue and tried the things there but haven't  gotten any errors

**Comment by end-4** [comment]
### light mode
- type `>light` in the search bar
### doesn't recognize lan
- not sure how lan is supposed to show up tbh. does the network icon in [aylur's dotfiles](https://github.com/aylur/dotfiles) (to test, rename the `ags` folder you currently have in `~/.config` and copy aylur's `ags` folder there) work like you expect?

**Comment by 4Gettt25** [comment]
Okay I tried the ags from Aylur and there it actually show that I'm connected to lan instead of wifi and I get the lan logo

**Comment by end-4** [comment]
it's yoinking time

**Comment by end-4** [comment]
does it work now?

**Comment by 4Gettt25** [comment]
nope there is still a wifi icon with a "?"

**Comment by end-4** [comment]
There shouldn't even be any wifi icon with question mark now - I removed it
Are you sure you downloaded the `illogical-impulse` (not `main`) branch and copied the `ags` folder?

**Comment by end-4** [comment]
i'm not familiar with using `git`, so i'm not sure if it's anything wrong
how about you try clicking the green "Code" button then "Download ZIP" on github instead? (this is better than cloning currently - you get a nice zip of the latest content instead of a 600mb folder (reducing that size is on my todo list))

**Comment by 4Gettt25** [comment]
ok just tried it with the zip file but still got the icon in the top right

**Comment by end-4** [comment]
How about now?
If it still doesn't work, add `console.log(Network.primary);` right below line 148 of `~/.config/ags/lib/statusicons.js` and show me the output of ags

**Comment by 4Gettt25** [comment]
(com.github.Aylur.ags:8377): Gjs-CRITICAL **: 09:32:00.636: JS ERROR: Error: Expected an object of type GtkWidget for argument 'widget' but got type undefined
setup@file:///home/felixg/.config/ags/widgets/bar/workspaces.js:58:47
set setup@resource:///com/github/Aylur/ags/widgets/widget.js:90:18
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:59:50
_init@resource:///com/github/Aylur/ags/widgets/widget.js:38:19
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:17:12
AgsOverlay@resource:///com/github/Aylur/ags/widgets/overlay.js:15:31
createCtor/<@resource:///com/github/Aylur/ags/widget.js:22:26
ModuleWorkspaces@file:///home/felixg/.config/ags/widgets/bar/workspaces.js:57:28
@file:///home/felixg/.config/ags/widgets/bar/main.js:20:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
 
 
(com.github.Aylur.ags:8377): Gjs-CRITICAL **: 09:32:00.651: JS ERROR: Error: Expected an object of type GtkWidget for argument 'widget' but got type undefined
setup@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:44:33
set setup@resource:///com/github/Aylur/ags/widgets/widget.js:90:18
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:59:50
_init@resource:///com/github/Aylur/ags/widgets/widget.js:38:19
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:17:12
AgsOverlay@resource:///com/github/Aylur/ags/widgets/overlay.js:15:31
createCtor/<@resource:///com/github/Aylur/ags/widget.js:22:26
ResourceValue@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:32:9
@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:54:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
 
 
(com.github.Aylur.ags:8377): Gjs-CRITICAL **: 09:32:00.657: JS ERROR: Error: Expected an object of type GtkWidget for argument 'widget' but got type undefined
setup@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:44:33
set setup@resource:///com/github/Aylur/ags/widgets/widget.js:90:18
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:59:50
_init@resource:///com/github/Aylur/ags/widgets/widget.js:38:19
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:17:12
AgsOverlay@resource:///com/github/Aylur/ags/widgets/overlay.js:15:31
createCtor/<@resource:///com/github/Aylur/ags/widget.js:22:26
ResourceValue@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:32:9
@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:61:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
 
 
(com.github.Aylur.ags:8377): Gjs-CRITICAL **: 09:32:00.663: JS ERROR: Error: Expected an object of type GtkWidget for argument 'widget' but got type undefined
setup@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:44:33
set setup@resource:///com/github/Aylur/ags/widgets/widget.js:90:18
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:59:50
_init@resource:///com/github/Aylur/ags/widgets/widget.js:38:19
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:17:12
AgsOverlay@resource:///com/github/Aylur/ags/widgets/overlay.js:15:31
createCtor/<@resource:///com/github/Aylur/ags/widget.js:22:26
ResourceValue@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:32:9
@file:///home/felixg/.config/ags/widgets/desktopbackground/system.js:68:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
 
 
(com.github.Aylur.ags:8377): Gtk-WARNING **: 09:32:00.695: Theme directory 16@2x/emblems of theme OneUI has no size field
 
 
(com.github.Aylur.ags:8377): Gtk-WARNING **: 09:32:00.696: Theme directory 22@2x/devices of theme OneUI has no size field
 
 
(com.github.Aylur.ags:8377): Gtk-WARNING **: 09:32:00.696: Theme directory 22@2x/emblems of theme OneUI has no size field
 
 
(com.github.Aylur.ags:8377): Gtk-WARNING **: 09:32:00.697: Theme directory 256@2x/applets of theme OneUI has no size field
 
 
(com.github.Aylur.ags:8377): Gjs-CRITICAL **: 09:32:00.803: JS ERROR: Error: Expected an object of type GtkWidget for argument 'widget' but got type undefined
setup@file:///home/felixg/.config/ags/widgets/desktopbackground/main.js:25:31
set setup@resource:///com/github/Aylur/ags/widgets/widget.js:90:18
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:59:50
_init@resource:///com/github/Aylur/ags/widgets/widget.js:38:19
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:17:12
AgsOverlay@resource:///com/github/Aylur/ags/widgets/overlay.js:15:31
createCtor/<@resource:///com/github/Aylur/ags/widget.js:22:26
default@file:///home/felixg/.config/ags/widgets/desktopbackground/main.js:15:19
@file:///home/felixg/.config/ags/config.js:46:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
 
 
Gjs-Console-Message: 09:32:01.074: wired
Gjs-Console-Message: 09:32:01.076: wired
 
(com.github.Aylur.ags:8377): GLib-GObject-CRITICAL **: 09:32:01.078: value "1,199921" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
 
(com.github.Aylur.ags:8377): GLib-GObject-CRITICAL **: 09:32:01.078: value "1,199921" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
 
(com.github.Aylur.ags:8377): GLib-GObject-CRITICAL **: 09:32:01.078: value "1,199921" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
 
(com.github.Aylur.ags:8377): GLib-GObject-CRITICAL **: 09:32:01.078: value "1,199921" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
 
(com.github.Aylur.ags:8377): GLib-GObject-CRITICAL **: 09:32:01.079: value "1,199921" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
 

    (com.github.Aylur.ags:8377): GLib-GObject-CRITICAL **: 09:32:01.079: value "1,199921" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'

**Comment by end-4** [comment]
wtf

**Comment by end-4** [comment]
Are you testing on Sway or something? The config only works on Hyprland.

**Comment by end-4** [comment]
turns out lan is wired... i wasn't aware of that 😅

**Comment by 4Gettt25** [comment]
hey just updated the config and now it works thanks mate

**Comment by end-4** [comment]
nice
