### ISSUE TITLE
Hyprland install script succeeded but has no UI icons

### ISSUE THREAD

**Issue by samvictordr** [end-4/dots-hyprland#142]
- **I have read the instructions** and I have a problem with branch: illogical impulse
---
## The issue
- After successfully installing using the install script, I rebooted my system for the configs to load fully, only hyprland loaded to the UI without any icons (I mean all, every icon's place was taken by a alt text.). Another thing I noticed is that I can't seem to change the wallpaper, and the home screen just stays blank.

**Comment by Gufderald** [comment]
Hi! Faced this issue. Check if you have `ttf-material-symbols-variable-git` AUR package installed. https://github.com/end-4/dots-hyprland/issues/118

**Comment by end-4** [comment]
... and make sure you did log out and log in or something
or run `fc-cache -fv`

**Comment by samvictordr** [comment]
@Gufderald was right, I didn't have the AUR icons package installed, I timed out during the script and I never noticed. That fixed it, thanks guys.
