### ISSUE TITLE
the volume bar is not working

### ISSUE THREAD

**Issue by alavaelian** [end-4/dots-hyprland#143]
- **I have read the instructions** and I have a problem with branch: 
illogical impulse
## The issue
although i have the audio working the volume bar is just showing a -1 and its not working. although when use the mouse scrolling for change the volume works.
also the brightness  is not working but i dont now how to setup it in a monitor in desktop pc

**Comment by end-4** [comment]
## "Audio"
- this progress indiccator?
![image](https://github.com/end-4/dots-hyprland/assets/97237370/1be0f71b-6c7f-463a-9e8a-21ca2d86d15e)
- if yes, it's battery. that -1 is to be expected on a desktop system. i really should add an icon and hide it appropriately...
## Brightness
- I'll look at this some time later when i have time and get access to an external monitor

**Comment by alavaelian** [comment]
oooooh  i see now thanks for the explanation dude, appreciated , for real.
but how i hide that bar since i am i an deskto and it not uselfull and looks bad, and change it for other like the audio or something else.

**Comment by end-4** [comment]
i don't think audio would make sense there since there's already an osd for it, and the music widget is on the left. what else do you want on your bar as a desktop user?

**Comment by alavaelian** [comment]
maybe processor usage ?

**Comment by end-4** [comment]
it'll likely be useless since it's going to be either very low or very high... but i guess i can make a ram/swap usage

**Comment by alavaelian** [comment]
that could do, but there is already one in the desktop

**Comment by end-4** [comment]
i can remove it :trollface:

**Comment by alavaelian** [comment]
that is right having one in the bar couldn't hurt

**Comment by end-4** [comment]
and done
can you see if it works now?

**Comment by alavaelian** [comment]
i  downladed the new version and replace the folders on my home directory to test , it is not working is till showing the -1 abut now shows an extra icon, do i need to do another extra configs

**Comment by end-4** [comment]
oops
i should check `Battery.available` not just `Battery`
can you try again

**Comment by alavaelian** [comment]
And when i hover the mouse over it , still show battery,

**Comment by alavaelian** [comment]
config error at line 69 hyperlad.conf error setting value 50 for field general gaps workspace no such field

**Comment by end-4** [comment]
> error setting value 50 for field general gaps workspace no such field
- should be `gaps_workspaces` (with an 's')
- why are you getting this now but not before? i didn't change hyprland configs?

**Comment by alavaelian** [comment]
i dunno only happened with the last version with the correction. let me check again

**Comment by alavaelian** [comment]
i dunno what happened before but now it is working perfectly amazing man
