### ISSUE TITLE
[feature requets] idle inhibitror button

### ISSUE THREAD

**Issue by alavaelian** [end-4/dots-hyprland#145]
## The issue
you know this could be usefull in case when you want to watch a movie away of the computer

**Comment by end-4** [comment]
hmm
this seems to work https://aur.archlinux.org/packages/wayland-idle-inhibitor-git

**Comment by alavaelian** [comment]
yes but i mean a button in the bar where you can activate and desactivate there are other configs that have done it with a button with an eye icon.

**Comment by end-4** [comment]
can you see if it works? i've added a coffee button here on the right sidebar
![image](https://github.com/end-4/dots-hyprland/assets/97237370/4c07035d-7910-4f36-81eb-8ca55150e737)

**Comment by alavaelian** [comment]
hello again dude, i have test it and the screen is still blocking in five minutes or so. and i love the icon of a cup of coffe is a nice touch

**Comment by end-4** [comment]
when enabling coffee do you see this python process?
![image](https://github.com/end-4/dots-hyprland/assets/97237370/6cefcebe-d5d7-412c-a0d0-a7a35b666dd0)

**Comment by Sridou** [comment]
Yeah, its working once you install [wayland-idle-inhibitor-git](https://aur.archlinux.org/packages/wayland-idle-inhibitor-git).
Before that I got the following error;
``(com.github.Aylur.ags:50210): Gjs-WARNING **: 21:12:31.009: JS ERROR: GLib.SpawnError: Failed to execute child process “wayland-idle-inhibitor.py” (No such file or directory)
subprocess@resource:///com/github/Aylur/ags/utils.js:165:37
onClicked@file:///home/sridou11/.config/ags/widgets/sideright/quicktoggles.js:122:37
AgsButton/<@resource:///com/github/Aylur/ags/widgets/button.js:26:44
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34``

**Comment by alavaelian** [comment]
> Yeah, its working once you install [wayland-idle-inhibitor-git](https://aur.archlinux.org/packages/wayland-idle-inhibitor-git). Before that I got the following error; `(com.github.Aylur.ags:50210): Gjs-WARNING **: 21:12:31.009: JS ERROR: GLib.SpawnError: Failed to execute child process “wayland-idle-inhibitor.py” (No such file or directory) subprocess@resource:///com/github/Aylur/ags/utils.js:165:37 onClicked@file:///home/sridou11/.config/ags/widgets/sideright/quicktoggles.js:122:37 AgsButton/<@resource:///com/github/Aylur/ags/widgets/button.js:26:44 _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

i did not install that [wayland-idle-inhibitor-git](https://aur.archlinux.org/packages/wayland-idle-inhibitor-git). XD

**Comment by end-4** [comment]
alright, imma close
