### ISSUE TITLE
[Illogical Impulse] Wallpaper and Dark/Light theme not working on fresh install

### ISSUE THREAD

**Issue by AchintyaSingh0220** [end-4/dots-hyprland#146]
Wallpaper is just a blank black screen and setting a new wallpaper doesn't work. Trying to switch using >dark / >light on launcher doesn't work and instead throws an error.

I tried with both EndeavourOS no desktop as well as GNOME install.

**Comment by end-4** [comment]
what happens if you run ` ~/.config/ags/scripts/color_generation/switchwall.sh`

**Comment by AchintyaSingh0220** [comment]
This is what I'm getting: https://pastebin.com/5uheWGfs
Also a gnome style file explorer tab opens up, with the ~/Pictures directory open but there's no files in the directory to choose from.

Also this is the error hyprland throws when I switch to dark/light theme:
![image](https://github.com/end-4/dots-hyprland/assets/113066524/405e2eb1-7dda-4906-8eef-dd99aef57e49)

**Comment by end-4** [comment]
No wallpaper then you gotta get one lol. No wallpaper = no colors to pick = themes not properly applied
You aren't bound to files in Pictures, you can select from any directory

**Comment by AchintyaSingh0220** [comment]
Omg
Super sorry for wasting your time, that worked.
I thought I'd tried setting the wallpaper already and that it didn't work, but it turned out I'd just been confused and set the gnome desktop wallpaper last time.
Thanks alot!!
