### ISSUE TITLE
Color Inversion not working

### ISSUE THREAD

**Issue by Sridou** [end-4/dots-hyprland#150]
- **I have read the instructions** and I have a problem with branch: illogical impulse
---
## The issue
- when I click color inversion [rain droplet] in AGS, Hyprland throws the error: 
- "Screen Shader Parser: Screen Shader Path not found". 
- I can confirm the normal commands " >light, >dark,>blackapple" work
![image](https://github.com/end-4/dots-hyprland/assets/74325914/7573fcae-12e9-45cc-8d54-491825dfb3c4)

**Comment by alavaelian** [comment]
i have the same problem

**Comment by end-4** [comment]
i forgot to upload it :P
just download that file and put into `~/.config/hypr/shaders`

**Comment by jontstaz** [comment]
@end-4 - I'm getting an issue with both the night-light and inversion options. I can enable them once, however once I then disable them, the buttons in the AGS right-bar stay activated/pressed/enabled and clicking on them does nothing. I have to completely restart AGS to get the buttons to go back to their disabled state. Not sure why.
![27 12_2023_22:25:41_grim](https://github.com/end-4/dots-hyprland/assets/6379873/2b0e52f0-642a-40a4-badd-86391f4fa206)

**Comment by end-4** [comment]
@jontstaz it's a Hyprland problem with shaders
see that reload button? it reloads hyprland config, which should fix this (temporarily, if you enable and disable a shader you'll have to reload again)

**Comment by end-4** [comment]
@jontstaz both those buttons have now been fixed
- night light: now wlsunset is used instead of a shader. go ahead and install `wlsunset-git`
- invert: i updated the toggle command so that reloading is no longer required in the above commit
