### ISSUE TITLE
[Issue] wallpaper and clipboard doesn't work

### ISSUE THREAD

**Issue by meduk0** [end-4/dots-hyprland#151]
i follow your tutorial and i got it  running but i cant set neither wallpaper(i din't find any st of wallpaper config in your dotfiles and the super+v doesn't work for the clipboard)

**Comment by end-4** [comment]
## wallpaper
- i don't redistribute wallpapers. get one yourself and press Ctrl+Super+T (i gotta add this to instructions and the init message)
## clipboard
- run `pacman -Q | grep clip`. see if you have `cliphist` andd `wl-clipboard`

**Comment by clsty** [comment]
I'm closing this issue because:
- `cliphist` and `wl-clipboard` are already in the dependency list now.
- Install script already has a reminder about wallpaper thingy. The wiki also has one under the "Manual installation" section.
