### ISSUE TITLE
Why chatgpt

### ISSUE THREAD

**Issue by meduk0** [end-4/dots-hyprland#152]
I mean i dont use it my self and after installing your lovely dots and making some changes i wa asking as i am new to AGS :
-can you provide more docs on how to use chatgpt especially if i dont wonna pay 
-made it optional so i can change it or remove it if i want 
-provide more docs on how the dots work (for easier integration) 
And thx for the daily update on the project

**Comment by end-4** [comment]
> especially if i dont wonna pay

nah it's free if you don't use it too much
> make it optional

well the souce codde is there, do whatever you want. though an easier way to toggle these would be nice, I agree
> provide more docs

I already documented some of the non-obvious stuff on the wiki page. It would really help if you could specify what needs to be clarified.  Thanks!

**Comment by harshafaik** [comment]
You can make ChatGPT work by changing the endpoint address in the chatgpt.js file. I changed it, got an API key and it worked fine. :)

**Comment by end-4** [comment]
There's now Google Gemini. It's also free (but it isn't directly compatible with the code for the ChatGPT API)
@harshafaik if you don't mind, what's that other free service?

**Comment by harshafaik** [comment]
I can't access Google Gemini API due to regional restrictions. :sob: As for chatGPT, I looked up for APIs in the list mentioned here: [https://github.com/zukixa/cool-ai-stuff/](url) (using Oxygen rn).

I can document it properly if that's something you want.

**Comment by end-4** [comment]
very cool, thanks for sharing!
## Task for me
- [ ] Make a dropdown menu to change endpoint
  - This way we won't even need documentation

**Comment by end-4** [comment]
I added the first two models on that list. Feel free to suggest more.

**Comment by MNkoder** [comment]
> You can make ChatGPT work by changing the endpoint address in the chatgpt.js file to some service that can offer a free API key for use. I changed it, got an API key and it worked fine. :)

hey im sorry if i sound stupid but i got the api key, now can you like help me where to put the endpoint address?

**Comment by clsty** [comment]
> hey you are using the free version of gemini right? i mean the pro.. or have you paid for the ultra or whatever its called?

The AI widget does not provide any service, but just work as a client. You still need to get API key by yourself, unless it's not required for the service.

> also just wanted to ask where can i access this dropdown menu to change models from?

![screenshot](https://github.com/end-4/dots-hyprland/assets/129247596/5c448b03-a724-427f-bb0c-36e88e375d63)

Click the OpenAI icon to switch to chatGPT and you'll see the dropdown menu. Also that's not for switching model, but just service endpoint.

**Comment by MNkoder** [comment]
ah thanks for the reply, idk why but I'm not getting that dropdown menu when clicking on thw openAI icon, I tried reinstalling the script and updating ags but the menu just doesn't come

**Comment by clsty** [comment]
> ah thanks for the reply, idk why but I'm not getting that dropdown menu when clicking on thw openAI icon, I tried reinstalling the script and updating ags but the menu just doesn't come

Have you refered to the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/01setup/#updating)?

Also you need to restart AGS (by default press `Super+Ctrl+R`) to make changes take effect.

**Comment by end-4** [comment]
> hey you are using the free version of gemini right? i mean the pro.. or have you paid for the ultra or whatever its called? also just wanted to ask where can i access this dropdown menu to change models from?

i'm using pro, which is free

**Comment by MNkoder** [comment]
> > ah thanks for the reply, idk why but I'm not getting that dropdown menu when clicking on thw openAI icon, I tried reinstalling the script and updating ags but the menu just doesn't come
> 
> Have you refered to the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/01setup/#updating)?
> 
> Also you need to restart AGS (by default press `Super+Ctrl+R`) to make changes take effect.

yeah, did everything I wonder what's the problem.. Is there any troubleshooting steps I can do?

**Comment by clsty** [comment]
> yeah, did everything I wonder what's the problem.. Is there any troubleshooting steps I can do?

If you did run `git pull` to get the latest repo, then it's kinda weird. A system reboot may help.
If it still does not work, please run `pkill ags;ags -t 'sideleft'` and paste the output here.

**Comment by MNkoder** [comment]
also just so you know I did install your dotfiles using your script, but then the resolution and everything was messed up so I switched to end's dotfiles by using his script again, any chance that might've been the problem?

**Comment by clsty** [comment]
> also just so you know I did install your dotfiles using your script, but then the resolution and everything was messed up so I switched to end's dotfiles by using his script again, any chance that might've been the problem?

If you're refering to dots-hyprarch, there will not be a problem just because you switched to this repo, because the install script will overwrite the whole config directory such as `~/.config/ags` (I wrote both of the scripts so I can guarantee this).

**Comment by end-4** [comment]
in `~/.config/ags/config.js`, 
![image](https://github.com/end-4/dots-hyprland/assets/97237370/6ead5446-48b1-4ecf-a6f9-9b983fc832b7)
and show output

**Comment by MNkoder** [comment]
> in `~/.config/ags/config.js`, ![image](https://private-user-images.githubusercontent.com/97237370/308578460-6ead5446-48b1-4ecf-a6f9-9b983fc832b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjk5OTAsIm5iZiI6MTcwOTEyOTY5MCwicGF0aCI6Ii85NzIzNzM3MC8zMDg1Nzg0NjAtNmVhZDU0NDYtNDhiMS00ZWNmLWE2ZjktOWI5ODNmYzgzMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE0MTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNzg3ODdkMjMxODIwZTVlOWI4MTA2YmM2ZmNiZDNjZDIxMmU1YTVkNjQ1MzAwMGE4YzRlOTViYjY1NmQwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dSVkp7VX8WYb91jm-oX7AHa1FynhAr0cpo3LWtbAseo) and show output

the pkill ags;ags -t 'sideleft' output?

**Comment by end-4** [comment]
still the same?i must've forgotten `.catch()` somewhere...

**Comment by MNkoder** [comment]
this is it right?
![image](https://github.com/end-4/dots-hyprland/assets/120258414/2d13847c-d09e-46b5-8b9e-45610365bfb6)

**Comment by MNkoder** [comment]
well hey I just reinstalled it again using the bash script and tada! now it works fine and the drop down menu is visible! thanks for the help guys <3

**Comment by MNkoder** [comment]
also hey can you like guide me on how to provide translations for the wiki, I can help you add some indian languages

**Comment by clsty** [comment]
Closing as completed.

**Comment by end-4** [comment]
yes
