### ISSUE TITLE
[Issue] Suggestions on installation script

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#156]
- **I have read the instructions** and I have a problem with branch: [illogical-impulse](https://github.com/end-4/dots-hyprland/tree/illogical-impulse)
---
## The issue

> There's now an install.sh script that does all the stuff below for you (except optional, non-commandline stuff). Feedback on it is appreciated!

So I have read the script a bit and, because I happened to wrote a lot of bash scripts in my own little [project](https://github.com/clsty/arCNiso), I guess I have earned some experiences about these stuff so that I may have some beneficial suggestions.

Here's some of them:

> 4. should be run from its folder.

Add `cd $(dirname $0)` to the top of the script, so that the working dir will be automatically at where the script locates.

> 3. will show all commands that it runs.

After executing `set -v` , all commands will be printed before executed. `set +v` turns this off.

> `yay -S ...`

I would prefer `yay --needed --noconfirm -S`. At least `--needed` to avoid already installed packages.

> "failed to clone into ags. Aborting..." && exit

Since it's an error, consider using `exit 1` instead of `exit`.
Also, if you want to automatically exit a script wherever it fails (i.e. the exit code is non-zero; note that `||` `&&` catch the stderr, hence the exit code), add `set -e` to the top of the script.

Last but not least, the program you use in this script gives a lot of outputs, which makes the `echo`s in your script likely to be ignored. You may consider a more colorful output, e.g.:
```bash
echo -e "This is \e[32mGreen\e[0m, and this is \e[41mRed\e[0m."
```

I'm here to discuss about this first, because I don't know how do you think of it. If you feel my suggestions making sense, I could also make a PR on this script.

**Comment by end-4** [comment]
Thanks for the in-depth review!
Does it look good now?

**Comment by clsty** [comment]
Yeah, that looks way better. Thanks for taking my advice so quickly.
