### ISSUE TITLE
Change accent colour

### ISSUE THREAD

**Issue by Mircas001** [end-4/dots-hyprland#157]
How do i use the >color command to change accent colour on illogical_impulse please?

**Comment by end-4** [comment]
ah, i forgot to add the dependency for that. added now.
you should install hyprpicker:  `yay -S hyprpicker-git`
then click on the pixel on the screen whose color you want to be the accent color

**Comment by Mircas001** [comment]
its still purple....

**Comment by end-4** [comment]
hmm
please check the output when you run  `~/.config/ags/scripts/color_generation/switchcolor.sh`

**Comment by RookiexCookie** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/136296017/2f2c517b-99f5-42f5-aa59-3a581913e100)

**Comment by end-4** [comment]
@RookiexCookie looks to me that ags is having a problem but gradience is working fine
do gtk apps and foot terminal get themed to the color you picked?

**Comment by RookiexCookie** [comment]
yes they are working now along with the apps, i forgot to add these with the above comment 
![image](https://github.com/end-4/dots-hyprland/assets/136296017/155562db-b4ba-46f4-af1d-a8465d0c14b7)
![image](https://github.com/end-4/dots-hyprland/assets/136296017/acb02e80-e22f-4d26-87e3-4f20eae9b953)

btw when i chose a gif as a wallpaper 
the themes stuff stopped working

**Comment by end-4** [comment]
so they do work? good
idk about gifs... guess it isn't supported by the color gen lib (https://github.com/avanisubbiah/material-color-utilities-python)

**Comment by Mircas001** [comment]
recently reinstalled and yup it works
