### ISSUE TITLE
[Issue] why hyprland-git/ swaylock?

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#158]
- **I have read the instructions** and I have a problem with branch: Illogical_impulse
---
## The issue

I'm wondering that is it necessary to use hyprland-git in AUR? Because Arch Linux has already a package named hyprland.
After all, hyprland-git is less stable.

Another thing is that
> swaylock and swaylock-effects-git are in conflict. Remove swaylock-effects-git? [y/N]

I mean, you can't install swaylock and swaylock-effects-git together in a script.

**Comment by clsty** [comment]
I'll try to make a PR, if you don't mind.

**Comment by end-4** [comment]
- about swaylock, oops
- about hyprland, i listed `hyprland-git` but actually i just compile the latest version manually
  - by using the development version i get exciting new features that are announced in its discord server once in a while
  - i sometimes make contributions so i just got used to staying up to date
  - you *can* use normal `hyprland` if it works. but if there's a breaking change on -git i normally try to update as soon as i can. if you just grab my dotfiles once and don't update it then it likely doesn't matter
