### ISSUE TITLE
[Question] How to get a list of available icons/ add available icons for keybind cheatsheet?

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#167]
- **I have read the instructions** and I have a problem with branch: Illogical impulse
---
## The issue

The file `~/.config/ags/data/keybinds.js` uses several icons by giving names:
```javascript
        "icon": "move_group",
// ...
        "icon": "pin_drop",
// ...
```
Please tell me how to get a list of available icon names, or how to add a custom icon with specified name, thanks!

**Comment by end-4** [comment]
Those are Labels that have the font family set to "Material Symbols Rounded"
see the cheatsheet here: https://fonts.google.com/icons
