### ISSUE TITLE
[Feature request] NOT show battery in bar when there's no battery.

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#169]
**What would you like to be added?**
My desktop computer does not have a battery, but the bar show it as `-1%`, which is really weird.

**How will it help**
No battery widget on ags bar for PCs without battery.

**How will I help**
Here's some js code to determine whether there is a battery:
```javascript
const fs = require('fs');

function checkBattery() {
  fs.readdir('/sys/class/power_supply', (err, files) => {
    if (err) {
      console.error(`Error when reading directory: ${err.message}`);
      return;
    }

    const batteryFiles = files.filter(file => file.startsWith('BAT'));
    if (batteryFiles.length > 0) {
      console.log('yes');
    } else {
      console.log('no');
    }
  });
}

checkBattery();
```
And I tested it on my desktop PC, which returns `no`;
and tested on my laptop, which returns `yes`.

The next thing is to integrate these code into the file `.config/ags/widgets/bar/system.js`, which is beyond my power currently, so I sincerely need your help!

**Comment by end-4** [comment]
the hard part isn't checking, but designing
feel free to suggest a design in #163
