### ISSUE TITLE
[Issue]the miniature of the media control does not actualize if you change the tap and play other youtube song

### ISSUE THREAD

**Issue by alavaelian** [end-4/dots-hyprland#172]
if you pause the actual song and open another tap and play another song it will work but the miniature will keep being the one of the first song,

**Comment by end-4** [comment]
I think it depends on your app ~~and luck~~

https://github.com/end-4/dots-hyprland/assets/97237370/22e63ff9-ad92-43bc-ad4c-4ce8d989dec9

**Comment by end-4** [comment]
which app you're having the problem with?
can you reccord a video like the one above?

**Comment by end-4** [comment]
for me it seems to work fine with firefox and messed up in thorium (which is chromium)

**Comment by end-4** [comment]
- Right, it doesn't work. It theoretically should, but a hackier solution is likely to work better. I'll go ahead and change to that

> too lazy to remember some of your keybinds
- On the music pill on the bar or top-right corner of the screen, middle-click to Play/Pause and right-click for Next track
- `¯\_(ツ)_/¯` Though the prev/next keybinds are pretty easy to remember (WinShift+**B**ack/WinShift+**N**ext) , and you can change it yourself in `~/.config/hypr/keybinds.conf`

**Comment by end-4** [comment]
okay it's not about the solution it was that i forgot to add it lmao

**Comment by end-4** [comment]
iirc playerctld does a good job at tracking this stuff
and i just found out about how to add it as a daemon here https://wiki.archlinux.org/title/MPRIS#Playerctl
I'll try to read data from its bus and see if media title shows more accurately

**Comment by end-4** [comment]
oh and i also found this fix for chromium
https://www.reddit.com/r/kde/comments/eih9jb/if_you_use_chromium_with_kde_plasma_integration/

**Comment by alavaelian** [comment]
thanks mate it working now
