### ISSUE TITLE
[Issue]i need to enter the password two times in the lock screen

### ISSUE THREAD

**Issue by alavaelian** [end-4/dots-hyprland#173]
when i pust the power button i need to unlock the lock screen two times before i can use the system again

**Comment by clsty** [comment]
Maybe you're have two lockscreen instance running at the same time.

> when i pust the power button
Please, what is that exactly? Push the power button? Which one? The physical one on your computer?

**Comment by alavaelian** [comment]
> Maybe you're have two lockscreen instance running at the same time.
> 
> > when i pust the power button
> 
> Please, what is that exactly? Push the power button? Which one? The physical one on your computer?

the physical one , to wake up the system sorry

**Comment by end-4** [comment]
this problem happens to me too but i've been too lazy to fix it
idk if this works, can you confirm?

**Comment by alavaelian** [comment]
no it does not , is weird what is running two instances of a lock screen

**Comment by enviado** [comment]
you could try adding this option to config file:
`daemonize`
it worked for me.

**Comment by end-4** [comment]
daemonize what

**Comment by enviado** [comment]
just put to` swaylock/config `file

**Comment by alavaelian** [comment]
did not work

**Comment by end-4** [comment]
i shrug
maybe change the lock command to not just `swaylock -f`, but `swaylock -f & notify-send 'locking!!!!!' 'notice when this occurs'`
then try to suspend the way you're having this problem with. watch when the notification is sent (on sleep, when the system wakes up, or when you unlock the first time)

**Comment by clsty** [comment]
I'm closing this issue since we have removed swaylock.

Feel free to reopen if you still encounter this problem using the latest version of this repo.
