### ISSUE TITLE
[Issue] gtklock not support by hyprland

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#177]
- **I have read the instructions** and I have a problem with branch: Illogical Impulse
---
## The issue
When I run `gtklock` directly in shell, screenlock does not appear. Here's the output:
```plain
** (gtklock:213330): WARNING **: 10:39:48.441: /usr/lib/gtklock/powerbar-module.so: module has mismatched minor version (0), may be incompatible

** (gtklock:213330): CRITICAL **: 10:39:48.457: Your compositor doesn't support wlr-input-inhibitor
```

According to a member of hyprwm [here](https://github.com/hyprwm/Hyprland/issues/2937#issuecomment-1855445290), gtklock is not supported by hyprland.

But as written [here](https://github.com/hyprwm/Hyprland/issues/2937#issuecomment-1879252045), `gtklock -i` still works.

And yes, `gtklock -i` does work on my PC.

So I suggest to use `gtklock -i` or just use `swaylock` instead.

(I'm also wondering that why use two different lockscreen providers together.)

**Comment by end-4** [comment]
>   -i, --no-input-inhibit     Don't use wlr-input-inhibitor

This allows you to focus and control windows using keybinds/keyboard without unlocking
I'm not using gtklock until it gets fixed for proper usage

> (I'm also wondering that why use two different lockscreen providers together.)

I forgot to remove gtklock from dependencies. but the hyprland config is set up to launch swaylock

**Comment by clsty** [comment]
> I forgot to remove gtklock from dependencies. but the hyprland config is set up to launch swaylock
Do you mean something else?

Yes, please run the following command under the folder of this git repo and you'll know what I mean.
```bash
ack gtklock
find . -name gtklock
```

**Comment by end-4** [comment]
anything else?

**Comment by clsty** [comment]
That's enough as the fix for buttons, thanks!

> i think it's fine to keep the gtklock theming in the color applying script

Sure, I agree on that.

Closing as fixed.
