### ISSUE TITLE
CheatSheet resolution

### ISSUE THREAD

**Issue by RookiexCookie** [end-4/dots-hyprland#180]
- **I have read the instructions** and I have a problem with branch: 
---
## The issue
![image](https://github.com/end-4/dots-hyprland/assets/136296017/d904d1c9-1ad2-4529-8932-7454478e6f96)

The Cheatsheet is like this in my screen and im not able to minimise it aswell only close 
  
 Resolution: 1366x768

**Comment by end-4** [comment]
you can use gsettings to change the font size, like this:
`gsettings set org.gnome.desktop.interface font-name 'Rubik 9'`
Rubik here is the font name and 11 is the font size in pt (1pt = 1.3333 px)

Stuff should scale according to the font size. If some elements don't change font size, hit Ctrl+Super+R

**Comment by RookiexCookie** [comment]
Cool ,it worked
Thanks alot

**Comment by Ate329** [comment]
> you can use gsettings to change the font size, like this: `gsettings set org.gnome.desktop.interface font-name 'Rubik 9'` Rubik here is the font name and 9 is the font size in pt (1pt = 1.3333 px)
> 
> Stuff should scale according to the font size. If some elements don't change their size, hit Ctrl+Super+R

It is possible to change the scale of the cheat sheet only? Because the other stuff will become smaller as well for instance the bar on the top of the screen (don't know how to call it)

**Comment by end-4** [comment]
nope
