### ISSUE TITLE
[Issue] Icon Theme was not installed

### ISSUE THREAD

**Issue by quadbyte** [end-4/dots-hyprland#181]
- **I have read the instructions** and I have a problem with branch: illogical impulse
---
## The issue
- Icon theme was not installed during install.
- Can you provide the name of the theme so I can install it manually ? thx!

![image](https://github.com/end-4/dots-hyprland/assets/2170677/0eae818b-9079-4634-803f-105914d5b90e)

**Comment by end-4** [comment]
- It's my VERY INCOMPLETE monochrome version of OneUI4-Icons 
  - You can find it here: https://github.com/end-4/OneUI4-Icons-Monochrome
  - The original can be found here: https://github.com/mjkim0727/OneUI4-Icons
