### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by AnuAnu22** [end-4/dots-hyprland#183]
- **I have read the instructions** and I have a problem with branch: everything not working??
---
## The issue
SO i  am on arch.
and installed hyprland.(all default from arch install)

I used your script ./install.sh of illogical impulse.
there were a few errors of missing files and retried and everything worked.

then it showed successful but nothing changed. I reboot using the terminal.
then when it opened it was all black. Nothing was working.
after smashing all keys while holding the super key only a few notable ones worked
Super + W
Super + Z
Super +Q
and alot of other buttons that did only two thing move from desktops 1 , 2, 1 .
cant access terminal. cant access anything other than firefox with the W.

So cant even provide anything.
Can you help?

**Comment by end-4** [comment]
> there were a few errors of missing files and retried and everything worked

- Why not take a pic of it? dont you have a phone or something? If you don't remember, you can run the script again and see what gives errors

> then when it opened it was all black. Nothing was working.

- Did you follow the note at the end of the install script (Ctrl+Super+T to select wallpaper)? 
- Did you follow the [troubleshooting steps on the wiki](https://github.com/end-4/dots-hyprland/wiki/illogical%E2%80%90impulse#steps-for-troubleshooting)? Can you show the output of that command?

**Comment by AnuAnu22** [comment]
I did all the things noted there

```

For a list of keybinds, hit Super+/

     Search
        Calculation: Type something starting with a number
        Commands: They'll be detected and shown to you if you type in.
            Performs a headless execution by default
            If the command starts with sudo, it'll be launched in foot terminal.
        Directory search: Type a directory starting with ~ or /.
            Subdirectories will be shown if the path is correct. Activating opens folder/file
            Hit enter directly on the entry to open the typed folder/file
        Actions: An actions starts with >. See the keybind cheatsheet for a list of actions
        Apps by default, of course!

Bar controls:

    Media:
        Top-right corner
            Middle-click to play/pause media, Right-click for next track
            Scroll to change volume
            Click the music pill for a controls window
    Brightness: Scroll top-left corner
    Launcher: Middle-click workspace widget
    Virtual keyboard: Right-click workspace widget

```
These dont work. 
but the window moving works.
I uninstalled arch completely and am trying to install again .

**Comment by end-4** [comment]
> I uninstalled arch completely and am trying to install again .

it is never required to reinstall for dotfiles lol

> These dont work.

okay but did you **open a terminal and run `pkill ags;ags`**

**Comment by AnuAnu22** [comment]
That's the problem.

Without the terminal and app menu.
What can I do?

**Comment by end-4** [comment]
oops
super+t, not ctrl+super+t
the former is for terminal and the latter is for wallpaper selection

**Comment by AnuAnu22** [comment]
> oops
> super+t, not ctrl+super+t
> the former is for terminal and the latter is for wallpaper selection
> if you still can't launch a terminal, go to a tty (ctrl alt f3), login and run `pacman -Q | grep foot`

I did that that time. All you said nothing worked. It was a direct hyprland install so no tty.

Now I downloaded a tty and again installed hyprland and your file with dependencies.

Still doesn't work.
Same problem only fire fox works.

But with tty I downloaded your terminal so both fire fox and tty works and nothing else

**Comment by AnuAnu22** [comment]
![IMG20240112214916.jpg](https://github.com/end-4/dots-hyprland/assets/129385032/37f0cc2e-19b6-4646-8ac1-31ec3c21d921)

![IMG20240112214912.jpg](https://github.com/end-4/dots-hyprland/assets/129385032/4cc0d2ba-4dbd-47ac-aad2-dca42b57459a)

**Comment by AnuAnu22** [comment]
Also I'm not using endeavor os
Is that the problem?

I'm using arch

**Comment by end-4** [comment]
what are you expecting me to do? you have a terminal working there, why not run the command i told you to?

endeavour os is not the problem.
