### ISSUE TITLE
[Issue] Clicking the media player does not show the preview

### ISSUE THREAD

**Issue by CrapTheCoder** [end-4/dots-hyprland#184]
- **I have read the instructions** and I have a problem with branch: illogical-impulse

## The issue
- Clicking the media player does not show the expected preview with the image and the media controls. Nothing happens when I click it. I tried restarting linux, but it didn't help.

![image](https://github.com/end-4/dots-hyprland/assets/41336229/59abefbc-ff02-4f7d-b21f-8ef9bdbdbb6b)
Clicking the above doesn't do anything.

I have installed hyprland along with EndeavourOS Gnome. It was working when I installed it around 10 days ago. Recently I reinstalled everything and followed the exact same steps, but it isn't working now.

**Comment by CrapTheCoder** [comment]
It might be worth noting that the keybinds for the media controls work. Only the preview doesn't show up

**Comment by end-4** [comment]
Known bug. I haven't really figured this out. It just broke after an AGS update. Its dev said he would do something that to make the errors clearer for easier troubleshooting but he hasn't done that yet

**Comment by CrapTheCoder** [comment]
Ahh sad. Hopefully gets fixed soon

**Comment by end-4** [comment]
ugh hey i forgot to tell you it's fixed
