### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Dialgatrainer02** [end-4/dots-hyprland#192]
[out.txt](https://github.com/end-4/dots-hyprland/files/13965499/out.txt)
- **I have read the instructions**
---
## The issue
- (describe your problem here)
- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)
ags doesnt show on boot and gives errors in the terminal this is a most fresh install minus dependency installing

**Comment by end-4** [comment]
install stuff:
```sh
yay -S ydotool gtksourceview3
```

**Comment by Dialgatrainer02** [comment]
Thank you your the best
