### ISSUE TITLE
[Issue] openai-logo, notification dismiss

### ISSUE THREAD

**Issue by Ben-Plagmann** [end-4/dots-hyprland#195]
---

- **I have read the instructions and I have a problem with the Illogical Impulse Branch**
---
## The issues
-  The openai-logomark.svg doesn't show up:

 ![no-logo](https://github.com/end-4/dots-hyprland/assets/149503466/e67d0d80-4927-430e-bcbd-e67cea1ddceb)

---

- Notifications don't dismiss automatically (fixed by ags)
- No longer relevant: (EDIT: I just managed to add it myself by modifying the script: [notification.zip](https://github.com/end-4/dots-hyprland/files/13981885/notification.zip) )

I don't know if this is intended or not. The notifications do not dismiss automatically although there is a circle around the image which seems to be intended as a count down to dismiss the message after it is finished.

![notifications-dont-dismiss](https://github.com/end-4/dots-hyprland/assets/149503466/caf00419-3537-4170-8e1f-acca3fb405dc)

**Comment by end-4** [comment]
they both broke after an ags update
there's so much to fix aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by end-4** [comment]
Logo fixed
Not sure if I can do anything about the cover arts though.

**Comment by Ben-Plagmann** [comment]
Ok thanks for the fast fix :).
