### ISSUE TITLE
ICON PROBLEM

### ISSUE THREAD

**Issue by iafshinafshin** [end-4/dots-hyprland#196]
Hey, my icon not working :
![swappy-20240118_230015](https://github.com/end-4/dots-hyprland/assets/138600371/9b01717a-1856-43db-a3d9-88141ae80a35)

and this is not worked :

![swappy-20240118_231805](https://github.com/end-4/dots-hyprland/assets/138600371/2b41ecd5-f35a-475d-9a8b-d1fd04e26d6a)

and how to resize my monitor from  verylarg or larg to medom

**Comment by Ben-Plagmann** [comment]
Did you read the readme.md? You installed one of the not maintained/broken configurations.

**Comment by iafshinafshin** [comment]
So what should i do ?

**Comment by Ben-Plagmann** [comment]
- If you want to use the configuration you installed you would have to troubleshoot it yourself (see https://github.com/end-4/dots-hyprland/blob/main/README.md ). 
- Or you could install a supported configuration: https://github.com/end-4/dots-hyprland/wiki/illogical%E2%80%90impulse

**Comment by iafshinafshin** [comment]
What desktop are you using?

**Comment by Ben-Plagmann** [comment]
I use hyprland wm.

**Comment by end-4** [comment]
Like Ben said, the config you installed is no longer maintained or supported. Consider using [illogical-impulse](https://github.com/end-4/dots-hyprland/tree/illogical-impulse), or you'll be in troubleshooting hell. _And I mean hell_, since my code back when I made those was very messy and has a lot of nesting

**Comment by iafshinafshin** [comment]
Hey, i used install script in [illogical-impulse](https://github.com/end-4/dots-hyprland/tree/illogical-impulse) and it gave me an error on line 59

**Comment by Ben-Plagmann** [comment]
Describe the error please. You are probably missing some packages.

**Comment by iafshinafshin** [comment]
Fixed my problem with install gojq .

But i can't open firefox or chromium

**Comment by iafshinafshin** [comment]
but my original's problem with firefox

**Comment by iafshinafshin** [comment]
![tmp](https://github.com/end-4/dots-hyprland/assets/138600371/edc98e50-6e1c-4322-9963-07a896c9244f)

**Comment by Ben-Plagmann** [comment]
Do you use a Nvidia GPU? I also noticed Firefox crashing sometimes with the same error but not at startup.

Can you post error logs?

**Comment by iafshinafshin** [comment]
No , i use intel GPU

**Comment by Ben-Plagmann** [comment]
Ok

- Does Firefox fail to launch at all or does it only crash sometimes?

- Can you Provide crash logs?

**Comment by clsty** [comment]
Actually, I've met some firefox crashes myself. I'm using AMD CPU and AMD GPU.
A workaround is to make firefox running under xwayland, to achieve which you can just add following line to `~/.config/hypr/env.conf`:
```conf
env=MOZ_ENABLE_WAYLAND,0
```

**Comment by end-4** [comment]
whats the point of wayland if you run the most used app in X lol

**Comment by clsty** [comment]
> whats the point of wayland if you run the most used app in X lol

Yeah, I know what you mean XD

It's just a workaround, not a solution.

I had tried many methods, e.g. switch to a new profile, use librewolf as alternative, etc.
But none of these worked. So I guess I have to bear this until it's fixed sometime in future... (not that really, because I can't tell whether my firefox is under xwayland unless I delibrately check it out)

**Comment by iafshinafshin** [comment]
Hey, i used your script in `~/.config/hypr/env.conf` and i fixed my problem with your script.
Thanks you
