### ISSUE TITLE
[Issue] install is failing because of cssutils 

### ISSUE THREAD

**Issue by BilatSlayer143** [end-4/dots-hyprland#197]
- **I have read the instructions**
---
## The issue
I dont know how to resolve this, the cssutils isnt installing, I even try installing it manualy but it fails. thank you

__________________________________________ TestErrorHandler.test_handlers __________________________________________

self = <cssutils.tests.test_errorhandler.TestErrorHandler object at 0x7ecb25247950>

    def test_handlers(self):
        "cssutils.log"
        s = self._setHandler()
    
        cssutils.log.setLevel(logging.FATAL)
        assert cssutils.log.getEffectiveLevel() == logging.FATAL
    
        cssutils.parseString('a { color: 1 }')
        assert s.getvalue() == ''
    
        cssutils.log.setLevel(logging.DEBUG)
        cssutils.parseString('a { color: 1 }')
        # TODO: Fix?
        # self.assertEqual(
        #     s.getvalue(),
        #     u'ERROR    Property: Invalid value for "CSS Color Module '
        #     'Level 3/CSS Level 2.1" property: 1 [1:5: color]\n')
        assert (
            s.getvalue() == 'ERROR    Property: Invalid value for "CSS Level 2.1" '
            'property: 1 [1:5: color]\n'
        )
    
        s = self._setHandler()
    
        try:
            socket.getaddrinfo('example.com', 80)
        except OSError:
            # skip the test as the name can't resolve
            return
    
        cssutils.log.setLevel(logging.ERROR)
        cssutils.parseUrl('http://example.com')
>       assert s.getvalue()[:38] == 'ERROR    Expected "text/css" mime type'
E       assert '' == 'ERROR    Exp...ss" mime type'
E         - ERROR    Expected "text/css" mime type

/home/endeavouros1/.cache/yay/python-cssutils/src/cssutils-2.9.0/cssutils/tests/test_errorhandler.py:124: AssertionError
------------------------------------------------ Captured log call -------------------------------------------------
ERROR    IGNORED-CSSUTILS-TEST:errorhandler.py:104 Property: Invalid value for "CSS Level 2.1" property: 1 [1:5: color]
================================================= warnings summary =================================================
cssutils/tests/test_domimplementation.py::TestDOMImplementation::test_createCSSStyleSheet
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_domimplementation.py::TestDOMImplementation::test_createCSSStyleSheet is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_domimplementation.py::TestDOMImplementation::test_createDocument
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_domimplementation.py::TestDOMImplementation::test_createDocument is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_domimplementation.py::TestDOMImplementation::test_createDocumentType
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_domimplementation.py::TestDOMImplementation::test_createDocumentType is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_domimplementation.py::TestDOMImplementation::test_hasFeature
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_domimplementation.py::TestDOMImplementation::test_hasFeature is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_encutils.py::TestAutoEncoding::test_getEncodingInfo
cssutils/tests/test_encutils.py::TestAutoEncoding::test_getEncodingInfo
  /home/endeavouros1/.cache/yay/python-cssutils/src/cssutils-2.9.0/encutils/__init__.py:652: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    log.warn(

cssutils/tests/test_value.py::TestPropertyValue::test_init
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_value.py::TestPropertyValue::test_init is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_value.py::TestPropertyValue::test_cssText
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_value.py::TestPropertyValue::test_cssText is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_value.py::TestPropertyValue::test_list
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_value.py::TestPropertyValue::test_list is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_value.py::TestPropertyValue::test_comments
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_value.py::TestPropertyValue::test_comments is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_value.py::TestPropertyValue::test_incomplete
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_value.py::TestPropertyValue::test_incomplete is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_value.py::TestPropertyValue::test_readonly
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_value.py::TestPropertyValue::test_readonly is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

cssutils/tests/test_value.py::TestPropertyValue::test_reprANDstr
  /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  cssutils/tests/test_value.py::TestPropertyValue::test_reprANDstr is using nose-specific method: `setup(self)`
  To remove this warning, rename it to `setup_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    fixture_result = next(generator)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================= short test summary info ==============================================
FAILED cssutils/tests/test_errorhandler.py::TestErrorHandler::test_handlers - assert '' == 'ERROR    Exp...ss" mime type'
============================== 1 failed, 400 passed, 43 xfailed, 13 warnings in 3.70s ==============================
==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: python-cssutils-exit status 4
==> Making package: gradience-git 0.3.1.r2.ge5dd5c9-1 (Fri 19 Jan 2024 07:27:17 PM PST)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> python-cssutils
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
 -> error making: gradience-git-exit status 8
 -> Failed to install the following packages. Manual intervention is required:
python-cssutils - exit status 4
gradience-git - exit status 8
[./install.sh]: Command "yay -S --needed adw-gtk3-git gradience-git swww fontconfig lexend-fonts-git ttf-jetbrains-mono-nerd ttf-material-symbols-variable-git ttf-space-mono-nerd fish foot starship" has failed.
You may need to resolve the problem manually BEFORE repeating this command.

**Comment by end-4** [comment]
¯\_(ツ)_/¯
i can install it just fine
does `yay -S python-cssutils` work?

**Comment by end-4** [comment]
no no no
+KDE or +GNOME doesn't matter 
I'm on EndeavourOS+KDE in fact.

**Comment by BilatSlayer143** [comment]
Really? It's been an issue for me since im actually trying to install your dotfiles since december. I don't know why, but it's the same issue. Even in the vanilla arch the same issue persists. I think im just unlucky lol.

**Comment by clsty** [comment]
The package you're about to install is an AUR package.

AUR package is not officially supported by Arch Linux. Although, you may require support at its webpage: <https://aur.archlinux.org/packages/python-cssutils>

Also, `yay` is NOT the only AUR helper. You may try `paru` as well.
```bash
yay -S --needed --noconfirm paru-bin
paru -S --needed python-cssutils
```

**Comment by iafshinafshin** [comment]
![tmp](https://github.com/end-4/dots-hyprland/assets/138600371/61ea69eb-686f-42da-9359-cf67a4295a20)

**Comment by Iridule** [comment]
Same issue here the above method also does not work

**Comment by Iridule** [comment]
I managed to fix my issue as I needed dependencies that yay nor paru would pull which were `python-setuptools-scm  python-wheel` after I got those all worked.

**Comment by BilatSlayer143** [comment]
Yeah, thank you so much. This actually fixed the issue for me.

**Comment by clsty** [comment]
Closing since it was fixed.
