### ISSUE TITLE
Complete freeze after exit/logout

### ISSUE THREAD

**Issue by rabaimor** [end-4/dots-hyprland#201]
(NOOB ALERT)
(my first time trying linux ever, I've been using kde plasma with xorg and sddm for two weeks, then I decided to try this)

After I exit either I get a stuck on black screen, or I can't use kde plasma until restart. So I can hop from plasma to hyprrland easily, but if I try try to log back into plasma after hyperland it just gets stuck on the loading screen until a reboot.

If I log out using ctrl+alt+del I get the blackscreen, and if I log out using hyprctl dispatch exit I can't log back into kde plasma (until reboot)

(This is on vanilla arch)

**Comment by clsty** [comment]
There're several ways to exit hyprland.
I'll list some of them here.

- `killall Hyprland`
- `loginctl terminate-user $USER`
- `hyprctl dispatch exit`

I recommend you to try `killall Hyprland` and `loginctl terminate-user $USER`.

Also, I think you'd better provide more info about how you start kde and hyprland, like, by sddm, lightdm, etc., or by directly execute `hyprland` for hyprland in tty, etc.

**Comment by RookiexCookie** [comment]
@clsty  isnt it Hyprland in tty?

**Comment by rabaimor** [comment]
> There're several ways to exit hyprland. I'll list some of them here.
> 
> * `killall Hyprland`
> * `loginctl terminate-user $USER`
> * `hyprctl dispatch exit`
> 
> I recommend you to try `killall Hyprland` and `loginctl terminate-user $USER`.
> 
> Also, I think you'd better provide more info about how you start kde and hyprland, like, by sddm, lightdm, etc., or by directly execute `hyprland` in tty (for hyprland), etc.

"killall Hyprland" Turns my monitor off until restart
"loginctl terminate-user $USER" Does the black screen I described before (same as the ctrl+alt+del logout)
"hyprctl dispatch exit" logs me out fine, but after that I use plasma, it doesn't load my desktop

Also I use sddm to log in, or switch between kde and hyprland

**Comment by clsty** [comment]
> @clsty isnt it Hyprland in tty?

@RookiexCookie You're right. That's a typo. Fixed.

@rabaimor I guess sddm may be the cause. You may use another tty and launch the directly in that tty instead.

To achieve this, you may press `Ctrl+Alt+F2` to switch to tty2 (And `Ctrl+Alt+F1` to tty1 as well).
Then, login and execute `Hyprland` to launch hyprland.
As for kde plasma, see [ArchWiki](https://wiki.archlinux.org/title/KDE#From_the_console).

**Comment by end-4** [comment]
In my experience the loginctl terminate thing will cause that if youre using sddm

**Comment by rabaimor** [comment]
Thanks for the responses. What do you recommend for an sddm replacement, that wouldn't have these issues?

**Comment by clsty** [comment]
Personal recommendation, just tty. Not eye-catching, but it's (nearly?) always the most stable one.

**Comment by end-4** [comment]
i use greetd+tuigreet
same as above, but it has an option to remember last logged in user

**Comment by rabaimor** [comment]
Okay, thanks. I just need to start Hyprland from tty and it will work fine. I still use sddm for plasma, since I can't launch plasma from tty for some reason, but thats a problem for another day.

Thanks for all the help, I really appriciate it.
