### ISSUE TITLE
[Issue] Nor >img neither Ctrl Win T permanently changed the wallpaper

### ISSUE THREAD

**Issue by ShadeZerox** [end-4/dots-hyprland#206]
- **I have read the instructions**
---
## The issue
After changing wallpaper from both CTRL + WIN + T or/and >img, the wallpaper does change but the change is not permanent. (by not permanent, I mean that the wallpaper gets removed everytime I log out or reboot)
(if thats the expected behavior how should I make my wallpaper permanent?)

**Comment by end-4** [comment]
try again

**Comment by ShadeZerox** [comment]
Works after adding those commands to the config, Thanks!
