### ISSUE TITLE
[Issue] wallpapers aren't working

### ISSUE THREAD

**Issue by scatcat5isdead** [end-4/dots-hyprland#207]
- **I have read the instructions**
---
## The issue
- (describe your problem here)
- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)
i ran the script it asked me to install gvc and typescript and i did but when its installed wallpapers dont work and theme changes gives me a hyprland may not work correctly error

**Comment by scatcat5isdead** [comment]
the drive and ram statuses and the clock doesnt work either nothing is there

**Comment by scatcat5isdead** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/113935053/0a5f4b80-2470-44e9-9d27-aa7dc91627e5)

**Comment by end-4** [comment]
Please show the error you had in the install script. Run it again then paste the logs here

**Comment by JakeEgler** [comment]
I am having the same issue.  How can I find the install logs?

**Comment by end-4** [comment]
So it's solved? If that's the case, you should close the issue

**Comment by Iridule** [comment]
I had this issue and had to reinstall swww it seemed to fix it not sure why

**Comment by scatcat5isdead** [comment]
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?) this is the error i get

**Comment by end-4** [comment]
> HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?) this is the error i get

unrelated to this issue. and it's your hyprland issue. please consult its wiki or ask in its discord server
