### ISSUE TITLE
[Issue] install script not working 

### ISSUE THREAD

**Issue by Iridule** [end-4/dots-hyprland#211]
Arch install script fails to build python-cssutils and gradience-git. Manual install failed as well...Hyprland loads to blank desktop with very limited functionality.

**Comment by clsty** [comment]
I just tested on my own system (Arch Linux), installed these two packages with `paru`. It works fine for me.

I suggest you to cleanup the build cache:
```bash
rm -rf ~/.cache/yay/{python-cssutils,gradience-git}
```
and then try again.

If it fails again, please post the error message.
And also please provide the output of:
```bash
lsb_release -a
```

**Comment by Iridule** [comment]
I've also tried paru...it still fails.  I am trying on a vanilla install of arch running lxde the upstream link recommend "python-css-parser" https://aur.archlinux.org/packages/python-cssutils

**Comment by clsty** [comment]
> the upstream link recommend "python-css-parser" https://aur.archlinux.org/packages/python-cssutils

That's a very old comment, but you can still try it by editing `scriptdata/dependencies.txt`, but risk on your own.

**Comment by Iridule** [comment]
Also lsv_release -a
LSB Version' n/a
Distributor ID: Arch
Description: Arch Linux
Release: rolling
Codename: n/a

**Comment by Iridule** [comment]
@clsty I fixed the issue ...python-setuptools-scm and python-wheel were needed neither paru nor yay got these dependencies...

**Comment by clsty** [comment]
> @clsty I fixed the issue ...python-setuptools-scm and python-wheel were needed neither paru nor yay got these dependencies...

That's strange... `python-setuptools-scm` and `python-wheel` are already listed as make dependencies on the [page](https://aur.archlinux.org/packages/python-cssutils), which means AUR helpers should install them automatically.

Anyway, since you've solved the problem, you may close this issue.

**Comment by Iridule** [comment]
Ok I do have another issue things seem to work but are way over sized...I can't read the entire cheat sheet or see the entire menu bar at the top nor do the chat GPT and Google Gemini icons look the proper size.

**Comment by clsty** [comment]
> Ok I do have another issue things seem to work but are way over sized...I can't read the entire cheat sheet or see the entire menu bar at the top nor do the chat GPT and Google Gemini icons look the proper size.

This is another issue. Refer to https://github.com/end-4/dots-hyprland/issues/180#issuecomment-1880385893 first, and if it does not solve your problem, please open another issue.
