### ISSUE TITLE
[Issue] Overview panel broken for multi monitor

### ISSUE THREAD

**Issue by midn8hustlr** [end-4/dots-hyprland#212]
- **I have read the instructions**
---
## The issue
- Overview for external monitor broken after commit [286f35e03ad0220a8aa34329926cd503f3dd00e6] 
- Overview panel and Icons are bigger than usual
- For primary screen it is okay (even if i am in ws group 11-20)
- Only affected when when connected to external monitor

Primary Screen (1920x1080)
![image](https://github.com/end-4/dots-hyprland/assets/47367711/1cf2ed76-e9d0-4da7-9e75-9cd97a9befe4)
External Monitor (1920x1080)
![image](https://github.com/end-4/dots-hyprland/assets/47367711/aa28f18e-28be-428a-affb-f6e0b0de26df)

Log seems normal

`
(com.github.Aylur.ags:21997): Gjs-WARNING **: 21:14:56.491: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

(com.github.Aylur.ags:21997): Gjs-WARNING **: 21:14:56.499: JS ERROR: TypeError: (intermediate value).config is undefined
_cacheCoverArt@resource:///com/github/Aylur/ags/service/mpris.js:137:13
_updateState@resource:///com/github/Aylur/ags/service/mpris.js:133:14
MprisPlayer@resource:///com/github/Aylur/ags/service/mpris.js:85:14
_addPlayer@resource:///com/github/Aylur/ags/service/mpris.js:225:24
_onProxyReady@resource:///com/github/Aylur/ags/service/mpris.js:246:22
async*wrapper/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:251:36
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

Gjs-Console-Message: 21:14:56.617: [LOG] Styles loaded

(com.github.Aylur.ags:21997): Gtk-WARNING **: 21:14:56.817: Attempting to add a widget with type Ags_AgsScrollable to a container of type Ags_AgsBox, but the widget is already inside a container of type Ags_AgsBox, please remove the widget from its existing container first.

(com.github.Aylur.ags:21997): Gtk-WARNING **: 21:14:56.920: Attempting to add a widget with type Ags_AgsRevealer to a container of type Ags_AgsBox, but the widget is already inside a container of type Ags_AgsBox, please remove the widget from its existing container first.

`

**Comment by end-4** [comment]
My config doesn't even have overview enabled on multiple monitors though? If you try to do add that `forMonitors` loop yourself it won't just magically work

**Comment by end-4** [comment]
does the above fix it

**Comment by midn8hustlr** [comment]
> does the above fix it

Yes, but the floating windows at corners of any monitor (except primary) will have the same effect as you have mentioned [here](https://github.com/end-4/dots-hyprland/pull/221#issuecomment-1923715894).
However the primary issue is resolved. Thanks!
Closing this in favor of new PR #232
