### ISSUE TITLE
[Issue]Hyprland keeps using a sustained 5% cpu while Hyprland barebones has no such issue

### ISSUE THREAD

**Issue by RipDr19** [end-4/dots-hyprland#213]
- **I have read the instructions**
---
## The issue
- (describe your problem here)
- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)

**Comment by end-4** [comment]
see if it's fixed

**Comment by RipDr19** [comment]
yeah I found it was because of the first wl-paste command "wl-paste -p --watch wl-copy -p """, I highlighted it out in my exec.conf and boom everything is fine, I guess somehow gradience-git also build itself or something and now material colours works again, thanks for this beautiful and lovely hyprland dots man, they might just be my most fav dots, just one question, since I don't wanna open another issue for my own doubt and that is do I need a custom key or api to use chatgpt or gemini? and if so, where do I need to put it?

**Comment by end-4** [comment]
If you have more questions, feel free to open a discussion

**Comment by RipDr19** [comment]
Cool man big thanks again
