### ISSUE TITLE
[Issue] Some multiple notifications not all disappear automatically

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#215]
- **I have read the instructions**
---
## The issue
- Linux distro: Arch Linux

This issue was a part of #195 but still exists:

> If multiple notifications are shown at once only one of them is closed automatically and the others have to be closed manually. (probably ags issue)

I receive notification every time when I operate the music player (clementine), so I often see multiple notifications.
Because of this, I have to keep using `silence` mode, which makes notification system actually not usable to me.

**Comment by clsty** [comment]
Update: I've noticed that only clementine (and maybe others) will result in such weird behavior.

This command:
```bash
notify-send -t 1 test
```
will create a notification that NOT auto-disappear.
Same if repeat multiple times quickly.

This command:
```bash
notify-send -t 3000 test
```
will create a notification that auto-disappear.
Same if repeat multiple times quickly.

And for clementine, when toggle pause/play just once, it will create a notification that auto-disappear.
But if quickly repeat it, then the 2nd,3rd,... times will NOT auto-disappear.

**Comment by end-4** [comment]
- I finally fixed spamming message of notifs on destroy woooooo
  - Somehow that fixed the timeout 1 too. Can you confirm? 
  - If it doesn't work, there's a fallback of 3s or 8s depending on urgency to make sure notifs eventually go away

- The only problem now is that ags doesn't provide any way to get the notif's timeout, so I can't animate the circular progress correctly. But I'll see what the dev says about it

**Comment by end-4** [comment]
okay there is a timeout property
it's just not documented

**Comment by clsty** [comment]
I've updated to latest and the problem still persist.

To reproduce this, install strawberry (a fork of Clementine but NOT need AUR):
```bash
sudo pacman -S strawberry
```
Open strawberry, open a music file in `Files` and play it.
Toggle pause/play quickly several times.
You'll find that the first notif disappears automatically, while the rest of them will NOT.

**Comment by end-4** [comment]
fixed

**Comment by clsty** [comment]
Yeah it works! Thanks!
