### ISSUE TITLE
[Issue] Wrong result on powers in the searchbar math

### ISSUE THREAD

**Issue by SpendIce** [end-4/dots-hyprland#217]
I tried using the searchbar's calculator for some quick math, but the result of doing the power of something is incorrect. Doing the multiplication works, I believe it doesn't recognize the ^ operator, I mean it detects it as a math operator, but I believe it does sum with no decimals or substraction.
![image](https://github.com/end-4/dots-hyprland/assets/62260972/1ab67a5a-ff3a-4890-9dd9-1b64881d4794)
![image](https://github.com/end-4/dots-hyprland/assets/62260972/35d77395-0c12-4930-a722-f897359933d9)
![image](https://github.com/end-4/dots-hyprland/assets/62260972/241ca1fb-aa1c-484f-8f46-4b4e62ea1773)

**Comment by end-4** [comment]
- `^` is XOR, not power
- `**` is power
- The math is calculated by a Javascript evaluation and I can't be bothered to write my own math parser/calculator
  - Maybe I should replace all occurence of `^` with `**` then

**Comment by SpendIce** [comment]
That would be great, thanks!
