### ISSUE TITLE
[Feature] Music <- + Memory usage  |  Battery fallback=weather

### ISSUE THREAD

**Issue by end-4** [end-4/dots-hyprland#220]
## What would you like to be added?
- Title
- As suggested in #219

## How will it help
- Makes left side of bar not too empty

**Comment by clsty** [comment]
My personal suggestion:
If `~/.cache/ags/user/barcmd.sh` exists, then execute this command and show its output every `$(cat ~/.cache/ags/user/barcmd-t.txt)` seconds.

**Comment by end-4** [comment]
Thanks for the suggestion
Fine I guess, though I don't really care about that. The point of using ags is to *not* use polling shell scripts.

**Comment by end-4** [comment]
the way i'll be implementing polls but doesn't need a script, just a command

**Comment by clsty** [comment]
About city for weather, I suggest that we could read an environment variable such as `$AGS_WEATHER_CITY` to override.

**Comment by end-4** [comment]
i forgot to close this

**Comment by clsty** [comment]
> My personal suggestion: If `~/.cache/ags/user/barcmd.sh` exists, then execute it and show its output every `$(cat ~/.cache/ags/user/barcmd-period.txt)` (default 5000) miliseconds.
> 
> By supporting this, user will be able to custom this area.
> 
> And it could be even more powerful:
> 
>     * If `~/.cache/ags/user/barcmd-leftclick.sh` exists, then execute it when leftclick on it.
> 
>     * If `~/.cache/ags/user/barcmd-rightclick.sh` exists, then execute it when rightclick on it.
> 
>     * ...

@end-4 However I still want this one because I'm familiar with bash scripting lol

I will not submit such code to this repo of course, but I want to use it in my own version of config, and I can add document to the wiki on how to do it (or maybe you could add this document).

**Comment by end-4** [comment]
oops then

**Comment by end-4** [comment]
@clsty try it
if you're happy close the issue

**Comment by clsty** [comment]
Very nice. Would you please allow custom polling period (and default 5000 ms when not customed)?

**Comment by clsty** [comment]
Very nice. Would you please allow customed polling period (and default 5000 ms when not customed)?

**Comment by end-4** [comment]
done
