### ISSUE TITLE
[Issue] GTK_IM_Module set?

### ISSUE THREAD

**Issue by Iridule** [end-4/dots-hyprland#222]
I get a Wayland diagnostic notification saying "GTK_IM_MODULE being set and Wayland input method frontend is working. It is recommended to unset GTK_IM_MODULE."

I've tried adding the lines below to ~/.bash_profile but same notification appears after login. 
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

**Comment by clsty** [comment]
What's your output when run
```bash
echo $GTK_IM_MODULE
```
?

Also please check `~/.config/hypr/env.conf`, where environment variables including `GTK_IM_MODULE` are defined.

**Comment by clsty** [comment]
I don't know but maybe you're using ibus and not fcitx5?

**Comment by Iridule** [comment]
I'm at a loss on what to do or how it impacts my setup. I've noticed some times of an app like vlc is open the keyboard won't work and the right mouse button doesn't work...not sure if these things are related to the diagnostic message or not

**Comment by clsty** [comment]
I guess you need to install the input method first, since they are not listed in `scriptdata/dependencies.txt`:
```bash
sudo pacman -S fcitx5{,-{qt,lua,rime,configtool,gtk}} ibus
```

Or, if you don't need input method, you can just remove the related lines in `~/.config/hypr/env.conf` and `~/.config/hypr/execs.conf`.

**Comment by Iridule** [comment]
@clsty I installed those packages yet the issue persists....
![IMG_20240131_211013397~2](https://github.com/end-4/dots-hyprland/assets/135180769/d9dcf0de-e9ef-4d58-87ed-5abf1ab153e3)

**Comment by clsty** [comment]
From <https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland>:

> For GTK_IM_MODULE, as for now, the modern Gtk 3/4 application should be able to use text-input-v3 which is supported almost by every compositor, except weston. There are a few different options in terms of setting the value of GTK_IM_MODULE. When it is unset, the Gtk built-in Wayland im module will be used for Gtk3 and Gtk4. While you can also enforce it by doing GTK_IM_MODULE=wayland, remember it will be also picked up by Gtk2. Setting GTK_IM_MODULE=fcitx can still work, and it is necessary if your compositor does not support Wayland input method frontend.

**Comment by clsty** [comment]
I guess you can just remove the `GTK_IM_MODULE` lines in hyprland's config as I mentioned before.

**Comment by clsty** [comment]
And there's another possibility that fcitx5 think you're in sway, not hyprland.

Notice that:
```cpp
    } else {
        // It is not clear whether compositor is supported, only warn if wayland
        // im is being used..
        if (isWaylandIM) {
            // Sway's input popup is not merged.
            if (!gtkIM.empty() && gtkIM != "wayland" &&
                desktop != DesktopType::Sway) {
                messages.push_back(
                    _("Detect GTK_IM_MODULE being set and "
                      "Wayland Input method frontend is working. It is "
                      "recommended to unset GTK_IM_MODULE "
                      "and use Wayland input method frontend instead."));
            }
        }
```

**Comment by clsty** [comment]
As for `$`, it's [here](https://github.com/fcitx/fcitx5/blob/2a9f7011a6b9eb01d66f50bcc8cfa41d2f732aef/src/lib/fcitx/misc_p.h#L127-L185):

<details>

<summary>Click to expand</summary>

```h
static inline DesktopType getDesktopType() {
    std::string desktop;
    // new standard
    auto *desktopEnv = getenv("XDG_CURRENT_DESKTOP");
    if (desktopEnv) {
        desktop = desktopEnv;
    }
    if (desktop.empty()) {
        // old standard, guaranteed by display manager.
        desktopEnv = getenv("DESKTOP_SESSION");
        if (desktopEnv) {
            desktop = desktopEnv;
        }
    }


    for (auto &c : desktop) {
        c = charutils::tolower(c);
    }
    auto desktops =
        stringutils::split(desktop, ":", stringutils::SplitBehavior::SkipEmpty);
    for (const auto &desktop : desktops) {
        if (desktop == "kde") {
            auto *version = getenv("KDE_SESSION_VERSION");
            auto versionInt = 0;
            if (version) {
                try {
                    versionInt = std::stoi(version);
                } catch (...) {
                }
            }
            if (versionInt == 4) {
                return DesktopType::KDE4;
            }
            return DesktopType::KDE5;
        } else if (desktop == "x-cinnamon") {
            return DesktopType::Cinnamon;
        } else if (desktop == "lxde") {
            return DesktopType::LXDE;
        } else if (desktop == "mate") {
            return DesktopType::MATE;
        } else if (desktop == "gnome") {
            return DesktopType::GNOME;
        } else if (desktop == "xfce") {
            return DesktopType::XFCE;
        } else if (desktop == "deepin") {
            return DesktopType::DEEPIN;
        } else if (desktop == "ukui") {
            return DesktopType::UKUI;
        } else if (desktop == "sway") {
            return DesktopType::Sway;
        }
    }
    return DesktopType::Unknown;
}


static inline bool isKDE() {
    static const DesktopType desktop = getDesktopType();
    return desktop == DesktopType::KDE4 || desktop == DesktopType::KDE5;
}
```

</details>

**Comment by clsty** [comment]
Please run:
```bash
echo "1=$XDG_CURRENT_DESKTOP"
echo "2=$DESKTOP_SESSION"
```
and paste your output.

**Comment by Iridule** [comment]
I tried to add the values below to ~/.bash_profile
But no change...I will try to remove the lines in Hyprland config...I suppose I could just dismiss the message as well yet that doesn't solve the problem.

export GTK_IM_MODULE=
export QT_IM_MODULE=wayland
export XMODIFIERS=@im=wayland

**Comment by clsty** [comment]
Well... Firstly, I hardly see people add these lines into `~/.bash_profile` when using hyprland, so I recommend you to just remove all related lines there.

Secondly, you mentioned there're vlc problems so I guess `$XDG_CURRENT_DESKTOP` may matters. Somewhere in your setup may be broken.

**Comment by Iridule** [comment]
> Please run:
> 
> ```shell
> echo "1=$XDG_CURRENT_DESKTOP"
> echo "2=$DESKTOP_SESSION"
> ```
> 
> and paste your output.

1=Hyprland 2=hyprland

**Comment by clsty** [comment]
And I forgot to mention that `~/.bash_profile` affect your shell, but maybe not other programs, so you need to clear those lines in `~/.bash_profile` first before running
```bash
echo "1=$XDG_CURRENT_DESKTOP"
echo "2=$DESKTOP_SESSION"
```
to get the "real" values.

**Comment by clsty** [comment]
And there may be `xdg-desktop-portal` problems. What's your output of
```bash
pacman -Q|grep xdg-desktop-portal
```
?

**Comment by Iridule** [comment]
Echo results are the same here is the additional output...
![Uploading IMG_20240131_224043817.jpg…]()

**Comment by Iridule** [comment]
![IMG_20240131_224043817](https://github.com/end-4/dots-hyprland/assets/135180769/ac8cfb72-7109-441c-bd32-9479fafc6b1f)

**Comment by clsty** [comment]
Ok, so let me summarize what for now:

## Problems
1. You're using `~/.bash_profile` for environment variable.
It may only affect your shell, not affect some programs, such as fcitx5,
which makes your `$XDG_CURRENT_DESKTOP` seems good in shell but actually broken.
(fcitx5 thinks it's Sway.)

2. You're using different `xdg-desktop-portal`s which will conflict with each others.

## Try to resolve
1. Add the following line to `~/.config/hypr/env.conf`:
```conf
env = XDG_CURRENT_DESKTOP, Hyprland
```
2. Run:
```bash
sudo pacman --noconfirm -Rdd xdg-desktop-portal-gnome
```
3. Reboot your computer.

**Comment by Iridule** [comment]
Ok desktop portal output 3 has changed to hyprland 1.3.1-2
Other values are the same asy previous post.  3 total listings for pacman -Q|grep xdg-desktop-portal 
Also I noticed at the top of the `~/.config/hypr/env.conf` file there was a section for input method with all options set to fcitx. I removed the first option and set GTK_IM_MODULE as empty, this for rid of the diagnostic notification from before. Thanks for your help. Though I'm not sure env variable in `~/.config/hypr/env.conf` is even needed ?

**Comment by Iridule** [comment]
![IMG_20240131_234315766](https://github.com/end-4/dots-hyprland/assets/135180769/f17de65a-3d24-4d35-ba08-2ab252a44f23)

**Comment by clsty** [comment]
As I mentioned before, the output is from shell, which might be different from other programs e.g. vlc and fcitx5.

`~/.config/hypr/env.conf` is recommended for editing environment variables.
I suggest you to stop using `~/.bash_profile` for such purpose.

**Comment by Iridule** [comment]
@clsty 
I was using the bash_profile because it was mentioned here https://fcitx-im.org/wiki/Configure_(Other)

**Comment by clsty** [comment]
Update: I may have mistaken something.
`xdg-desktop-portal-gnome` and `-kde` are conflicting with `-hyprland` and `-wlr` before, e.g. https://github.com/hyprwm/Hyprland/discussions/2041

But I can't find such description anymore on <https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/>, so I guess they're NOT conflicting anymore due to some updates.

**Comment by Iridule** [comment]
I have not noticed any issue. All seems to work well.
