### ISSUE TITLE
[Issue] the chat-gpt assistant side bar looks wayy too enlarged after i updated my system today. 

### ISSUE THREAD

**Issue by notLonelySoul** [end-4/dots-hyprland#226]
- **I have read the instructions**
---
## The issue
- Linux distro: Endeavour OS
- The left sidebar ui is suddenly way too zoomed in after i updated my system today.

![This is how it looks](https://github.com/end-4/dots-hyprland/assets/108740082/a7cf90b3-1c76-42e6-9af4-18a53dceb380)

**Comment by end-4** [comment]
hit Ctrl+Super+R to reload
Either your machine is really slow or you got extremely unlucky today

**Comment by notLonelySoul** [comment]
😭😭😭😭
I hit Ctrl+Super+R and AGS did reload but it still remains the same 😭

**Comment by notLonelySoul** [comment]
for me it still remains the same. All u did was change the gnome font, how will that affect the large size of the buttons.

I just saw that its the buttons that are way too enlarged. Could you please tell me the file to config so i can try to find and fix it ?

**Comment by Iridule** [comment]
for me that fixed my entire setup. not sure maybe @clsty can help?

**Comment by clsty** [comment]
Sorry but I have no idea.

**Comment by notLonelySoul** [comment]
> @notLonelySoul maybe you can run:
> pkill ags;ags

This is the output that i get: 
![Output](https://github.com/end-4/dots-hyprland/assets/108740082/c120b6fe-a509-49b4-b94e-3e3955beb4b2)

**Comment by notLonelySoul** [comment]
I fixed it by following this fix posted here. #225. Thank you guys.
