### ISSUE TITLE
[Issue] no option to change time to 12h ?

### ISSUE THREAD

**Issue by Iridule** [end-4/dots-hyprland#228]
How do I get the time to be 12h instead of 24 on sddm, ags lockscreen and the dock bar?

**Comment by clsty** [comment]
For AGS bar, you should edit `~/.config/ags/widgets/bar/system.js`.

Find `"%H:%M"` there and change it to what you like.
As for format, refer to [this page](https://docs.gtk.org/glib/method.DateTime.format.html).

**Comment by Iridule** [comment]
@clsty 
I assumed it was somewhere in those locations, thanks for the tip. I found the sddm clock settings as well in my case `/usr/share/sddm/themes/elarunMain.qml`   however I am still having an issue with logout not working from Hyprland it only goes to blackscreen with blinking cursor

**Comment by Iridule** [comment]
it seem that `/usr/lib/systemd/systemd-login` is getting stuck when clicking logout or `loginctl terminate-user XXXX` if i go to tty3 and kill `/usr/lib/systemd/systemd-login ` sddm shows up again.

**Comment by Iridule** [comment]
update* logout works fine in lxde but logout from hyprland still freezes

**Comment by end-4** [comment]
> it seem that /usr/lib/systemd/systemd-login is getting stuck when clicking logout or loginctl terminate-user XXXX

Huh i though i fixed this some time ago.... It's an `sddm` skill issue. Changing that logout command to `pkill Hyprland` fixes

**Comment by Iridule** [comment]
@end-4 Thanks. Logout works by changing `{ App.closeWindow('session'); execAsync(['bash', '-c', 'systemctl terminate-user $USER ']) });` to `{ App.closeWindow('session'); execAsync(['bash', '-c', 'pkill Hyprland']) });` in "sessionscreen.js found in `~/.config/ags/widgets/session  ` however terminate-user was working a few days ago? Not sure what happened?

**Comment by clsty** [comment]
I'm closing this issue since end-4 already switched to `pkill Hyprland`.

For time/date format, now you can directly configure it by editing `~/.config/ags/user_options.js`. See [Wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/#set-date-and-time-format).
