### ISSUE TITLE
color picker not working properly

### ISSUE THREAD

**Issue by Iridule** [end-4/dots-hyprland#230]
I have multiple permission denied trying to run 
` .config/ags/scripts/color_generation/switchcolor.sh`...choosing background works but theme will not change and color picker does not work ...
```shell
Permission denied
sed: couldn't open temporary file /home/iridule/.config/fuzzel/sed5iaJqU: Permission denied
sed: couldn't open temporary file scripts/templates/gradience/sedoe1p8G: Permission denied
sed: couldn't open temporary file /home/iridule/.config/fuzzel/sed2Mbc3U: Permission denied
sed: couldn't open temporary file scripts/templates/gradience/sedRLMUDp: Permission denied
sed: couldn't open temporary file scripts/templates/gradience/sed58SmE9: Permission denied
sed: couldn't open temporary file /home/iridule/.config/fuzzel/sedpCv
```

**Comment by clsty** [comment]
I guess it's not a issue related to this repo...
Please refer to <https://wiki.archlinux.org/title/Users_and_groups#Permissions_and_ownership> to fix those permissions first.

**Comment by Iridule** [comment]
@end-4 chown fixed it. Color picker works now. Thank you.

**Comment by clsty** [comment]
Welp, since `chown` fixed the problem, it's very possible that you have messed up with permission and ownership somewhere... 

E.g. maybe you have misused `sudo` (which can be fixed by `chown`) or abuse `chmod 777` (which can be fixed somehow but is hard to entirely fix).

This can cause many **weird** problems in your system, not only for setup of Hyprland.

And, for color picker in AGS bar... Again, you need to provide more info about it (such as run `pkill ags;ags` and paste output if there're any errors), not just say "not working" because hence its reason could be anything and no one could figure out what's happening.

**Comment by Iridule** [comment]
not sure how permissions would be messed with this is a new install of Arch I only have used it to test install Hyprland I only have used sudo a few times when installing some things with pacman to get the system usable. 
`pkill ags;ags` (seems to be no errors...

Gjs-Console-Message: 10:07:11.407: [LOG] Styles loaded

**Comment by clsty** [comment]
> seems to be no errors

And what happened when you click color picker on AGS bar? such as new output

**Comment by Iridule** [comment]
@clsty there was no output

**Comment by clsty** [comment]
You may fix those permissions from paccheck, but it may not related to the color picker problem.

**Comment by Iridule** [comment]
I noticed if i run hyprpicker from terminal it cathces the color code. Shouldn't it change the theme? Can I change the line in `/home/iridule/.config/ags/widgets/barsessionscreen.js` from hyperpicker to  `.config/ags/scripts/color_generation/switchcolor.sh` ?

**Comment by Iridule** [comment]
update* this method did work i changed 
```javascript
       UtilButton({
            name: 'Color picker', icon: 'colorize', onClicked: () => {
                Utils.execAsync(['hyprpicker', '-a']).catch(print)
            }
``` 
to 
```javascript
UtilButton({
    name: 'Color picker',
    icon: 'colorize',
    onClicked: () => {
        Utils.execAsync(['.config/ags/scripts/color_generation/switchcolor.sh', '-a']).catch(print);
    }
```

**Comment by clsty** [comment]
I'm closing this issue since the misuse of sudo has been prevented by install script. And for the other issue here,

> perhaps I misunderstand how hyperpicker works?

It's just a color picker and will not change the theme.
