### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by pierre-rs** [end-4/dots-hyprland#231]
Hello!

Please, could you share the wallpaper presented in the preview image in [https://github.com/end-4/dots-hyprland](https://private-user-images.githubusercontent.com/97237370/293474372-abd05702-a248-4f53-ac82-500219aa19f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDY3MzUsIm5iZiI6MTcwNjkwNjQzNSwicGF0aCI6Ii85NzIzNzM3MC8yOTM0NzQzNzItYWJkMDU3MDItYTI0OC00ZjUzLWFjODItNTAwMjE5YWExOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDIwNDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZjkxZGViNjg1MWY5YWZhY2IzNGZkMTZkZjcyM2Y5ZjM2YjM0NjUxZWRiYjExYmQ1MDA3MWEyZWQ5NjY3YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pVT-vlsvXkpqP4YvxRWuBU0WYYhvW6SRgUcJ08Z-LT8) ?

![Screenshot from 2024-02-02 17-48-58](https://github.com/end-4/dots-hyprland/assets/57575719/07be870d-7b72-4a88-8c27-54f0de99c107)

**Comment by end-4** [comment]
https://unsplash.com/photos/background-pattern-fahoKISAg08

**Comment by VenomLightpro** [comment]
can you send all your wallpapers please
