### ISSUE TITLE
different AGS bar?

### ISSUE THREAD

**Issue by Iridule** [end-4/dots-hyprland#235]
not sure what changed however I installed illogical-impulse on my desktop and now there is a weather section and a system monitor on the AGS bar but no color picker or screencut tool like on my laptop? has the repo changed?

**Comment by end-4** [comment]
laptop shows different stuff since it doesn't have battery

**Comment by end-4** [comment]
hit super+/ for a list of keybinds
you should find ones for color picker and screen snip there

**Comment by Iridule** [comment]
Yeah I found the key bondings I was just wondering why the AGS bar was different? Is there a difference between hyprland-git and Hyprland?

**Comment by end-4** [comment]
ags is ags and hyprland is hyprland
new ram indicators because i added, it's that simple
