### ISSUE TITLE
[Issue] Text not appearing correctly in sideleft widget (Gemini Pro)

### ISSUE THREAD

**Issue by NextStep-IM** [end-4/dots-hyprland#239]
- **I have read the instructions**
---
## The issue
- Linux distro: Arco Linux
- The text appears unmodified in the sideleft widget when I use Gemini. The html code appears along with the text.

<details>
<summary>Click to expand</summary>

The text appears correctly right after ags restart but goes awry after further usage.

![2024-02-06_00-35](https://github.com/end-4/dots-hyprland/assets/140648058/94f8fae3-a615-40a8-8091-d2a8f6f3e56c)

![2024-02-06_01-45](https://github.com/end-4/dots-hyprland/assets/140648058/6ad69356-120d-4b71-a59e-a60a296184d4)

</details>

**Comment by clsty** [comment]
It frequently happen for me too.

**Comment by end-4** [comment]
Can confirm
It's weird how this doesn't seem to ChatGPT.... I wonder if adding a newline at the end of every paragraph will help

**Comment by clsty** [comment]
> It's weird how this doesn't seem to happen with the ChatGPT one.... I wonder if adding a newline at the end of every paragraph will help

I can confirm that they are actually the same for me.

**Comment by end-4** [comment]
Okay I admit I no longer use chatgpt that much, maybe that's why I didn't notice xd
But this seems to happen when Pango tags (those xml `<tags>`) are used after bulletpoint lines

**Comment by end-4** [comment]
- That should fix a bit, but still doesn't fix all cases
- I'll see if i can figure out what exactly could mess up Pango parsing... something to do with inline code I think

**Comment by end-4** [comment]
hmm
![image](https://github.com/end-4/dots-hyprland/assets/97237370/321d6977-7aaa-4ab3-a8f1-e9e94bab83be)

**Comment by end-4** [comment]
Oh I see! the ampersand isn't  escaped correctly

**Comment by end-4** [comment]
That should do it
See if there's anything I missed

**Comment by NextStep-IM** [comment]
Mine's fixed. Thanks a lot, @end-4!

**Comment by end-4** [comment]
i'll close this for now
feel free to open another issue if you find something again
