### ISSUE TITLE
Brightness and App search

### ISSUE THREAD

**Issue by LeVraiArdox** [end-4/dots-hyprland#24]
Hi. 
First of all, sorry for by bad english, I'm french.

I had a few problems when i installed your main eww config. The sound (that i resolved), the battery percentage (you said BATT, but for me it was BAT0), but two more problems are unsolvable for me.

First we have the **Brightness selection problem**.
My keyboard shortcuts for screen brightness don't works. The slider for brightness in settings either. I don't have any ideas, so can you help me with that plz ?

Also, the **App search problem**.
I saw in another issue that someone has solved the problem, but i didn't understood very well. 
The search bar in the overview tab result nohing.

Thanks for your time !

**Comment by WizenedPottle** [comment]
Regarding the Brightness problem, possible answer could be adding yourself to `audio` group. More can be found in [light](https://github.com/haikarainen/light/blob/master/README.md#installation) documentation.

**Comment by LeVraiArdox** [comment]
didn't worked. Thanks for trying

However, my priority is the app launcher. i am searching in every lines of the code.

**Comment by LeVraiArdox** [comment]
**Light**
- Worked, thx

**Search**
- i deleted the content of `cache `dir, rebooted, and still not working.
- The `entrynames.txt` file is blank, nothing is written on it. As for the `entries.txt`, i can find apps names and desktop entries, so looks fine for me.

**Comment by end-4** [comment]
That's just really weird. The script that is responsible for `entrynames.txt` is simpler than `entries.txt`. 
Can you comment the line that says `ios::sync_with_stdio(false);` of the file `.config/eww/scripts/allappnames.cpp`, compile and run it to see if there are any errors?

**Comment by LeVraiArdox** [comment]
Here is the line: 
```
int main(int argc, char* argv[]) {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    if (argc == 3 && string(argv[1]) == "--mode") {
        if (string(argv[2]) == "object")
            mode = 0;
        else if (string(argv[2]) == "array")
            mode = 1;
        else
            mode = stoi(string(argv[2]));
    }

```

Here is a pastebin with the gcc return, there are too many errors to pas them here. 
https://pastebin.com/cAYM2acd
It is a french gcc, i hope you will not find too much difficulties to understand.

I also tried with another methode: 
`g++ allappnames.cpp -o /home/ardox/.config/eww/scripts/output/allappnames -Wall -Wextra -g3`
I had no errors with this one, but it didn't worked.

**Comment by end-4** [comment]
You didn't comment those lines I told you to (add `//` at the beginning of the line)
The part of the code you showed should be changed to this:
```cpp
int main(int argc, char* argv[]) {
    //ios::sync_with_stdio(false);  //  <------------- CHANGE HERE
    cin.tie(nullptr);

    if (argc == 3 && string(argv[1]) == "--mode") {
        if (string(argv[2]) == "object")
            mode = 0;
        else if (string(argv[2]) == "array")
            mode = 1;
        else
            mode = stoi(string(argv[2]));
    }

```

**Comment by LeVraiArdox** [comment]
Oh, sorry. 
So i  commented the line, compiled it,  then i executed allappnames. all my apps were listed in the terminal, but the menu didn't worked. i rebooted, cleared the cache, re-rebooted and still nothing.

**Comment by LeVraiArdox** [comment]
Oh, sorry. 
So i  commented the line, compiled it,  then i executed allappnames. all my apps were listed in the terminal, but the menu didn't worked. i rebooted, cleared the cache, re-rebooted and still nothing.

**Comment by LeVraiArdox** [comment]
Ok, i solved the problem, thx. 

`fzf` was missing, i have seen that when i executed `appsearch`. So, it was just a missing dependencie (add it to your list). 

Oh, and can you plz tell me wich is the file that select the icons ? then i can select my icon theme for the search menu.

Thx a lot !

**Comment by end-4** [comment]
i set my icon theme using `gnome-tweaks`. people also recommend `nwg-look`.

(idk how to set this manually xd)

**Comment by end-4** [comment]
bruh typo
