### ISSUE TITLE
NaN% on cpu usage

### ISSUE THREAD

**Issue by Dimplythree2** [end-4/dots-hyprland#242]
## The issue
On my bar the cpu usage says is using NaN% (not a number)

<details>
im using the illogical_impulse on arch linux

![image](https://github.com/end-4/dots-hyprland/assets/46870900/339056a1-4b14-4292-acb3-ecfbee238f06)

any ideas?

**Comment by NextStep-IM** [comment]
Can you give the output of this command: `top -bn1 | grep Cpu | awk '{print $2}'`

**Comment by end-4** [comment]
try this
`top -bn1 | grep Cpu | awk '{print $2}'`

**Comment by Gilgames000** [comment]
> try this `top -bn1 | grep Cpu | awk '{print $2}'` give output pls

Same thing here. Here's the output of the command above:

![image](https://github.com/end-4/dots-hyprland/assets/22778436/64674795-caf6-41f1-86c5-c081a6f00c17)

**Comment by end-4** [comment]
ahhhhhhhhhhhh localization
i'll just sed those `,` into `.` real quick

**Comment by end-4** [comment]
Should work now, test please

**Comment by clsty** [comment]
> ahhhhhhhhhhhh localization i'll just sed those `,` into `.` real quick

Tip: `LANG=C` is commonly used for a consistent locale.

E.g. 

```bash
$ pacman --version
 .--.                  Pacman v6.0.2 - libalpm v13.0.2
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2021 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       本程序可以在GNU一般公众许可条款下
                       自由

$ LANG=C pacman --version
分发
 .--.                  Pacman v6.0.2 - libalpm v13.0.2
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2021 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.
```

**Comment by Dimplythree2** [comment]
> Should work now, test please

Yeah, it works now, Thanks
