### ISSUE TITLE
[Issue] Music controls inconsistency

### ISSUE THREAD

**Issue by NextStep-IM** [end-4/dots-hyprland#243]
- **I have read the instructions**
---
## The issue
- Arco Linux
- If mpd (even if paused) and firefox are running together, music widget goes a little wonky. 

<details>
<summary>
I read the `Firefox mpris dbus is useless` comment so I guess it is not exactly fixable. Can firefox be removed from the widget config? It's messing with the cover and title in the widget.

Killing mpd when running youtube then restarting ags gives the error `No player found` in the output of `ags`. I haven't seen any error regarding firefox in the output.</summary>

![2024-02-07_20-00](https://github.com/end-4/dots-hyprland/assets/140648058/6e0d7c52-f1de-44ae-9186-aec809cd3164)
This is working correctly:
![2024-02-07_20-04](https://github.com/end-4/dots-hyprland/assets/140648058/4f7552b5-b821-42c6-bef3-492c7c6fbf7a)

</details>

**Comment by end-4** [comment]
okay that didn't solve the problem but is a somewhat relevant improvement

**Comment by end-4** [comment]
Multiple players are allowed now, so a bit more consistency
But now there's color inconsistency in cases with many players
![image](https://github.com/end-4/dots-hyprland/assets/97237370/adaf63f1-f99c-4ea5-a462-387bff284be4)
_player styles are compiled with colors of image on the right_

**Comment by NextStep-IM** [comment]
Sorry, I know nothing about js so I don't know what you changed. I paused mpd and ran YouTube on Firefox, but the title and cover don't change. The controls work perfectly on the current player except the ones on the right of the music widget.

https://github.com/end-4/dots-hyprland/assets/140648058/fbb7a6f0-2ae6-4451-9fbb-c3eb0831018e

> Multiple players are allowed now, so a bit more consistency

Cool! How do I get multiple players though? I had mpd, youtube and spotify running but only got one window.

**Comment by NextStep-IM** [comment]
Hmmm. Both of my windows seem to have covers and progress from the same song from mpd. The controls are working correctly. Though the responses from controls on the mutiple windows are synchronized.

**Comment by end-4** [comment]
> Both of my windows seem to have covers and progress from the same song from mpd

- Can you get D-Spy and search "mpris" or "mpd" please? i don't use mpd so not sure about it
- If there are many buses for mpd, show me their info
![image](https://github.com/end-4/dots-hyprland/assets/97237370/4bff6ca9-3e64-445b-b436-ec28b37800ac)

**Comment by NextStep-IM** [comment]
Here you go:
![2024-02-07_22-41_1](https://github.com/end-4/dots-hyprland/assets/140648058/68ad68b8-4ab5-4f50-b1fd-4163c1106594)
![2024-02-07_22-41](https://github.com/end-4/dots-hyprland/assets/140648058/6219cdd9-c78f-4e0e-ac21-12c67b1b668f)

**Comment by end-4** [comment]
i'm guessing i should block the non-instance bus?

**Comment by NextStep-IM** [comment]
> i'm guessing i should block the non-instance bus?

I am a beginner to this whole thing so I will leave it to you.

**Comment by NextStep-IM** [comment]
Thank you so much!! mpd and spotify are working perfectly! No luck for firefox, I assume?

**Comment by end-4** [comment]
install 
- [plasma browser integration](https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/) extension
- `sudo pacman -S plasma-browser-integration`

**Comment by NextStep-IM** [comment]
Man you are great. Enabled the plasma integration extension in firefox and it worked perfectly! Thanks again!
