### ISSUE TITLE
[Feature] Docs as repo rather than wiki

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#246]
**What would you like to be added?**
Currently the docs are in the wiki of this repo, which is not open to edit, and it does not support pull request even if you make it open to edit.

**Method A:**
You may create another repo `dots-hyprland-docs` just for docs for this repo, and add me as a collaborator for that repo, because I like maintaining docs and you seems busy sometimes, so that I can handle documenting for you.

As for publishing, there're 2 methods.

**A.a:**
Some `*.md`s will be just enough. 

**A.b:**
Similar to [the doc repo of ags](https://github.com/Aylur/ags-docs), we can use GitHub Pages and Astro and Starlight, so that searching across different docs is enabled, and also a modern look is provided.

If you trust me, you may just create that empty repo named `dots-hyprland-docs` and enable github pages in settings of that repo (use GitHub Actions as source), and add me as a collaborator, and I'll do the rest of things (including copying markdown files from wiki of this repo, arrange the files, edit workflow files, etc.).

**Method B:**
You may arrange document files inside a `docs` folder, so that people can contribute to docs.

---
**How will it help**
I've noticed that the wiki is kind of... basic, and not covering some rather important how-to-s and why-s.

If it's open to contribute, I guess people using this repo will contribute to the docs so that the usage and trouble shooting will be more comprehensive.
Therefore, people will be **less** likely to ask duplicated questions (such as <https://github.com/end-4/dots-hyprland/issues/211#issuecomment-1918295223>).

Also you may add docs for development as a note for yourself and other maintainers/contributors.

---
**Extra info**
I've already collected some FAQs [here](https://github.com/clsty/dots-hyprarch#FAQ).

**Comment by end-4** [comment]
https://github.com/end-4/dots-hyprland-wiki
I sent a collaborator invite @clsty

**Comment by clsty** [comment]
> https://github.com/end-4/dots-hyprland-wiki I sent a collaborator invite @clsty

Nice.
BTW today is New Year's Eve, therefore the wiki will not be completely ready very quickly.

**Comment by end-4** [comment]
same thing here in vietnam haha
no rush, quality is priority

**Comment by clsty** [comment]
Do you mind if I use your avatar as favicon for that wiki? @end-4

**Comment by end-4** [comment]
sure my avatar should be good for now
i'll change it later if i decide to design a logo for illogical impulse
