### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by WizenedPottle** [end-4/dots-hyprland#25]
Hi there,

I'm curious about the calendar application being used in this project. Could you please share the name or provide more details about it? (Sorry if it is stated elsewhere)

Thanks!

**Comment by end-4** [comment]
frontend is [eww](https://github.com/elkowar/eww)
backend is my simple c++ program which is stored in .config/eww/scripts/calendarlayout.cpp

the script outputs a json of the layout of the calendar. eww loops through it and draw the calendar.

**Comment by WizenedPottle** [comment]
I was actually reffering to the 4th screenshot in photo from reddit.
![image](https://github.com/end-4/dots-hyprland/assets/94008053/a5986234-d1ae-4db7-887d-35ea9d26f5fc)

**Comment by end-4** [comment]
yeah i am talking about that one if you mean the sidebar
if ur talking about the app its gtk widget factory

**Comment by WizenedPottle** [comment]
Thank you, I meant the app. I taught it was calendar/organisation/dayplanning app.
