### ISSUE TITLE
Font in use?

### ISSUE THREAD

**Issue by renyuneyun** [end-4/dots-hyprland#26]
Hi. Thanks for sharing the beautiful and powerful theme/rice.
I'm new to hyprland and everything (though had used awesome previously with X11), and am trying to set this theme up. (I'm on Arch.)
Many things seem to be working. But The icons are not rendered correctly. I bet it's because they use text as icons, and the font I use does not have them. See example screenshot:
![output](https://github.com/end-4/dots-hyprland/assets/3293723/2c62c70e-bd24-4bc3-9e82-b4ef5674dc8c)

So, may I ask what is the font used by you?
And could you give some suggestions on how to set that up if you happen to have that done before? I'm aware fontconfig is complicated, so maybe I'll have to figure it out myself.

**Comment by end-4** [comment]
- hi, glad you like my rice
- you will need `Torus`, `Material Symbols Rounded` (they're bundled in the repo, just install them. see https://github.com/end-4/dots-hyprland/tree/main/.local/share/fonts)
- fontconfig? tbh idk any of that stuff :P. just use `gnome-tweaks`
![image](https://github.com/end-4/dots-hyprland/assets/97237370/570d27f5-b822-4126-9557-9f362b0dfa35)

**Comment by renyuneyun** [comment]
Thanks for the info. Ah, I did not copy the `.local` directory, that's why.
Maybe I should skip some of my cleanness habit :p
