### ISSUE TITLE
HYPRLAND_INSTANCE_SIGNATURE not set!

### ISSUE THREAD

**Issue by Penguin-SAMA** [end-4/dots-hyprland#260]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: EndeavourOS GNOME

---
## The issue

I am using a script to install Hyprland, but every time it reaches this step, it exits directly, and Hyprland is not installed correctly. How should I solve this problem?
![image](https://github.com/end-4/dots-hyprland/assets/50973632/5fa9f371-b674-437f-9ab4-d41e7a565755)

<details>
<summary>Click to expand</summary>

```plain
[./install.sh]: Found target: .config/wlogout
####################################################
[./install.sh]: Next command:
rsync -av --delete .config/wlogout/ /home/penguin/.config/wlogout/
sending incremental file list

sent 97 bytes  received 12 bytes  218.00 bytes/sec
total size is 1,089  speedup is 9.99
[./install.sh]: Command "rsync -av --delete .config/wlogout/ /home/penguin/.config/wlogout/" finished.
####################################################
[./install.sh]: Next command:
rsync -av .local/bin/ /home/penguin/.local/bin/
sending incremental file list

sent 111 bytes  received 12 bytes  246.00 bytes/sec
total size is 89,559  speedup is 728.12
[./install.sh]: Command "rsync -av .local/bin/ /home/penguin/.local/bin/" finished.
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)[penguin@penguinsama dots-hyprland]$ 
```

</details>

**Comment by clsty** [comment]
Sorry that's my fault. It's because a missing 'try' in the script.

Also actually your installation is actually done, the only thing left to be excuted is print following message:
```bash
printf "\e[36m[$0]: Finished. See the \"Import Manually\" folder and grab anything you need.\e[97m\n"
printf "\e[36mPress \e[30m\e[46m Ctrl+Super+T \e[0m\e[36m to select a wallpaper\e[97m\n"
printf "\e[36mPress \e[30m\e[46m Super+/ \e[0m\e[36m for a list of keybinds\e[97m\n"
```

That's it. You may use hyprland directly now.
