### ISSUE TITLE
[Issue]Three widgets seem to have encountered a problem

### ISSUE THREAD

**Issue by Penguin-SAMA** [end-4/dots-hyprland#265]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: EndeavourOS

---
## The issue

1. Both RAM usage and swap usage are constantly at 0%.
2. CPU usage is abnormally jumping around between 5% and 95%.

<details>
<summary>Click to expand</summary>

![image](https://github.com/end-4/dots-hyprland/assets/50973632/21b27403-6f94-40d1-9c2b-6515f2cdf826)

</details>

**Comment by clsty** [comment]
I notice that it's similar for me, except for the CPU.
