### ISSUE TITLE
[Feature] [install.sh] paru support

### ISSUE THREAD

**Issue by end-4** [end-4/dots-hyprland#269]
## What would you like to be added?
- Support for `paru`in install script
- @clsty I wonder if it's something simple
  - Of course I can copy paste the normal script and replace `yay` with `paru` (this worked), but I think you likely have a better solution

## How will it help
- Help users who use a distro offering `paru` by default, like CachyOS

**Comment by clsty** [comment]
I'll think about it later and find a suitable solution.

**Comment by clsty** [comment]
Ok, it's done.

Though I found this:
```plain
❯ ack 'alias'|grep yay
.config/fish/config.fish:20:alias yay=paru
```
It's emmm... Do you really want to keep this?

**Comment by end-4** [comment]
Do you really want to keep this? It may behave unexpectedly when user actually has 'yay' already installed.

Right, though having both installed is weird. I'll add a check

**Comment by clsty** [comment]
I'm having both installed for long lol

Sometimes one works and another does not.
And vice versa.

**Comment by end-4** [comment]
> I'm having both installed since long time ago XD

Since you're a bash wizard I'm taking this as "having both installed is fine". Fine.

**Comment by clsty** [comment]
I'm closing this issue since it's fixed.

Feel free to re-open it.
