### ISSUE TITLE
No autocomplete in bar

### ISSUE THREAD

**Issue by Dialgatrainer02** [end-4/dots-hyprland#27]
I installed the novelknock branch and have installed all the dependencies but when I try to search for apps no autocompletion happens I'm not sure what logs would help if there's anything else you need I'll provide it

**Comment by end-4** [comment]
what autocompletion?
like app entries don't show up?

**Comment by end-4** [comment]
see if there are any errors
`cd ~/.config/eww/ && scripts/allappnames` should print app names
`cd ~/.config/eww/ && scripts/allapps`  should print a json of app entries
if not, provide the output pls

**Comment by Dialgatrainer02** [comment]
Apparently fzf didn't install and I missed it
