### ISSUE TITLE
[Issue] cannot use ibus-rime in illogical_impulse

### ISSUE THREAD

**Issue by wewesdr** [end-4/dots-hyprland#274]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Archlinux

---
## The issue

After some basic installaion, ibus-rime cannot use, even if i added environment varitie .

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

**Comment by clsty** [comment]
`fcitx5` is used by default.

Please recheck your `.config/hypr/hyprland/env.conf`. Env vars are defined there.

Also please check your `.config/hypr/hyprland/execs.conf`. Maybe you need to add a line for auto starting ibus there.

**Comment by wewesdr** [comment]
do you mean i should edit   `.config/hypr/env.conf` 
from: 

>env = QT_IM_MODULE, fcitx
>env = XMODIFIERS, @im=fcitx
>env = SDL_IM_MODULE, fcitx
>env = GLFW_IM_MODULE, ibus
>env = INPUT_METHOD, fcitx

to:

>env = QT_IM_MODULE, ibus
>env = XMODIFIERS, @im=ibus
>env = SDL_IM_MODULE, ibus
>env = GLFW_IM_MODULE, ibus
>env = INPUT_METHOD, ibus

and    ` .config/hypr/execs.conf`

from:
>exec-once = fcitx5

to:
>exec-once = ibus


is it right?
