### ISSUE TITLE
swww not running at startup and breaking eww workspaces

### ISSUE THREAD

**Issue by Dialgatrainer02** [end-4/dots-hyprland#28]
after intalling the dotfiles on a fresh install and loading hyprland swww dosent start and the eww workspaces are missaligned and a few are missing i have had thiss issue a few times and even after uninstalling swww and resetting eww and replacing the dot files this still happens
![image](https://github.com/end-4/dots-hyprland/assets/96637854/73b5e548-4a32-4835-a874-469932e6ab3c)

steps to reporduce 
install archlinux 
boot arch install dependencies and other apps 
install and copy the dotfiles 
restart sww when it dosent work 
restart hyprland 
eww is broken and so is swww

**Comment by end-4** [comment]
## swww
- try selecting a wallpaper? (scroll down on the left pill of the bar then click the button on the left, select an image file)
## eww
 - i'm not sure what caused the broken workspace indicator, but try installing the right fonts (Lexend, Material Symbols Rounded) to see if the widths look less weird

**Comment by Dialgatrainer02** [comment]
changing wallpaper dosent work it shows the new wallpaper for a second then revets back to blue 
i installed the material desgn icons and that lead to eww doing this 
![image](https://github.com/end-4/dots-hyprland/assets/96637854/bfa8bb1e-772a-4c94-bd04-0ee60b1c5db2)
the lexend packages didnt change anything 
i have uninstalled both the fonts but eww still looks broken

**Comment by Dialgatrainer02** [comment]
restoring the old dotfiles fixed it but not the workspace spacing

**Comment by Dialgatrainer02** [comment]
when i chane wallpaper to the cultured wallpaper i get this error from hyprland
![image](https://github.com/end-4/dots-hyprland/assets/96637854/b1f6b59c-9451-4a30-a6fa-0ae73cc79983)

**Comment by end-4** [comment]
## Hyprland error
- **Why**: the colors were unsuccessfully  generated, so it's wrong.
- **What to do**: 
  - Make sure you have dependencies installed. In this case, it's likely you're missing `gojq` or `pywal`. Install them and try selecting a wallpaper again. 
  - If it still doesn't work, see if this command prints a json: `cat ~/.cache/wal/colors.json | gojq -c`
 ## Brightness
  - Make sure you installed `light` and added yourself to the `video` group: `usermod -aG video <USERNAME>` (as mentioned in the instructions)
  ## Night light icon
 - Install font: Material Symbols Rounded
 - run `fc-cache -fv` for the new font to be detectable
 - run `pkill eww && eww daemon && eww open bar` to restart eww

**Comment by Dialgatrainer02** [comment]
### brightness
i reran the instructions for brightness and it still looks like this 
![image](https://github.com/end-4/dots-hyprland/assets/96637854/0d7f257b-f514-43e8-b45f-2a839aa49cb6)
### hyprland
i reinstalled gojq  and it worked but it only flashes on the screen for less than a second before going back to the  blue colour 
### eww
when i restarted eww the wallpaper appeared but resized so it dosen't go beneath the bar
![image](https://github.com/end-4/dots-hyprland/assets/96637854/7ae2f2f5-cbb2-4c5b-b704-60e9830c5291)
the symbol fonts were already installed  and the bugged out workspace indicator is still happening 
### swww
if i try and change the wallpaper after restarting eww it doesn't work and appears to have no effect

**Comment by end-4** [comment]
## eww
- pretty sure that's a problem with the styles. can you attach 
- are you using the right version of eww? 
  - use the git version of eww
  - note: if you also want the radial menu to work (Ctrl+Super+RMB), as mentioned in the novelknock readme, you should compile [my fork of eww](https://github.com/end-4/eww/tree/trigonometry) 
## swww 
- can you switch swww  wallpaper manually? (`swww img /path/to/your/image`) 
  - of course remember to start it first (`swww init`)

**Comment by Dialgatrainer02** [comment]
### eww
im using your fork and i pulled and complied it a few days ago 
eww -V
> eww 0.4.0 1205b871d0cfe2e60c94b18d1e0f454796e813b5

###swww
yes i can change manually but it still clashes with the bar and doesnt layer properly and it being init by the exec line in exec.conf although it isnt displaying it still being initialised

**Comment by end-4** [comment]
## eww
- that should be new enough
- run `cd ~/.config/eww && scripts/workspaces`. see if it outputs an array of 10 workspaces
## swww
> still being initialised

???

**Comment by end-4** [comment]
also there is **_definitely_** something wrong with the css
can you type `>load` in the search bar (middle click the workspaces to open it) then hit enter?

**Comment by Dialgatrainer02** [comment]
### swww
despite it still being initialised at startup 
### eww
cd ~/.config/eww && scripts/workspaces
> [{"num":"1","clr":"rgba(154,152,162,0.7)"},{"num":"2","clr":"rgba(106,105,105,0.6)"},{"num":"3","clr":"rgba(106,105,105,0.6)"},{"num":"4","clr":"rgba(106,105,105,0.6)"},{"num":"5","clr":"rgba(106,105,105,0.6)"},{"num":"6","clr":"rgba(106,105,105,0.6)"},{"num":"7","clr":"rgba(106,105,105,0.6)"},{"num":"8","clr":"rgba(106,105,105,0.6)"},{"num":"9","clr":"rgba(106,105,105,0.6)"},{"num":"10","clr":"rgba(106,105,105,0.6)"}]

i get this output

**Comment by Dialgatrainer02** [comment]
i entered >load and now it looks like this 
![image](https://github.com/end-4/dots-hyprland/assets/96637854/c83e18c0-fdc5-4b8e-9e32-0de2cd9f5fb9)
 my wallpaper isnt yellow so im unsure where it got the colour scheme from

**Comment by Dialgatrainer02** [comment]
is bottom sheet meant to be transparent? in the dotfile images it is but when i run it its blue like the backround could  the no wallpaper problem could be transparency  breaking in eww for some reason then its falling back to a solid colour?

**Comment by end-4** [comment]
## workspaces
 `>load NAME`  loads the NAME colorscheme. since you didnt type anything, the first theme ("alive") was selected among the ones with matching names (searching for nothing will return every result)
- the workspace json looks alright
- at this point idk what could be wrong tbh
## bottom sheet
- yes it's meant to be transparent. another window is behind and it's hyprland's job to blur whatever image that is shown in it. (if no music with media cover is lpaying, it's transparent)

**Comment by Dialgatrainer02** [comment]
### bottom sheet
okay then i think tranparency is broken as it looks like this regardless of what appears behind it 
![image](https://github.com/end-4/dots-hyprland/assets/96637854/8ca60b5a-6422-460a-a9fd-b032f997f9a9)
### workspaces 
the only way ive fixed the problem is with a full reinstall as restting the dots dosent fix it so could something be changing up the filesystem causing the breaking change?
if so how would you find it

**Comment by end-4** [comment]
## transparency
- is not broken. it's like that because my decoration:blur_xray is set to true
## workspaces
- so were you able to fix it or not? i don't understand, could you please phrase that clearer?

**Comment by Dialgatrainer02** [comment]
### transparency 
even when blur_xray is turned offf it still isnt transparent and swww is showing the image but eww is ontop of it so its not visible untill i kill eww if i am understanding it right?
### workspaces
i have had this issue multiple times before the one i reported to check if it wasnt a fluke whenever it occured which was after a reboot the only way i couls solve the issue was to completely reinstall arch which isnt favourable and it was only a temp fix as when i would then try and install the dotfiles again it would happen again getting me in an endless loop of reinstalling to fix it so no i dont have a fix sorry for the misunderstaning

**Comment by end-4** [comment]
- every of your above problems listed are all because there's a problem with the styles (so your gtk theme (which has solid background) is loaded instead) 
  - there's a widget for screen corners. failing style load = solid background = blocks the wallpaper
  - the same goes for the bottom sheet
- check:
  - did you modify anything? if yes, what changes did you make? or any action other than that caused these problems
  - check `eww.scss`. there should be a section that looks like this
 ```scss
 * {
  all: unset;
  transition: 75ms cubic-bezier(0.05, 0.7, 0.1, 1);
  background-repeat: no-repeat;
}
```

**Comment by Dialgatrainer02** [comment]
i used the gtk theme from the .theme folder in the repo the tokyo night one i moved the gtk.40 3 and 2 into .config 
i checked eww.scss and that section does exist i havent modified the files only moved them into .config

**Comment by Dialgatrainer02** [comment]
i removed the gtk themes and it works 
the workspace indicators are normal blur and transparency are working and wallpaper is visible

**Comment by end-4** [comment]
removed gtk themes?
maybe conflictions or something? or is it because of my gtk-4.0 gtk-3.0 gtk-2.0  folders

for brightness control, remember to add yourself to the video group

**Comment by end-4** [comment]
## brightness
does `light -U 10` make your screen darker?
## gtk themes
- i'd appreciate it if you could help me narrow down which is causing the problem. eww uses gtk3, so it's either the themes or the gtk-3.0 folder to blame

**Comment by Dialgatrainer02** [comment]
### brightness 
yes it does
### gtk 
yes sure tell me what i have to do to help

**Comment by end-4** [comment]
## brightness
- does this command make your screen darker then? `echo 'down' | sed -e 's/down/-U 10/g' -e 's/up/-A 10/g' | xargs light`
## gtk themes
- you should install *either* the `.themes` folder or the `gtk-3.0` folder. see the presence of which folder messes eww styles up (you might wanna restart eww when you test that: `pkill eww && eww daemon && eww open bar`). simple as that

**Comment by Dialgatrainer02** [comment]
### brightness
yes it decreased my brightness
### gtk 
the tokyo night one is the breaking one

**Comment by end-4** [comment]
## brightness
- `cd ~/.config/eww && scripts/brightness`
  - does it print something like this? `{ "level": 39.22, "icon": "" }`
## gtk
- thanks (while i still don't get how a theme can mess up eww)

**Comment by Dialgatrainer02** [comment]
### brightness 
cd ~/.config/eww && scripts/brightness
> { "level": 100.00, "icon": "" }
yes it does

**Comment by end-4** [comment]
make sure you scroll the right spot
dont scroll the icon, scroll the line/slider 
that's all i can think of now 😅

**Comment by Dialgatrainer02** [comment]
okay i can survive without brightnes control and i still have keyboard shortcuts 
thank you for all the help and the amazing dot files

**Comment by end-4** [comment]
alright
have you tried scrolling the top left corner of the screen though?

**Comment by Dialgatrainer02** [comment]
yes that works
