### ISSUE TITLE
[Issue] Cheatsheet appears too large on small displays when using display scaling

### ISSUE THREAD

**Issue by b4shful** [end-4/dots-hyprland#283]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**: yes
- Linux distro: Arch

---
## The issue

When display scaling is set in hyprland.conf on a smaller display (for example the 13 inch display of my XPS 13 9360) the cheatsheet is too big and exceeds the boundaries of the display.

The hyprland config setting used was:
```
monitor=,preferred,auto,1.5
```

It is worth noting this bug also happens if you are not using scaling but instead using a larger font size. (Specified in `gsettings` as outlined in the Usage instructions "How to resize the UI / change font size?")

Apologies, couldn't take a screenshot so hopefully a photo suffices, here is the cheatsheet when triggered with `Super` + `/`:
<img src='https://github.com/end-4/dots-hyprland/assets/28313200/62c7bf57-c38e-4a88-94f1-52140c3598df' width=50%>

<details>
<summary>Click to expand</summary>

Monitor resolution: 1920x1080
Monitor size: 13.3 inches
</details>

**Comment by end-4** [comment]
you'll just have to either reduce the monitor scacle or the font size

**Comment by b4shful** [comment]
@end-4 the scaling is great everywhere else on the system, which is why I am reluctant to do either of those things. Is there a way I could somehow either reduce scale or font size for only the cheatsheet?

**Comment by b4shful** [comment]
oh sorry, what I meant was that I am satisfied with the font size and scaling for all the other elements of the UI and so don't want to have to change it globally like that (it's a laptop so only one monitor)

**Comment by daUnknownCoder** [comment]
> you'll just have to either reduce the monitor scale or the font size

i also have this problem:
![image](https://github.com/end-4/dots-hyprland/assets/84800625/5dab61cb-db44-4795-839c-3e3cca524de3)
tried adding `width` and `height` in cheatsheet's export window to find that they dont have such propertied fiddled with scss too which didnt yield any results

**Comment by end-4** [comment]
> tried adding width and height in cheatsheet's export window to find that they dont have such propertied fiddled with scss too which didnt yield any results

no point in adjusting the size when the children content still take up that much space

**Comment by b4shful** [comment]
Think this one got fixed a while back (perhaps by the new cheatsheet system?) - closing
