### ISSUE TITLE
[Issue] execs.conf uses a cursor which isn't installed by the install script

### ISSUE THREAD

**Issue by b4shful** [end-4/dots-hyprland#284]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**: yes
- Linux distro: Arch

---
## The issue

Apologies if this is a strangely laid out report, but I wish to outline the exploration I did as this will potentially be good to know in case others are experiencing issues with cursor sizes. Also, I am not completely familiar with how cursors work in Wayland and different UI libraries so I may get some terminology wrong here.
## TL;DR
The default execs.conf file tries to run `exec-once = hyprctl setcursor Bibata-Modern-Classic 24` but this cursor is not preinstalled and not installed in the setup.sh script either. This (I think) causes a fallback to be used instead (for Xcursor apps I think??) which doesn't observe the Hyprland display scaling or the XCURSOR_SIZE variable.
## Exploration
I was running into issues with the cursor size when using display scaling via `monitor=,preferred,auto,1.5` in hyprland.conf
The cursor scaling was fine on all Wayland apps, but would resize in things like the foot terminal and also the blank workspace background. For example hovering the cursor over the status bar at the top of the screen it would appear correctly sized, but then moving the cursor down to below the status bar (just hovering over the desktop/blank workspace with no windows opened) would cause it to change to a very small cursor.

I tried to change cursor size by editing the line in execs.conf (restarting Hyprland afterwards):
```exec-once = hyprctl setcursor Bibata-Modern-Classic 24```
This correctly propagated the XCURSOR_SIZE change (and XCURSOR_THEME also gets propagated to the environment correctly), but the small cursor issue was still present in the scenarios I described above.

I commented out the `exec-once = hyprctl setcursor Bibata-Modern-Classic 24` line entirely, restarted Hyprland, and this fixed my issue entirely.

Looking a bit more into this, I tried to locate Bibata-Modern-Classic anywhere on the system and couldn't find anything, so I believe that Bibata-Modern-Classic is not installed on my Arch system and was also not installed by the setup.sh script for this repository. This presumably caused it to revert to some sort of fallback cursor which did not support or did not have the correct DPI scaling. Or perhaps the XCURSOR_SIZE gets ignored if XCURSOR_THEME isn't a valid value of an installed cursor?

## Workaround and potential fix
Commenting out the line `exec-once = hyprctl setcursor Bibata-Modern-Classic 24` in execs.conf fixed my particular issue, but the underlying issue is probably the fact Bibata-Modern-Classic is not installed.

For an actual fix, either this line should be removed or commented out from execs.conf, or maybe the install script should install the Bibata-Modern-Classic cursor so that this line will work as intended. Whatever you think is most appropriate.

It's probably also worth noting that, having just looked up what Bibata Modern Classic looks like, my cursor looks completely different (both when hovering over the status bar and hovering over the blank desktop as outlined in [my exploration](#exploration)), so a fix which aims to keep using the Bibata cursor would need to ensure it works both when hovering over the status bar, and when hovering over the blank desktop (which uses the same cursor source as many apps).

**Comment by clsty** [comment]
To install the cursor in install script, I think `aur/bibata-cursor-theme-bin` or `aur/bibata-cursor-theme` is needed.

About that cursor change-on-hovering thing, a system reboot may be needed. Also GTK and QT and xcursor thingy has there own config for cursor theme, which may cause that cursor change-on-hovering thing too.

**Comment by end-4** [comment]
the `-bin` aur package is big since it installs all bibata variants. i didn't want that so didn't add it. i haven't tried the non `-bin` one but i'm guessing it's going to be similar
@clsty can you make the install script download just Bibata Modern Classic from [Bibata's releases](https://github.com/ful1e5/Bibata_Cursor/releases)

**Comment by b4shful** [comment]
> To install the cursor in install script, I think `aur/bibata-cursor-theme-bin` or `aur/bibata-cursor-theme` is needed.
> 
> About that cursor change-on-hovering thing, a system reboot may be needed. Also GTK and QT and xcursor thingy has there own config for cursor theme, which may cause that cursor change-on-hovering thing too.

I had not rebooted in a while, so to test this I uncommented the setcursor line in execs.conf and restarted Hyprland. Weirdly, the cursor starts out big, and is animated to float from the bottom right corner into the center of the screen as a startup animation I guess. If I move the mouse around in the blank workspace after Hyprland starts up, it stays big (!), but the moment I move the mouse to the status bar and then back down to the blank workspace it goes back to being tiny.

I am confused what you meant with the system reboot. To be clear, I have not yet attempted to install the cursor package so it couldn't have been due to a reboot being required for that. The weird changing cursor thing occurs whenever I have the setcursor line in the execs.conf (and the Bibata cursor not installed) so in a way it's a secondary issue (maybe Hyprland's hyprctl shouldn't just return "ok" when you give it a cursor that doesn't exist 😆) and I'm not 100% on the cause.

I will keep the setcursor line in the execs.conf, and try installing what @end-4 linked, so that I can switch over to Bibata instead of whatever default thing I had when the line was commented out.

(Also, to both of you @end-4 and @clsty , thank you so much for the work you've done on this. It's fantastic and was a godsend to me given that Hyprland and its surrounding ecosystem of software can be quite overwhelming trying to jump in and configure from scratch. Being able to get such a beautiful environment up and running painlessly while also having the flexibility to configure it without diving too deep is an incredible achievement. A lot of projects decide to aim for either "works out of the box but not easily configurable" or "does nothing out of the box but you can configure everything" - it seems here you've managed in many ways to get the best of both worlds!❤️)

**Comment by clsty** [comment]
> @clsty can you make the install script download just Bibata Modern Classic from [Bibata's releases](https://github.com/ful1e5/Bibata_Cursor/releases)

Ok. It's done.

> I am confused what you meant with the system reboot. To be clear, I have not yet attempted to install the cursor package so it couldn't have been due to a reboot being required for that.

Welp, that's exactly what I meant, i.e. a reboot is needed to make the installed cursor theme fully take effect. Sorry for the confusion.

**Comment by clsty** [comment]
Closing as fixed. Feel free to re-open if you still meet issue about cursor-theme.
