### ISSUE TITLE
[How-To] Custom Theme

### ISSUE THREAD

**Issue by JosephDemarest** [end-4/dots-hyprland#285]
Hi. I really like your dotfiles, the only thing I would like to change is the theming. I know it's autogenerated, but I want to define something custom. I am a programmer so i can go deep, i just wanted to ask if you could point me in the right direction... thanks and good work here. I really love the UI.

**Comment by end-4** [comment]
- If you just want to change the color scheme, modify `.config/ags/scss/_material.scss`
- If you want to change the looks of everything
  - The JS files where widget layouts are defined and classes are applied are in `.config/ags/modules`
  - The stylesheets are in `.config/ags/scss`

- **Tip**: Folder search can be very helpful. I normally have the `.config/ags` folder open in vscode then just search when I want to quickly get to places where a css class is defined/applied

**Comment by JosephDemarest** [comment]
Yeah... it's 3am for me somehow didn't think to do that LOL.

Thanks for the tip boss

**Comment by JosephDemarest** [comment]
THERE WE GO GOT CATPPUCCIN WORKING XD
