### ISSUE TITLE
eww with dual monitor setup

### ISSUE THREAD

**Issue by Dialgatrainer02** [end-4/dots-hyprland#29]
is there any way to have the bar widget open on both monitors simultaneously as on the second monitor the is space reserved for the bar but eww refuses to open a new bar for the monitor

**Comment by end-4** [comment]
## yes
- go to `eww.yuck`
- see the definition `(defwindow bar ...... )`? duplicate it and rename it to something else (`bar1` for example)
- change the `:monitor` property to 1 instead of 0

**Comment by Dialgatrainer02** [comment]
the bar run as expected aside from buggy inputs due to the other widgets could i use the same approach with the other widgets and just ignore the errors when no 2nd display is there?
im also trying to get udev to work properly but thats out the scope of the issue

**Comment by end-4** [comment]
- you can, but you'll have to do a lot more modifications for the 2nd bar to actually open the other widgets on the 2nd monitor (actually duplicate their widget definitions and toggle script so the buttons open the correct window)
- can't help you with udev here, i have no experience with it

**Comment by Dialgatrainer02** [comment]
okay thats not realy feasible as i have no idea about yuck 
would it be as simple as sticking a 1 behind everything?
fair enough i also have no idea how udev work and im just reading docs and copy pasting code 
thank you for the help

**Comment by Dialgatrainer02** [comment]
okay, thank you
