### ISSUE TITLE
[Issue] AGS looks a bit too zoomed in. 

### ISSUE THREAD

**Issue by notLonelySoul** [end-4/dots-hyprland#294]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: EndeavourOS

---
## The issue

I just installed this config and the AGS widgets look too big on the screen. 

Installation method: Automated script for arch distros.

![view](https://github.com/end-4/dots-hyprland/assets/108740082/043ef11d-c8d8-45ab-85b8-e66f7bfd4b66)

Output of `pkill ags;ags`

![output](https://github.com/end-4/dots-hyprland/assets/108740082/6f65b79d-60b2-466b-ab7c-3d3d895b86d6)

**Comment by end-4** [comment]
this should help you
https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/#resize-the-ui--change-font-size

**Comment by notLonelySoul** [comment]
Thanks man, sorry btw. I never thought changing the font size would fix it.
