### ISSUE TITLE
[Issue] compile ERROR during hyprlock-git installation

### ISSUE THREAD

**Issue by alphanhp** [end-4/dots-hyprland#296]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: 

---
## The issue

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>
Error message(during automatic install shell script):
[ 25%] Building CXX object CMakeFiles/hyprlock.dir/src/core/hyprlock.cpp.o
/home/nhp/.cache/yay/hyprlock-git/src/hyprlock/src/core/hyprlock.cpp: In member function ‘void CHyprlock::onKey(uint32_t, bool)’:
/home/nhp/.cache/yay/hyprlock-git/src/hyprlock/src/core/hyprlock.cpp:661:57: error: ‘class CHyprlock’ has no member named ‘m_tGraceEnd’; did you mean ‘m_tGraceEnds’?
  661 |     if (std::chrono::system_clock::now() < g_pHyprlock->m_tGraceEnd) {
      |                                                         ^~~~~~~~~~~
      |                                                         m_tGraceEnds
/home/nhp/.cache/yay/hyprlock-git/src/hyprlock/src/core/hyprlock.cpp: In member function ‘std::string CHyprlock::spawnSync(const std::string&)’:
/home/nhp/.cache/yay/hyprlock-git/src/hyprlock/src/core/hyprlock.cpp:843:50: warning: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Wignored-attributes]
  843 |     const std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd.c_str(), "r"), pclose);
      |                                                  ^
/home/nhp/.cache/yay/hyprlock-git/src/hyprlock/src/core/hyprlock.cpp: In member function ‘void CHyprlock::spawnAsync(const std::string&)’:
/home/nhp/.cache/yay/hyprlock-git/src/hyprlock/src/core/hyprlock.cpp:819:14: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  819 |         write(socket[1], &grandchild, sizeof(grandchild));
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nhp/.cache/yay/hyprlock-git/src/hyprlock/src/core/hyprlock.cpp:827:9: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  827 |     read(socket[0], &grandchild, sizeof(grandchild));
      |     ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/hyprlock.dir/build.make:174: CMakeFiles/hyprlock.dir/src/core/hyprlock.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hyprlock.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/hyprlock.dir/rule] Error 2
make: *** [Makefile:170: hyprlock] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hyprlock-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprlock-git - exit status 4
[./install.sh]: Command "yay -S --needed python-pywayland python-psutil hypridle-git hyprlock-git wlogout wl-clipboard hyprpicker-git anyrun-git" has failed.
You may need to resolve the problem manually BEFORE repeating this command.

I've repeat the yay command, and it doesn't work, and I choosed to ignore this to continue executing the shell script.

I'm not familiar with programming, just read a little  book of python. I think maybe i need advanced programmer's help.Thanks

**Comment by clsty** [comment]
So, the main problem here is that you can't install `hyprlock-git`.

You may try to build and install hyprlock from its [repo](https://github.com/hyprwm/hyprlock), and it still does not work, please open an issue in that repo.

**Comment by clsty** [comment]
Closing in favor of #300
