### ISSUE TITLE
[Issue] AGS Weather module not legible in light mode

### ISSUE THREAD

**Issue by yrnmsk** [end-4/dots-hyprland#298]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: EndeavourOS

---
## The issue

Setting theme to light mode from any dark theme variant doesn't change weather module's text color, making it illegible. Other text colors are fine though.

Screenshot:
![image](https://github.com/end-4/dots-hyprland/assets/72034970/5c1bb540-7f02-4fc1-9a8c-32b40373cc79)

No explicit errors are shown via `pkill ags; ags &` in terminal. I haven't explored any of the color generation scripts yet, but I think the issue may be caused from there, not really sure tho idk.

**Comment by end-4** [comment]
forgot to add text color class

**Comment by yrnmsk** [comment]
Yep that fixed it, closing this now.
