### ISSUE TITLE
[Feature] Window Title showing on all monitors

### ISSUE THREAD

**Issue by josvvn** [end-4/dots-hyprland#299]
**What would you like to be added?**

![image](https://github.com/end-4/dots-hyprland/assets/34856305/44352de4-d430-434f-ad4a-8a52080b25c6)

I have 3 monitors and I often get lost on where my cursor is or even what is the current active window.
The current active window label only shows on the main monitor, and that's okay, but at least in my case I need to turn my head very often and it hurts because of that.
The label is defined on **spaceleft.js** in .**/config/ags/modules/bar**. 
I wanted to add this "feature" but I'm not very proficient at Javascript :)

**Comment by end-4** [comment]
I'm not exactly sure what you want, but I guess something like pressing a keybind to toggle a highllight at mouse position will do?

**Comment by end-4** [comment]
oh actually, if you mean spawning the bar on all monitors, that would be hard with how the code for it is currently

**Comment by BasitAli** [comment]
I found it. We had a single instance of the WindowTitle that was being reused between all the Bars which is why it didn't appear on any other monitor.

This works for me,

![image](https://github.com/end-4/dots-hyprland/assets/869390/ce98adc9-ea19-4e8b-bb1e-add74d8aaaf2)

**Comment by end-4** [comment]
I would have to ditch sway support or my subpar JS skills would not allow me to have this work correctly
fine

**Comment by end-4** [comment]
huh i totally forgot about this
why close

**Comment by end-4** [comment]
does it work now?
