### ISSUE TITLE
[Issue] Various hyprlock freezes/hangs 

### ISSUE THREAD

**Issue by b4shful** [end-4/dots-hyprland#300]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)** yes
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)** yes
- Linux distro: Arch Linux

---
## The issue

I've been running into weirdness where sometimes the lock screen doesn't take any keyboard input and seems to hang (the textbox with the password characters/dots doesn't even appear when typing). I couldn't find any way to recover from this aside from SIGTERM-ing Hyprlock/Hyprland etc. or going into another tty and using loginctl to terminate the session.

Hyprlock seems to hang sometimes when waking up from suspension (laptop lid closed and then opened after some time) and also when you hit enter without typing a password. Not 100% sure yet if it's actually related to suspension or not, it might be that I had hit the enter key in order to wake the laptop up and then it triggered the Hyprlock bug mentioned below.

It seems this is a Hyprlock problem, there are reports on their repo that potentially Hyprlock is crashing when waking up from suspended/sleep state. 

I have been able to reproduce hyprwm/hyprlock#95 "Hitting enter with empty password hangs app"

I will try to get some logs (not sure how to even get a log out of hyprlock, couldn't find anything by default)

My current hyprlock version according to pacman is `hyprlock-git 0.1.0.r80.8969351-1`, there seems to have been some updates to hyprlock addressing these issues, maybe I should try updating hyprlock manually?

**Comment by clsty** [comment]
Hyprlock is a very new project. When I tried it for the first time, it locks me out of my PC without receiving any input. I had to reboot the computer and then it works.

If the version provided by AUR package could be problematic for now (see also #296), maybe we can directly built it in install script, and also use a hash commit to control version, similar to AGS? @end-4

**Comment by b4shful** [comment]
Just updated via `yay -S hyprlock-git` to the current latest version on AUR (hyprlock-git 0.1.0.r42.gcb08f602-1) and can confirm it fixes all of these issues.

There is a little delay if I press enter without typing a password (when the password entry box isn't visible at all) before I can start typing again and have it register/make the password entry box appear. It would be nice if, despite the password box not being visible, there was some sort of indication that it was trying to login when enter is pressed, but this might be Hyprlock's responsibility.

As it stands if I am on the lock screen and press enter without typing anything else (password box not visible) , I will need to wait a few seconds before it lets me type anything again (at which point the password box appears). Not the end of the world, but when the system is busy (after pressing enter without typing a password) and can't take input it might be nice to know this.

But anyways, after updating hyprlock I tested pressing enter without typing a password, and also suspended my laptop then unsuspended it and everything worked fine with no hangs or crashes. I haven't tested the different possible sleep states yet so I can't say for certain everything is 100% fixed with this. But it seems promising. Assuming the install script just installs the latest version from AUR, that means no fix would be needed for this particular issue (and anyone experiencing issues just needs to update their Hyprlock).

**Comment by end-4** [comment]
Can confirm. But does `loginctl lock-session` work for you now? It no longer does for me somehow :thinking:
