### ISSUE TITLE
[Feature] Implementing the weather for cities with spaces in the name

### ISSUE THREAD

**Issue by William-Tatum** [end-4/dots-hyprland#301]
**What would you like to be added?**
Adding a .replace() or something similar to this return JSON.parse(output)['city'].replace(/ /g, "_").toLowerCase(); on line 193ish in the file .config/ags/modules/bar/normal/system.js

**How will it help**
It will allow cities with a space in the name to work with the weather thing.

**Comment by end-4** [comment]
but doesn't entering the city name without spaces work? pretty sure it should

**Comment by William-Tatum** [comment]
Yeah probably I was just saying that at least for me when it did the curl for the city, since my city has a space in it the weather wouldn't show up unless I did something like that.
