### ISSUE TITLE
[Issue] After update, primary colours of status bar changed

### ISSUE THREAD

**Issue by b4shful** [end-4/dots-hyprland#306]
OS: Arch Linux

I have no wallpaper set, it's just the default one. After updating to use the new config style, my primary colour seems to have went from a light grey to a more reddish colour.

Not sure what happened, and whether it's maybe an easy fix or not? Just not entirely sure where it gets the primary colour from. I know it may be something to do with the wallpaper, but my wallpaper didn't change.

I have no easily accessible pictures of it before, only after the change:
![image](https://github.com/end-4/dots-hyprland/assets/28313200/5e0f4a66-33a1-4d67-b3d9-0ff5d7dfddc9)

Is this reddish tint the default? Or does it not work that way. How could I get it back to something a bit more,, grey?

![image](https://github.com/end-4/dots-hyprland/assets/28313200/e8e1c4bc-b201-4fce-9db2-2c9dbc91479c)

This is the current colour profile (the one I don't want), which I got by default, provided here for reference (sorry that it's  a terrible screenshot)

**Comment by end-4** [comment]
oopsies then, it's because i uploaded something with my color files
anyway you can just type `>color` in the search menu, hit enter and click on your favourite color to change it

**Comment by b4shful** [comment]
Sure, that works! Cheers.

Btw, is there a list of those actions beginning with `>` ? Not sure if I saw much about them in the docs.

**Comment by clsty** [comment]
> Btw, is there a list of those actions beginning with `>` ? Not sure if I saw much about them in the docs.

In the [Wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/):
> Actions: An actions starts with >. See the keybind cheatsheet for a list of actions
