### ISSUE TITLE
[Feature] Configurable time/date formats and refresh interval

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#307]
**What would you like to be added?**

For this part in wiki:

> For the statusbar, edit `~/.config/ags/modules/bar/system.js`. Change `"%H:%M"` according to the format described [here](https://docs.gtk.org/glib/method.DateTime.format.html).

- It will be better to make this one configurable via `user_options.js`.

- Also please allow custom interval because user may prefer a 1000 ms interval for using `%H:%M:%S` format.

- Also the date format.

Thanks in advance.

**How will it help**

Convenient for user to customize time/date format.

**Comment by end-4** [comment]
ok

**Comment by clsty** [comment]
Thanks a lot, you save me much time changing the format per updating.
