### ISSUE TITLE
Firefox Gnome Theme Icons

### ISSUE THREAD

**Issue by MaulanaMalikS** [end-4/dots-hyprland#31]
Hello!
I am trying to import Firefox Gnome Theme on `Import Manually` folder under `novelknock` branch.
But `icons` folder is not included there.

If it's intentional, can you tell me where i can get that icons?
Thanks!

**Comment by end-4** [comment]
Hi
- There is no icon theme for Firefox though.
   - Other themes might have an icon folder but not this one 
   - If you mean normal icons for apps, you can find them in `.local/share/icons`

**Comment by MaulanaMalikS** [comment]
I mean icon for this theme, because i can't see refresh button, add new tab button, home button, etc when i apply this theme.

When i look inside the files, `theme/parts/tabsbar.css` for example, there is a reference to `icons` folder,
like this one:
https://github.com/end-4/dots-hyprland/blob/36873cad35e33e9746dc135f9c447c1d2e848419/Import%20Manually/firefox/GNOME_red/theme/parts/tabsbar.css#L303

then i assume there is a folder for icons.
Thanks for your reply!

**Comment by end-4** [comment]
bruh i had .svg in .gitignore
https://github.com/end-4/dots-hyprland/commit/372548f28261da055993e7f9deb6758be804651e

**Comment by end-4** [comment]
Days since end-4 was an idiot counter reset to 0

**Comment by MaulanaMalikS** [comment]
thanks for the update!
