### ISSUE TITLE
I like your wallpapers

### ISSUE THREAD

**Issue by Memory-Studio** [end-4/dots-hyprland#310]
I like your **wallpapers** =)
can you **send all your wallpapers** please
Thank you very much!
XD

**Comment by end-4** [comment]
red one https://unsplash.com/photos/red-and-black-artwork-ioJBsYQ-pPM

<details> <summary> black one </summary>

![black-fluid-abstract](https://github.com/end-4/dots-hyprland/assets/97237370/ec0a71b3-0bcd-4de8-8b49-3f5d4d81d3aa)
</details>

cherry blossom with egrill one https://www.pixiv.net/en/artworks/111749410

the blue blocks one https://4kwallpapers.com/abstract/windows-11-windows-365-blocks-3d-background-blue-background-8630.html

others i forgor and deleted. maybe do a reverse image search (just screen snip to clipboard (super+shift+s), go to https://images.google.com , hit the camera button, then Ctrl+V)

**Comment by Memory-Studio** [comment]
Thank you!!!
=)
