### ISSUE TITLE
[Feature] Keep screen on

### ISSUE THREAD

**Issue by catmeowjiao** [end-4/dots-hyprland#313]
Sometimes, we need to prevent the screen from locking when closing the laptop lid. Therefore, I wrote a script.

First, create `~/.config/hypr/hypridle.conf.bak`, in which you replace both `$lock_cmd` and `$suspend_cmd` with `echo " "`.

Next, add the following code to `~/.config/hypr/hyprland/keybinds.conf`.

```
# Normal screen off / Keep screen on
bind = Super+Alt, S, exec, mv ~/.config/hypr/hypridle.conf ~/.config/hypr/hypridle.conf.bak.bak && mv ~/.config/hypr/hypridle.conf.bak ~/.config/hypr/hypridle.conf && mv ~/.config/hypr/hypridle.conf.bak.bak ~/.config/hypr/hypridle.conf.bak
```

This way, after pressing Super + Alt + S, you can toggle between normal screen off and keeping the screen on.

`Pull Requests` are cumbersome, so I submitted an `Issue`. Please consider adding this feature in your busy schedule, thank you!

**Comment by end-4** [comment]
Use the coffee button on the sidebar

**Comment by catmeowjiao** [comment]
oh, i'm an idiot
