### ISSUE TITLE
[Issue] Anyrun Launcher doesn't work

### ISSUE THREAD

**Issue by sametersoylu** [end-4/dots-hyprland#315]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: 
Fedora 39

---
## The issue
Okay, I'm not sure if I should open the Issue here or at the Anyrun's repo, but I decided to open it first here. 
I use Fedora and AnyRun (if I installed correct thing) doesn't have a package for Fedora. So I installed it manually, but when I try to run it, it throws error and it doesn't run with shortcuts, only through terminal. I'll past the error down.

<details>
<summary>Click to expand</summary>

```plain
[theany@fedora ~]$ anyrun
Error reading applications plugin config: No such file or directory (os error 2)
Error reading directory /home/theany/.local/share/flatpak/exports/share: No such file or directory (os error 2)
```

</details>

**Comment by end-4** [comment]
- I don't think those file not found errors are critical. I get like 4 of them and it runs fine.
- Does it run successfully if you don't use my config? just rename the config folder: `mv ~/.config/anyrun ~/.config/anyrun.bak`
  - If it does, then it's my problem. (though no idea how that might be the case)
  - If it doesn't, ask in anyrun repo

**Comment by sametersoylu** [comment]
> * I don't think those file not found errors are critical. I get like 4 of them and it runs fine.
> * Does it run successfully if you don't use my config? just rename the config folder: `mv ~/.config/anyrun ~/.config/anyrun.bak`
>   
>   * If it does, then it's my problem. (though no idea how that might be the case)
>   * If it doesn't, ask in anyrun repo

I removed the config and still no luck, it won't open with the shortcut. Only opens through terminal. I probably should open an issue on their repo.  

Okay one more addition, it works now, but the command was just anyrun right on the config file, and since I compiled it from source, and cargo installed locally, it was installed to ~/.cargo/bin, the problem was, even tho I added it  to the path Hypr dispatch appearently couldn't find it. So giving full directory to executable fixed. Well, problem fixed. Sorry to bother you!
