### ISSUE TITLE
Screenshot command is wrong

### ISSUE THREAD

**Issue by catmeowjiao** [end-4/dots-hyprland#316]
The screenshot area of grim should be enclosed in quotes, but the current screenshot command is this: 
`grim -g $(slurp) - | swappy -f -`
This causes grim to prompt `invalid geometry` and prevents swappy from working. 
Solution: Change `$(slurp)` to `"$(slurp)"`.

**Comment by clsty** [comment]
I can confirm this. I just realized I have been using `"$(slurp)"` in my config long time before.
