### ISSUE TITLE
hyprland.conf is wrong

### ISSUE THREAD

**Issue by catmeowjiao** [end-4/dots-hyprland#319]
Custom configuration file not imported in hyprland.conf

**Comment by end-4** [comment]
can't say "A is wrong" without pointing out what specifically is lol

**Comment by clsty** [comment]
If you already have `hyprland.conf` exists before, it will not be overwritten, which will cause such problem.

Use `hyprland.conf.new` as reference if you don't know what the `hyprland.conf` should be like.

**Comment by end-4** [comment]
consider putting that "Custom configuration file not imported in hyprland.conf" in the issue title next time

**Comment by catmeowjiao** [comment]
oh, sorry
