### ISSUE TITLE
Connecting Music Player to eww 

### ISSUE THREAD

**Issue by coacharnold1** [end-4/dots-hyprland#32]
How do I connect my music player to the upperbar  and bottom bar controls/display?  What player/s are they looking for MPD?

This is AMAZING  work BTW .... thank you

**Comment by end-4** [comment]
i'm sure it works for firefox and chromium-based stuff
remember to install both "Plasma browser integration" extension for it and `plasma-browser-integration` package (as mentioned in the main readme)

**Comment by end-4** [comment]
it is supposed to display the art
could you provide a link to the site where you were playing music?

**Comment by end-4** [comment]
it tells me to login

**Comment by coacharnold1** [comment]
Sorry ... i guess it wants you to go from here to get the correct guest login

http://demo.subsonic.org/login.view?user=guest1&password=guest

**Comment by end-4** [comment]
- get plasma browser integration extension and get `plasma-browser-integration` package (like mentioned in the readme)
- if it still doesnt work, run `playerctl metadata -F` like i did above and play a track. is there a line that says "artUrl"?

**Comment by coacharnold1** [comment]
I'm sorry ,,,, I thought i was getting a  bottom cover ...  but i's just displaying the metedata text ....  here's what i see

![image](https://github.com/end-4/dots-hyprland/assets/30500110/dff31707-8fd9-4f06-ba57-41c2b4da890e)

**Comment by end-4** [comment]
pls provide the output for
`cd ~/.config/eww && scripts/music cover`

**Comment by nekonya3031** [comment]
> I'm sorry ,,,, I thought i was getting a bottom cover ... but i's just displaying the metedata text .... here's what i see
> 
> ![image](https://user-images.githubusercontent.com/30500110/254936967-dff31707-8fd9-4f06-ba57-41c2b4da890e.png)

I am sorry but u printed `mccover` instead of `mcover` in ur terminal...

**Comment by coacharnold1** [comment]
I'm sorry ..... I missed this,   here you go 

{"image": "eww_covers/cover_art_default", "color": {"alpha":"100","colors":{"color0":"#111215","color1":"#2B698F","color10":"#597591","color11":"#447CC0","color12":"#3A9FB7","color13":"#6192A6","color14":"#60ABCC","color15":"#c4c6ca","color2":"#597591","color3":"#447CC0","color4":"#3A9FB7","color5":"#6192A6","color6":"#60ABCC","color7":"#c4c6ca","color8":"#898a8d","color9":"#2B698F"},"special":{"background":"#111215","cursor":"#c4c6ca","foreground":"#c4c6ca"},"wallpaper":"~/.config/eww/eww_covers/cover_art","source":"󰗃"}}

**Comment by end-4** [comment]
okay try again
this is a bug i tackled for newer branches but not this one
shouldve thought of that when i saw the `firefox mpris:artUrl file:///home/fausto/.mozilla/firefox/firefox-mpris/18149_10.png`

**Comment by coacharnold1** [comment]
Newer branches of firefox?  or this version of the hyprland theme?   is there something I should do to get kicked up to the newest version?

Thanks

**Comment by end-4** [comment]
i meant newer branches of this repo
the "novelknock" branch and "suichanmywaifu" (wip) branch

more importantly, did that fix it for you on the "hybrid" branch

**Comment by end-4** [comment]
just download the hybrid branch and copy the eww folder again

**Comment by coacharnold1** [comment]
can you post a link to the most recent branch.  not sure where i'm grabbing it.

**Comment by end-4** [comment]
- the two above mentioned branches have a different style compared to the one you're using. 
- if that's what you want, go to 
  - [novelknock](https://github.com/end-4/dots-hyprland/tree/novelknock)
  - [suichanmywaifu)](https://github.com/end-4/dots-hyprland/tree/suichanmywaifu)
- and close this issue

**Comment by coacharnold1** [comment]
192

**Comment by end-4** [comment]
the heck is a 192 lol

**Comment by coacharnold1** [comment]
a type o .... probably me going over to my media server and typing  the wrong place....doh!
