### ISSUE TITLE
[Issue] Material colors cause info loss for terminal e.g. htop

### ISSUE THREAD

**Issue by nullptroma** [end-4/dots-hyprland#323]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arch

---
## The issue
The point is to automatically determine the color scheme of the environment. They are applied in the terminal, after entering fish, and remain even if you exit back to bash. So, for example, htop doesn't display a lot of information because of this. What colors do I need to fix?
![image](https://github.com/end-4/dots-hyprland/assets/64524860/0e8f94f2-68d5-4a42-915e-98adbc06f1a4)

**Comment by nullptroma** [comment]
The background of the foot terminal and the generated color are the same, so they merge. How do I redefine one of the colors?

**Comment by end-4** [comment]
Maybe i should stop trying to use material colors in terminals... 

You can try one of the following:
- Not have fish apply colors: in `~/.config/fish/config.fish`, comment out lines 16-18 that `cat` the sequence file
- Not use `fish` shell (change foot config in `~/.config/foot/foot.ini`)
- Or just use a graphical task manager :)

**Comment by end-4** [comment]
should look like this now
![image](https://github.com/end-4/dots-hyprland/assets/97237370/8d0abc28-447a-4adf-b169-5ce43100a690)
