### ISSUE TITLE
[Feature]  Add icon for battery

### ISSUE THREAD

**Issue by BlokCSS** [end-4/dots-hyprland#325]
**What would you like to be added?**
Battery icon for the bar

**How will it help**
It is very usfeul to have at first sight hows my life's battery

**Extra info**
We all are know the actual bar (wich is AMAZING), but it lacks the icon for battery. I just recently noticed that next to the gear, its the actual life battery 
![image](https://github.com/end-4/dots-hyprland/assets/82058445/29f0f08e-89a0-4c3c-a8db-f7ba39115b27)

I suggest a few considerations:

1) Change that gear icon for a battery icon. On the other hand, i think we dont really need that click action to launch the "sideright" widget since we can use by keybinding or clicking on the wifi/bluetooth icon

2)Take off the gear/percentage utility (the same as the image above) and add the icon for battery next to the wifi/blueetooth. Inside here: 
![image](https://github.com/end-4/dots-hyprland/assets/82058445/c5eaacb1-e4a0-4fe5-982c-8c3bcabab65c)
Insetad where the actual battery percentage is, i dont know, maybe you can add a button/utlity/clickeable thing to rapidly make a "pacman -Syu" to update the system. Maybe other thing could be more helpful hahah.

This is the type of icon im thinking for the battery, like in gnome:
![image](https://github.com/end-4/dots-hyprland/assets/82058445/56f5eb81-8c7d-4d3c-ba3a-702670984457)
Maybe just the icon with the chargin body (green good %, red under 20%) and the tooltip could say the percentage on hover.

Im telling you this cuz i dont know ANY about ags =C
Thank you so much for this dotfiles and configs, you are an amazing artist. This is my new main system on my laptop

**Comment by BlokCSS** [comment]
PD: i read the issues talking about this, but i didnt understand XD

**Comment by clsty** [comment]
> Take off the gear/percentage utility (the same as the image above) and add the icon for battery next to the wifi/blueetooth. Inside here:

It is reasonable to put the indicators together I guess.

> Insetad where the actual battery percentage is, i dont know, maybe you can add a button/utlity/clickeable thing to rapidly make a "pacman -Syu" to update the system. Maybe other thing could be more helpful hahah.

A `pacman -Syu` button is not very helpful to me, though we already have a similar one on the left sidebar (Tools - Quick scripts - Update packages).
As for a desktop computer which does not have a battery, this place will automatically changed to a weather widget.

---

However, everyone may have their own logic for the widget arrangement on the bar.
It will be perfect if user may custom it themselves.
(Related issue: #271)

**Comment by end-4** [comment]
- i won't color the battery cuz it would look out of place
- i don't like battery icons since they're often filled at certain filled levels, which is the most misleading thing ever on a top bar

but i'll see what i can do

**Comment by end-4** [comment]
what do yo think
![image](https://github.com/end-4/dots-hyprland/assets/97237370/fd9061bb-0539-4e3b-a9e2-be2d031050dd)

**Comment by end-4** [comment]
- About relocation of battery display, I don't want that because I care about my battery more than wifi connection strength and want it in the middle
- Having update function on battery icon isn't exactly fitting... A battery saver toggle might make sense, though. But some might use `tlp` while others use `power-profiles-daemon`... (I use the former since it does actually seem to save battery)

**Comment by BlokCSS** [comment]
it is fantastic!
amazing job, really thanks you. So i just have to grab from the repo and put it locally on my .config right?

**Comment by BlokCSS** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/82058445/ef892cdd-6396-439b-98fc-6990b4f61f7f)
perfect!

PD: i wrote in other issue about something weird. I dont know if its bug or something related to color scheme or whatever, but when i change the wallpaper, suddenly, the image for hyprlock just disappear and comes back to default

**Comment by end-4** [comment]
> So i just have to grab from the repo and put it locally on my .config right?

basically
you can run the install script again then tell it to install desired parts only
