### ISSUE TITLE
[Issue] Hyprlock changes the path (wallpaper)

### ISSUE THREAD

**Issue by BlokCSS** [end-4/dots-hyprland#328]
Hello again!
I dont really know if its a bug or something related to match the color from the wallpaper, but each time i change the wallpaper, the hyprlock.conf go back to default and there is no more wallpaper. Is it a way to fix this and keep the wallpapaer when lock the screen.
Thanks!

**Comment by BlokCSS** [comment]
I need some help in this same issue just not to open another. I want to have consistency with the cursors. I already exec-once gsetting stuff, but when the cursor is on desktop it change to bibata, on the apps its adwaita and i want to keep the adwaita through all
![image](https://github.com/end-4/dots-hyprland/assets/82058445/9f3fdeb4-3279-46ad-b7ae-c5c36705c6cc)

**Comment by clsty** [comment]
> I need some help in this same issue just not to open another. I want to have consistency with the cursors. I already exec-once gsetting stuff, but when the cursor is on desktop it change to bibata, on the apps its adwaita and i want to keep the adwaita through all ![image](https://private-user-images.githubusercontent.com/82058445/312700008-9f3fdeb4-3279-46ad-b7ae-c5c36705c6cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTE0NjEsIm5iZiI6MTcxMDM5MTE2MSwicGF0aCI6Ii84MjA1ODQ0NS8zMTI3MDAwMDgtOWYzZmRlYjQtMzI3OS00NmFkLWI3YWUtYzVjMzY3MDVjNmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA0MzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYWVjMzJjMjJhMjlkOTEzMmNjOTM1YmI4ZjYxNGRmNWU5OWUwOTMyNzdmZTAwOGI3M2VmNTRkZDk2Y2JjYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lIQr7l45BDUZN3V5Un22J5rNQtSz6qwQSxq2Sw8r3CU)

Did you reboot your system to ensure your config take effects totally?

**Comment by BlokCSS** [comment]
cursor is fixed, i reboot and works!

**Comment by end-4** [comment]
> I need some help in this same issue just not to open another. I want to have consistency with the cursors. I already exec-once gsetting stuff, but when the cursor is on desktop it change to bibata, on the apps its adwaita and i want to keep the adwaita through all ![image](https://private-user-images.githubusercontent.com/82058445/312700008-9f3fdeb4-3279-46ad-b7ae-c5c36705c6cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTI1MzcsIm5iZiI6MTcxMDM5MjIzNywicGF0aCI6Ii84MjA1ODQ0NS8zMTI3MDAwMDgtOWYzZmRlYjQtMzI3OS00NmFkLWI3YWUtYzVjMzY3MDVjNmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA0NTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMTkzNWUzNDVhZjA2YzViMzRmNzg0YTJhNmFjMDJhMzEzNzUzOGZlMDVhYjY2MmVkN2E1YjIyZDRiYTkyYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pfAjYPgwRMpM03pDx77sqxAjyjaBZb4AX-RZct9N_Aw)

you don't have to run gsettings every time you start hyprland like this. just set them once then remove those two lines
