### ISSUE TITLE
Workspace switcher

### ISSUE THREAD

**Issue by coacharnold1** [end-4/dots-hyprland#33]
The workspace switcher is working great,  it does 2 things weird:

1 - It will not allow you to mouse select workspace #1. Is this by design?

2- The workspace labels do not switch to highlight/identify which workspace you are on.

I've been searching for the widget that controls this and  i cannot figure it out.

73
Thanks
Tim

**Comment by end-4** [comment]
1. It doesn't allow you to mouse select a workspace if you're already at that workspace. move around workspaces and see if the indicator follows
2. workspaces with windows have a brighter indicator. the active workspace has a highlight with accent color. if these don't show properly, provide the output of `cd ~/.config/eww && scripts/workspaces`

**Comment by coacharnold1** [comment]
Here's what I get:

[{"num":"1","clr":"rgba(174,172,182,0.7)"},{"num":"2","clr":"rgba(174,172,182,0.7)"},{"num":"3","clr":"rgba(174,172,182,0.7)"},{"num":"4","clr":"rgba(146,145,145,0.5)"},{"num":"5","clr":"rgba(146,145,145,0.5)"},{"num":"6","clr":"rgba(146,145,145,0.5)"},{"num":"7","clr":"rgba(146,145,145,0.5)"},{"num":"8","clr":"rgba(146,145,145,0.5)"},{"num":"9","clr":"rgba(146,145,145,0.5)"},{"num":"10","clr":"rgba(146,145,145,0.5)"}]
scripts/workspaces: line 83: socat: command not found
fausto@fedora ~/.c/eww >

**Comment by coacharnold1** [comment]
just fixed that "socat" requirement    I get a highlighted workspace,  but it doesn't switch the workspace that is hilighted.   I can mouse click on any workspace,  and it moves except to the one that is highlighted.  ( in my case, workspace # 1)

**Comment by coacharnold1** [comment]
OK ...  everything works perfect when switching with the mouse scroll.  Is this this correct functionality?  If so cool ...  I just expected it to behave the same with a SUPER-(number) key-press as in:

super + 5 = Moves to workspace 5 and the 5 is highlighted in the top bar.

If not ...its no big deal,   just wanting to make sure I do everything in setup correct.

**Comment by coacharnold1** [comment]
scratch all that ....  did a reboot,  looks as if evrything is working perfect now... I guess the issue was the "socat" package... thanks!
