### ISSUE TITLE
[Feature] Light theme variant for `>badapple` action command

### ISSUE THREAD

**Issue by yrnmsk** [end-4/dots-hyprland#330]
**What would you like to be added?**

Title pretty self-explanatory, I want a bad apple scheme variant for light mode theme.

Right now, the action command seems to be ignoring the current color-scheme. I confirmed this, since if you:

- execute the action command (`>badapple`) in overview
- and then check the color-scheme (via `gsettings get org.gnome.desktop.interface color-scheme`)

it still properly outputs 'prefer-light'.

But `>badapple` statically applies a dark color scheme regardless of what the user's current color-scheme is by applying a scheme that seems to be made for dark mode only.

This raises issues where applications that properly respond to user's current color-scheme and applies a light mode theme seem to be the ones that are out of place since everything else seem to be in dark mode theme (e.g.: file explorer, terminal, AGS, etc).

<details>

<summary> Preview of Discord that seem to be out of place </summary>

<br>

![image](https://github.com/end-4/dots-hyprland/assets/72034970/ccdf0286-ec99-45f7-a302-63ee1d0077b6)

</details>

I want the action `>badapple` to consider what the current user preferred theme mode is and apply the appropriate color scheme based on that.

**How will it help**

This addition will make the color/theme generation much more consistent across user's current color-scheme.

**Comment by end-4** [comment]
should work now, pls test

**Comment by yrnmsk** [comment]
Yes, it works perfectly. Will close this issue now, but will just reopen if I maybe missed out or some other things related to light badapple variant
