### ISSUE TITLE
[Feature] Add Support for ZSH

### ISSUE THREAD

**Issue by michii-h** [end-4/dots-hyprland#333]
**What would you like to be added?**
I prefer the zsh over fish shell. But when I change to zsh, it always uses the default colors.
So support for the zsh shell would be awesome.

**How will it help**
Makes the dotfiles more usable for people who prefer zsh.

**Comment by end-4** [comment]
@clsty handle the installation please?

**Comment by clsty** [comment]
> @clsty handle the installation please?

Sure, but as for `.zshrc`, I don't think directly overwrite this file is a good idea. We can let user to source this file though.

Will work on this later.

**Comment by end-4** [comment]
why there?

**Comment by clsty** [comment]
So, if we put the file under `$HOME`, we are "trashing" the home directory. And if other places, I'm not sure where. Do you have an idea though?

**Comment by end-4** [comment]
trashing? no? zshrc is supposed to be in home?
we're going to ask the user whether they want to overwrite or not right?

else we could have it in "Import Manually" folder

**Comment by clsty** [comment]
I meant we'd better not to overwrite it, but let user to **source** it, i.e. put something like this in their `.zshrc`:
```zsh
source ~/.zshrc.d/ags_colors.zsh
```

**Comment by clsty** [comment]
I'll put it in `~/.config/zshrc.d/` for now.

Feel free to talk more about it or make further changes.

**Comment by clsty** [comment]
Done.

(The color looks weird on my zsh, so personally I'm not sourcing it.
Very probably because I'm already using another zsh theme.)

After sourcing:
![image](https://github.com/end-4/dots-hyprland/assets/129247596/db8eddde-5e74-4101-b933-9c7b046cccf2)

Without sourcing:
![image](https://github.com/end-4/dots-hyprland/assets/129247596/09a51ec7-60d1-4b77-905d-b3d5d4cb0be3)

**Comment by end-4** [comment]
your colors look not very readable because you're using them wrong (i do that too lol)
colors are meant to be on bg color, not on top of each other,

**Comment by clsty** [comment]
> your prompt looks not very readable because you're using colors wrong (i do that too lol) colors are meant to be on bg color, not on top of each other,

I'm not sure, just using a preset of [p10k](https://github.com/romkatv/powerlevel10k) and did not tweak around its colorscheme.

**Comment by michii-h** [comment]
Thanks a lot, works perfectly :)
