### ISSUE TITLE
[Issue] Missed Icons/Symbols almost everywhere

### ISSUE THREAD

**Issue by michael555444** [end-4/dots-hyprland#353]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Fedora Linux 39 (Thirty Nine)
---
## Missed Icons/Symbols almost everywhere
I have been installed all the dependencies provided in `scriptdata/dependencies.conf` that included 
```
fontconfig ttf-readex-pro ttf-jetbrains-mono-nerd ttf-material-symbols-variable-git ttf-space-mono-nerd
```
but no one icon is loaded and typed as text. What is name of required font or where is the configuration to change it by myself.

![image](https://github.com/end-4/dots-hyprland/assets/33288939/02381a72-97cd-4bb5-8756-9f0ff7ad9a9b)

<details>
<summary>Log</summary>

```plain
╭─m1cham0v at m1cham0v in ⌁
╰─λ ags
(com.github.Aylur.ags:804306): Gjs-WARNING **: 07:06:06.461: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
(com.github.Aylur.ags:804306): Gjs-WARNING **: 07:06:06.461: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
Gjs-Console-Message: 07:06:06.961: [LOG] Styles loaded
(com.github.Aylur.ags:804306): Gtk-WARNING **: 07:06:07.167: Attempting to add a widget with type Ags_Scrollable to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.
(com.github.Aylur.ags:804306): Gtk-WARNING **: 07:06:07.228: Attempting to add a widget with type Ags_Revealer to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.231: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.231: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.232: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.233: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.233: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.263: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.263: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.299: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
(com.github.Aylur.ags:804306): GLib-GObject-CRITICAL **: 07:06:07.300: value "1.000427" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
```

</details>

**Comment by michael555444** [comment]
I read about an error when restarting the `ags`, which I hope will also be solved soon.

**Comment by clsty** [comment]
I've added a new script `non-Arch-installer.temp.sh`. It's a temporary quick solution and I may improve it some day in future.

(Accidentally closed, sorry)

**Comment by end-4** [comment]
michael, mind sharing your result of `cat /etc/os-release`?
i'll make that penguin icon fedora

**Comment by michael555444** [comment]
> michael, mind sharing your result of `cat /etc/os-release`? i'll make that penguin icon fedora

welcome

```plain
╭─m1cham0v at m1cham0v in ⌁
╰─λ cat /etc/os-release
NAME="Fedora Linux"
VERSION="39 (Thirty Nine)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Thirty Nine)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
```

**Comment by michael555444** [comment]
> I've added a new script `non-Arch-installer.temp.sh`. It's a temporary quick solution and I may improve it some day in future.
> 
> (Accidentally closed, sorry)
> 
> Please run the script and see if it solves the problem.

nope, still text only...
![image](https://github.com/end-4/dots-hyprland/assets/33288939/c246d7dc-c460-43d7-838d-fd03e862c884)

**Comment by clsty** [comment]
What about running `fc-cache -fv` and test again?

If that still does not work, I don't know how to help then. Probably fedora has another method to install font/symbols and I don't know how.

**Comment by end-4** [comment]
can you search for the font in gnome-font-viewer? does it show up?
![image](https://github.com/end-4/dots-hyprland/assets/97237370/6244fe33-38af-4b7e-91f8-8b7082d68fac)

**Comment by michael555444** [comment]
hmmmm.... it's unavailable

![image](https://github.com/end-4/dots-hyprland/assets/33288939/4c415338-1fba-4386-a09d-1710796097b0)

I'll try to install that one and type a cheatsheet below

**Comment by end-4** [comment]
You need Material **Symbols**, not Material **Icons**

**Comment by end-4** [comment]
symbols is the new one and is used in my config

**Comment by Architect0rr** [comment]
Sorry, but where do I find proper fonts? I tried downloading it from `marella/material-symbols` but it does not helped

**Comment by nicefaa6waa** [comment]
I've faced this issue before,To fix it basically reinstall it and don't skip when something doesn't work.Just look for the error install them manually and restart the script.That solved the issue for me

**Comment by w8z4rd** [comment]
![Screenshot_2024-05-03_13 47 43](https://github.com/end-4/dots-hyprland/assets/161143192/03e50a13-322a-4f85-b25b-a6f648d75e87)


> You need Material **Symbols**, not Material **Icons**

I'm having the same problem even though I have material symbols installed ( i already did fc-cache -fv and restarted ags)

**Comment by TechLionDev** [comment]
where do you get the material symbols font?

**Comment by TechLionDev** [comment]
Any Luck? @michael555444 
> I'll try to install that one and type a cheatsheet below

**Comment by TechLionDev** [comment]
I found that if you visit https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined

you will find teh woff2 file at https://fonts.gstatic.com/s/materialsymbolsoutlined/v179/kJF1BvYX7BgnkSrUwT8OhrdQw4oELdPIeeII9v6oDMzByHX9rA6RzaxHMPdY43zj-jCxv3fzvRNU22ZXGJpEpjC_1v-p_4MrImHCIJIZrDCvHOej.woff2

I then converted with cloudconvert to ttf and installed all Good!

**Comment by end-4** [comment]
actually if you aren't in china just do `yay -S ttf-material-symbols-variable-git`
