### ISSUE TITLE
[Issue] Get Rid Of Black Text in Terminal

### ISSUE THREAD

**Issue by GPSolo** [end-4/dots-hyprland#357]
- Linux distro: 
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
---
The Text in the terminal, sometimes when using 'ls', or sometimes when using random commands, I get black text that is practically unreadable without turning the brightness all the way up. This is really annoying and makes no sense if intentional, that's why I'm assuming this is an issue and not a deliberate decision. I've looked a little bit through foot and fish configs but can't find why this is happening.

Example image:
![image](https://github.com/end-4/dots-hyprland/assets/44757793/0cb7a5ad-70ef-4fad-a426-3cf72afb6f80)

**Comment by GPSolo** [comment]
I think this issue ties into my other issue #358 because after removing the .config files and replacing them with up-to-date config files, the issue no longer is present, at least not until I use the colorpicker or '>img' in ags. my "color-scheming" is messed-up.

**Comment by end-4** [comment]
Looks like something's wrong with color generation. Can you run `~/.config/ags/scripts/color_generation/generate_colors_material.py --path '/PATH/TO/YOUR/WALLPAPER' --smart True` and gimme the output?

I'll close #358 since that and this problem have the same cause

**Comment by GPSolo** [comment]
```
Traceback (most recent call last):
  File "/home/gp/.config/ags/scripts/color_generation/generate_colors_material.py", line 9, in <module>
    from materialyoucolor.hct import Hct
ModuleNotFoundError: No module named 'materialyoucolor'
```
I realize now this issue was caused by a missing dependency for materialyoucolor, on my arch system it was easily fixed by install the AUR package 'python-materialyoucolor-git'
