### ISSUE TITLE
Tray stops working 

### ISSUE THREAD

**Issue by D3ja-vu** [end-4/dots-hyprland#359]
Tray stops working after multiple reloads with the keybinds
+ 
i got this error while reruning it 

`(com.github.Aylur.ags:457345): Gjs-Console-CRITICAL **: 06:12:23.814: failed to cache /home/dr/.cache/ags/media/f146bee8813c026b07f99df4b959f667bf78943f, do you have gvfs installed?`

**Comment by end-4** [comment]
install `gvfs`?

**Comment by end-4** [comment]
also, is that the only error? i can't do anything about the tray if there aren't any logs

**Comment by D3ja-vu** [comment]
i was trying to install it but it needed manual edits + this part of the code that keep repeating while launching it

**Comment by end-4** [comment]
can you elaborate on "manual edits"? editing the installation? what did you do?

**Comment by D3ja-vu** [comment]
nivermind it didnt crash again after update
