### ISSUE TITLE
Strange Multi-head Issues

### ISSUE THREAD

**Issue by mistertuna93** [end-4/dots-hyprland#37]
Hey,

I am trying to get the NovelKnock Dots to work with my hyprland install.  I am on a machine that has a fresh arcolinuxD install with just XFCE and I had installed hyprland and the needed depends from the XFCE desktop.  When I first boot into hyprland it seems to work pretty smoothly, A bit of delay opening applications but that was the only thing I had noticed. After following the instructions for install my monitors start acting goofy.  A cursor appears on both screens, and it seems that only one display is actually active.  The cursor moves around in the same place on both screens but only actually interacts with one screen.  I tried restarting and still had the same issues.  I do have an Nvidia card if that may be part of the problem.  Any ideas?

Thanks,
Charles

**Comment by end-4** [comment]
Hi there,
### Delay when opening apps
- I don't have that issue, but these are possible related answers on the FAQ page of Hyprland wiki: 
  - [Some of my apps take a really long time to open…?](https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open)
  - [My apps take a long time to start / can’t screenshare](https://wiki.hyprland.org/FAQ/#my-apps-take-a-long-time-to-start--cant-screenshare)
### Monitors
- You should look in `~/.config/hypr/hyprland.conf` and edit the first few lines
- Remove the following line to stop monitor mirroring 
```ini
monitor=HDMI-A-1,1920x1080@60,1920x0,1,mirror,eDP-1
```

**Comment by mistertuna93** [comment]
Hey,

Thanks for the quick response.  The gnome xdg portal was the issue for the apps being slow, however, my monitor config appears to be correct and I am still having the same issue. Ill post my config below and the output of hyprctl monitors.  Is there anything else that would be helpful for debugging?  Let me know.

Thanks again.

hyprland.conf:
`#monitor=,preferred,auto,1

# Output
# Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

monitor=DP-2,1920x1080@165,0x0,1
monitor=HDMI-0, 1920x1080@60, 1920x0, 1
#workspace=HDMI-A-1,1
#monitor=HDMI-A-2,1920x1080@60,1920x0,1
#workspace=HDMI-A-2,2

# Example :
#monitor=eDP-1,1920x1080@60,0x0,1
#monitor=eDP-1,transform,0
#monitor=eDP-1,addreserved,10,10,10,10
#workspace=eDP-1,1`

hyprctl monitors Output:
`Monitor HDMI-A-1 (ID 0):
	1920x1080@59.987999 at 0x0
	description: Acer Technologies P244W LEB0D0078520 (HDMI-A-1)
	make: Acer Technologies
	model: P244W
	serial: LEB0D0078520
	active workspace: 3 (3)
	reserved: 0 39 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor DP-2 (ID 1):
	1920x1080@165.003006 at 0x0
	description: GIGA-BYTE TECHNOLOGY CO., LTD. G27FC 0x00000AC1 (DP-2)
	make: GIGA-BYTE TECHNOLOGY CO., LTD.
	model: G27FC
	serial: 0x00000AC1
	active workspace: 2 (2)
	reserved: 0 39 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0`

**Comment by mistertuna93** [comment]
I figured it out, The monitor was declared wrong in the Conf, I just didn't realize it.  Thank you for the help and speedy responses!

**Comment by mistertuna93** [comment]
I figured it out, The monitor was declared wrong in the Conf, I just didn't realize it.  Thank you for the help and speedy responses!
