### ISSUE TITLE
[Issue] Fedora 40 Upgrade 

### ISSUE THREAD

**Issue by coacharnold1** [end-4/dots-hyprland#373]
Hello 

So i've updated to Fedora 40 Beta on my HP-chromebox.   I assumed it wouldn't be perfect.  Here are the issues:

On boot it drops back to the default log in manager and gives an error that it couldn't load ssdm because it didn't see "qtgraphicaleffects"  as called for in the ssdm config file.    QTgraphicaleffects is installed 

I log in and hyprland works perfect with the exception of the wallpaper ....  The wallpaper loads without color and is distorted,  EVRYTHING else shows perfect.   attached is a screen shot:

![swappy-20240329-124651](https://github.com/end-4/dots-hyprland/assets/30500110/1ab3f6b6-4c39-4ccb-b221-922af70499dd)

```

</details>

**Comment by end-4** [comment]
> On boot it drops back to the default log in manager and gives an error that it couldn't load ssdm because it didn't see "qtgraphicaleffects" as called for in the ssdm config file. QTgraphicaleffects is installed

~~idk, sddm sucks~~

> I log in and hyprland works perfect with the exception of the wallpaper .... The wallpaper loads without color and is distorted, EVRYTHING else shows perfect. attached is a screen shot:

pls update the config and swww. I fixed this problem in #362

---

...after typing all that i noticed the unfamiliar bar. are you sure you're using my dotfiles lol

**Comment by coacharnold1** [comment]
OMG ,,,, I'm so sorry ... i'm on Jakoolit's dot files ....   closing this ...   thank you ... my fault !

**Comment by end-4** [comment]
then tell them to use `swww-daemon --format xrgb` instead of `swww init`
