### ISSUE TITLE
[Issue] Install fails on EndevourOS

### ISSUE THREAD

**Issue by NotAF0e** [end-4/dots-hyprland#375]
When I run the install command on gnome EndevourOS `bash <(curl -s "https://end-4.github.io/dots-hyprland-wiki/setup.sh")`

I get the following errors:

```
hyprland-git - exit status 8
gradience-git - exit status 8
hyprpicker-git - exit status 4
python-cssutils - exit status 4
```

I can manually install an older version of cssutils with `makepkg -sic` (#342) but the other packages simply do not build correctly. I have also attempted to use EndevourOS with no de but the same issue arises.

**Comment by aleandro6804** [comment]
When you run the installation script and it fails building some packages, you should see the yay/paru  error saying "i tried build this packages: ........ but it failed".
Try install all the packages in another terminal except for the hyprland-git, gradience-git, hyprpicker-git and python-cssutils (just to be sure you installed correctly all the other packages).

Then try fix those 4 packages individually and, in the installation script, press "ignore" when it asks you what to do with that  error.


To solve the problem of gradiance and hyprpicker try installing the normal version (not the git one) (i had the same problem some weeks ago and i solved it like this).

For the hyprland i suggest you to uninstall the current version and install the git one manually.

I know it may be confusing so ask me if it is not completely clear.

**Comment by NotAF0e** [comment]
Ok thanks @aleandro6804 and yes @clsty I have. I have checked and all other packages have installed just fine. I have installed gradience and hyprpicker with your method but hyprland-git is still failing. Can I just install the stable hyprland package instead? I am getting `error making: hyprland-git-exit status 8`

**Comment by end-4** [comment]
> Can I just install the stable hyprland package instead

likely yes, just try it

**Comment by NotAF0e** [comment]
@end-4 can you somehow force css utils to only install [this version](https://aur.archlinux.org/cgit/aur.git/commit/?h=python-cssutils&id=36dd7dbaffaf2b628db44be920f1a4f8c656d2f8) as the newer versions are broken

**Comment by NotAF0e** [comment]
@end-4 ok I will try it

**Comment by end-4** [comment]
> @end-4 can you somehow force css utils to only install [this version](https://aur.archlinux.org/cgit/aur.git/commit/?h=python-cssutils&id=36dd7dbaffaf2b628db44be920f1a4f8c656d2f8) as the newer versions are broken

idk, maybe chaotic aur

**Comment by NotAF0e** [comment]
Ok everything is done, install script too. I have entered the tty to run `Hyprland` to run it but it just puts me back to the tty login screen.

**Comment by NotAF0e** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/75176016/fa03217c-b4a3-409c-af18-a49daf117206)
This is my crash log, sorry that it is not in plaintext, cant copy from tty to my local pc

**Comment by NotAF0e** [comment]
This might actually be an issue because of the VM I will try again with different settings

**Comment by aleandro6804** [comment]
Have you tried launching the Hyprland command not in the tty but in the console?

**Comment by NotAF0e** [comment]
I will

**Comment by NotAF0e** [comment]
Ah man I might have to reformat my linux drive for the 1 millionth time lol. Ok I will repeat all of this on a fresh EndevourOS gnome setup

**Comment by NotAF0e** [comment]
Ok I have got it working. So the solution would be to change the install script so that only working CSS utils is installed and not using git versions of gradience and hyprpicker

**Comment by NotAF0e** [comment]
Maybe not, Firefox does not open

**Comment by clsty** [comment]
A tip: now you can specify another dependency list file.

Run `./install.sh -h` to see usage.

**Comment by end-4** [comment]
> Maybe not, Firefox does not open (as well as most apps)

this happens if you've logged in something else before hyprland. a reboot will help

**Comment by NotAF0e** [comment]
Sorry I don't understand, why would I need the dependency list file? Would this be to fix the gradience and hyprpicker problems?

**Comment by clsty** [comment]
> Sorry I don't understand, why would I need the dependency list file? Would this be to fix the gradience and hyprpicker problems?

You may need it if you want another package to install as alternative to the original one.
Though only use it when you really sure.

**Comment by NotAF0e** [comment]
I have rebooted but it does not automatically boot into Hyprland instead into gnome

**Comment by aleandro6804** [comment]
Do you mean that you can't see the entry in the greeter?

**Comment by NotAF0e** [comment]
@aleandro6804 yes on the gnome login screen there was no cog to let me choose Hyprland

**Comment by aleandro6804** [comment]
Probably you don't have hyprland.desktop in your entries

Add a file called hyprland.desktop in your /usr/share/wayland-sessions and put this inside:
```
[Desktop Entry]
Name=Hyprland
Comment=An intelligent dynamic tiling Wayland compositor
Exec=Hyprland
Type=Application
``` 

(i'm using SDDM but it should work also in GDM)

**Comment by NotAF0e** [comment]
That file already existed

**Comment by aleandro6804** [comment]
Have you tried with SDDM?

**Comment by NotAF0e** [comment]
No, whats the least destructive way of installing it? Or what about [ly](https://github.com/fairyglade/ly) something minimal is better in my opinion. I find SDDM ugly. But I can still try to see if it works

**Comment by aleandro6804** [comment]
If you have systemd, you just need to install it from the official repository and then:

sudo systemctl disable gdm

sudo systemctl enable sddm

**Comment by NotAF0e** [comment]
Thanks a lot

**Comment by end-4** [comment]
> yes on the gnome login screen there was no cog to let me choose Hyprland

and you say the desktop entry already existed, which suggests you're using nvidia. there's this fix in arch wiki in case you wanna go back to gdm (you probably will) https://wiki.archlinux.org/title/GDM#Wayland_and_the_proprietary_NVIDIA_driver

**Comment by NotAF0e** [comment]
Lol ok thanks. I feel like this issue highlights that the install script is not really great for new users. If I knew how to write one I would do a pull request. An example of an install script I've had a good experience is with the one from hyprdots. It does literally everything for you so when the script is done you are at the greeter with everyone ready

**Comment by end-4** [comment]
> It does literally everything for you so

I dislike install scripts that do too much. From hyprdots readme:

> The script modifies your grub config to enable Nvidia drm and theme

Subjective, but I think this is off-limit. I'd rather not have my system touched by a dotfiles script. What if I don't want to enable Nvidia?

**Comment by aleandro6804** [comment]
Maybe it could be useful to ask during the installation if the user wants to automatically enable this feature or if he wants to install the normal version or the git one of the package

**Comment by NotAF0e** [comment]
@aleandro6804 yeah i agree giving the user choice over how automated the install is would be great. Or maybe having it detect if there may be issues in the install for example for Nvidia users (Nvidia f you 🖕)

**Comment by NotAF0e** [comment]
@end-4 yeah I see your perspective

**Comment by clsty** [comment]
I agree with @end-4 that the script should not do too much on system-level things.

Though, we already have some issues/discussions complaining about that they don't know how to launch Hyprland.
One of them even tried to run Hyprland **inside** kde by directly run `Hyprland` in terminal emulator.

As the maintainer on the install script, I'm open to the idea that we could provide an option to automate the process. I may work on it some days later.
(I still won't touch nvidia things. Though we can add it to the Wiki.)

**Comment by NotAF0e** [comment]
Wonderful, thank you all
