### ISSUE TITLE
[Issue]AGS not working after DOTFILES update

### ISSUE THREAD

**Issue by Kalidude69** [end-4/dots-hyprland#376]
**Ags fails to start because there is no file named wifinetworks.js**

**Error Message:**
(com.github.Aylur.ags:6786): Gjs-WARNING **: 19:46:46.090: JS ERROR: ImportError: Unable to load file from: file:///home/deb/.config/ags/modules/sideright/centermodules/wifinetworks.js (Error opening file /home/deb/.config/ags/modules/sideright/centermodules/wifinetworks.js: No such file or directory)
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Explanation:**

The error message indicates that the program encountered an issue while trying to import the file `wifinetworks.js`. This file is located in the path `/home/deb/.config/ags/modules/sideright/centermodules/wifinetworks.js`. However, the program is unable to find the file, likely because it doesn't exist or the path is incorrect.

**Possible Causes:**

* The `wifinetworks.js` file is  missing from the expected location.

**Unfortunately:**

* I didn't have a backup of the previous ags config to resolve this issue...which has led to me not able to use my system with ags .

* even tried killing ags then restarting it again but problem doesn't seem to be fixed due to the file not there.

I hope this formatted error log aids the developer in resolving the issue effectively.

**Comment by end-4** [comment]
oops

**Comment by end-4** [comment]
i forgot to push that file
now try again

**Comment by Kalidude69** [comment]
> i forgot to push that file now try again

yes works now issue is solved ✅
