### ISSUE TITLE
[Issue]Hyprland color generation bug and AGS critical error on css.

### ISSUE THREAD

**Issue by Kalidude69** [end-4/dots-hyprland#378]
# Issue Report: AGS, CSS, and Color Generation Bugs

## Description
AGS (specific feature) isn't functioning properly, while the CSS is giving critical errors and causing the application to bug out. Additionally, the color generation feature isn't working as intended.

## Bug Error Messages
- AGS: [Error message]
- (com.github.Aylur.ags:20556): Gjs-Console-CRITICAL **: 22:02:50.054: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/deb/.cache/ags/user/generated/style.css
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class

- HYPRLAND: [Error message]
- config error in file ~/.config/hypr/hyprland/colors.conf at line 9: rgba() expects length of 8 characters (4bytes) or 4 comma separated values
- Color Generation: [Error message]
- no error message but color from the wallpaper doesn't apply on gtk theme.

## Everything is up to date dotfiles had been updated and installed locally yesterday.
![image_2024-04-01_22-09-43](https://github.com/end-4/dots-hyprland/assets/112244509/38b54e87-6372-43a4-bc27-49099ce72618)

Thanks for your attention to this matter!

**Comment by D3ja-vu** [comment]
is this a gif ?

**Comment by Kalidude69** [comment]
> is this a gif ?

no its a png not only with this wallpaper every other wallpaper gives the same error.... be it jpeg png ......

**Comment by Lormars** [comment]
same here. Switch to dark mode would cause this error.

**Comment by Kalidude69** [comment]
> same here. Switch to dark mode would cause this error.

yes in any mode im facing the same issue currently for keeping it working i run the install script again to fix it but I cannot change wallpapers nor the gtk theme applies :(

**Comment by end-4** [comment]
> (com.github.Aylur.ags:20556): Gjs-Console-CRITICAL **: 22:02:50.054: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/deb/.cache/ags/user/generated/style.css
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class

then send that file

**Comment by end-4** [comment]
i'm guessing color generation didn't work
can you run `~/.config/ags/scripts/color_generation/switchwall.sh` in a terminal, proceed to pick a wallpaper normally then see if it logs something?

**Comment by Kalidude69** [comment]
> > (com.github.Aylur.ags:20556): Gjs-Console-CRITICAL **: 22:02:50.054: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/deb/.cache/ags/user/generated/style.css
> > Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class
> 
> then send that file

/* Error: Undefined variable.
 *    ,
 * 10 | @if $darkmode == True {
 *    |     ^^^^^^^^^
 *    '
 *   scss/_colors.scss 10:5  @import
 *   scss/main.scss 9:9      root stylesheet */

body::before {
  font-family: "Source Code Pro", "SF Mono", Monaco, Inconsolata, "Fira Mono",
      "Droid Sans Mono", monospace, monospace;
  white-space: pre;
  display: block;
  padding: 1em;
  margin-bottom: 1em;
  border-bottom: 2px solid black;
  content: "Error: Undefined variable.\a    \2577 \a 10 \2502  @if $darkmode == True {\a    \2502      ^^^^^^^^^\a    \2575 \a   scss/_colors.scss 10:5  @import\a   scss/main.scss 9:9      root stylesheet";
}

**Comment by end-4** [comment]
looks to me you modified the styles. did it work before you did that?
also see if `~/.config/ags/scss/_material.scss` contains `$darkmode`

**Comment by Kalidude69** [comment]
> looks to me you modified the styles. did it work before you did that? also see if `~/.config/ags/scss/_material.scss` contains `$darkmode`

i didn't touch any file from .config dir

**Comment by Kalidude69** [comment]
> umm material.scss is empty ...

**Comment by end-4** [comment]
which means the color generation failed. that's why i told you to
> run ~/.config/ags/scripts/color_generation/switchwall.sh in a terminal, proceed to pick a wallpaper normally then see if it logs something?

do i have to explicitly tell you to send it?
in case you don't know whether or not to, yes, send it

**Comment by end-4** [comment]
and just in case, i mean send logs and not the script

**Comment by Kalidude69** [comment]
> which means the color generation failed. that's why i told you to
> 
> > run ~/.config/ags/scripts/color_generation/switchwall.sh in a terminal, proceed to pick a wallpaper normally then see if it logs something?
> 
> do i have to explicitly tell you to send it? in case you don't know whether or not to, yes, send it

oops sorry for that im sending it right now ....

   ~/.config/ags/scripts/color_generation/switchwall.sh

(yad:57777): Gtk-WARNING **: 20:43:29.052: Theme parsing error: gtk.css:95:30: '' is not a valid color name

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:95:44: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:96:46: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:97:41: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:98:47: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:99:49: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:100:44: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:105:41: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:106:43: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:107:47: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:108:49: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:109:42: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:110:44: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:112:60: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:113:62: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:116:45: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:117:55: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:119:55: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:120:57: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:121:56: Expected a valid selector

(yad:57777): Gtk-WARNING **: 20:43:29.053: Theme parsing error: gtk.css:122:58: Expected a valid selector
Traceback (most recent call last):
  File "/home/deb/.config/ags/scripts/color_generation/generate_colors_material.py", line 5, in <module>
    from materialyoucolor.quantize import QuantizeCelebi
ImportError: cannot import name 'QuantizeCelebi' from 'materialyoucolor.quantize' (unknown location)
Error: Undefined variable.
   ╷
10 │ @if $darkmode == True {
   │     ^^^^^^^^^
   ╵
  scss/_colors.scss 10:5  @import
  scss/main.scss 9:9      root stylesheet

**Comment by end-4** [comment]
`yay -S python-materialyoucolor-git`

**Comment by Kalidude69** [comment]
> `yay -S python-materialyoucolor-git`

yes its installed ..... now what should I do

**Comment by clsty** [comment]
You should see if the problems still exists.

**Comment by Kalidude69** [comment]
> > `yay -S python-materialyoucolor-git`
> 
> yes its installed ..... now what should I do
**thanks issue is fixed now**
