### ISSUE TITLE
Missing permissions for uinput device

### ISSUE THREAD

**Issue by Cu3PO42** [end-4/dots-hyprland#382]
I have read the wiki and in particular the usage and troubleshooting page. I am running a recent NixOS Unstable.

---
## The issue

When starting AGS with your config installed, the following error is logged:

```(com.github.Aylur.ags:3863): Gjs-WARNING **: 22:42:44.614: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:

_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

failed to open uinput device: Permission denied
```

My user is in the `input` and `video` group, but the above error still occurs. Clearly there is some permission problem here. Unfortunately, I was not able to pinpoint where in the configuration the offending promise is created. Since there is no callstack at all, I assume it is at the top-level in some file, but I don't know where exactly. I'm hoping you might point me in that direction.

Once I know what exactly is failing, I'm happy to debug the permission problem myself and potentially contribute a fix or more detailed error message.

**Comment by end-4** [comment]
beightness control stuff probably
are you sure it isn't a nix moment?

**Comment by end-4** [comment]
my groups, if it matters:
```
$ groups
sys network plugdev rfkill users video storage lp input audio wheel end
```

**Comment by Cu3PO42** [comment]
Thank you for the reply! I'm relatively certain this isn't related to Nix, but more the general configuration of my system. This is after I have patched any file paths that aren't writable.

I don't believe brightnessctl has given me trouble in the past, but I'll make sure the error message isn't coming from it. Since uinput is specifically mentioned, I'm more inclined to believe it's related to the on-screen keyboard or any special gesture handling or something along those lines. I just didn't find any OSK code that I thought wouldn't have a callstack. Maybe it's coming from ydotool... I'll check that tonight.

**Comment by Cu3PO42** [comment]
As far as I can tell right now, this is most likely a udev issue and chances are high it's related to ydotool. I'll confirm this later and hopefully add a check and better error message.

**Comment by Cu3PO42** [comment]
Sorry this took a while. I unfortunately got sick. The error message is indeed coming from `ydotoold`, because the udev rule that is supposed to give my user access to `/dev/uinput` wasn't/isn't working. However, rather than give all applications running as my user permissions to write to `/dev/uinput`, I'd rather run `ydotool` as a service. It ships with a systemd service that should "just work". Is this something you would be open to?

**Comment by end-4** [comment]
arch package doesn't include the service?

**Comment by end-4** [comment]
I guess this means we'll have to add yet another manual install func in the install script that gets the service file from [ydotool repo](https://github.com/ReimuNotMoe/ydotool/blob/master/Daemon/ydotoold.service.in)

**Comment by Cu3PO42** [comment]
> arch package doesn't include the service?

Hmm. I just checked this and it seems the Arch package includes a user service only. That is, it can be run by systemd, but in the context of the user, which still means giving them `/dev/uinput` permissions. This doesn't really influence my use case one way or the other.

That said, it might be the "cleaner" solution to run it as the user service anyway. Maybe there could just be a config option to start ydotoold automatically (as it currently is) or to not do that and assume it will be spawned by a service. That way the config will continue working as is for everyone and people who want to run `ydotoold` differently can.

**Comment by end-4** [comment]
ydotool should now run as a user service

**Comment by Cu3PO42** [comment]
Lovely! Thanks so much! This makes it significantly easier to fix my use case on my system.
