### ISSUE TITLE
[Issue] Second monitor flickering

### ISSUE THREAD

**Issue by Architect0rr** [end-4/dots-hyprland#383]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Archlinux
---
## The issue
On clear, just installed Hyprland there were no issues. After I installed these dotfiles, the second monitor started flickering.
Sometimes, the image on it is half-heighted in the bottom half of the monitor. Image appears for 0.5 seconds, then disappears for 1–2 seconds. If I don't move the mouse, the image stays on screen, but if I drag the mouse, image disappears.
`~/.config/hypr/hyprland/general.conf:`
```
monitor=eDP-1,    3200x2000@120,   0x0, 1.6
monitor=HDMI-A-1, 1920x1080@74.97, 2000x0, 1
```
Second monitor is `HDMI-A-1`

<details>
<summary>`hyprctl monitors`</summary>

```plain
[kein@aleaf hyprland]$ hyprctl monitors
Monitor eDP-1 (ID 0):
	3200x2000@120.00000 at 0x0
	description: Thermotrex Corporation TL156MDMP31-0
	make: Thermotrex Corporation
	model: TL156MDMP31-0
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 40 0 0
	scale: 1.60
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 1
	activelyTearing: false
	currentFormat: XRGB8888
	availableModes: 3200x2000@120.00Hz 3200x2000@48.00Hz 3200x2000@96.00Hz 3200x2000@72.00Hz 3200x2000@60.00Hz 3200x2000@60.00Hz 3200x2000@50.00Hz 3200x2000@48.00Hz 1920x1200@120.00Hz 1920x1080@120.00Hz 1600x1200@120.00Hz 1680x1050@120.00Hz 1280x1024@120.00Hz 1440x900@120.00Hz 1280x800@120.00Hz 1280x720@120.00Hz 1024x768@120.00Hz 800x600@120.00Hz 640x480@120.00Hz

Monitor HDMI-A-1 (ID 1):
	1920x1080@74.97300 at 2000x0
	description: Acer Technologies SA240Y 0x0480DAE1
	make: Acer Technologies
	model: SA240Y
	serial: 0x0480DAE1
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 1
	activelyTearing: false
	currentFormat: XRGB8888
	availableModes: 1920x1080@74.97Hz 1920x1080@72.01Hz 1920x1080@60.01Hz 1920x1080@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.03Hz 1920x1080@50.00Hz 1920x1080@48.02Hz 1680x1050@59.88Hz 1280x1024@60.02Hz 1440x900@59.90Hz 1280x800@59.91Hz 1152x864@75.00Hz 1280x720@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@60.32Hz 800x600@56.25Hz 720x576@50.00Hz 720x576@50.00Hz 720x480@60.00Hz 720x480@60.00Hz 720x480@59.94Hz 720x480@59.94Hz 720x480@59.94Hz 640x480@66.67Hz 640x480@60.00Hz 640x480@59.94Hz 640x480@59.94Hz 720x400@70.08Hz
```

</details>

**Comment by clsty** [comment]
1. It's recommended to put your custom config in `~/.config/hypr/custom/general.conf`.

2. According to [Hyprland Wiki](https://wiki.hyprland.org/Configuring/Monitors/):
> The position is calculated with the scaled (and transformed) resolution, meaning if you want your 4K monitor with scale 2 to the left of your 1080p one, you’d use the position 1920x0 for the second screen. (3840 / 2) If the monitor is also rotated 90 degrees (vertical), you’d use 1080x0.

So your config should be
```conf
monitor=eDP-1,    3200x2000@120,   0x0, 1.6
monitor=HDMI-A-1, 1920x1080@74.97, 1250x0, 1
```
Where `1250` is the result of `2000/1.6`.

**Comment by Architect0rr** [comment]
1. Of course.
2. It was needed to disable `vrr`, so...
