### ISSUE TITLE
get-icon.py and missing dependencies

### ISSUE THREAD

**Issue by MaulanaMalikS** [end-4/dots-hyprland#39]
Hello!

I'm using the `novelknock` branch. The script below executes the `get-icon.py` script, but it seems that the `get-icon.py` script doesn't exist.
https://github.com/end-4/dots-hyprland/blob/07a664a3de60228c5397b62b858fbb5961789771/.config/eww/scripts/appicons#L26

According to PR #15, `get-icon.py` should be replaced by the `geticons` script, right?

Also, I think you are missing `gnome-keyring` and `polkit-gnome` in the dependencies.
https://github.com/end-4/dots-hyprland/blob/07a664a3de60228c5397b62b858fbb5961789771/.config/hypr/execs.conf#L17C1-L18C72

**Comment by end-4** [comment]
- aaaaaand the appicons script isn't even used lol
- keyring and polkit: alright, i'll make a separate section of the readme for those kinda "core" dependencies

**Comment by MaulanaMalikS** [comment]
> * aaaaaand the appicons script isn't even used lol

so this line in the script unused?
https://github.com/end-4/dots-hyprland/blob/07a664a3de60228c5397b62b858fbb5961789771/.config/eww/variables.yuck#L111

**Comment by end-4** [comment]
yeah unused
it's just declared there 
just comment that line out and you'll see that the setup runs fine without any errors

**Comment by end-4** [comment]
i do have a lot of scripts
ive done cleanups but havent managed to remove every unnecessary thing

**Comment by MaulanaMalikS** [comment]
Alright, thanks!
I'm sorry for bothering you.

**Comment by end-4** [comment]
no problem
glad you reported that
