### ISSUE TITLE
[Feature] Install packages via system PM's if possible

### ISSUE THREAD

**Issue by Architect0rr** [end-4/dots-hyprland#390]
**What would you like to be added?**

All packages are installed using system PM's, if possible.

**How will it help**

Easier system maintaining, cleaning. No need to write self-written non-tested uninstalling scripts.

**Extra info**

**Comment by clsty** [comment]
Basiacally, it means that we need to write PKGBUILD for AGS, Rubik, Gabarito, OneUI, bibata, microtex to replace the `scriptdata/installers`.

That's a good idea but I don't know how to do that (nor do I'm interested to).

PR is welcomed.

**Comment by Architect0rr** [comment]
Just those packages from AUR, whose upstream URL matches those used in installers

[AGS](https://aur.archlinux.org/packages/aylurs-gtk-shell), [AGS-git](https://aur.archlinux.org/packages/aylurs-gtk-shell-git)

[OTF-Rubik](https://aur.archlinux.org/packages/otf-rubik), [TTF-Rubik-VF](https://aur.archlinux.org/packages/ttf-rubik-vf)

[Bibata-cursor-theme](https://aur.archlinux.org/packages/bibata-cursor-theme), [Bibata-cursor-theme-bin](https://aur.archlinux.org/packages/bibata-cursor-theme-bin) (there are also another packages from ful1e5)

[MicroTeX](https://aur.archlinux.org/packages/microtex-git)

-----------------------------

I'll try to add in installers a check if these packages are available, in this case then install they from repos

**Comment by clsty** [comment]
Nope we knew about those packages but they does not meet our standards.

E.g. We do version controlling for AGS as it's under active developing and always has breaking changes.

For other packages, one of them needs connection to Google which is banned for some regions e.g. China.
Also some of them involve unneccessary files for this repo and is too big.

In conclusion, thanks for those packages but we're not using them.
New PKGBUILDs should be written for this issue.
