### ISSUE TITLE
[Issue] Enter to send in APIs and Tools section

### ISSUE THREAD

**Issue by kshitijaucharmal** [end-4/dots-hyprland#395]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro:  
```
LSB Version:    n/a
Distributor ID: Garuda
Description:    Garuda Linux
Release:        Soaring
Codename:       Spizaetus
```

---
## The issue

I just wan't to know if there is any way to press enter to to confirm/send the prompt in the chatgpt/gemini window. Right now I need to press the button next to the prompt, and being a keyboard only guy, is pretty tedious. I know its a noob question but please let me know if theres an option I can change, as I haven't used AGS ever

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

**Comment by clsty** [comment]
> Right now I need to press the button next to the prompt, and being a keyboard only guy, is pretty tedious.

Just press Shift+Enter (or Alt+Enter? Ctrl+Enter? if I remember it wrong)

**Comment by kshitijaucharmal** [comment]
None of these work, sry I failed to mention that

**Comment by end-4** [comment]
Shift+Enter for a newline (intended, but in reality actually any modkey + Enter)
Enter to send

If you can't press Enter to send, try updating Hyprland

**Comment by kshitijaucharmal** [comment]
I'm on Garuda, and hyprland is fully updated already. Can it be due to me adding a keybind for my terminal to Super Enter?

**Comment by end-4** [comment]
> Can it be due to me adding a keybind for my terminal to Super Enter?

nope

> hyprland is fully updated already

Are you using the `-git` package? If yes,I'm not sure. In that case, for now, you can hit Tab (which should switch focus from text area to the Send button) then hit Enter

**Comment by kshitijaucharmal** [comment]
That's what I was doing 😁
