### ISSUE TITLE
[Feature] Transparency Issue Requires `ignore_opacity = on` in Decorations -> Blur

### ISSUE THREAD

**Issue by Alexandos** [end-4/dots-hyprland#398]
Description:
Transparency effects are not working as expected without explicitly setting `ignore_opacity = on` in the `decorations -> blur` section of the configuration. This setting is crucial for enabling transparency effects to function correctly.
Steps to Reproduce:
1. Configure the `decorations -> blur` section in the configuration file.
2. Attempt to apply transparency effects without setting `ignore_opacity = on`.
3. Observe that the transparency effects do not work as expected.

Expected Result:
Transparency effects should work as expected when `ignore_opacity = on` is set in the `decorations -> blur` section.
Actual Result:
Transparency effects do not work without setting `ignore_opacity = on` 🥸.
Proposed Solution:
Add the following line to the `decorations -> blur` section of the configuration file:
```
ignore_opacity = on
```
This change will ensure that transparency effects are enabled and function correctly, saving time for other developers who may encounter the same issue.

**Comment by end-4** [comment]
I prefer not using transparency for apps at all
You can add that option to `~/.config/hypr/custom/general.conf` if you wish

**Comment by Alexandos** [comment]
Yes, but in the .config/hypr/hyprland/general.conf file, there are lines:
```
blur {
    enabled = true
    xray = true
    special = false
    new_optimizations = true
    size = 7
    passes = 4
    brightness = 1
    noise = 0.01
    contrast = 1
    popups = true
    popups_ignorealpha = 0.6
}
```
Why not add `ignore_opacity = on` there? If these lines are not working at all, it would be a waste of time for people who wanted to configure transparency to figure out why nothing is working.

**Comment by end-4** [comment]
While I don't have an in-depth understanding of how Hyprland renders blur, that option to the end user seems to make Hyprland render blur behind every window, even if unnecessary, which affects performance.

> If these lines are not working at all, it would be a waste of time for people who wanted to configure transparency to figure out why nothing is working

This is *my* dotfiles, and by design *I* don't need app blur. If someone wants to configure this, they are free to check the Hyprland wiki. I can add a comment there, but I do not want to change this option. I hope you understand.
