### ISSUE TITLE
all in one install command?

### ISSUE THREAD

**Issue by XxnittanixX** [end-4/dots-hyprland#4]
all in one install command? 
so that i can comeback and see this

**Comment by end-4** [comment]
- From the notice in main branch: "There are no plans to make an install script, as it basically helps newbies to f*ck up their system and makes things harder to troubleshoot when they ask for help. Please take care, and copy things manually."

- However I might consider making a script that allows the user to choose which components to install. I'll try to create that later today

**Comment by end-4** [comment]
https://github.com/end-4/dots-hyprland/commit/9c29279da26a890d58f4fe06e35fcad30883e30b

for now it will install basic stuff

**Comment by end-4** [comment]
added installation of some fonts and icons

idk how much stuff i should install

what do you think?

**Comment by XxnittanixX** [comment]
Yea same here

**Comment by XxnittanixX** [comment]
U should  just  upload this the aur a desktop enviorment

**Comment by end-4** [comment]
It's not something very stable and it's not a proper software so I won't do that.
However an arch-based pentesting distro called [AthenaOS](https://github.com/Athena-OS/athena-iso) offers this rice on their repos.

**Comment by end-4** [comment]
since you guys dont have any further suggestions and started suggesting other stuff, i'll close this issue
shouldve done this long ago lol
