### ISSUE TITLE
Music buttons with uncorrect icons

### ISSUE THREAD

**Issue by SpendIce** [end-4/dots-hyprland#40]
I believe the icons for the play, previous and next buttons on music controls have incorrect icons (I installed the fonts as seen in  #26 I don't know if it was those or what)
![image](https://github.com/end-4/dots-hyprland/assets/62260972/52002ec6-5a3a-43f0-8400-dd13dce13a46)
I also seem to have an issue where eww either reloads or something when I turn on scroll accesibility, after a minute I can see the top bar slide to the side and reappear and then scroll accesibility is turned off.

**Comment by nekonya3031** [comment]
I have same issue too, as result of my research it is really incorrect icons (I am using nerdsfont as system default) and fix it using changes in eww config source code.

**Comment by end-4** [comment]
it uses Segoe Fluent Icons
which i copied from windows 11

but you can also get it here: https://learn.microsoft.com/en-us/windows/apps/design/downloads/#fonts
awkwardly, ive just read the eula, which says "You may use the Segoe and icon fonts, or glyphs included in this file (“Software”) solely to design, develop and test your programs that run on a Microsoft Platform"

basically this is illegal lol

**Comment by end-4** [comment]
i'll replace with material design ones

**Comment by end-4** [comment]
see if that commit fixed it

**Comment by SpendIce** [comment]
Yep, fixed, thanks
