### ISSUE TITLE
New terminal colours doesnt apply correctly on Monochrome [Issue]

### ISSUE THREAD

**Issue by D3ja-vu** [end-4/dots-hyprland#406]
https://github.com/end-4/dots-hyprland/assets/164979079/1efc99f3-e70d-4f8d-b6e0-2fed25a293b5

**Comment by midn8hustlr** [comment]
Currently, the new terminal colors are generated by blending the hue of all the colors in source colorscheme (default gruvbox) with the material accent color.
For monochrome theme, the accent color can have any random hue, while chrome or tone is at the extreme end.
So it generates any random colors for the scheme.
For this specific case, we can turn off harmonization and override with a hardcoded monochrome colorscheme.
However I would love to have a black/white colorscheme which can differentiate all 8 terminal colors (with shades of gray).
Right now I can't find any such colorsheme in the internet, so we might have to create our own.

If you have any suggestion for monochrome colorsheme (8 terminal color hex values), you can suggest. Or, I will implement this based on my own personal preference.

**Comment by midn8hustlr** [comment]
Btw what fetch are you using for the pokemons? I like it. 
And can you share your hyprland animations, its smooth :)

**Comment by end-4** [comment]
There's this vscode theme called Bianco Nero that's monochrome ish
it looks like this
![image](https://github.com/end-4/dots-hyprland/assets/97237370/397fcf53-2de7-4487-88a4-dba6137a493d)

**Comment by midn8hustlr** [comment]
lgtm
end-4, Can you add this to override the term colors only for monochrome in the python script?

**Comment by D3ja-vu** [comment]
actually i love tinkering all stuff and exploring this awesome dotfiles even though i dont know how to code nor J.S or python but i try planning to learn them in the near future 

i use pokemon-colorscript by excuting this command with fish
 `pokemon-colorscripts --no-title -r 1,3,6`

**Comment by D3ja-vu** [comment]
this is my animation config i edited it today and the ags walker animation overveiw ,....etc 
this is the in video one `animations {
    # Flick0's animations
    first_launch_animation =true
    enabled=1
    bezier=overshot,0.13,0.99,0.29,1.10
    animation=windows,1,5,overshot,slide
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,4,default,slide
    first_launch_animation = true
}`

**Comment by end-4** [comment]
done

**Comment by midn8hustlr** [comment]
> actually i love tinkering all stuff and exploring this awesome dotfiles even though i dont know how to code nor J.S or python but i am planning to learn them in the near future
> 

Same, i also don't code in JS. But these configurations are are nicely written, which makes even beginners like me to follow easily. Also, thanks to LLMs, now its the best time to be a learner :)

We are all in a part of same journey, just starting at different points. We can learn together!

Also thanks for your configs ^_^

**Comment by D3ja-vu** [comment]
all love bro

**Comment by D3ja-vu** [comment]
so i updated and edited the configs  myself and reinstalled the whole thing but it still gives me this colors

https://github.com/end-4/dots-hyprland/assets/164979079/f4ae45ee-27bf-492a-bb2f-87584fa38779

**Comment by midn8hustlr** [comment]
Yes, I see
You can fix this by changing the file `~/.config/ags/scripts/templates/terminal/scheme-monochrome. json`
You can replace all the hex values with some black-white color like "#CFCFCF"

I guess its a mistake end-4?

**Comment by end-4** [comment]
it wasn't a mistake
bianconero is like that
i'm lazy to invent a real monochrome scheme

**Comment by D3ja-vu** [comment]
![screenshot-20240419-081611](https://github.com/end-4/dots-hyprland/assets/164979079/a34bf502-8282-421f-9806-38e6546490c8)

**Comment by D3ja-vu** [comment]
{
  "dark": {
    "term0": "#BBBBBB",
    "term1": "#FFFFFF",
    "term2": "#CCCCCC",
    "term3": "#555555",
    "term4": "#FFFFFF",
    "term5": "#111111",
    "term6": "#CCCCCC",
    "term7": "#FFFFFF",
    "term8": "#404040",
    "term9": "#CCCCCC",
    "term10": "#FFFFFF",
    "term11": "#909090",
    "term12": "#CCCCCC",
    "term13": "#808080",
    "term14": "#CCCCCC",
    "term15": "#FFFFFF"
  },
  "light": {
    "term0": "#CCCCCC",
    "term1": "#777777",
    "term2": "#FFFFFF",
    "term3": "#909090",
    "term4": "#CCCCCC",
    "term5": "#FFFFFF",
    "term6": "#FFFFFF",
    "term7": "#CCCCCC",
    "term8": "#FFFFFF",
    "term9": "#FFFFFF",
    "term10": "#CCCCCC",
    "term11": "#808080",
    "term12": "#CCCCCC",
    "term13": "#FFFFFF"
  }
}

**Comment by D3ja-vu** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/164979079/8f1be2ba-cb9f-40fa-996f-1c6bb2a7a5e6)

**Comment by midn8hustlr** [comment]
hey @D3ja-vu 
nice colorsheme
Can you do a PR for this?

**Comment by ZeyadMoustafaKamal** [comment]
Also I need to mention that I am not using the monochrome I am using tonal spot
