### ISSUE TITLE
top bar size 

### ISSUE THREAD

**Issue by coacharnold1** [end-4/dots-hyprland#41]
I have 2 laptops I'm trying to get this working on .  So far it's going very well,   I have a small netbook that is having issues displaying the top bar in a way that doesn't bleed over the top of the window below.  its a fairly small amount,  i just can't find the right setting in the config files to adjust the height of the bar correctly .  Can someone direct me to the right config variable?

**Comment by end-4** [comment]
edit `~/.config/hypr/hyprland.conf`
you have to change the line with "addreserved" (it's quite near the top)
see [this hyprland wiki section](http://wiki.hyprland.org/Configuring/Monitors/#custom-reserved-area) for more info

**Comment by coacharnold1** [comment]
Awesome thank you !!!!!!
