### ISSUE TITLE
How to change start commands in App Search results

### ISSUE THREAD

**Issue by Mooling0602** [end-4/dots-hyprland#416]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arch Linux

---
As title, I didn't find any related tips in the wiki. And I tried edit desktop files in ~/Desktop folder, but it's useless.

**Comment by end-4** [comment]
what is a start command

**Comment by clsty** [comment]
Apparently `~/Desktop` is not what you want.
Use `~/.local/share/applications/` instead.

See more:
https://wiki.archlinux.org/title/Desktop_entries
