### ISSUE TITLE
[Issue] Sessionscreen interface display is misaligned when enable HiDPI

### ISSUE THREAD

**Issue by Mooling0602** [end-4/dots-hyprland#417]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arch Linux

---
## Detail
When enable HiDPI, in config ~/.config/hypr/custom/env.conf
```
# You can put extra environment variables here
# https://wiki.hyprland.org/Configuring/Environment-variables/
monitor = eDP-1,highres,auto,1.6
...
```
The sessionscreen will be displayed like this: 
![image](https://github.com/end-4/dots-hyprland/assets/147964268/b63277b4-8ff7-4387-9539-57828945bd6f)
And if nothing changed, the sessionscreen will be normal: 
![image](https://github.com/end-4/dots-hyprland/assets/147964268/079a19a4-89f1-4a99-a4d6-42e41c66346e)
I don't know how to fix it, and I need help so I issue here.

**Comment by alok-debnath** [comment]
yes that happens with me too when I use higher scaling
![image](https://github.com/end-4/dots-hyprland/assets/67475527/d2e65f6a-2d45-4c84-87a6-21238e8e4cae)

**Comment by alok-debnath** [comment]
Btw, this can be fixed if we use this pull request #336 (mainly this file `.config/ags/variables.js`).
We just need to replace
```js
min-width: ${SCREEN_WIDTH}px;
min-height: ${SCREEN_HEIGHT}px;
```
with
```js
min-width: ${SCREEN_REAL_WIDTH}px;
min-height: ${SCREEN_REAL_HEIGHT}px;
```
after importing those 2 variables from the mentioned file.
@end-4 Is there any plans for merging that PR, not sure how it will behave on a multi monitor setup but it is working fine on my laptop

**Comment by Mooling0602** [comment]
Sorry I forgot I should import this PR first.

**Comment by Ate329** [comment]
Substitute SCREEN_WIDTH and SCREEN_HEIGHT in /.config/ags/variables.js with these two lines can solve the issue and that's how my problem was solved.
```
export const SCREEN_WIDTH = Number(exec(`bash -c "hyprctl monitors -j | gojq '.[].width / .[].scale' | awk '{print int($1+0.5)}'"`));
export const SCREEN_HEIGHT = Number(exec(`bash -c "hyprctl monitors -j | gojq '.[].height / .[].scale' | awk '{print int($1+0.5)}'"`));
```
See the this comment in the other issue for details: https://github.com/end-4/dots-hyprland/issues/424#issuecomment-2065543053

**Comment by end-4** [comment]
that fixed it for me when I adjust monitor scale
let me know if it fixed it for you

**Comment by Mooling0602** [comment]
> that fixed it for me when I adjust monitor scale let me know if it fixed it for you

My installation was broken because of wrong changes by myself, I'll test it later after reinstalling.

**Comment by Mooling0602** [comment]
> that fixed it for me when I adjust monitor scale let me know if it fixed it for you

Works fine on my Surface Pro.
