### ISSUE TITLE
Animation on sideleft and sideright

### ISSUE THREAD

**Issue by BlokCSS** [end-4/dots-hyprland#421]
Hello!

I was wondering how can i put animation on the leftside and rightside?
I was trying to do it but nothin works. I remember they had time ago animation like slide, but not anymore.
Please someone can help me to do it, ill appreciate it!

**Comment by D3ja-vu** [comment]
you can edit in windowrules.config 
and to specify custom layer animation read hyprland wiki

**Comment by end-4** [comment]
> I was wondering how can i put animation on the leftside and rightside?

Update Hyprland. The panels are animated by its layer animations

**Comment by BlokCSS** [comment]
ill update hyprland an try again, i know there was animations, but now they dont. Ill do and answer this. And yes i read the hyprland wiki and i didnt understand very well the windowrules.config

**Comment by BlokCSS** [comment]
i already updated hyprland and still the same, the slide animation isnt there
![image](https://github.com/end-4/dots-hyprland/assets/82058445/d329329f-dcc8-48e0-a6c8-351633b80c32)
 i never ever touch this config, so its the same as always.

**Comment by D3ja-vu** [comment]
comment noanim rules

**Comment by BlokCSS** [comment]
now works! thank you
