### ISSUE TITLE
[Issue] How do I change how round the corners of the screen is?

### ISSUE THREAD

**Issue by Ate329** [end-4/dots-hyprland#423]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: 

---
## The issue

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>
I went through the wiki but I didn't find this option maybe I was just blind.

**Comment by end-4** [comment]
line 308, `~/.config/ags/scss/_bar.scss`
which is in the `.corner-black` class and contains `@include large-rounding;` 

replace that with something like `border-radius: 69px;`

**Comment by Ate329** [comment]
Thank you! I have another issue is that after I had installed a package, I had to logout or reboot the system in order to be able to search it in the search bar when I press the super key.

**Comment by D3ja-vu** [comment]
> ~/.config/ags/scss/_bar.scss

you can reload ags by pressing ctrl+Super,r

**Comment by end-4** [comment]
after I had installed a package, I had to logout or reboot the system

known ags issue

**Comment by alr86** [comment]
Also available in ~/.config/ags/user_options.js

```javascript
const userConfigOptions = {
  "appearance": {
    "barRoundCorners": 0, // 0: No, 1: Yes
    "fakeScreenRounding": 0, // 0: None | 1: Always | 2: When not fullscreen
  },
}
```
