### ISSUE TITLE
svg files

### ISSUE THREAD

**Issue by MaulanaMalikS** [end-4/dots-hyprland#43]
Hello!

Is this script still being used?
https://github.com/end-4/dots-hyprland/blob/b24178eec5662961bf63654abc00517498d10e08/.config/eww/scripts/applycolor#L23C1-L29C1
I didn't find those .svg files in `.config/eww/images/svg.`

Thanks!

**Comment by end-4** [comment]
that's either the `main` or `hybrid` ranch right? then yes
lemme just check it real quick

**Comment by MaulanaMalikS** [comment]
> that's either the `main` or `hybrid` ranch right? then yes lemme just check it real quick

i'm sorry, but it's on `novelknock` branch

**Comment by end-4** [comment]
oh
it is used, but those icons arent necessary
will remove those lines, thanks
