### ISSUE TITLE
[Issue] [./install.sh]: Command "fc-cache -fv" has failed

### ISSUE THREAD

**Issue by orcbolg3612** [end-4/dots-hyprland#435]
[./install.sh]: Next command:
install-Rubik
[./install.sh]: Command "mkdir -p /home/keyhost505/.cache/dots-hyprland/cache/Rubik" finished.
[./install.sh]: Command "cd /home/keyhost505/.cache/dots-hyprland/cache/Rubik" finished.
Initialized empty Git repository in /home/keyhost505/.cache/dots-hyprland/cache/Rubik/.git/
remote: Enumerating objects: 25663, done.
remote: Counting objects: 100% (1507/1507), done.
remote: Compressing objects: 100% (614/614), done.
remote: Total 25663 (delta 888), reused 1481 (delta 883), pack-reused 24156
Receiving objects: 100% (25663/25663), 102.47 MiB | 3.57 MiB/s, done.
Resolving deltas: 100% (23844/23844), done.
From https://github.com/googlefonts/rubik
 * branch              main       -> FETCH_HEAD
 * [new branch]        main       -> origin/main
[./install.sh]: Command "git pull origin main" finished.
[./install.sh]: Command "sudo mkdir -p /usr/local/share/fonts/TTF/" finished.
[./install.sh]: Command "sudo cp fonts/variable/Rubik-Italic[wght].ttf fonts/variable/Rubik[wght].ttf /usr/local/share/fonts/TTF/" finished.
[./install.sh]: Command "sudo mkdir -p /usr/local/share/licenses/ttf-rubik/" finished.
[./install.sh]: Command "sudo cp OFL.txt /usr/local/share/licenses/ttf-rubik/LICENSE" finished.
Font directories:
	/home/keyhost505/.local/share/fonts
	/home/keyhost505/.local/share/flatpak/exports/share/fonts
	/var/lib/flatpak/exports/share/fonts
	/usr/local/share/fonts
	/usr/share/fonts
	/home/keyhost505/.fonts
	/usr/local/share/fonts/TTF
	/usr/share/fonts/TTF
	/usr/share/fonts/adobe-source-code-pro
	/usr/share/fonts/cantarell
	/usr/share/fonts/encodings
	/usr/share/fonts/gnu-free
	/usr/share/fonts/gsfonts
	/usr/share/fonts/noto
	/usr/share/fonts/ttf-material-symbols-variable
	/usr/share/fonts/ttf-readex-pro
	/usr/share/fonts/encodings/large
/home/keyhost505/.local/share/fonts: skipping, no such directory
/home/keyhost505/.local/share/flatpak/exports/share/fonts: skipping, no such directory
/var/lib/flatpak/exports/share/fonts: skipping, no such directory
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/local/share/fonts/TTF: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts: caching, new cache contents: 0 fonts, 9 dirs
/usr/share/fonts: failed to write cache
/usr/share/fonts/TTF: caching, new cache contents: 112 fonts, 0 dirs
/usr/share/fonts/adobe-source-code-pro: caching, new cache contents: 30 fonts, 0 dirs
/usr/share/fonts/cantarell: caching, new cache contents: 6 fonts, 0 dirs
/usr/share/fonts/encodings: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/encodings/large: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/gnu-free: caching, new cache contents: 12 fonts, 0 dirs
/usr/share/fonts/gsfonts: caching, new cache contents: 35 fonts, 0 dirs
/usr/share/fonts/noto: caching, new cache contents: 607 fonts, 0 dirs
/usr/share/fonts/ttf-material-symbols-variable: caching, new cache contents: 24 fonts, 0 dirs
/usr/share/fonts/ttf-readex-pro: caching, new cache contents: 6 fonts, 0 dirs
/home/keyhost505/.fonts: skipping, no such directory
/usr/local/share/fonts/TTF: skipping, looped directory detected
/usr/share/fonts/TTF: skipping, looped directory detected
/usr/share/fonts/adobe-source-code-pro: skipping, looped directory detected
/usr/share/fonts/cantarell: skipping, looped directory detected
/usr/share/fonts/encodings: skipping, looped directory detected
/usr/share/fonts/gnu-free: skipping, looped directory detected
/usr/share/fonts/gsfonts: skipping, looped directory detected
/usr/share/fonts/noto: skipping, looped directory detected
/usr/share/fonts/ttf-material-symbols-variable: skipping, looped directory detected
/usr/share/fonts/ttf-readex-pro: skipping, looped directory detected
/usr/share/fonts/encodings/large: skipping, looped directory detected
/var/cache/fontconfig: not cleaning unwritable cache directory
/home/keyhost505/.cache/fontconfig: cleaning cache directory
/home/keyhost505/.fontconfig: cleaning cache directory
fc-cache: failed
[./install.sh]: Command "fc-cache -fv" has failed.
You may need to resolve the problem manually BEFORE repeating this command.
  r = Repeat this command (DEFAULT)
  e = Exit now
  i = Ignore this error and continue (your setup might not work correctly)
 [R/e/i]: 

How to fix this bugs?

**Comment by orcbolg3612** [comment]
I am in arch fresh install before 20 minutes.

**Comment by end-4** [comment]
maybe delete `cache/rubik` (relative to repo path) (from another terminal or app) then repeat command

**Comment by orcbolg3612** [comment]
> maybe delete `cache/rubik` (relative to repo path) (from another terminal or app) then repeat command

How to delete cahe/rubik? I'm just run simple command from your readme, didn't git clone the repo.

**Comment by end-4** [comment]
the one line thing? if so the repo should be in `~/.cache/dots-hyprland`

**Comment by clsty** [comment]
We're now using `aur/ttf-rubik-vf` for Arch(based) distros so this issue is deprecated. Closing.
