### ISSUE TITLE
gtklock or swaylock

### ISSUE THREAD

**Issue by MaulanaMalikS** [end-4/dots-hyprland#44]
Hello!

I am using the `novelknock` branch.

In the dependencies section, `gtklock` is listed and being used in this script:
https://github.com/end-4/dots-hyprland/blob/7a1b4ef54a53568e1fc5cd20568d25c92812ba59/.config/eww/windows/dashboard.yuck#L573

But in this script, `swaylock` is being used:
https://github.com/end-4/dots-hyprland/blob/7a1b4ef54a53568e1fc5cd20568d25c92812ba59/.config/eww/windows/sideright.yuck#L186
https://github.com/end-4/dots-hyprland/blob/7a1b4ef54a53568e1fc5cd20568d25c92812ba59/.local/bin/lock.sh#L1

So which one is actually used? Or both?

If `swaylock` is being used, I think it should be listed in the dependencies section (`swaylock-effect`).

Thanks!

**Comment by end-4** [comment]
just gtklock
i didnt remove the lock script when i switched

**Comment by MaulanaMalikS** [comment]
thanks!
`lock.sh` is also used in this script:
https://github.com/end-4/dots-hyprland/blob/617dfa0b9a9caf51d7a8c15fe087eb0a02a6b2e3/.config/hypr/execs.conf#L20

**Comment by end-4** [comment]
a
