### ISSUE TITLE
No CJK font support?

### ISSUE THREAD

**Issue by kaine0x00** [end-4/dots-hyprland#440]
- Linux distro: 
Arch Linux
---
## CJK characters not displaying
I don't know if this is the expected behaviour, but CJK characters aren't being recognized by the default fonts on the dotfiles. For example, whenever i play J-Pop music, my widget will just show the character codes instead of the actual Japanese characters. This doesn't just happen on widgets, it's basically everywhere.

Am i missing a dependency or maybe the font didn't install propperly? I'm not too familiar with CJK character compatible fonts, but I'm now more interested than ever because I'm trying to learn Japanese.

**Comment by kaine0x00** [comment]
Okay I'm dumb, i was missing a dependency. You can download a cjk compatible font and it will automatically be used as fallback. Fixed on Arch with:
```bash
sudo pacman -S noto-fonts-cjk
```

**Comment by nonetrix** [comment]
cjk fonts should really be installed by default since the translation side panel assumes them kinda

**Comment by end-4** [comment]
> cjk fonts should really be installed by default since the translation side panel assumes them kinda

We would have to install so many other fonts for full language support, so I will leave that decision to the user

Non-weeb people not from those countries might not need it
