### ISSUE TITLE
Color Scheme fails to generate

### ISSUE THREAD

**Issue by ln64-git** [end-4/dots-hyprland#441]
EndeavourOS

Description:
AGS breaks while switching wallpaper or color scheme.

Problem:
This morning while switching color schemes my system failed to execute generate_colors_material.py, effectively collapsing AGS. After running the installer script AGS loads in fine although will break if switchwall.sh is initialized or if generate_colors_material.py is executed from ColorScheme menu. 

Steps to reproduce:
1. Pull changes from repo.
2. Run the install script.
3. Attempt to initialize switchwall.sh or execute generate_colors_material.py from the ColorScheme menu.

Expected behavior:
- AGS should successfully switch color schemes without breaking, and generate_colors_material.py should execute without errors.

Actual behavior:
- AGS collapses when attempting to switch color scheme, generate_colors_material.py fails to execute resulting in an error.

generate_colors_material.py Error log:
```plain
Traceback (most recent call last):
  File "/home/ln64/.config/ags/scripts/color_generation/generate_colors_material.py", line 6, in <module>
    from materialyoucolor.quantize import QuantizeCelebi
ModuleNotFoundError: No module named 'materialyoucolor'
```

![image](https://github.com/end-4/dots-hyprland/assets/111171675/c4242525-c071-4ad9-86ba-bf7ead657d6d)

**Comment by YadavYashvant** [comment]
I am also having the exact same problem 🥲
![image](https://github.com/end-4/dots-hyprland/assets/113130559/70ae5c98-cfaa-4dc4-8579-802d68029381)

**Comment by Euroysx** [comment]
same problem here

**Comment by end-4** [comment]
#428

**Comment by Detteee** [comment]
same problem after update packages with `pacman -Syu` today. Timeshift to yesterday could fix

**Comment by clsty** [comment]
@Detteee it seems to be python3.11 upgrade to python3.12 and many AUR python related packages needs a cleanbuild to move to the latest location.

I may have resolved it, just `git pull` latest repo and `./install.sh`.
