### ISSUE TITLE
[Issue] App launcher/search doesn't show newly installed apps, requires Hyprland restart before new apps appear

### ISSUE THREAD

**Issue by b4shful** [end-4/dots-hyprland#444]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch Linux

---
## The issue
Haven't fully looked into this as I am traveling currently.

When a new application or program is installed, searching for it with the Super key search menu/app launcher does not produce any results. Searching for the partial program name will only show "search the web", and then when the actual program name is typed in, it will show "Run command" as well as "Search the web", but nothing else. After a new program is installed, Hyprland must be restarted and then it shows up in the app launcher/search.

Is there any way this can be improved? Either with some sort of automatic "refresh"-ing or is there a command (existing or otherwise) that could be run to refresh the app launcher and its search? Maybe something like that already exists but isn't documented?

**Comment by end-4** [comment]
just restart ags with Ctrl+Super+R
see #117
