### ISSUE TITLE
[Feature] darkman integration

### ISSUE THREAD

**Issue by MoetaYuko** [end-4/dots-hyprland#447]
**What would you like to be added?**
Use darkman to automatically toggle light/dark color schemes based on geolocation (provided by geoclue).

**How will it help**

1. eye candy
2. browsers can retrieve day/night from dbus provided by darkman and adjust webpage contents accordingly (e.g. activates dark theme provided by github and google).

**Comment by end-4** [comment]
Simply speaking, dark mode at night and light theme during the day? 

I'm not really familiar with darkman. Is waiting for the right time and running hooked scripts all it does? If that's all then I wonder if it's a good idea to just have an AGS service do it

**Comment by MoetaYuko** [comment]
I noticed that there's already a toggle for dark mode in the color scheme dropdown. the script can be used for darkman
