### ISSUE TITLE
Missing config in m3ww branch?

### ISSUE THREAD

**Issue by hewenjin** [end-4/dots-hyprland#45]
Hello there. 
I tried `m3ww` branch. Is the dunst config missing? Notify doesn't present like the video.
And one more thing, is ibus work well in your hyprland? In my case, the float window of ibus not in the right position, fcitx5 work just fine for me.

**Comment by end-4** [comment]
i now use eww for that so no more dunst
uses notify-receive as the backend

**Comment by end-4** [comment]
forgot to add notify-receive source code. there you go, in `Projects/notify-receive`

**Comment by end-4** [comment]
oh and i should note that you have to kill dunst before launching eww or it won't work
