### ISSUE TITLE
[Issue] Command printsrc for screenshot not working, and capture screenshot with gnome-screenshot apps got error,

### ISSUE THREAD

**Issue by zydnrbrn** [end-4/dots-hyprland#454]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: LSB Version:	n/a
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	rolling

---
## The issue

use flameshot same too
<details>
<summary>Click to expand</summary>

```plain
• 󰅙  gnome-screenshot
** Message: 15:57:02.707: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.

(gnome-screenshot:2176): Gdk-CRITICAL **: 15:57:02.707: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(gnome-screenshot:2176): GdkPixbuf-CRITICAL **: 15:57:02.707: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gnome-screenshot:2176): GdkPixbuf-CRITICAL **: 15:57:02.707: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(gnome-screenshot:2176): GdkPixbuf-CRITICAL **: 15:57:02.708: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gnome-screenshot:2176): GdkPixbuf-CRITICAL **: 15:57:02.708: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gnome-screenshot:2176): Gtk-CRITICAL **: 15:57:02.720: gtk_window_resize: assertion 'width > 0' failed

** (gnome-screenshot:2176): CRITICAL **: 15:57:02.720: Unable to capture a screenshot of any window
```

</details>

**Comment by clsty** [comment]
It's under Hyprland, not Gnome. So it does not work, as expected.

**Comment by zydnrbrn** [comment]
> It's under Hyprland, not Gnome. So it does not work, as expected.

ahh yess i see, but there is an options for every take screenshot is automatically saved to pictures directory?

**Comment by clsty** [comment]
Press `Super+/` so you will see a list of keybindings. Screenshot included.

**Comment by end-4** [comment]
Ctrl + PrtSc

**Comment by zydnrbrn** [comment]
> Ctrl + PrtSc Then you should get your file in ~/Pictures/Screenshots

woahhh thanks sir
