### ISSUE TITLE
[Help] Anyone know how to increase touchpad speed?

### ISSUE THREAD

**Issue by zydnrbrn** [end-4/dots-hyprland#463]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: 

---
## The issue

<details>
<summary>Click to expand</summary>
I've been try editing the libinput, but there is no result.
```plain
Paste your log here
```

</details>

**Comment by clsty** [comment]
This issue is not a dots-hyprland problem, but I'll still provide these links anyway:
- https://wiki.hyprland.org/Configuring/Variables/#input
- https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs
- https://wiki.archlinux.org/title/Laptop#Touchpad

Closing.

**Comment by zydnrbrn** [comment]
> This issue is not a dots-hyprland problem, but I'll still provide these links anyway:
> - https://wiki.hyprland.org/Configuring/Variables/#input
> - https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs
> - https://wiki.archlinux.org/title/Laptop#Touchpad
> 
> Closing.

hehe im sorry sir, i'm not have community to asked, have you discord server refferences or something else to asked about archlinux or hyprland worlds? thank u very much about your answer

**Comment by end-4** [comment]
> hehe im sorry sir, i'm not have community to asked, have you discord server refferences or something else to asked about archlinux or hyprland worlds? thank u very much about your answer

should've thought of hyprland discord server smh
![image](https://github.com/end-4/dots-hyprland/assets/97237370/4d1b3a10-7498-428e-9e9e-1361e9b05928)
