### ISSUE TITLE
no ags features working[Issue]

### ISSUE THREAD

**Issue by playerz-unknowns** [end-4/dots-hyprland#464]
- Linux distro: endeavouros

## The issue
i installed endeavouros gnome and immediately installed dots-hyprland.no errors during installation and after rebooting into hyprland
all i can see is a blank brown screen.
ags is completely non-functional.
i dont even know what log files to attach.please inform me what to do

command:pkill ags;ags
output:GLib.SpawnError: Failed to execute child process “sass” (No such file or directory)

(com.github.Aylur.ags:4023): Gjs-WARNING **: 17:56:05.160: JS ERROR: TypeError: optionsArr[initIndex[0]] is undefined
ConfigMulipleSelection@file:///home/admin/.config/ags/modules/.commonwidgets/configwidgets.js:149:17
ColorSchemeSettings@file:///home/admin/.config/ags/modules/indicators/colorscheme.js:155:17
ColorSchemeSettingsRevealer@file:///home/admin/.config/ags/modules/indicators/colorscheme.js:40:16
ColorschemeContent@file:///home/admin/.config/ags/modules/indicators/colorscheme.js:206:9
default@file:///home/admin/.config/ags/modules/indicators/colorscheme.js:215:12
default@file:///home/admin/.config/ags/modules/indicators/main.js:28:17
forMonitors@file:///home/admin/.config/ags/config.js:28:24
Windows@file:///home/admin/.config/ags/config.js:51:5
@file:///home/admin/.config/ags/config.js:79:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

'''
(com.github.Aylur.ags:4023): Gjs-Console-CRITICAL **: 17:56:05.181: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
update@file:///home/admin/.config/ags/modules/overview/overview_hyprland.js:334:26
default/OverviewRow/setup/<@file:///home/admin/.config/ags/modules/overview/overview_hyprland.js:377:60
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  '''
the last part repeats itself hundreds of times and just stops

**Comment by playerz-unknowns** [comment]
i tried running npm install sass and it worked flawlessly but the ags error didnt disappear

**Comment by end-4** [comment]
why not use `dart-sass`? it should be installed by the install script... you sure there wasn't any error?

**Comment by end-4** [comment]
`sudo pacman -S dart-sass` then try again

**Comment by playerz-unknowns** [comment]
the error message changed a little.
pkill ags;ags
Gjs-Console-Message: 20:53:38.481: [LOG] Styles loaded

(com.github.Aylur.ags:10184): Gjs-WARNING **: 20:53:38.637: JS ERROR: TypeError: optionsArr[initIndex[0]] is undefined
ConfigMulipleSelection@file:///home/admin/.config/ags/modules/.commonwidgets/configwidgets.js:149:17
ColorSchemeSettings@file:///home/admin/.config/ags/modules/indicators/colorscheme.js:155:17
ColorSchemeSettingsRevealer@file:///home/admin/.config/ags/modules/indicators/colorscheme.js:40:16
ColorschemeContent@file:///home/admin/.config/ags/modules/indicators/colorscheme.js:206:9
default@file:///home/admin/.config/ags/modules/indicators/colorscheme.js:215:12
default@file:///home/admin/.config/ags/modules/indicators/main.js:28:17
forMonitors@file:///home/admin/.config/ags/config.js:28:24
Windows@file:///home/admin/.config/ags/config.js:51:5
@file:///home/admin/.config/ags/config.js:79:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:10184): Gjs-Console-CRITICAL **: 20:53:38.701: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
update@file:///home/admin/.config/ags/modules/overview/overview_hyprland.js:334:26
default/OverviewRow/setup/<@file:///home/admin/.config/ags/modules/overview/overview_hyprland.js:377:60
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by playerz-unknowns** [comment]
a reinstallation fixed all problems.this stuff is great.btw using chaotic-aur greatly speeds up the installation process,it might be worth mentioning
