### ISSUE TITLE
[Issue] Ags & cursor related problem

### ISSUE THREAD

**Issue by Rafi1018** [end-4/dots-hyprland#465]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro:  CachyOS

I installed your dotfiles via the script just a few moments ago & I think the ags is acting weird. Please let me know How can I fix them & what else do I need to provide to get this fixed.

As you can see in the screenshot below ags looks pretty weird
![image](https://github.com/end-4/dots-hyprland/assets/142591064/002e1db1-10b0-42d7-8727-05d19844d18f)

Also in the screenshot I have 2 invisible like scrollbar stuff
![image](https://github.com/end-4/dots-hyprland/assets/142591064/59e2cab0-3e2d-4ab5-a184-665033861b9a)

Also the cursor theme doesn't show up it's the default one

**Comment by end-4** [comment]
`sudo pacman -S dart-sass` then try again

**Comment by Rafi1018** [comment]
> `sudo pacman -S dart-sass` then try again

thanks a ton mate it's all good now & everything is working fine. You can close the issue now but I have a few questions :

- from notification side bar
  - widget I can't control speaker volume ( only the playback audio )
  - Can't get the night light to working
Can't confirm about "keep system awake" & "Raw input" .

Other works fine by the way. So is this intended ?

- How can I change the weather information location ?
- How can I update the dotfiles ?

**Comment by end-4** [comment]
> widget I can't control speaker volume ( only the playback audio )

you scroll top right corner to change volume

> Can't get the night light to working

it's because wlsunset is broken. there's a pr to switch to gammastep which i'll review soon

> Can't confirm about "keep system awake" & "Raw input" .

Raw input changes mouse accel profile to flat in hyprland, and keep system awake launches a python script which should inhibit idle. just turn it on and leave your device for a while and you'll see?

> How can I change the weather information location ?

https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/#set-city-for-weather-widget

> How can I update the dotfiles ?

run the install script again

> Any way to remove AI stuffs ? As I can't afford to use those.

you can if you dig in the code and comment relevant stuff

> Cursor theme still doesn't load up

maybe check this [hyprland faq entry](https://wiki.hyprland.org/FAQ/#me-cursor-no-render)

**Comment by Rafi1018** [comment]
> > widget I can't control speaker volume ( only the playback audio )
> 
> you scroll top right corner to change volume

I don't have any option for volume there actually just Ethernet & Bluetooth

**Comment by end-4** [comment]
i mean top right corner of the bar
and i said scroll, just,     scroll it

**Comment by Rafi1018** [comment]
> i mean top right corner of the bar and i said scroll, just, scroll it

oh my bad understood now
