### ISSUE TITLE
[Issue] AGS doesnt show up in fresh install. Breaks on wallpaper change, color generation error

### ISSUE THREAD

**Issue by allen7731** [end-4/dots-hyprland#467]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: EndeavourOS

---
## The issue

`pkill ags; ags `gives

```plain
(com.github.Aylur.ags:2101): Gjs-Console-CRITICAL **: 21:31:21.279: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/end/.cache/ags/user/generated/style.css
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class
```

</details>

**Comment by NextStep-IM** [comment]
Please check if the solution in #452 helps.
