### ISSUE TITLE
[Issue] Blank Screen at start (AGS)

### ISSUE THREAD

**Issue by BlokCSS** [end-4/dots-hyprland#474]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: 

---
## The issue

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

Hello! ive been reading the problems some people may have. I have to re install all my system again so i run the script for the dotfiles. All seems good, i installed separetely hyprland with yay and the script doesnt show any kind of errors. So, when i log in in hyprland i only see a blank brown screen with the cursor and nothing more. Ags isnt showing at all and the keybinds dont work at all either. Am i doing something wrong or maybe i have to do something else that i dont know?
Also, the script install AGS right? cuz when i do pacman -Q ags it doesnt appear like installed D:

Any kind of help would be nice!

**Comment by pepperonipizzah** [comment]
same issue, I'm on my second fresh arch install trying to install these dot files but same issue again... #468

**Comment by clsty** [comment]
> Also, the script install AGS right? cuz when i do pacman -Q ags it doesnt appear like installed D:

It did install AGS but the path is `/usr/local/bin/ags` , where is not managed by the package manager i.e. pacman.

Just run `which ags` to see it.

**Comment by EldoDebug** [comment]
I ran into the same problem myself
That problem seems to occur if no wallpaper is selected
Selecting the wallpaper with ctrl + super + t on that blank screen solves everything

**Comment by BlokCSS** [comment]
you are a genius my man!

**Comment by end-4** [comment]
i guess that's solved? gonna close

**Comment by nvn152** [comment]
> I ran into the same problem myself That problem seems to occur if no wallpaper is selected Selecting the wallpaper with ctrl + super + t on that blank screen solves everything

I selected a wallpaper, but after restarting the system, there was a blank screen with no wallpaper again. Also the night is turned on which I turned off in previous session.
