### ISSUE TITLE
[Issue] Cheat shit doesn't fit on hidpi screen

### ISSUE THREAD

**Issue by GreenBabyBorn** [end-4/dots-hyprland#477]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: 

---
## The issue

Cheat shit doesn't fit on hidpi screen

`monitor=,highres,auto,2`
![image](https://github.com/end-4/dots-hyprland/assets/35188249/8df9831e-0cb4-4bf8-9748-dbb557846e85)

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

**Comment by end-4** [comment]
decrease font size so widgets have a smaller scale 
https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/#resize-the-ui--change-font-size

**Comment by GreenBabyBorn** [comment]
> decrease font size so widgets have a smaller scale https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/#resize-the-ui--change-font-size

Thanks! I would like a responsive interface..
