### ISSUE TITLE
How can I modify the novelknock three top bar interval?

### ISSUE THREAD

**Issue by TheSonder** [end-4/dots-hyprland#48]

**Comment by TheSonder** [comment]
I find this config for some times, but it not work, maybe I'm wrong.

**Comment by end-4** [comment]
- top bar interval like the transition speed? 
  - just realized i hard-coded it :skull: 
  - anyway you wanna change line 48 of `~/.config/eww/eww.yuck`

**Comment by TheSonder** [comment]
> * top bar interval like the transition speed?
>       
>       * just realized i hard-coded it in the yuck file skull
>       * anyway you wanna change line 48 of `~/.config/eww/eww.yuck`

Maybe there is something wrong with my expression, I want to know how to adjust the spacing of the top three bars

**Comment by TheSonder** [comment]
> 

Thank you and I solved this problem.
