### ISSUE TITLE
[Feature] Proxy for llm's

### ISSUE THREAD

**Issue by CherkaSSH** [end-4/dots-hyprland#483]
**What would you like to be added?**
An ability to use proxy server as im unable to access gemini nor chatgpt cuz i live in russia

**How will it help**
I live in russia and i would like to use gemini and i could use a proxy just for that not for my whole sytem

**Comment by end-4** [comment]
already implemented in #396
the config option is `ai.proxyUrl`

**Comment by CherkaSSH** [comment]
Where is it located?
