### ISSUE TITLE
[Issue] cant install it 

### ISSUE THREAD

**Issue by EsamLasheen** [end-4/dots-hyprland#486]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: 
ARCH
## The issue
i can't install the config it's donsn't copy the file 

<details>
<summary>i can't install the config </summary>

```plain
cp: cannot stat '.config/hypr/hyprland.conf': No such file or directory
[./install.sh]: Command "cp -f .config/hypr/hyprland.conf /home/blue/.config/hypr/hyprland.conf.new" has failed.
You may need to resolve the problem manually BEFORE repeating this command.

```

</details>

**Comment by clsty** [comment]
`.config/hypr/hyprland.conf` is [a file in this repo](https://github.com/end-4/dots-hyprland/blob/main/.config/hypr/hyprland.conf).

Since the file is missing, you may download this repo again.

**Comment by EsamLasheen** [comment]
thanks bro it's work, but now i have problem in general.conf 
log is 

`
config error at line 130 (/home/blue/.config/hypr/hyprland/neneral.conf): no such animtion 
Hyprland may not work correctly.
`
![image](https://github.com/end-4/dots-hyprland/assets/55217611/e6b9b935-eabd-49f8-9ac6-ea966725f580)

**Comment by clsty** [comment]
Use AUR package `hyprland-git`.

**Comment by EsamLasheen** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/55217611/bd49243b-0908-4ca2-88b2-d8934d34e8fb)
i use it , maybe i need to clear all configs i installed it beofre ?
becuase i was use this config :
https://github.com/AhmedSaadi0/my-hyprland-config/tree/main

**Comment by clsty** [comment]
The `install.sh` before its ending will inform you that `~/.config/hypr/hyprland.conf` should be overwritten manually if it already exists, and it is your first time installation.

Though, this seems not to be the problem at present, since `~/.config/hypr/hyprland/general.conf` is taking effect, thus `~/.config/hypr/hyprland.conf` should already be there.

If clearing configs does not work for you, it is really weird.

A workaround is commenting out the line which causes the problem.
(Btw my hyprland works fine with the same animation.)

But let's dig it futher:
What's your output of `hyprctl version`? And have you restarted your system?

**Comment by EsamLasheen** [comment]
``` bash
Hyprland, built from branch main at commit 3caaa483d4bf8f18f62f8a8f03a0922ea8a4cb7e  (configmgr: fix parsing of touchdevice groups).
Tag: v0.32.3-86-g3caaa483

flags: (if any)
```
how i can update it to your version ?

**Comment by EsamLasheen** [comment]
and look at the las line 
sudo: deluser: command not found

``` bash
 ./uninstall.sh
Hi there!
This script 1. will uninstall [end-4/dots-hyprland > illogical-impulse] dotfiles
            2. will try to revert *mostly everything* installed using install.sh, so it's pretty destructive
            3. has not beed tested, use at your own risk.
            4. will show all commands that it runs.
Ctrl+C to exit. Enter to continue.
A
Removing copied config and local folders...
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/ags
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/fish
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/fontconfig
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/foot
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/fuzzel
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/hypr
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/mpv
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/wlogout
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/starship.toml
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.config/rubyshot
[./uninstall.sh]: Now executing:
rm -rf /home/la4een/.local/bin/fuzzel-emoji
Removing user from video, i2c, and input groups and removing packages...
[./uninstall.sh]: Now executing:
sudo deluser la4een video
sudo: deluser: command not found
```

**Comment by clsty** [comment]
> ```shell
> Hyprland, built from branch main at commit 3caaa483d4bf8f18f62f8a8f03a0922ea8a4cb7e  (configmgr: fix parsing of touchdevice groups).
> Tag: v0.32.3-86-g3caaa483
> 
> flags: (if any)
> ```
> 
> how i can update it to your's version ?

Just run `yay -S --answerclean=a hyprland-git`.

> and look at the las line
> sudo: deluser: command not found

Sorry but I'm not the one who write that uninstallation script.
Also I recommend not to use it.

That `deluser` command seems just trying to remove your user `la4een` from group `video`, but this is actually not something important, so you can just ignore it.

**Comment by EsamLasheen** [comment]
Thank you, brother, for your help. ❤️
But I've got this log.
``` bash 

hyprctl version
Hyprland, built from branch main at commit 3caaa483d4bf8f18f62f8a8f03a0922ea8a4cb7e  (configmgr: fix parsing of touchdevice groups).
Tag: v0.32.3-86-g3caaa483

flags: (if any)





la4een@mla4een ~> yay  -S --answerclean=a hyprland-git
Sync Explicit (1): hyprland-git-0.40.0.r39.85f7f690-1
[sudo] password for la4een: 
warning: hyprland-git-0.40.0.r39.85f7f690-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) hyprland-git-0.40.0.r39.85f7f690-1

Total Installed Size:  53.71 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                     [####################################################################] 100%
(1/1) checking package integrity                                                                                   [####################################################################] 100%
(1/1) loading package files                                                                                        [####################################################################] 100%
(1/1) checking for file conflicts                                                                                  [####################################################################] 100%
(1/1) checking available disk space                                                                                [####################################################################] 100%
:: Processing package changes...
(1/1) reinstalling hyprland-git                                                                                    [####################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...



la4een@mla4een ~> hyprctl version
Hyprland, built from branch main at commit 3caaa483d4bf8f18f62f8a8f03a0922ea8a4cb7e  (configmgr: fix parsing of touchdevice groups).
Tag: v0.32.3-86-g3caaa483

flags: (if any)

```

**Comment by clsty** [comment]
1. What's the output of `which hyprctl`?
2. Have you reboot your system after installing hyprland-git ?

**Comment by EsamLasheen** [comment]
yup i think it's it

yay -Qi hyprland-git 
Name            : hyprland-git
Version         : 0.40.0.r50.33742291-1
Description     : A dynamic tiling Wayland compositor based on wlroots that doesn't sacrifice on its looks.
Architecture    : x86_64
URL             : https://github.com/hyprwm/Hyprland
Licenses        : BSD
Groups          : None
Provides        : hyprland=0.40.0
Depends On      : cairo  cpio  gcc-libs  glib2  glibc  glslang  hyprcursor  hyprwayland-scanner  libdisplay-info  libdrm  libglvnd  libinput  libliftoff  libx11  libxcb  libxcomposite
                  libxfixes  libxkbcommon  libxrender  opengl-driver  pango  pixman  polkit  seatd  systemd-libs  tomlplusplus  wayland  wayland-protocols  xcb-proto  xcb-util
                  xcb-util-errors  xcb-util-keysyms  xcb-util-renderutil  xcb-util-wm  xorg-xinput  xorg-xwayland  libdisplay-info.so=1-64  libhyprlang.so=2-64
Optional Deps   : chaotic-interfere
Required By     : None
Optional For    : None
Conflicts With  : hyprland
Replaces        : None
Installed Size  : 53.74 MiB
Packager        : Garuda Builder <team@garudalinux.org>
Build Date      : Fri 10 May 2024 07:03:51 AM EEST
Install Date    : Fri 10 May 2024 02:27:04 PM EEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum  Signature

la4een@mla4een ~> hyprctl version
Hyprland, built from branch main at commit 3caaa483d4bf8f18f62f8a8f03a0922ea8a4cb7e  (configmgr: fix parsing of touchdevice groups).
Tag: v0.32.3-86-g3caaa483

flags: (if any)

la4een@mla4een ~> which hyprctl
/usr/local/bin/hyprctl
