### ISSUE TITLE
[Issue] Screen recording doesn't work unless ~/Videos folder exists

### ISSUE THREAD

**Issue by b4shful** [end-4/dots-hyprland#489]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki** Yes
- **I have made sure that both my config and system packages are up to date** Yes
- Linux distro: Arch

---
## The issue

Screen recording using one of the default shortcuts (e.g CTRL+ALT+R) does not work (no notification or anything, it does nothing) unless the ~/Videos folder already exists.

Reproduction:
1. Ensure your home directory does not have a ~/Videos folder
2. Attempt to take a screen recording using CTRL+ALT+R
(It does nothing)
3. Create a ~/Videos directory (e.g `mkdir ~/Videos`)
4. Take a screen recording using CTRL+ALT+R to start and stop
5. Notification appears and screen recording works as expected

This behaviour is not the same as the screenshot functionality (CTRL+PrintScreen) which creates a ~/Pictures directory to save the screenshot into even if it doesn't yet exist.

**Comment by end-4** [comment]
made the script create that folder
i also added the xdg-user-dirs package just in case other stuff are like this too (maybe ~/Pictures)
