### ISSUE TITLE
Help?!

### ISSUE THREAD

**Issue by daUnknownCoder** [end-4/dots-hyprland#49]
i actually came here from ur reddit post : https://www.reddit.com/r/unixporn/comments/13lrz09/hyprland_and_eww_people_tell_me_i_should_go_touch/?sort=new, i am not able to find the configs for these, like the music daemon (which is it), the bar on top(waybar/polybar), that awesome neofetch alt. , the cool showing off dashboard configs : ref --> https://i.redd.it/vtv4copepr0b1.png

**Comment by end-4** [comment]
in the `hybrid` branch of this repo

**Comment by end-4** [comment]
i also updated the details comment on reddit
