### ISSUE TITLE
Vesktop notification BADGE missing on top taskbar

### ISSUE THREAD

**Issue by codewithkenzo** [end-4/dots-hyprland#493]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- All packages up to date
- Linux distro: Arch Linux

---
Hi, thank you for these dots, i love the workflow and they look great. I apologize if this comes out as off-topic or rather Vesktop-related.

My issue is that I cant get a badge for my notifications for Vesktop(a web discord version packaged into a desktop client), I've had this issue while using _hyprdots_ as well.
I get proper notification **popups** when my **green online is set**. My desired effect would be to have either the pop up while on DND, or alternatively have just a badge working. For now it just shows default icon. Though I think the former depends on discord

I've tried both the aur 'vesktop' package & and the Flatpak version, while also having 'lib-unity' package & 'Flatseal' installed and 'Show notification' permission set, but they'll behave the same.

Cheers

**Comment by end-4** [comment]
Does it work in a proper desktop environment like KDE/GNOME? If it doesn't work there then probably a Vesktop issue
I don't use it so idk

**Comment by codewithkenzo** [comment]
i don't have the means to test it. it has to do with dbus name being different than what libunity picks up. idk how to figure that out so I'll close.

thanks
