### ISSUE TITLE
[Issue] AGS

### ISSUE THREAD

**Issue by einCyberSimon** [end-4/dots-hyprland#496]
- Linux distro: Arch

## The issue
After updating the repo, running the install script, and rebooting, I do not have a bar anymore.
Killing and restarting ags reveals the following log:

```plain
(com.github.Aylur.ags:7950): Gjs-WARNING **: 12:00:41.041: JS ERROR: Gio.IOErrorEnum: Could not connect: No such file or directory
socket@resource:///com/github/Aylur/ags/service/hyprland.js:7:6
_socketStream@resource:///com/github/Aylur/ags/service/hyprland.js:140:34
message@resource:///com/github/Aylur/ags/service/hyprland.js:151:43
Hyprland@resource:///com/github/Aylur/ags/service/hyprland.js:102:41
@resource:///com/github/Aylur/ags/service/hyprland.js:321:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:
```

I don't know much about ags and where the error comes from, but since this only happened after updating the dotfiles, I wanted to start here. Feel free to redirect me to the ags repo if this isn't an issue with the dotfiles :)

</details>

**Comment by end-4** [comment]
make sure both hyprland is on the latest version (-git)

**Comment by einCyberSimon** [comment]
Ah, this seems to be the error. The current (hyprland-git) package does not build because of some issue with packaging.
Thanks for helping!
