### ISSUE TITLE
[Issue] Ags workspace switcher doesn't display most icons

### ISSUE THREAD

**Issue by rabaimorp** [end-4/dots-hyprland#497]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: 
Arch Linux
## The issue
Ags workspace switcher missing almosy every icon. The only icons properly displaying in the workspace swither are foot (footclient doesn't) and firefox-nightly. All the other apps just show a missing icon. Whats weird that the app launcher doesn't have this problem and displays all the icons properly. (see example in screenshots)
![screenshot_2024-05-13_12-27-34](https://github.com/end-4/dots-hyprland/assets/161316025/f882ed38-927e-4ccc-8222-8286e2ed36c4)
![screenshot_2024-05-13_12-27-47](https://github.com/end-4/dots-hyprland/assets/161316025/a75cb7bd-48ba-488c-8ae4-0edbe5b3849d)

As seen here the same program (qutebrowser for this example) only shows icon in the app launcher.
I have no idea where to start troubleshooting, as well as what logs to post.

**Comment by end-4** [comment]
the app class name (top-left corner) looks valid. it's just your icon pack doesn't support it
and you said "most icons", but only showed one

**Comment by end-4** [comment]
> I just have trouble understanding why ags doesn't display icons in the workspace switcher when it does in the app launcher.

https://github.com/end-4/dots-hyprland/issues/487#issuecomment-2099657493

**Comment by end-4** [comment]
that's how it guesses icon name
apps in launcher have desktop entries which tell what icon to use, but apps reported by hyprland don't
