### ISSUE TITLE
[Issue] Blur effect disappears during ags widget fade-out

### ISSUE THREAD

**Issue by EldoDebug** [end-4/dots-hyprland#498]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch Linux
## The issue
Blur effect disappears during widget fade-out
Not a major issue, but it did bother me personally
https://github.com/end-4/dots-hyprland/assets/75922660/1a9b5353-84fb-4085-a0a6-d39f62ef7cac

**Comment by end-4** [comment]
it's a hyprland problem
it doesn't draw blur when the layers are exiting
prob gonna dig in its source when i have time

**Comment by EldoDebug** [comment]
Ah, I understand
Thank you!
