### ISSUE TITLE
Cursor jumps to the center of the screen

### ISSUE THREAD

**Issue by Roverp1** [end-4/dots-hyprland#499]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch

---
## The issue
When in nautilus (gnom file manager), after changing folder mouse cursor jumps to the center of the screen.   
In other file managers (I tried thunar, nemo and pcmanfm), cursor behaves normally (stays at the place after double clicking on the folder).  
Same issue also present in `telegram-desktop`, when changing chats - cursor jumps to center of the screen.
I added video with recorded issue.

https://github.com/end-4/dots-hyprland/assets/149878979/7f7406d1-5036-4e29-bdc3-76b40e3937bc

   

<details>
<summary>Click to expand</summary>

This may not related to dotfiles at all, but I never experienced that issue before on my dwm setup, where cursor behaved normally at every app (telegram included). So Im apologizing if it not related, and asking for a direction where I may find help.  
<br>

The thing i wanned to ask additionally:
- the bind of the emoji menu (Super, Period) does not work for me. And behaves very strangely. It works as intended when i execute it from terminal, but with bind I was able to get only debugging `notify-send "..."` at the 2nd line of script, and menu did not appear.
> I tried moving script to different folder
> Tried running `chmod 777` on script
> Tried changing bind
> Tried removing repeated if else logic in the script
The menu still doesn't work

</details>

**Comment by end-4** [comment]
i'm experiencing this too, probably a hyprland issue
it also happens to chromium when i click on links

**Comment by Roverp1** [comment]
I've also found a similar issue on the Hyprland GitHub page: [Game: cursor warps to center when it's near screen edges](https://github.com/hyprwm/Hyprland/issues/6078). I will move the issue if I can reproduce it on a clean Arch install.

**Comment by ssvx** [comment]
Does it still happen if you use this?

> general {
>     no_cursor_warps = true
> }

Or that other one from the wiki
> cursor {
>     no_warps = true
> }
(either new or old, yields an error when i use that one)

**Comment by Roverp1** [comment]
Yes, it fixed the problem. Even though it disabled warping the cursor to the active window when changing focus with the keyboard. 
I am happy enough with this solution. Thanks for the help.

**Comment by ssvx** [comment]
It remains unclear tho if nautilus is at fault here or not tho. Could imagine something like nautilus spawning new instances or requesting focus or something on opening a folder, causing the cursor to warp to the window's center. Could also mean there's room for improvement on Hyperland's side regarding the event trigger...

**Comment by end-4** [comment]
> It remains unclear tho if nautilus is at fault here or not tho

No, since this happens after I update Hyprland and it happens to Chromium too

**Comment by end-4** [comment]
update hyprland guys
it's fixed for me
