### ISSUE TITLE
The wallpaper is not installed, but the colors change.

### ISSUE THREAD

**Issue by shtekxr** [end-4/dots-hyprland#501]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch-based(CachyOS)

---
## The issue

The wallpaper is not installed, but the colors change.
When I try to start the wallpaper changer via CTRL+ SUPER+T, it starts, but when I select the wallpaper, they do not change. Only the colors change. I launched ~/.config/ags/scripts/color_generation/switchwall.sh through the terminal, and received logs about invalid coordinates, I tried to edit the file switchwall.sh but this did not lead to a solution to the problem and I returned everything as it was. I have two monitors:
DP-1, 10801440@165, 1920x0, 1
DP-2, 1920x1080, 0x180, 1
GPU - RTX 3070 Ti

<details>
<summary>Click to expand</summary>

```plain
/home/whiteplugg/.config/ags/scripts/color_generation/switchwall.sh: line 12: bc: command not found
/home/whiteplugg/.config/ags/scripts/color_generation/switchwall.sh: line 14: bc: command not found
error: invalid value ', 1440' for '--transition-pos <TRANSITION_POS>': Invalid x coord: 

For more information, try '--help'.
 3s ••     
•   
undefined
[Gradience] INFO: Preset Material3_Generated applied successfully for Gtk 3 and Gtk 4 applications.
[Gradience] INFO: In order for changes to take full effect, you need to log out.
undefined
```

</details>

**Comment by end-4** [comment]
> line 12: bc: command not found

obviously, go ahead and install `bc`

**Comment by end-4** [comment]
hold on, my script doesn't even use `bc`...
are you sure it's intact?
