### ISSUE TITLE
[Issue] Background not setting

### ISSUE THREAD

**Issue by Wafflewithketchup** [end-4/dots-hyprland#509]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch Linux

---The issue:

When setting a background in the Gnome settings, no background appears. Background is solid black.
Using 3 monitors with different resolutions (4k, 1440p and 1080p).
Not a single workspace has a background

**Comment by end-4** [comment]
set it with ctrl+super+t
not everything in the gnome settings app will work, this for example

**Comment by Wafflewithketchup** [comment]
ctrl+super+t does open a popup to select a background. This does trigger a new colour scheme, but the desktop background will be a solid colour from the colour scheme, not the background image selected.

**Comment by end-4** [comment]
`~/.config/ags/scripts/color_generation/switchwall.sh --noswitch`
give logs pls

**Comment by grimkraut** [comment]
I had the same issue and found out that i didn't have the bc command available, so after installing it it did work for me

**Comment by Wafflewithketchup** [comment]
~/.config/ags/scripts/color_generation/switchwall.sh
/home/user/.config/ags/scripts/color_generation/switchwall.sh: line 12: bc: command not found
/home/user/.config/ags/scripts/color_generation/switchwall.sh: line 14: bc: command not found
error: invalid value ', 1440' for '--transition-pos <TRANSITION_POS>': Invalid x coord: 

For more information, try '--help'.

undefined
[Gradience] INFO: Preset Material3_Generated applied successfully for Gtk 3 and Gtk 4 applications.
[Gradience] INFO: In order for changes to take full effect, you need to log out.
undefined

**Comment by Wafflewithketchup** [comment]
@grimkraut's suggestion solved my issue, thanks!

**Comment by end-4** [comment]
what...
idk where it's used but i guess i'll just add that package anyway

**Comment by Roverp1** [comment]
Same, after updating the dotfiles yesterday via update-dots.sh, Ctrl+Super+T no longer changed the wallpaper, only the color scheme. Installing `bc` fixed the problem.

<details>
<summary>Currently on commit</summary>

```plain
commit c5b159d19f5807b1ee943f1a5a41faed77f457e0 (HEAD -> main, origin/main)
Author: end-4 <97237370+end-4@users.noreply.github.com>
Date:   Sat May 18 19:45:36 2024 +0700

    remove unecessary click2close
```

</details>

**Comment by SVTA-OP** [comment]
I'm getting this issue when running the script and setting a wallpaper. The colors work, however.
![image](https://github.com/end-4/dots-hyprland/assets/126323835/2f11ad78-922c-46cd-a021-ef5fa6ed11bf)

**Comment by end-4** [comment]
install jq

**Comment by SVTA-OP** [comment]
Yes, I found the issue a few minutes after posting. Thanks.
