### ISSUE TITLE
The eww logs show error about "notifications.yuck" and can't see notifications int sideright widget.

### ISSUE THREAD

**Issue by TheSonder** [end-4/dots-hyprland#51]
The eww logs:

`error: Failed to turn `{"count":1,"data":[{"content":[["Test notification","Hyprland, built from branch main at commit 0314a727eb27dd880b172b9ff2dc78c863f3ce5f dirty (layers: set proper alpha to top grabbing surfaces)."]],"count":1,"name":"notify-send"}]}` into a value of type json-array
   ┌─ ./modules/notifications.yuck:55:22
   │
55 │             :text "${arraylength(notifications) > 0 ? notifications[0]['body'] : ''}"
   │                      ──────────────────────────`

**Comment by end-4** [comment]
which branch are you using?
if i'm right that you're using the novelknock branch, the notifications variable format shouldn't look like that

can you show line 114 of `variables.yuck` please?
it should be
```lisp
(deflisten notifications :initial '[]' "scripts/notify-receive | gojq -c -M 'reverse'")
```

**Comment by TheSonder** [comment]
> which branch are you using? if i'm right that you're using the novelknock branch, the notifications variable format shouldn't look like that
> 
> can you show line 114 of `variables.yuck` please? it should be
> 
> ```lisp
> (deflisten notifications :initial '[]' "scripts/notify-receive | gojq -c -M 'reverse'")
> ```

yes, i'm using novelknock branch and file `variables.yuck` is `(deflisten notifications :initial '[]' "scripts/notify-receive | gojq -c -M 'reverse'")` and what should i do to fix this problem?

**Comment by TheSonder** [comment]
yes, i'm using novelknock branch and file variables.yuck is (deflisten notifications :initial '[]' "scripts/notify-receive | gojq -c -M 'reverse'") and what should i do to fix this problem?

**Comment by TheSonder** [comment]
yes, i'm using novelknock branch and file variables.yuck is `(deflisten notifications :initial '[]' "scripts/notify-receive | gojq -c -M 'reverse'") `and what should i do to fix this problem?

**Comment by end-4** [comment]
well
idk
it should not print the above you sent
run that binary manually (or compile it manually - you can find the source in the Projects folder) it should output something like this
```json
[{"id":1,"app_name":"eww","summary":"Low battery","body":"Plug in ur charger pweeaase","time":"07:15","icon":"","timeout":-1,"urgency":2,"actions":[],"visible":true}]
```

**Comment by TheSonder** [comment]
If I run this binary, it will print an error message saying "Error: name already taken on the bus." Then I stopped the command (deflisten notifications :initial '[]' "scripts/notify-receive | gojq -c -M 'reverse'"). After restarting Hyprland, I manually executed ./scripts/notify-receive | gojq -c -M 'reverse', and it ran successfully. However, when I use the shortcut key Super + Alt + F12, the notify-receive command doesn't produce any output.

**Comment by end-4** [comment]
kill any other notification daemon first

**Comment by end-4** [comment]
`pkill dunst; pkill mako; pkill notify-receive`

**Comment by Dialgatrainer02** [comment]
does this replace the notif daemon or run with it as i am running this before dunst and no notifications show up when using notify send

**Comment by end-4** [comment]
- yes, `notify-receive` is a notification daemon that i use with `eww`. 
  - binary at `.config/eww/scripts/notify-receive` 
  - source in the `Projects` folder.
- only one notif daemon can be ran at once
  - if you already have another one running before launching eww, it won't work. that's why i told you to kill them

**Comment by end-4** [comment]
EWW-powered setups are no longer supported, so I'm closing this
