### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by user12xxxxxx** [end-4/dots-hyprland#510]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**

- Linux distro: 
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	24.0.0
Codename:	Wynsdey
---

## The issue
music widget does't shows timer
![swappy-20240518_200048](https://github.com/end-4/dots-hyprland/assets/111512589/458273d8-520e-4a8e-8108-e42787827880)

**Comment by end-4** [comment]
maybe your music player doesn't give sufficient info?
provide output of `playerctl -F metadata` plz

**Comment by user12xxxxxx** [comment]
here
`G4Music xesam:artist              K/DA
G4Music xesam:album               THE BADDEST
G4Music xesam:title               THE BADDEST
G4Music mpris:artUrl              file:///home/nautesh/.var/app/com.github.neithern.g4music/cache/com.github.neithern.g4music/4e17190480a16045165682db812eb8c3
G4Music mpris:length              162600022`

**Comment by user12xxxxxx** [comment]
> maybe your music player doesn't give sufficient info? provide output of `playerctl -F metadata` plz

yeah i think g4music sends insufficient info
