### ISSUE TITLE
[Issue] Enable touch when typing

### ISSUE THREAD

**Issue by cheyao** [end-4/dots-hyprland#511]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch Linux

---
## The issue

I've been trying to enable touch when typing, but I can't get it to work.

I've tries several options:
`gsettings set org.gnome.desktop.peripherals.touchpad disable-while-typing false`
`gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled`
Turning off `disable while typing` in gnome settings

But the mouse is still disabled. How can I enable it? 

<details>
<summary>libinput list-devices output for the trackpad</summary>

```plain
Device:           bcm5974
Kernel:           /dev/input/event15
Group:            6
Seat:             seat0, default
Size:             107x75mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    enabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    button-areas *clickfinger 
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive custom
Rotation:         n/a
```

</details>

**Comment by Roverp1** [comment]
Are you using Hyprland? 
If you are, then it is
```
input {
  touchpad {
    disable_while_typing = false
  }
}
```
in `~/.config/hypr/custom/general.conf`, in case of this dotfiles.

**Comment by cheyao** [comment]
Ah thanks for the solution! Didn't know that hyprland also has this option.

**Comment by end-4** [comment]
you can temporary toggle it on the sidebar btw
![image](https://github.com/end-4/dots-hyprland/assets/97237370/44123588-2118-442b-8321-a3bf39348e97)
