### ISSUE TITLE
ags not working 

### ISSUE THREAD

**Issue by panospap004** [end-4/dots-hyprland#514]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: arco-linux

---
after i updated my system with yay today the ags stoped working i restarted my arch based distro sinced i was thinking it might neded a reboot for some package (idk) when i loged back in the ags stoped showing and when i run ags -r it said ags is already running so i did killall ags and re run ags with ags -r and hot the following error

(com.github.Aylur.ags:4186): Gjs-WARNING **: 18:12:10.443: JS ERROR: Gio.IOErrorEnum: Could not connect: No such file or directory
socket@resource:///com/github/Aylur/ags/service/hyprland.js:7:6
_socketStream@resource:///com/github/Aylur/ags/service/hyprland.js:140:34
message@resource:///com/github/Aylur/ags/service/hyprland.js:151:43
Hyprland@resource:///com/github/Aylur/ags/service/hyprland.js:102:41
@resource:///com/github/Aylur/ags/service/hyprland.js:321:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by end-4** [comment]
make sure both hyprland and ags are up to date, as recently hyprland introduced a breaking change
run the `update-ags.sh` script and it should be fine

**Comment by panospap004** [comment]
i get the following error when i try to do ./install.sh and i have done git pull to have the latest branch 
and i get the following error from update-args
install.sh:
ags 1.7.8

  Subprojects
    gutils: YES
    gvc   : YES

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 186, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 363, in run
    app.generate()
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 187, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 241, in _generate
    cdf = env.dump_coredata()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/environment.py", line 825, in dump_coredata
    return coredata.save(self.coredata, self.get_build_dir())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/coredata.py", line 1242, in save
    shutil.copyfile(filename, prev_filename)
  File "/usr/lib/python3.12/shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/pappanos/.cache/dots-hyprland/cache/ags/build/meson-private/coredata.dat.prev'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
[./install.sh]: Command "meson setup build --reconfigure" has failed.
You may need to resolve the problem manually BEFORE repeating this command.
  r = Repeat this command (DEFAULT)
  e = Exit now
  i = Ignore this error and continue (your setup might not work correctly)
  
  update-args:
  [./update-ags.sh]: Command "mkdir -p /home/pappanos/.cache/dots-hyprland/cache/ags" finished.
[./update-ags.sh]: Command "cd /home/pappanos/.cache/dots-hyprland/cache/ags" finished.
warning: re-init: ignored --initial-branch=main
Reinitialized existing Git repository in /home/pappanos/.cache/dots-hyprland/cache/ags/.git/
error: remote origin already exists.
fatal: unable to access 'https://github.com/Aylur/ags.git/': Could not resolve host: github.com
[./update-ags.sh]: Command "git pull origin main" has failed.
You may need to resolve the problem manually BEFORE repeating this command.
  r = Repeat this command (DEFAULT)
