### ISSUE TITLE
[Issue] clicking any buttons in super+comma dosen't show any difference in color scheme preview

### ISSUE THREAD

**Issue by l4v3nx** [end-4/dots-hyprland#522]
https://github.com/end-4/dots-hyprland/assets/58698398/d69f7300-ad2b-4719-9516-80fc6c972823

_Originally posted by @l4v3nx in https://github.com/end-4/dots-hyprland/issues/519#issuecomment-2120755513_

**Comment by H0mire** [comment]
https://github.com/end-4/dots-hyprland/issues/524
