### ISSUE TITLE
[Issue] random critical ags error

### ISSUE THREAD

**Issue by l4v3nx** [end-4/dots-hyprland#523]
reproducible by hitting Escape when cheatsheet window is opened
```plain
(com.github.Aylur.ags:175212): Gjs-Console-CRITICAL **: 18:56:17.764: Error: There is no window named click2close0
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
closeWindow@resource:///com/github/Aylur/ags/app.js:125:24
globalThis.closeEverything@file:///home/old4ever/.config/ags/variables.js:50:13
default/setup/<@file:///home/old4ever/.config/ags/modules/.widgethacks/popupwindow.js:21:46
keybind/<@resource:///com/github/Aylur/ags/widgets/widget.js:81:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

_Originally posted by @l4v3nx in https://github.com/end-4/dots-hyprland/issues/519#issuecomment-2120757533_

**Comment by end-4** [comment]
update the config
i've already removed every instance of click2close

**Comment by l4v3nx** [comment]
> update the config i've already removed every instance of click2close

I did clean install (removing ags files from .cache, .config and .local/state and reinstalling with install.sh script) several times. maybe I'm too dumb, I'll try again later

**Comment by l4v3nx** [comment]
error does reference here https://github.com/end-4/dots-hyprland/blob/5337260a462470376c54cca54b92ae9910b0476e/.config/ags/variables.js#L50

>  i've already removed every instance of click2close
I doubt this error is somehow related to c5b159d

**Comment by end-4** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

me when uncommited changes
