### ISSUE TITLE
[Issue] Material colors are not regenerated on config change

### ISSUE THREAD

**Issue by theskyblockman** [end-4/dots-hyprland#529]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch Linux

---
## The issue
I've just used the installer and after a bunch of dependency resolution problems I got to start testing the system, I put the light mode, then I got this error and no styles were working anymore + a big red error message in Hyprland:
```
Config error in file ~/.config/hypr/hyprland/colors.conf at line 9: rgba() expects length of 8 characters (4 bytes) or 4 comma separated values
```
Here's the line in the config: (the error is probably ``$surface`` being empty)
```
background_color = rgba({{ $surface }}FF)
```

I did not went under the hood on this project so I don't have any idea of where/why this happens. Nor I know how to collect more logs (if I run ``Hyprland`` in KDE Plasma, the logs aren't really interesting)

Can someone explain to me how/where those variables are generated so that I can come up with a fix or do a more in-depth analysis?

**Comment by theskyblockman** [comment]
> > * **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
> > * **I have made sure that both my config and system packages are up to date**
> > * Linux distro: Arch Linux
> > 
> > 
> > 
> > ## The issue
> > I've just used the installer and after a bunch of dependency resolution problems I got to start testing the system, I put the light mode, then I got this error and no styles were working anymore + a big red error message in Hyprland:
> > ```
> > 
> > Config error in file ~/.config/hypr/hyprland/colors.conf at line 9: rgba() expects length of 8 characters (4 bytes) or 4 comma separated values
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's the line in the config: (the error is probably `$surface` being empty)
> > ```
> > 
> > background_color = rgba({{ $surface }}FF)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I did not went under the hood on this project so I don't have any idea of where/why this happens. Nor I know how to collect more logs (if I run `Hyprland` in KDE Plasma, the logs aren't really interesting)
> > Can someone explain to me how/where those variables are generated so that I can come up with a fix or do a more in-depth analysis?
> 
> I encountered the same error but fixed it by using ctrl + SUPER + t keybind and choosing a wallpaper (png, jpg) when the file browser opens.

Thanks! This worked flawlessly, I am gonna inspect what is going on here and try to come up with a fix (if I succeed...)

**Comment by clsty** [comment]
It just requires a wallpaper to generate color scheme, so there is actually nothing unexpected here. Closing.
