### ISSUE TITLE
As the framerate size of `scripts/custom_configs/cava` increases, the bottomsheet will crash more frequently and at a faster rate.

### ISSUE THREAD

**Issue by TheSonder** [end-4/dots-hyprland#53]
I am unable to find certain useful messages in the eww logs.
When I use `./script/cavajson` in the terminal, everything works fine and it prints numbers correctly without any application crashes.

**Comment by TheSonder** [comment]
No matter what cava configuration file I set, it will cause eww to crash completely.

**Comment by TheSonder** [comment]
I got this 
`Caused by:
    channel closed
 2023-08-16T18:02:23.954Z ERROR eww::error_handling_ctx > sending response from main thread

Caused by:
    0: Failed to send success response from application thread
    1: channel closed
`

**Comment by end-4** [comment]
i think it's just becausse of my eww abuse
too many animated boxes

**Comment by TheSonder** [comment]
How can I solve this issue? Having an i7 12900H processor on my computer is advantageous.

**Comment by end-4** [comment]
im clueless. maybe reduce the number of columns?
edit line 6 of `~/.config/eww/scripts/custom_configs/cava`  (which is currently `bars = 70`)

**Comment by end-4** [comment]
I'm closing this, since I no longer support EWW-powered setups
