### ISSUE TITLE
[Issue] Hyprlock configuration removed

### ISSUE THREAD

**Issue by Srkless** [end-4/dots-hyprland#533]
I have problem with hyprlock, when I use my configuration and change wallpaper, default hyprlock config from github overwrites my. Why is this happening?

**Comment by Srkless** [comment]
Script "applycolor.sh" from ags color_generation was problem.

**Comment by end-4** [comment]
yea if you wanna change it edit the template in `~/.config/ags/scripts/templates/hypr/hyprlock.conf`

**Comment by stinobook** [comment]
> yea if you wanna change it edit the template in `~/.config/ags/scripts/templates/hypr/hyprlock.conf`

maybe update this line in your guide as well or add a comment about it ? :)
https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/#configure-lock-screen
had to find it here to find the fix.
