### ISSUE TITLE
[Feature] maunal accent color

### ISSUE THREAD

**Issue by kittenvr** [end-4/dots-hyprland#534]
**What would you like to be added?**

make me able to set accent color hex or rgb
**How will it help**

i want it to be diferent from wallpaper
**Extra info**

**Comment by end-4** [comment]
open overview, type `>color`, pick desired color on screen

**Comment by end-4** [comment]
but if you wanna manually type it in, sure

**Comment by kittenvr** [comment]
How to open overview

**Comment by clsty** [comment]
Press Super key (you may find it as "Windows" icon key).

**Comment by kittenvr** [comment]
> Press Super key (you may find it as "Win(dows)" icon key).

thanks, for me its code key

**Comment by end-4** [comment]
i'm assuming it works then? reopen if not

**Comment by Luquatic** [comment]
it's not working for me?

I open overview and type `>color #128C7E` but nothing happens

**Comment by end-4** [comment]
> it's not working for me?
> 
> I open overview and type `>color #128C7E` but nothing happens

this thread was from the old ags version

now you do /accentcolor and pick color on the screen
