### ISSUE TITLE
Can't modify todo list

### ISSUE THREAD

**Issue by end-4** [end-4/dots-hyprland#536]
## The issue
- Changes to todo list aren't saved
- `Gio.IOErrorEnum: Error opening file “/home/end/.local/state/ags/user/todo.json”: Permission denied`

**Comment by end-4** [comment]
@Cu3PO42 does this happen to you

**Comment by clsty** [comment]
This does not happen to me.
I suggest you to delete that file and try again.

**Comment by end-4** [comment]
huh right, it's normal now
i guess permission issues caused by copying with admin permissions

**Comment by Cu3PO42** [comment]
Glad this is sorted. I also haven't encountered this particular issue, but I've definitely unintentially written things as `root`.
