### ISSUE TITLE
Beginner friendly Documentation

### ISSUE THREAD

**Issue by deveshXm** [end-4/dots-hyprland#55]
I really love your work. But I am not able to set it up. Can you please make the documentation more beginner friendly documentation.

I am not able to configure the config like the one in your videos and screenshots.

Please provide a more easier documentation. I hope you will do something about it.

Humble request from a beginner

**Comment by end-4** [comment]
thanks for letting me know that it isnt beginner friendly
it would be really helpful if you could point out all the things that aren't friendly

**Comment by deveshXm** [comment]
> thanks for letting me know that it isnt beginner friendly
> it would be really helpful if you could point out all the things that aren't friendly

Definitely. I am facing the following problems right now. But firstly what I could understand on how to install it is download all the dependencies including the python ones, then run the ./guided_install.sh. for more things I can copy folders inside .config. I hope that's the right way to do it.
 
While I tried to install it I am facing the following issues.

- No changes took place. Apart from wallpaper changing. And I could only start foot. Couldn't change the theme using Shift + super + W.

- Waybar was missing. I think it was because I couldn't install waybar-hyprland-git. It always throws error showing it cannot build. I tried to find a solution but I am not able to fix it yet.

- There was an error on top saying "couldn't set false on blur". Figured out the now the blur needs to mentioned as now blur needs to mentioned as sub field in decorations so I was able to fix that. But I really couldn't notice any change.

- Also my right click is not working.

Right now these are all the errors I am facing. It will be helpful if you could provide me some info how to fix them.

**Comment by end-4** [comment]
Appreciate that.
And to answer your questions:
- Python dependencies: alright, I'll change that to the command format so newbies can just copy run it. It's simple as adding `pip` at the beginning of that list
- Don't assume keybinds or software used. Dotfiles are personal and they will vary a lot. The readme doesn't mention that you can use a keybind to change theme.
- About waybar:
  - An AUR package failed to build. Welcome to Arch Linux! ;)
  - Waybar in my setup doesn't really use hyprland-specific features, so you can just install the normal waybar (`sudo pacman -S waybar`).
- That blur has the wrong format because you're using an old branch. ~~(too lazy to fix that lol, i have too many setups).~~
- Right click isn't working... How is it not working? Doesn't work for apps? Does it work before installing my configs? Does reloading the config help?

**Comment by deveshXm** [comment]
Do I need to do a setup of hyprland before using your dotfiles. Like I was using a config of a custom youtuber before. Now I want to switch to yours so I basically installed all the dependencies and ran the guided_install.sh 

Apart from that do I need to do anything else?

**Comment by end-4** [comment]
- if you used the install script basic stuff will work. i never actually tested it on a fresh machine. it does advise the user to check the repo and see if anything they want to copy manually. see if something's missing. 
- right click: 
  - are you using a mouse or a touchipad? if you're using a touchpad then you have to use 2 fingers. clicking the bottom-right corner doesn't work - that's a Windows thing
  - other than that idk what can be wrong. maybe check `~/.config/hypr/hyprland.conf` and find if you accidentally configured something with only `mouse:273`

**Comment by deveshXm** [comment]
- Is it possible that you can make a youtube tutorial. I know I am asking a lot but it will definitely help a lot.
- yes I am using touchpad. Thanks for the info. It is working now.

**Comment by end-4** [comment]
- About a Youtube tutorial, I've been asked this in the past but it's really hard
  - Hyprland doesn't work (at least not ootb) in a VM
  - I don't have a 2nd machine and don't want to reinstall my system for a tutorial

**Comment by deveshXm** [comment]
Well I hope you make it someday. For now I guess I'll have to use a normal hyprland setup until I figure out how to use yours. Thanks for the help

**Comment by Dialgatrainer02** [comment]
> Appreciate that. And to answer your questions:
> 
>     * Python dependencies: alright, I'll change that to the command format so newbies can just copy run it. It's simple as adding `pip install` at the beginning of that list
> 
>     * Don't assume keybinds or software used. Dotfiles are personal so they will vary a lot. The readme doesn't mention that you can use a keybind to change theme.
> 
>     * About waybar:
>       
>       * An AUR package failed to build. Welcome to Arch Linux! ;)
>       * Waybar in my setup doesn't really use hyprland-specific features, so you can just install the normal waybar (`sudo pacman -S waybar`).
> 
>     * That blur has the wrong format because you're using an old branch. ~(too lazy to fix that lol, i have too many setups).~
> 
>     * Right click isn't working... How is it not working? Doesn't work for apps? Does it work before installing my configs? Does reloading the config help?

fyi pip install wont work as a patch was made to pip to prevent it from overridding system packages 
the fix is too suffix python-<package> instead as we dont want to kill peoples python and updates by using break system packages

**Comment by end-4** [comment]
i know pip prevention is a thing but idk that happens even if you've never installed a python- package. thanks for informing.

**Comment by end-4** [comment]
btw you can use github desktop if you dont wanna mess with git :wink:

**Comment by s03i0path** [comment]
eww is not working my man ... any solution ?

**Comment by end-4** [comment]
i suggest you read the warning in the readme

**Comment by end-4** [comment]
There's now an install script which makes things easy. 
And there's also a nice new wiki ([end-4/dots-hyprland-wiki](https://github.com/end-4/dots-hyprland-wiki)). If you'd like to suggest ideas for it, open an issue in its repo

I'm closing this for now, since I no longer support EWW-powered setups. The new widget system of choice is AGS, which makes things much easier and less hacky.

**Comment by clsty** [comment]
@deveshXm I happened to see this issue again and, it's now at the most beginner-friendly status in its history lol

I guess you'll like it if you try it now.
