### ISSUE TITLE
no eq on music/bottom sheet

### ISSUE THREAD

**Issue by Dialgatrainer02** [end-4/dots-hyprland#56]
i have cava installed and running the background but i have no eq when playing music i have a standard cava wich does recognise the input im using pipewire and wireplumber

**Comment by end-4** [comment]
oops i missed this one
- does `cava -p ~/.config/eww/scripts/custom_configs/cava` print numbers separated by semicolons?
- does `~/.config/eww/scripts/cavajson` print those numbers, but in JSON arrays?

**Comment by MyLiege23** [comment]
I have the same issue. I believe it's a cava issue. When running cava (and the first command you gave):

``
❯ cava -p ~/.config/eww/scripts/custom_configs/cava 
Linux kernel module "snd_aloop" does not seem to  be loaded.
Maybe run "sudo modprobe snd_aloop".
``
After runnind `sudo modprobe snd_aloop` the `cava -p ~/.config...` command gives all 0's separated by semicolons continuously until exited. The cavajson command provides `[[0,0],[0,1],[0,3]`... up to ...`[0,69]]` then repeats until exited.

**Comment by end-4** [comment]
hmm yeah i also went through the same thing but i don't remember it
i'm not even sure if this is just a cava problem or my problem. @Dialgatrainer02 please confirm this. If you have to go through the same procedure as above, tell me so i can add it to the instructions

**Comment by Dialgatrainer02** [comment]
I had to set-up the inputs using the config
 `[input]
Method=pipe wire
Source=auto`
This got my output of [0-0] on repeat I'm on mobile so I can't gat the output but even with cava setup properly no eq was showing

**Comment by end-4** [comment]
so cava works but doesn't visualize? have y'all tried playing some music?

**Comment by loulou310** [comment]
Having the same problem here, and cava itself doesn't output anything. Same issue with GNOME

**Comment by end-4** [comment]
- @loulou310 do you mean like running cava in gnome or something?
- about the cava only outputting 0s in raw output mode, i *do* remember experiencing that but i don't remember how i fixed it. iirc i had to read the example config or ask an ai or something. 
  - i may do that later, but you guys should do that too

**Comment by loulou310** [comment]
> @loulou310 do you mean like running cava in gnome or something?

Yup

**Comment by end-4** [comment]
guys try
```
[input]
method = pulse
source = auto
```
in ~/.config/eww/scripts/custom_configs/cava
a guy told me it's related to Windows support shit

**Comment by Dialgatrainer02** [comment]
> so cava works but doesn't visualize? have y'all tried playing some music?

Yes I have had a cava with a standard config running alongside the music eww sheet and cava displays but bottom sheet doesn't

**Comment by Dialgatrainer02** [comment]
> guys try
> 
> ```
> [input]
> method = pulse
> source = auto
> ```
> 
> in ~/.config/eww/scripts/custom_configs/cava a guy told me it's related to Windows support shit

I have had the music sheet working in the past and I don't think this will work with pipewire

**Comment by end-4** [comment]
im using pipewire and that config fixed normal cava

**Comment by end-4** [comment]
it also fixed cava in eww for me. that's with cava 0.9

**Comment by Dialgatrainer02** [comment]
> im using pipewire and that config fixed normal cava

I used pipewire instead of pulse in the method line so I'll try pulse when my laptop is returned to me and I'll report back

**Comment by MyLiege23** [comment]
Thanks, the config worked!

**Comment by end-4** [comment]
yo @Dialgatrainer02 please verify this and close the issue if it works

**Comment by Dialgatrainer02** [comment]
I'm currently traveling give me a few hours and I'll check and potentially close it

**Comment by end-4** [comment]
oh sure, no rush

**Comment by Dialgatrainer02** [comment]
i added the pulse line and it doesnt work i ran cava -p  ~/.config/eww/scripts/custom_configs/cava  
i got this error Error loading config. output method pipewire is not supported, supported methods are: 'noncurses', 'raw', 'noritake', 'ncurses', 'sdl'
[cava.txt](https://github.com/end-4/dots-hyprland/files/12474908/cava.txt)
this is the config i have and it doefinatly says output method is raw 
im really sorry for the delayed and late replys

**Comment by end-4** [comment]
update cava maybe

**Comment by Dialgatrainer02** [comment]
ran an update and still doesnt work

**Comment by end-4** [comment]
could it be that you don't have `pipewire-pulse`? (just a guess, i've never installed this kinda thing myself manually)

**Comment by Dialgatrainer02** [comment]
i have pipewire pulse and i just updated it aswell to be sure

**Comment by Dialgatrainer02** [comment]
just looking through eww logs (trying to troubleshoot #84 )and i found this 

2023-09-21T13:42:37.004Z WARN  eww::script_var_handler > stderr of `music`: No player could handle this command
 2023-09-21T13:42:37.071Z WARN  eww::script_var_handler > stderr of `music`: (standard_in) 1: syntax error

**Comment by end-4** [comment]
I no longer support EWW-powered setups, so I'm closing this issue. The new widget system of choice is AGS, which makes things much easier and less hacky. If I implement this cava thing later, I'll probably find a better solution
