### ISSUE TITLE
[Issue] Mpd control window

### ISSUE THREAD

**Issue by EvanSunde** [end-4/dots-hyprland#566]
- Linux distro: Arch linux

---
## The issue

There is no Control window for mpd, but the control window of firefox and other music player opens just fine

```plain

(com.github.Aylur.ags:348121): Gjs-Console-WARNING **: 01:26:19.351: Error: can't assign "music player daemon" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/evan/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

</details>

**Comment by end-4** [comment]
it's an mpris widtget not mpd widget
there's mpd-mpris which sounds like something that would help

**Comment by EvanSunde** [comment]
I do have that installed
![image](https://github.com/end-4/dots-hyprland/assets/77535604/3d307cac-7fbe-4aad-8aee-3a9afa56063c)

**Comment by EvanSunde** [comment]
mpd control are working and music names are also shown but there is no control window when i click on it

**Comment by EvanSunde** [comment]
Tried using mpris2 and still no window control for mpd, but there was notification everytime next music played in mpris2.

also it seems 2 of the system monitor are hidden when mpris detect any music player

when no music playing
![image](https://github.com/end-4/dots-hyprland/assets/77535604/01c729fc-008e-473f-879d-3b799ea99d83)

when any music starts playing 
![image](https://github.com/end-4/dots-hyprland/assets/77535604/5876a1dd-020d-4ee1-ab6f-fd48651fbf0c)

**Comment by EvanSunde** [comment]
in .config/ags/modules/indicators/musiccontrol.js

`function isRealPlayer(player) {
    return (
        // Remove unecessary native buses from browsers if there's plasma integration
        !(hasPlasmaIntegration && player.busName.startsWith('org.mpris.MediaPlayer2.firefox')) &&
        !(hasPlasmaIntegration && player.busName.startsWith('org.mpris.MediaPlayer2.chromium')) &&
        // playerctld just copies other buses and we don't need duplicates
        !player.busName.startsWith('org.mpris.MediaPlayer2.playerctld')
        // &&
        // Non-instance mpd bus
        // !player.busName.endsWith('.mpd')
    );
}`

commenting 

`!player.busName.endsWith('.mpd')`

solved the problem

dont forget to remove the && before that.


for what this caused it seems when you run mpd-mpris from systemctl it will return as in dbus

`org.mpris.MediaPlayer2.mpd`

which caused it to not show it that why there was no window control popup

**Comment by end-4** [comment]
i can't remember why i had that there, but i guess i'll remove that

**Comment by end-4** [comment]
hmmm will it work if you change that line to this
```js
!(player.busName.endsWith('.mpd') && !player.busName.endsWith('MediaPlayer2.mpd'))
```

**Comment by EvanSunde** [comment]
yes it does work with that
