### ISSUE TITLE
Broder

### ISSUE THREAD

**Issue by AKA-Akhil** [end-4/dots-hyprland#569]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: 

---
The active and inactive borders dont change colors when edited.
Note that the border size works fine

[<details>
<summary>Click to expand</summary>](https://private-user-images.githubusercontent.com/145592032/335112605-f7c80861-83c2-453d-9e39-272592981c37.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2ODIsIm5iZiI6MTcxNzI2ODM4MiwicGF0aCI6Ii8xNDU1OTIwMzIvMzM1MTEyNjA1LWY3YzgwODYxLTgzYzItNDUzZC05ZTM5LTI3MjU5Mjk4MWMzNy5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxODU5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzBkNjMwYjFjMTZlMWU5NjUxMTQzYzRiNjgwNGJmMjU5ODMwYWE4ZWQ3YjU3MmU4OTkzYzZmZDAwMmVlZDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZT0T6CEMfLm3msA8ApEfEeYXyWC1f4KCJEs69znOS-I)

```plain
Paste your log here
```

</details>

**Comment by Makrennel** [comment]
It does change, the defaults just have the alpha values set very low for both active and inactive so it can be difficult to see them. You can change this in `~/.config/ags/scripts/templates/hypr/hyprland/colors.conf`

Change it to:

```
general {
    col.active_border = rgba({{ $onSurface }}EE)
    col.inactive_border = rgba({{ $outline }}77)
}
```

If you want to change the actual colors of the borders you can see the list of the variables and their associated generated color for your wallpaper in `~/.cache/ags/user/generated/material_colors.scss`.
