### ISSUE TITLE
Eww sidebar spacing on ultra-wide monitors (m3ww) - fix with material-symbols

### ISSUE THREAD

**Issue by MyLiege23** [end-4/dots-hyprland#57]
Hi, I've got interesting spacing issues with eww on a ultrawide monitor (3440x1440). Each side bar is very wide, and the left sidebar shows part of the volume mixer and/or the default panel when on the other. Also, the side panels weren't properly hiding off screen. I found `.hide-side-left` and `.hide-side-right` and changed their values from 40rem to 60rem which properly hides the bars. 

edit: I also realize that the desktop area doesn't shrink when the eww scales with font size. What I mean is that the eww bar will start to overlap the tops of open windows when scaled up with font size.

I'm at a loss for the sidebar width issue. 

It's hard to explain what I'm talking about so here's a video:
note: The watermark is from having to compress the video, so that's obviously not on my desktop.
https://github.com/end-4/dots-hyprland/assets/96258840/76711e3b-06d5-4ea8-868e-956e28e91380

I installed from EndeavourOS gnome, followed dependencies strictly, and built from the eww pull request with tray support

Awesome work on the ricing btw!

**Comment by end-4** [comment]
- for the sidebar, install material symbols rounded font
- about desktop space, you have to change the screen reserve in hyprland config
  - i'll try to make the bar reserve space on its own so this won't happen

**Comment by end-4** [comment]
aghhhhh reserved spaces are a freaking pain

**Comment by MyLiege23** [comment]
Thanks! I edited with that comment before searching the closed issues, but I saw that the reserved space has been brought up before, so sorry to pester.

Any idea what the issue is about the sidebar sizing? What eww files/lines configure the sizes for the sidebar? I've been poking around all the eww files and can't find what I'm looking for

**Comment by end-4** [comment]
- it's line 5 of ~/.config/eww/css/_sidebar.scss (whcih says `min-width: 34.091rem;`). I can't guarantee editing this will work, as other elements may affect the size
- also, have you installed Material Symbols Rounded?

**Comment by MyLiege23** [comment]
Wow, that was an unexpected fix. Yes, the font also worked to fix the spacing issue. For everyone reading this, I used `yay -S ttf-material-symbols-git`

Maybe add this to the dependencies list?

**Comment by end-4** [comment]
good idea

**Comment by end-4** [comment]
done
i also added lexend-fonts-git
so that's it right?

**Comment by MyLiege23** [comment]
For this issue, yes! Thanks! I just installed lexend-fonts-git, what's it used for? I'm good with closing. :)

**Comment by end-4** [comment]
lexend is the main font for the widgets
run `fc-cache -fv` then restart eww and you'll see

**Comment by MyLiege23** [comment]
This looks niiiice. Good job, thank you!
