### ISSUE TITLE
[Issue] Substitutions in user_config broken

### ISSUE THREAD

**Issue by myryk31415** [end-4/dots-hyprland#572]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Opensuse Tumbleweed

---
## The issue

Just tried to substitute an app icon and it gave me a wrong config notification. There was a check added a week, ig that broke substitutions. It looks for the specific app name as option in the user_config template, doesn't find it and complains.

**Comment by myryk31415** [comment]
* a week ago

**Comment by myryk31415** [comment]
Issue at .config/ags/modules/.configuration/user_options.js:198

**Comment by end-4** [comment]
send your `~/.config/ags/user_options.js`
and give full log pls
