### ISSUE TITLE
apps dont have icons

### ISSUE THREAD

**Issue by vnuxa** [end-4/dots-hyprland#59]
im using the novelknock branch and all the apps dont have icons (they use the default icon on the search bar). ive went in to the entries.txt and all of the icon data is just empty.

i might be missing a dependency i don't know how to check though

**Comment by end-4** [comment]
## Icons
- make sure you have `geticons` installed and have the icon pack installed in `/usr/share/icons` (not your local icons folder)
## No apps shown
- what does `cd ~/.config/eww && scripts/overview` say?

**Comment by vnuxa** [comment]
thanks the apps now have icons in the search bar but that didnt fix the second issue,

the `cd ~/.config/eww && scripts/overview` says this

`[[[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"1","workspace":{"id":1,"name":"1"}},{"address":"0x5641b57938a0","at":[1927,62],"class":"floorp","icon":"/usr/share/icons/hicolor/512x512/apps/floorp.png","size":[1907,1011],"title":"apps dont have icons · Issue #59 · end-4/dots-hyprland — Ablaze Floorp","workspace":{"id":1,"name":"1"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"2","workspace":{"id":2,"name":"2"}},{"address":"0x5641b52cde90","at":[1927,62],"class":"discord","icon":"/usr/share/icons/hicolor/256x256/apps/discord.png","size":[1907,1011],"title":"Friends - Discord","workspace":{"id":2,"name":"2"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"3","workspace":{"id":3,"name":"3"}},{"address":"0x5641b52cafd0","at":[1927,62],"class":"foot","icon":"/usr/share/icons/hicolor/48x48/apps/foot.png","size":[1907,1011],"title":"vnuxa: cd ~/.config/eww && scripts/overview - cd","workspace":{"id":3,"name":"3"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"4","workspace":{"id":4,"name":"4"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"5","workspace":{"id":5,"name":"5"}}]],[[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"6","workspace":{"id":6,"name":"6"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"7","workspace":{"id":7,"name":"7"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"8","workspace":{"id":8,"name":"8"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"9","workspace":{"id":9,"name":"9"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"10","workspace":{"id":10,"name":"10"}},{"address":"0x5641b5170690","at":[2830,490],"class":"xwaylandvideobridge","icon":"/usr/share/icons/hicolor/scalable/apps/xwaylandvideobridge.svg","size":[100,100],"title":"Wayland to X Recording bridge — Xwayland Video Bridge","workspace":{"id":10,"name":"10"}}]]]`

**Comment by vnuxa** [comment]
also dont know if this will help but here are the eww logs
`    ┌─ ./modules/system.yuck:105:30
    │
105 │             :style "color: ${battery.color}; background-color: ${battery.bgcolor};"
    │                              ───────


 2023-08-22T16:30:21.514Z WARN  eww::script_var_handler > stderr of `awin`: scripts/activewin: line 9: gojq: command not found
 2023-08-22T16:30:21.515Z WARN  eww::script_var_handler > stderr of `awin`: scripts/activewin: line 9: gojq: command not found
 2023-08-22T16:30:22.596Z WARN  eww::script_var_handler > stderr of `awin`: scripts/activewin: line 9: gojq: command not found
 2023-08-22T16:30:22.604Z WARN  eww::script_var_handler > stderr of `awin`: scripts/activewin: line 9: gojq: command not found`

**Comment by end-4** [comment]
install gojq

**Comment by vnuxa** [comment]
yes i have and gojq when i run the same line in console it works perfectly fine

**Comment by vnuxa** [comment]
is overview supposed to work on novelknock? if it is supposed to work well overview errors
`cd ~/.config/eww && scripts/overview`

failed to open window `overview`

Caused by:
    No window named 'overview' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.

**Comment by end-4** [comment]
nope
due to laziness-related reasons, in novelknock branch, that thing is called `powerview` instead of `overview`

**Comment by vnuxa** [comment]
alright but i find it weird that it works with only xwaylandvideobridge for me

**Comment by end-4** [comment]
does the thing work when you don't have that window?

**Comment by vnuxa** [comment]
mo like if i screenshared previously on discord and then opened the powerview the only application i would be able to see is xwaylandvideobridge and nothing else

**Comment by vnuxa** [comment]
after further testing it appears to be an issue with the workspaces windows margins
when i would make any application floating and would scale it over the left side it would become visible within the powerview as seen here
https://media.discordapp.net/attachments/769923541818671124/1147512025648476210/image.png?width=1430&height=329

**Comment by end-4** [comment]
"scale" could be the keyword we're looking for here
mess with the variables `RES_WIDTH`, `RES_HEIGHT`, `OVERVIEW_SCALE` in `~/.config/eww/variables.yuck` and see if it works

**Comment by vnuxa** [comment]
fixed it by tweaking the margin-left and margin-right formulas
`margin-left: ${round( ((ws-window.at[0]) * OVERVIEW_SCALE) - (RES_WIDTH * OVERVIEW_SCALE), 0)}px;`
`margin-right: -${round((((ws-window.at[0]) + ws-window.size[0]) * OVERVIEW_SCALE) - (RES_WIDTH * OVERVIEW_SCALE),0)}px;`
