### ISSUE TITLE
Clicking the Virtual keyboard keys doesn't work

### ISSUE THREAD

**Issue by Biaogo** [end-4/dots-hyprland#592]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: 
artixlinux
---
## The issue

Cannot enter content into the text box when clicking the on-screen keyboard

**Comment by end-4** [comment]
do you have ydotool installed?
also give logs when running `pkill ags; ags` and pressing those keys

**Comment by end-4** [comment]
nothing seems relevant there...
if you run `ydotool key 22:1 22:0 17:1 17:0 22:1 22:0` in the terminal, does it type in "uwu"?
![image](https://github.com/end-4/dots-hyprland/assets/97237370/5cd99848-7e36-47ab-8731-7aadf16b5b5c)
