### ISSUE TITLE
[Issue]ags overview window and cheatsheet not spawning properly

### ISSUE THREAD

**Issue by Kalidude69** [end-4/dots-hyprland#596]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Cachy os 

---
## The issue
**Error report for AGS overview and cheatsheet windows not spawning properly**

**Description:**

When attempting to spawn the overview or cheatsheet windows in AGS, the windows appear for a brief moment (half a second) and then disappear. This issue persists even after reloading AGS and Hyprland, and no error logs are generated in the terminal.

**Troubleshooting steps taken:**

- Verified that AGS and Hyprland are running properly...

<details>

**Possible causes:**

- The windows may be spawning in the backend but not displaying on screen.

**Additional notes:**

- The issue persists even after restarting the computer.
- Even after relogging the same things happen.
- The issue affects both the overview and cheatsheet windows also same with sideleft.

<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

**Comment by end-4** [comment]
in terminal run `pkill ags; ags` -> paste logs here

**Comment by Kalidude69** [comment]
> pkill ags; ags

yess i knew about this but the problem is no logs are showing up other than this ```Gjs-Console-Message: 11:28:45.395: [LOG] Styles loaded```

**Comment by Kalidude69** [comment]
i am trying now even the wallpaper wont show up nor the overview window comes up or cheetsheat tried updating , cleaning cache still the problems exist

**Comment by Kalidude69** [comment]
pls address my issue developers.... @end-4 @clsty im stuck with this problems for days now ... i reinstalled my system and configured everything again i made sure all packages are installed ran the install script again....still now a new error(actually old) the wallpaper doesnt change...but the colour scheme does and the cheetsheet also stopped appearing.... i need it bcoz of the periodic table and binds....

**Comment by Kalidude69** [comment]
i fixed it myself jq was not installed seeing the output of switchwall.sh....now keybinds and everything work
