### ISSUE TITLE
Hypr config has disappeared in main branch

### ISSUE THREAD

**Issue by shahirsiraj** [end-4/dots-hyprland#6]
Hello, I can't seem to find the hypr config in the main branch anymore. Am i looking wrongly or is it gone for now?

**Comment by end-4** [comment]
Oops

ill fix it 2 or 3 hrs later when i can
for now you can use the hypr config in the summer branch

**Comment by end-4** [comment]
Solved
https://github.com/end-4/dots-hyprland/commit/0c2b84c69a8f691c77c9f45c4e0c90949839c332
let me know if there's any other issues, thanks!
