### ISSUE TITLE
[Feature request] Add xwayland screenshare support with xwaylandvideobridge

### ISSUE THREAD

**Issue by MyLiege23** [end-4/dots-hyprland#60]
This would be nice to have out of the box:
for apps like discord, you can screenshare by installing xwaylandvideobridge.

Then add `exec-once = xwaylandvideobridge` to execs.conf

and finally add this to hyprland.conf
```
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
```

source is from here: https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/

**Comment by end-4** [comment]
dotfiles are personal, and i don't need that, so no. 
i hope you understand

**Comment by MyLiege23** [comment]
I completely understand. Thanks for looking anyway.
