### ISSUE TITLE
切换线条模式有问题

### ISSUE THREAD

**Issue by 2445244810** [end-4/dots-hyprland#608]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: 

---
## The issue

<details>
<summary>Logs</summary>

```plain
Paste logs here
```

</details>

**Comment by clsty** [comment]
Please write in English and write details about the problem.

**Comment by end-4** [comment]
what is line mode

**Comment by clsty** [comment]
> what is line mode
> edit: bar?

To be honest, I also don't know what it exactly refers to.

Let's wait for one day or two, and if @2445244810 can't provide details in English, the issue should be closed, since we can't do anything useful about it.

**Comment by clsty** [comment]
Closing.
