### ISSUE TITLE
[Issue] Yapsy requierement

### ISSUE THREAD

**Issue by Legnatbird** [end-4/dots-hyprland#609]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: 
Arch
No AUR package found for python-yapsy

**Comment by Legnatbird** [comment]
Fixed using this:
git clone https://aur.archlinux.org/python-yapsy.git
And just makepkg -si

**Comment by Acourd** [comment]
Hi, this is what I see on the page: 404 - Page Not Found

Is it possible to obtain the file by some other means?
