### ISSUE TITLE
Wallpaper not loading at startup(m3ww)

### ISSUE THREAD

**Issue by MyLiege23** [end-4/dots-hyprland#61]
Wallpaper isn't loading at startup. Swww is starting fine, but the error is in the execs.config. 

by default, the line is:
`swww img $HOME/.config/eww/images/wallpaper --transition-step 230 --transition
-fps 60 --transition-type grow --transition-angle 30 --transition-duration 1 --t
ransition-pos "$cursorposx $cursorposy_inverted" &`

it needs to be adjusted because `$cursorposx` and `$cursorposy_inverted` are not system variables. 

I copied the lines from .config/eww/scripts/switchwall and now, I believe `swww img $HOME/.config/eww/images/wallpaper --transition-step 230 --transition
-fps 60 --transition-type grow --transition-angle 30 --transition-duration 1 --t
ransition-pos "$(hyprctl cursorpos -j | gojq '.x'), $(hyprctl cursorpos -j | goj
q '.y')" &` will load the wallpaper on start. The y position isn't inverted, but ya know, it'll load at least. :/

**Comment by end-4** [comment]
oh
i copied that from that switchwall script to execs lol

**Comment by MyLiege23** [comment]
Hahaha I figured as such, it makes sense! :) 

I just realized that my edits did not work in setting the wallpaper at boot. Perhaps the answer is to have `exec-once = swww init && ~/.config/eww/scripts/switchwall`. I'll check next reboot.

**Comment by end-4** [comment]
nah, just remove the transition post argument
