### ISSUE TITLE
Cannot share screen with illogical-inpulse XDG portal backend

### ISSUE THREAD

**Issue by ddbnl** [end-4/dots-hyprland#610]
I couldn't share screen on arch with 'teams-for-linux', and after much searching found out that uninstalling 'illogical-impulse-portal' instantly solved the issue.

Is this a known issue? Googling around there seem to be a lot of issues with screen share and Wayland, but other backends seemed to have solved this. This link for example lists backends and their screen share compatibility: (https://wiki.archlinux.org/title/XDG_Desktop_Portal).

It's solved for me now by removing the backend, but perhaps it's possible to fix the illogical-impulse portal? I don't know enough to provide the relevant logs, but if there's anything I can provide to help troubleshoot I can reinstall the portal and provide any output here if that helps.

Here is the one error I could capture from teams:

```
[9097:0613/145933.550076:ERROR:egl_dmabuf.cc(608)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH

[9097:0613/145933.550102:ERROR:shared_screencast_stream.cc(940)] Dropping DMA-BUF modifier: 72057594037927944 and trying to renegotiate stream parameters
```

**Comment by dattamlong** [comment]
I have the same problem as you, I cannot share my screen on Google Meet (Black screen), but I can use OBS for recording

**Comment by clsty** [comment]
"illogical-impulse portal" is just a "meta" package (i.e. a bundle of packages) and has no real content inside itself.

**Comment by ddbnl** [comment]
Apologies, turns out it was working only intermittently, making it seem as though the uninstall had helped when it was unrelated. I have found the solution and will share here, even though it's not related to the dot. That way anyone else similarly confused might find the solution:

```
sudo pacman -R teams-for-linux
git clone https://aur.archlinux.org/ms-teams-for-linux-bin.git
cd ms-teams-for-linux-bin
makepkg -si
```
Solution from: https://github.com/hyprwm/Hyprland/issues/2940
