### ISSUE TITLE
Language characters not working

### ISSUE THREAD

**Issue by Z3ZU** [end-4/dots-hyprland#611]
It's my first arch install, and I've managed to work out most of the issues I had by myself so far BUT

## The issue
I am having trouble getting polish signs to show up using ALT+ a/o/c/n/z/
I tried multiple ways of setting it up, based on arch wiki 

```
localectl
System Locale: LANG=en_US.UTF-8
    VC Keymap: pl2
   X11 Layout: pl
```

I have` Alternate Characters Key` set correctly to Right Alt
When I changed language and region to Polish in the same settings menu (top right corner). The language changes for some apps but I still cant type PL characters

I edited vconsole.conf
```
KEYMAP=pl2
XKBLAYOUT=pl
FONT_MAP=8859-2
```
to no avail

Also since I have gnome installed I tried
In GNOME Tweaks I set Keyboard & Mouse->Additional Layout Options -> Key to choose the 3rd level -> Right Alt.
Didn't work

These are the contents of my 00-keyboard.conf for X11
```
ection "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "pl"
EndSection
```
Any help or tips would be very appreciated, I'm lost at this point on what to do

I think I do get those character before entering Hyprland just without the font for it, they appear as squares, but when i enter Hyprland and try using Alt + any of those characters I get absolutely nothing

**Comment by end-4** [comment]
in `~/.config/hypr/hyprland/general.conf` edit this
```ini
kb_layout = us
```
to this
```ini
kb_layout = us,pl
```
then uncomment this line:
```ini
# kb_options = grp:win_space_toggle
```

If that works, cool. Else, try fcitx5

**Comment by Z3ZU** [comment]
> in `~/.config/hypr/hyprland/general.conf` edit this
> 
> ```ini
> kb_layout = us
> ```
> 
> to this
> 
> ```ini
> kb_layout = us,pl
> ```
> 
> then uncomment this line:
> 
> ```ini
> # kb_options = grp:win_space_toggle
> ```
> 
> If that works, cool. Else, try fcitx5

That did it, thank you!
