### ISSUE TITLE
color generation not working as intended

### ISSUE THREAD

**Issue by Kalidude69** [end-4/dots-hyprland#613]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Cachy os 

### Color generation issue after changing wallpaper

Detailed summary

The color generation feature is malfunctioning. **It generates  black and white shades for all wallpapers with COLOURFUL COLORSCHEMES**,regardless of their actual colors. This issue was not present before and started recently.

Additional details

 - Observed behavior:
     - Wallpapers are generating properly but the ags colours and the gtk theming in general dont work as expected..

 - Troubleshooting steps taken:
     - Checked all packages according to script all packages are there.
     - Wallpaper selection and every other related scripts are working but without color generation
     - cleared the cache and tried again still no success
 - Logs and screenshots:
     **LOGS**
_~/.config/ags/scripts/color_generation/switchcolor.sh_

```
undefined
[Gradience] INFO: Preset Material3_Generated applied successfully for Gtk 3 and Gtk 4 applications.
[Gradience] INFO: In order for changes to take full effect, you need to log out.
undefined
```
- Screenshots: 
![img](https://github.com/end-4/dots-hyprland/assets/112244509/a5950f17-93cd-45cc-947c-2ca6d5fdf734)

**Comment by Kalidude69** [comment]
@clsty @end-4 🙏

**Comment by xiw1ll** [comment]
I had a similar problem once, try checking if you have the `~/.config/ags/scss/_material.scss` file if you do, you should delete it as it interferes with the file generation.
If it doesn't help, then I suggest going through the `colorgen.sh` script and debug.

**Comment by end-4** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/97237370/11146ab1-4c3e-4ed3-bfad-d5468698150e)

**Comment by end-4** [comment]
> try checking if you have the ~/.config/ags/scss/_material.scss file if you do, you should delete it as it interferes with the file generation

no it's the default file and shouldn't be deleted

**Comment by Kalidude69** [comment]
> ![image](https://private-user-images.githubusercontent.com/97237370/340143280-11146ab1-4c3e-4ed3-bfad-d5468698150e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTUxMDYsIm5iZiI6MTcxOTE1NDgwNiwicGF0aCI6Ii85NzIzNzM3MC8zNDAxNDMyODAtMTExNDZhYjEtNGMzZS00ZWQzLWJmYWQtZDU0Njg2OTgxNTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE1MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZDJlM2U1ZTA5ZGYzMjI5ZGNkNzVkNGUwZThiMTRjMDU5NTcyNzI2MDgwZGI1YWRhMmIyYmJjNTkxOTQ0OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mLeATxYx4EKDQBHwAJSn-tx7VgYD3iynaCaNlUrMIY)

sure thanks!!!
