### ISSUE TITLE
[Feature] Custom AI API link and key

### ISSUE THREAD

**Issue by Biaogo** [end-4/dots-hyprland#622]
Is it possible to add a custom API proxy and key? Maybe there is but I didn't find it?

**Comment by end-4** [comment]
added the ability to do so in 793be4b2048c653b69ed4996d29b6b72cf9ab784  (i know it's a funny commit message, ignore it, i'm lazy to fix it)

see sidebar.ai.extraGptModels user option

**Comment by end-4** [comment]
added the ability to do so in 793be4b2048c653b69ed4996d29b6b72cf9ab784  (i know it's a funny commit message, ignore it, i'm lazy to fix it)

see sidebar.ai.extraGptModels user option
