### ISSUE TITLE
Top bar overlaps

### ISSUE THREAD

**Issue by loulou310** [end-4/dots-hyprland#63]
- **I have read the instructions** and I have a problem with branch: 
NovelKnock
## The issue
Hey, I think I have a haunted system. The top bar in the NovelKnock branch is rendering over the windows. I run EndeavourOS freshly installed yesterday (with Gnome base, copied your work). Also tried put `:exclusive "true"` but that push the sidebars down too. Don't have any logs tho. And I still miss some icons but that's minor inconvenience. 

Might be a simple fix but my stupid ass can't figure what it is

## Additional Screenshot
![image](https://github.com/end-4/dots-hyprland/assets/57544287/5fa8750b-78ce-4577-8777-c63e767a3c83)

**Comment by loulou310** [comment]
## swww
Also I swww is not working for me either but by running the command directly I see why it doesn't work:
```
~$ swww img ~/.config/eww/images/wallpaper/wallpaper --transition-step 230 --transition-fps 60 --transition-type grow --transition-angle 30 --transition-duration 1 --transition-pos "$cursorposx, $cursorposy_inverted"
error: invalid value ', ' for '--transition-pos <TRANSITION_POS>': Invalid x coord: 

For more information, try '--help'.
```

**Comment by end-4** [comment]
## top bar over windows
- edit line 10 of `~/.config/hypr/hyprland.conf` to change the reserved space (see [this hyprland wiki section](http://wiki.hyprland.org/Configuring/Monitors/#custom-reserved-area))
## swww 
- just remove that transition pos thing. i'll fix that in a moment

**Comment by loulou310** [comment]
Resolved by adding `monitor=eDP-1,addreserved,50,0,0,0` in hyprland.conf
