### ISSUE TITLE
[Issue] AGS fails to load: syntax error from keybinds.js in the cheatsheet module 

### ISSUE THREAD

**Issue by daviiiL** [end-4/dots-hyprland#632]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: CachyOS

---
## The issue
AGS fails to load after reboot and system upgrade. Everything worked fine before ``` pacman -Syu ``` after a fresh install. Everything works if the cheat sheet module is not loaded (as tested when I commented out lines related to the cheatsheet module in config.js. I have not modified anything else. 

Let me know if more information is needed.
<details>
<summary>Logs</summary>

```plain
(com.github.Aylur.ags:8022): Gjs-WARNING **: 11:31:38.640: JS ERROR: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data @ file:///home/byleth/.config/ags/modules/cheatsheet/keybinds.js:21:17
getKeybindList@file:///home/byleth/.config/ags/modules/cheatsheet/keybinds.js:21:17
@file:///home/byleth/.config/ags/modules/cheatsheet/keybinds.js:23:21
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

</details>

**Comment by daviiiL** [comment]
Sorry found the issue myself and its related to my python setup... Issue closed

**Comment by Username696969696969** [comment]
Please for the lord's sake tell people how you fixed it if already did, don't _just_ close the issue without an extra word.

**Comment by clsty** [comment]
> Please for the lord's sake tell people how you fixed it if already did, don't _just_ close the issue without an extra word.

Please `git pull` to get the latest version and then rerun `install.sh`.

**Comment by daviiiL** [comment]
> Please for the lord's sake tell people how you fixed it if already did, don't _just_ close the issue without an extra word.

Your setup might be different than mine. In my case, it was a python environment issue since I had adsf to globally manage my dev environments. But I have since moved on to write my own Astal setup and now running NixOS.
