### ISSUE TITLE
[Tty]

### ISSUE THREAD

**Issue by tlg-tg** [end-4/dots-hyprland#635]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: arch vanilla

I used the script on vanilla arch right after installing without any de or wm. At first it threw an error for installing hyprutils etc
Than I ised paru to install it and still after rebooting there was no display except the tty/ default vanilla arch wothout desktop.

Can anyone help?

**Comment by end-4** [comment]
error installing hyprutils, you installed hyprutils, but then have you continued installing whatever that depends on that thing?
also, the script doesn't touch greeters/display managers. if you don't have one you'll have to set up yourself of just login and manually run `Hyprland`

**Comment by tlg-tg** [comment]
So I tried to run hyprland but there was an error hyprland_instance_signature not set

**Comment by tlg-tg** [comment]
Are you using swaylock as a greeter?

**Comment by end-4** [comment]
> Are you using swaylock as a greeter?

no, it's a lock screen
plus it isn't cool as hyprlock
