### ISSUE TITLE
Sub-windows are centered to the parent window, not the screen.

### ISSUE THREAD

**Issue by aliqut** [end-4/dots-hyprland#636]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: OpenSUSE Tumbleweed

---
## The issue

If a window is not maximised, and opens a sub-window, it is centered to the window itself, not the screen.

For example, if you have four windows open, with an internet browser in one of the corners, and try to upload a file to a website, the file explorer is centered to the internet browser window, and gets cut off by the screen's edges. Having to set the window to floating and drag it into the screen's boundaries is annoying.

 This issue is not exclusive to the file explorer, it happens with any sub-window.

Not sure what logs to check for this.
<details>
<summary>Logs</summary>

```plain
Paste logs here
```

</details>

**Comment by end-4** [comment]
thanks for the suggestion
fixed
kind of

**Comment by aliqut** [comment]
Didn't work for me, but this does:

```# Dialogs
windowrule=center ,title:^(Open File)(.*)$
windowrule=center ,title:^(Select a File)(.*)$
windowrule=center ,title:^(Choose wallpaper)(.*)$
windowrule=center ,title:^(Open Folder)(.*)$
windowrule=center ,title:^(Save As)(.*)$
windowrule=center ,title:^(Library)(.*)$
windowrule=center ,title:^(File Upload)(.*)$```

**Comment by end-4** [comment]
that would require so many lines
i realized my solution should be a windowrulev2 rule, my bad

**Comment by end-4** [comment]
then i realized if i "fix" my solution, xwayland context menus would be all centered
so i'm gonna use your solution
