### ISSUE TITLE
New apps Not show in launcher[Issue]

### ISSUE THREAD

**Issue by me6a** [end-4/dots-hyprland#642]
Hey i realized new app wont show in app launcher i try ctrl+super+r and app that i installed via pacman showned but i cant find a solution for aur apps . is there any way to add aur apps into the launcher ?

**Comment by end-4** [comment]
there are apps that come with an app entry, and others don't
run `fuzzel` (or any other normal launcher that ignores hidden entries) to see if it's there
if not, you have to create a `.desktop` file for it yourself, or just launch through terminal

**Comment by iUnstable0** [comment]
this is a real ossue, it seems like on mine also new app entries are not showing, i have to killall ags and relaunch it for new installed apps to show or just re login or reboot

**Comment by end-4** [comment]
right, if a *newly installed* app has a desktop entry you gotta restart ags for it to be shown
this is an ags problem

**Comment by NotAF0e** [comment]
Also some apps like settings don't show up in default launcher

**Comment by end-4** [comment]
because settings apps are usually DE-specific and they not showing up in other environments is intended. not everything works
if you wanna open them anyway, use another launcher that doesn't bother hiding them (ctrl+super+/ for `anyrun` in my dotfiles)

**Comment by NotAF0e** [comment]
Yeah ok thanks for the note
