### ISSUE TITLE
[Issue] ags not starting

### ISSUE THREAD

**Issue by paindespik** [end-4/dots-hyprland#646]
ags is not starting with the folowing error 
![image](https://github.com/end-4/dots-hyprland/assets/18008490/970148c7-cdb0-42a1-9d88-430c1779449a)

I have updated with the install script of the up to date main branch. Had a problem with the installation of hyprland-git, wich while installing/updating did not find  the include/wlr folder.
so i decided to compile hyprland from the sources with no problem, relaunched your installation script with no error this time, but I still have the ags error

**Comment by end-4** [comment]
run `LANG=c ags` so errors appear in english

**Comment by end-4** [comment]
not entirely sure but it seems to be a hyprland socket problem

**Comment by paindespik** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/18008490/e272d5f5-e7a8-480c-94c3-6a1ab5e1ad76)

**Comment by paindespik** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/18008490/aae56aa8-1319-49c8-969c-c461e5ba7f2f)

**Comment by paindespik** [comment]
i did not overwrite the ags config

**Comment by end-4** [comment]
is this resolved?
i just rebuilt hyprland and ags from source and can't reproduce this. ags works fine.

**Comment by paindespik** [comment]
> is this resolved?
> i just rebuilt hyprland and ags from source and can't reproduce this. ags works fine.

Yes the problem came from my fork of ags config. When overwritten, the problem was gone. No Idea what caused it
