### ISSUE TITLE
Weather and Battery on status bar

### ISSUE THREAD

**Issue by notthansen** [end-4/dots-hyprland#651]
### Discussed in https://github.com/end-4/dots-hyprland/discussions/650

<div type='discussions-op-text'>

<sup>Originally posted by **notthansen** June 26, 2024</sup>
I recently realized that people using pcs get a weather info on the status bar instead of the battery status on the status bar. How do I enable both on a laptop</div>

**Comment by end-4** [comment]
not done easily with a config option
weather doesn't even work properly at all times or when you use a vpn. it's just a fallback for devices without battery

**Comment by notthansen** [comment]
Okay I appreciate

**Comment by fruitsaladchan** [comment]
@notthansen you can get something like this 

![swappy-20240831-153308](https://github.com/user-attachments/assets/2f3d9205-3ee4-4e3a-b382-069f692770c3)

by replacing the battery module in ~/.config/ags/modules/bar/normal/system.js

with this 
https://gist.github.com/fruitsaladchan/a227e71098ef5914795061c73ed33866
