### ISSUE TITLE
Browser Notifications not working well

### ISSUE THREAD

**Issue by notthansen** [end-4/dots-hyprland#652]
![Pasted image](https://github.com/end-4/dots-hyprland/assets/75609068/f9d121e7-cc8c-4804-8950-143528e4fb0a)

Browser notifications are not showing the respective web app icons and instead of a preview it shows html ...href and stuff.Am using chromium and I have also tried google chrome.Its the same for every notification from youtube,whatsapp web, insta just everything. 
What notification daemon is being used

Has anyone come across this

**Comment by aliqut** [comment]
https://github.com/end-4/dots-hyprland/issues/288#issuecomment-1967583944

**Comment by notthansen** [comment]
Earlier today I realized that this issue was only happening with chromium and google chrome both latest versions from pacman . Firefox notifications work just fine. I'll try to find the problem and close this issue

**Comment by end-4** [comment]
do firefox notifications have links?

**Comment by notthansen** [comment]
> do firefox notifications have links with `<a href=...>`?

No they dont

**Comment by end-4** [comment]
i can't do anything about chrome using html and not pango
i'm not gonna bother loading webviews on notifications
