### ISSUE TITLE
Error setting value <4> for field <decoration:blur:passes>: No such field

### ISSUE THREAD

**Issue by nanashi-1** [end-4/dots-hyprland#66]
- **I have read the instructions** and I have a problem with branch: hybrid
---

OS: Fedora 38

## The Issue

![20230831_172754](https://github.com/end-4/dots-hyprland/assets/54083498/6006004b-ad0b-4f2e-a23b-9a13d2dbb52d)

**Comment by end-4** [comment]
make sure you use Hyprland 0.28.0 or newer
you should either find a copr with a new enough version or compile from source

**Comment by end-4** [comment]
or if you can't, revert that category to the old format as described here
http://wiki.hyprland.org/0.27.2/Configuring/Variables/#decoration

**Comment by end-4** [comment]
basically remove that `blur {` and '}' subcategory thing, add `blur_` to each of the blur-related options and remove noise/contrast/brightness values

**Comment by nanashi-1** [comment]
I installed `hyprland 0.29.0-1.f38`, the error doesn't show up anymore but it won't read the config anymore too.

**Comment by end-4** [comment]
> won't read the config anymore  

what makes you think it doesn't?

**Comment by nanashi-1** [comment]
Cause I get this, 

![20230831_180311](https://github.com/end-4/dots-hyprland/assets/54083498/84f6478d-2b14-42d7-becd-4dcfbc23bc04)

**Comment by end-4** [comment]
have you installed all the dependencies?
the command provided for fedora is incomplete and you'll still have to do some dependency hunting based on the arch package names

**Comment by nanashi-1** [comment]
> have you installed all the dependencies? the command provided for fedora is incomplete and you'll still have to do some dependency hunting based on the arch package names would appreciate it if you could do it and tell me what the names for fedora are

it seems that I haven't. I'll try that

**Comment by nanashi-1** [comment]
Seems too troublesome. I switched to arch.
