### ISSUE TITLE
[Issue] Booting up x11 plasma shows black screen with cursor

### ISSUE THREAD

**Issue by horyzen1** [end-4/dots-hyprland#662]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Arch Linux

---
## The issue

Black screen with cursor when loading up KDE Plasma X11. How can I add Hyprland to start up when booting up x11?

<details>
<summary>Logs</summary>

```plain
Paste logs here
```

</details>

**Comment by end-4** [comment]
~~wtf~~ hyprland is a wayland compositor. it's not an x11 window manager
