### ISSUE TITLE
Cava config not working ?

### ISSUE THREAD

**Issue by Clemorange22** [end-4/dots-hyprland#67]
- **I have read the instructions** and I have a problem with branch: m3ww
---
## The issue
![image](https://github.com/end-4/dots-hyprland/assets/62897760/a21323e8-a5ac-4f96-8e5b-24bf79dacf71)

- cava doesn't take all the space available, and the bars are thin compared to the showcase video
- first of all, is that behavior normal ?

**Comment by end-4** [comment]
i guess it's because i increased the margins
just edit line 21 of `~/.config/eww/css/_visualizer.scss` (decrease margins) if you would like thicker bars

**Comment by end-4** [comment]
also, cava does take all the space available, it's just that your sound doesn't take all the space available (how do i accurately describe this lol) 
![image](https://github.com/end-4/dots-hyprland/assets/97237370/d36aab90-3e5f-4f3e-8ab1-ae7555e4682f)
notice these tiny columns?

**Comment by Clemorange22** [comment]
> also, cava does take all the space available, it's just that your sound doesn't take all the space available (how do i accurately describe this lol) ![image](https://user-images.githubusercontent.com/97237370/264836199-d36aab90-3e5f-4f3e-8ab1-ae7555e4682f.png) notice these tiny columns?

i notice them but i'm talking about the bottom right corner (sorry i didn't precised earlier)

**Comment by Clemorange22** [comment]
decreased margin to 0.6 from 0.7 and it's  much better 
![image](https://github.com/end-4/dots-hyprland/assets/62897760/3ba69e83-da2c-4952-8d75-b06267f158fb)

you can notice there are bars even on the right side
