### ISSUE TITLE
Eww bar size

### ISSUE THREAD

**Issue by MaulanaMalikS** [end-4/dots-hyprland#68]
- **I have read the instructions** and I have a problem with branch: novelknock
---
## Eww bar size
Hello!
I am using the novelknock branch.
Is there a setting to adjust the bar height?
Some of the bars don't fit my screen.
### Top Bar
![image](https://github.com/end-4/dots-hyprland/assets/67823073/5bd3b24b-f27c-443e-a5fb-7203676b1d14)
### Side left Bar
![image](https://github.com/end-4/dots-hyprland/assets/67823073/9546472c-17c0-4401-a6ce-afe0489dbe2b)
### Side left Bar 2
![image](https://github.com/end-4/dots-hyprland/assets/67823073/9de1d378-2096-4e13-b7c0-72d2662a4acf)

The side right bar fits perfectly,
and for powerview and bottomsheet, I can find the settings.
Thank you!

**Comment by end-4** [comment]
Hi!
## bar size
- you can't change the bar size as it's hard-coded in pixels, but you can change the reserved space. i'll fix that, but for now change that line 10 of hyprland.conf. (see [this hyprland wiki section](http://wiki.hyprland.org/Configuring/Monitors/#custom-reserved-area))
## sidebars
- if it doesn't fit your screen then ouch. there's no quick solution
  - you can change *every single* size property in the stylesheets, but that's obviously tedious
## the recommended solution
- use the m3ww branch instead (i know this kind of "use X instead" solution sucks, but it's the only way if you don't wanna do a lot of work)
  - with this, you can scale the widgets by changing font size

**Comment by end-4** [comment]
you did change that addreserved thing right? i'm sure in that branch the reserved space is 56

**Comment by MaulanaMalikS** [comment]
> * use the m3ww branch instead (i know this kind of "use X instead" solution sucks, but it's the only way if you don't wanna do a lot of work)

I already checked the m3ww branch, and the only thing preventing me from trying the branch is the requirement that says "eww with systray needed." From what I can see, the PR still has a lot of changes.

But maybe I'll give it a try.
Thanks for the reply!

**Comment by MaulanaMalikS** [comment]
> you did change that addreserved thing right? i'm sure in that branch the reserved space is 56

Yes, I changed the addreserved setting. I tried to make the bar smaller, but I couldn't find a way.

I already reverted the value back. Thanks!

**Comment by end-4** [comment]
i find that PR pretty stable (at least one month ago). it could be that i rarely actually use the tray, so i'm not sure.

if you don't need the tray or are too lazy to build that thing, you can always comment out line 5 of `.config/eww/modules/status.yuck` (the line with systray widget)

**Comment by MaulanaMalikS** [comment]
> * use the m3ww branch instead

I have been messing around with `m3ww` branch, and it fits my screen! 
However, based on this issue, do you have any plans to introduce customizable bar sizes in this `novelknock` branch?

**Comment by end-4** [comment]
No plans. It's too much work.
