### ISSUE TITLE
[Issue](gradience)gtk4 theming doesnt work ...all other themes work fine

### ISSUE THREAD

**Issue by Kalidude69** [end-4/dots-hyprland#681]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Athena os

---
###  gradience throws this error even though gtk4 and gtk.css exists theming doesnt work on gtk4 and gtk3

<details>
<summary>Logs</summary>

```plain
[Gradience] WARNING: gtk.css file not found in /home/deb/.config/gtk-4.0/gtk.css. Generating new stylesheet.
Traceback (most recent call last):
  File "/usr/bin/gradience-cli", line 557, in <module>
    cli = CLI()
          ^^^^^
  File "/usr/bin/gradience-cli", line 141, in __init__
    self.__parse_args()
  File "/usr/bin/gradience-cli", line 165, in __parse_args
    self.apply_preset(args)
  File "/usr/bin/gradience-cli", line 309, in apply_preset
    PresetUtils().apply_preset("gtk4", preset)
  File "/usr/lib/python3.12/site-packages/gradience/backend/theming/preset.py", line 136, in apply_preset
    with open(gtk_css_path, "w", encoding="utf-8") as css_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deb/.config/gtk-4.0/gtk.css'
```

</details>nothing has been tampered with....

**Comment by end-4** [comment]
I'd appreciate it if you could at least say why you closed the issue

**Comment by Kalidude69** [comment]
> I'd appreciate it if you could at least say why you closed the issue

i fixed it by the time i waited for the issue only some errors on permission of gtk4 directory nothing else ......that is why closed the issue never mind....
