### ISSUE TITLE
[Issue] Failed to install `illogical-impulse-pymyc-aur` because of `gradience-git`

### ISSUE THREAD

**Issue by wuhang2003** [end-4/dots-hyprland#687]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: CachyOS

---
## The issue

Because `gradience-git` was deleted in aur. `illogical-impulse-pymyc-aur` install failed.
Maybe need change `gradience-git` to `gradience`.

<details>
<summary>Logs</summary>

```plain
[/home/laoren/.cache/dots-hyprland/install.sh]: Command "yay -S --asdeps python-materialyoucolor-git gradience-git python-libsass python-material-color-utilities" finished.
==> Making package: illogical-impulse-pymyc-aur 1.0-1 (2024-07-10 Wed. 23:21:02)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: gradience-git
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> gradience-git
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
[/home/laoren/.cache/dots-hyprland/install.sh]: Command "makepkg -si --noconfirm" has failed.
You may need to resolve the problem manually BEFORE repeating this command.
  r = Repeat this command (DEFAULT)
  e = Exit now
  i = Ignore this error and continue (your setup might not work correctly)
```

</details>

**Comment by krister-dahl** [comment]
I had the same issue. Solved it with:

git clone https://aur.archlinux.org/gradience-git.git
Then makepkg -si

**Comment by unhelpfulninja** [comment]
Still having that issue 😕 it's crazy how it's not been fixed or given any attention..

**Comment by kainzilla** [comment]
> Still having that issue 😕 it's crazy how it's not been fixed or given any attention..

These are someone's personal configuration and it's only been a few days lol, gotta chill

Plus this is something you can update yourself easily - after you have cloned the `dots-hyprland` repo, the file with the package name is located in `arch-packages/illogical-impulse-pymyc-aur/PKGBUILD`, and you can change `gradience-git` to `gradience`.

This command should help make it easy - try running this command **while you are in the directory for `dots-hyprland`**:

```bash
sed -i s/gradience-git/gradience/g arch-packages/illogical-impulse-pymyc-aur/PKGBUILD
```

**Comment by unhelpfulninja** [comment]
> > Still having that issue 😕 it's crazy how it's not been fixed or given any attention..
> 
> These are someone's personal configuration and it's only been a few days lol, gotta chill
> 
> Plus this is something you can update yourself easily - after you have cloned the `dots-hyprland` repo, the file with the package name is located in `arch-packages/illogical-impulse-pymyc-aur/PKGBUILD`, and you can change `gradience-git` to `gradience`.
> 
> This command should help make it easy - try running this command **while you are in the directory for `dots-hyprland`**:
> 
> ```shell
> sed -i s/gradience-git/gradience/g arch-packages/illogical-impulse-pymyc-aur/PKGBUILD
> ```

Yeah ofc we can fix this script easily but void should have done it and checked everything before putting it on the internet tho... Hyprland having issues and everything else is one thing but script having stuff like this is not cool at all yes ofc we can edit but like what's the point

**Comment by kainzilla** [comment]
> Yeah ofc we can fix this script easily but void should have done it and checked everything before putting it on the internet tho... Hyprland having issues and everything else is one thing but script having stuff like this is not cool at all yes ofc we can edit but like what's the point

When End-4 committed, it _worked_. You do understand that someone that End-4 has no control over archived their `gradience` project after End-4 wrote that code, right? You're complaining about them having put up functional code that broke when someone else changed something, and having not updated it _fast enough for you_. The entitlement is amazing

**Comment by unhelpfulninja** [comment]
> > Yeah ofc we can fix this script easily but void should have done it and checked everything before putting it on the internet tho... Hyprland having issues and everything else is one thing but script having stuff like this is not cool at all yes ofc we can edit but like what's the point
> 
> When End-4 committed, it _worked_. You do understand that someone that End-4 has no control over archived their `gradience` project after End-4 wrote that code, right? You're complaining about them having put up functional code that broke when someone else changed something, and having not updated it _fast enough for you_. The entitlement is amazing

It's been 4 days since the issue opened, come on what about entitlement huh? I think it's reasonable to ask for a lil fixey fix tbh

**Comment by a3ro-dev** [comment]
I have the same issue, trying some fixes from here will lyk if it works at the end

**Comment by JustMadeline** [comment]
> I had the same issue. Solved it with:
> 
> git clone https://aur.archlinux.org/gradience-git.git Then makepkg -si

Tried this but apparently some of the dependencies were removed as well

**Comment by blest333** [comment]
> > > Yeah ofc we can fix this script easily but void should have done it and checked everything before putting it on the internet tho... Hyprland having issues and everything else is one thing but script having stuff like this is not cool at all yes ofc we can edit but like what's the point
> > 
> > 
> > When End-4 committed, it _worked_. You do understand that someone that End-4 has no control over archived their `gradience` project after End-4 wrote that code, right? You're complaining about them having put up functional code that broke when someone else changed something, and having not updated it _fast enough for you_. The entitlement is amazing
> 
> It's been 4 days since the issue opened, come on what about entitlement huh? I think it's reasonable to ask for a lil fixey fix tbh

frankly, absolutely terrible bait

**Comment by unhelpfulninja** [comment]
Come again

**Comment by mrsfigatto** [comment]
you can fix with yay -S gradience

**Comment by wuhang2003** [comment]
Now the issue is fix in [this commit](https://github.com/end-4/dots-hyprland/commit/e241366016d7dbe7dd04d0245f1e51e0876461ea) , I will close this issue.
