### ISSUE TITLE
Some icons missing

### ISSUE THREAD

**Issue by nanashi-1** [end-4/dots-hyprland#69]
Everything seems working fine but some icons are missing.

![no ic](https://github.com/end-4/dots-hyprland/assets/54083498/02a4d6bb-3cda-478b-9590-23692f4d5d81)
![no ic 2](https://github.com/end-4/dots-hyprland/assets/54083498/ec71fb13-3286-4e1c-97cd-eff23927c17c)

I suspect this is some font issue but I don't know how to handle it.

**Comment by end-4** [comment]
The Torus font should provide it
I'm not quite sure why it isn't working...

**Comment by nanashi-1** [comment]
After:
![after](https://github.com/end-4/dots-hyprland/assets/54083498/fe522ca9-b9fc-4b75-9f43-f002274e3efc)
![but](https://github.com/end-4/dots-hyprland/assets/54083498/20aba6fe-9320-40ed-b31e-661af46994e0)

There are some issues but this is a lot better than before.

**Comment by end-4** [comment]
hmm
- that icon isn't working because i bundled an outdated version of material symbols. you should remove the material symbols from your fonts folder and install `ttf-material-symbols-git`
- those empty pills on the music window are time indicators. it looks like that because you don't have music playing

**Comment by end-4** [comment]
oh and the top left corner of the music window looks weird because JetBrainsMono Nerd Font is needed

**Comment by nanashi-1** [comment]
> hmm
> 
> * that icon isn't working because i bundled an outdated version of material symbols. you should remove the material symbols from your fonts folder and install `ttf-material-symbols-git`
> * those empty pills on the music window are time indicators. it looks like that because you don't have music playing

> oh and the top left corner of the music window looks weird because JetBrainsMono Nerd Font is needed

Already had them installed, I just needed a restart. (silly me)
