### ISSUE TITLE
How to edit foot appearance?

### ISSUE THREAD

**Issue by Alanzcc** [end-4/dots-hyprland#694]
I noticed foot's appearance configurations are overriden by AGS and can't find a way to make the terminal's background semitransparent without compromising the text opacity too with windowrule. Does anyone know the solution?

**Comment by Alanzcc** [comment]
Answer: I found a especific variable for this at applycolor.sh and after restart my notebook it worked.

**Comment by crastiflette** [comment]
Hello can you tell me which file and what you change to have the semitransparent terminal ?
