### ISSUE TITLE
[Issue] AGS Color

### ISSUE THREAD

**Issue by nullptroma** [end-4/dots-hyprland#704]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro:  void linux

---
## The issue
I just discovered that when changing the wallpaper, the AGS theme does not change. I found that the colors for it are set in `~/.config/ags/scss/_material.scss`. But there is no code in the entire .config/ags directory that updates this file. The newly generated colors remain in `~/.local/state/ags/scss`. As a temporary solution, I used `ln -rc ~/.local/state/ags/scss/_material.css ~/.config/ags/scss/`, it helped.

**Comment by nullptroma** [comment]
I also found that the new colors are not applied on firefox, or is there something else missing?

**Comment by nullptroma** [comment]
![image](https://github.com/user-attachments/assets/706bfbba-ff5e-4f9c-9524-474ed99fc543)
And one more thing

**Comment by nullptroma** [comment]
dconf-editor: 
![image](https://github.com/user-attachments/assets/dac16b89-3d77-454e-aabf-b2d87faa4ade)

**Comment by nullptroma** [comment]
![image](https://github.com/user-attachments/assets/49e93c56-3090-419f-ac49-8dbc13f872f3)

**Comment by nullptroma** [comment]
![image](https://github.com/user-attachments/assets/70ce1603-74aa-4763-bd8c-39374e69ff99)
However, everything is fine with the gnome settings, which means that the theme is still used for gtk

**Comment by nullptroma** [comment]
AGS color broke down in this commit https://github.com/end-4/dots-hyprland/commit/234fc4b84734ba0d2722dca3107fb93718d86ed5

**Comment by end-4** [comment]
maybe delete `~/.local/state/ags/user/colormode.txt` and pick wallpaper again

**Comment by nullptroma** [comment]
It really worked, thanks.
What about FireFox? It seemed to me that it uses some colors from gtk and the title is colored accordingly. There is also a question about dconf-editor, is it supposed to look like this? I probably got something mixed up, since I expect a different appearance

**Comment by end-4** [comment]
no clue about firefox
dconf editor has always looked weird

**Comment by nullptroma** [comment]
Ok
Thank you
