### ISSUE TITLE
[Issue] AGS bar and widgets crashing on interaction

### ISSUE THREAD

**Issue by sametaor** [end-4/dots-hyprland#708]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Arch Linux

---
## The issue

AGS bar and widgets crash upon any sort of interaction, whether it is the sidebar, color picker or on-screen keyboard.

### Expected behaviour:

AGS and its widgets remain intact on the screen, regardless of the amount of interactions.

### Actual behaviour:

AGS and its widgets crash upon interacting with any module on the ags bar or its subcomponents.

### Steps to Reproduce:

1. Start ags as usual
2. Click on the sidebar to open it once.
3. Close the sidebar by clicking outside it.
4. Repeat Steps 2 and 3 once again.
5. Ags crashes and needs to be restarted again.

<details>
<summary>Logs</summary>

```plain
Gjs-Console-Message: 11:16:04.076: [LOG] Styles loaded
gjs: ../cairo/src/cairo-surface.c:962: cairo_surface_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed.
[1]    3455 IOT instruction (core dumped)  ags
```

</details>

**Comment by FrancescoCaracciolo** [comment]
I also have the same problem

**Comment by Sakurapole** [comment]
I also met this problem. It seems to have appeared after I updated the system.

**Comment by Kalidude69** [comment]
same problem i thought only me ..... 
**this happens randomly ....this is just an example of launching a qt application which leads to crash**

```
Gjs-Console-Message: 18:49:48.623: [LOG] Styles loaded
Qt WARNING: QApplication: invalid style override 'kde' passed, ignoring it.
	Available styles: qt5ct-style, Windows, Fusion
gjs: ../cairo/src/cairo-surface.c:962: cairo_surface_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed.
fish: Job 1, 'ags' terminated by signal SIGABRT (Abort)

```

**Comment by beilusm** [comment]
It happened the same after my arch Linux update

**Comment by Kalidude69** [comment]
> does using an old version of hyprland fix it (whatever tagged version, before wlroots rewrite)

hyprland now uses aquamarine as backend ... let me check to see what happens

**Comment by sametaor** [comment]
> does using an old version of hyprland fix it (whatever tagged version, before wlroots rewrite)

I think it still worked until yesterday night, even with the aquamarine backend. It only occurred today morning, so it was most likely because of the latest update so far. For now, I am reinstalling the dots from the bash script again on a fresh install just to check if it works.

**Comment by Kalidude69** [comment]
> > does using an old version of hyprland fix it (whatever tagged version, before wlroots rewrite)
> 
> I think it still worked until yesterday night, even with the aquamarine backend. It only occurred today morning, so it was most likely because of the latest update so far. For now, I am reinstalling the dots from the bash script again on a fresh install just to check if it works.

yes it did work properly ... just today morning when I updated `hyprland-git 0.41.2.r98.33a5c8ce-1` the issues are happening ... i even tried installing aylur-ags-git (ik both are the same building from source)....still the issue exists

**Comment by sametaor** [comment]
> > > does using an old version of hyprland fix it (whatever tagged version, before wlroots rewrite)
> > 
> > 
> > I think it still worked until yesterday night, even with the aquamarine backend. It only occurred today morning, so it was most likely because of the latest update so far. For now, I am reinstalling the dots from the bash script again on a fresh install just to check if it works.
> 
> yes it did work properly ... just today morning when I updated `hyprland-git 0.41.2.r98.33a5c8ce-1` the issues are happening ... i even tried installing aylur-ags-git (ik both are the same building from source)....still the issue exists

Alright, please do lemme know the results you find otherwise, I can't really afford to reinstall it all again 😅

**Comment by Kalidude69** [comment]
> > > > does using an old version of hyprland fix it (whatever tagged version, before wlroots rewrite)
> > > 
> > > 
> > > I think it still worked until yesterday night, even with the aquamarine backend. It only occurred today morning, so it was most likely because of the latest update so far. For now, I am reinstalling the dots from the bash script again on a fresh install just to check if it works.
> > 
> > 
> > yes it did work properly ... just today morning when I updated `hyprland-git 0.41.2.r98.33a5c8ce-1` the issues are happening ... i even tried installing aylur-ags-git (ik both are the same building from source)....still the issue exists
> 
> Alright, please do lemme know the results you find otherwise, I can't really afford to reinstall it all again 😅

ok so after testing for a bit of time .... it seems there are some problems with ags as per @end-4 referenced... I switched to non git branch of hyprland and hyprutlis ...seems to be stable no crashing yet .... but as soon i shift to the git branch frequent crashing comes up ....
the versions are referenced below
```hyprland 0.41.2-3```
```hyprutils 0.2.0-1.1```
```aylurs-gtk-shell-git 1.8.2.r10.g344ea72-1``` _**Note only ags is on the git branch**_

**Comment by Euroysx** [comment]
same issue, any feedback ??

**Comment by beilusm** [comment]
So the issue is because of hyprland, not dots-hyprland or ags

**Comment by Kalidude69** [comment]
yes

**Comment by XMinty77** [comment]
Hello! I'm a completely new Arch Linux user. I found this and thought it's quite neat, so I'm trying it out. I have encountered the problems mentioned in this issue, so I came here to look for a fix. A post above mentions downgrading releases works, so I removed hyprland-git and hyprutils-git and reinstalled them with pacman. However, I had to remove a bunch of packages that depend on them, and reinstall them. One of these is illogical-impulse-widgets, but I encountered a problem with this one specifically: I couldn't reinstall it because it depends on hyprutils-git, hyprlock-git and hypridle-git, which in turn depend on hyprland-git and hyprutils-git. For the record, I'm totally green at this, I went to the cache directory where the Git repo was cloned, and tried to pacman -U the built package file. That of course didn't work, so I edited the PKGBUILD file myself, changed the dependencies, then rebuilt/reinstalled. Is this a sane thing to do? What other information should I be aware of? I'm very sorry if this isn't an appropriate place to ask, but I can't think of anywhere else. Insights would be greatly appreciated, thank you!

**Comment by omarbhl** [comment]
Had the same issue just fixed it, the issue lies with the hyprland-git package, just make a backup for the config files before removing it `sudo pacman -Rns hyprland-git` after removing it i installed the hyprland package `sudo pacman -S hyprland` then ran `pacman -Qs hyprland` to check.
So far its working fine no crashes are happening with the bar and its seems that everything is stable.

**Comment by XMinty77** [comment]
> > Hello! I'm a completely new Arch Linux user. I found this and thought it's quite neat, so I'm trying it out. I have encountered the problems mentioned in this issue, so I came here to look for a fix. A post above mentions downgrading releases works, so I removed hyprland-git and hyprutils-git and reinstalled them with pacman. However, I had to remove a bunch of packages that depend on them, and reinstall them. One of these is illogical-impulse-widgets, but I encountered a problem with this one specifically: I couldn't reinstall it because it depends on hyprutils-git, hyprlock-git and hypridle-git, which in turn depend on hyprland-git and hyprutils-git. For the record, I'm totally green at this, I went to the cache directory where the Git repo was cloned, and tried to pacman -U the built package file. That of course didn't work, so I edited the PKGBUILD file myself, changed the dependencies, then rebuilt/reinstalled. Is this a sane thing to do? What other information should I be aware of? I'm very sorry if this isn't an appropriate place to ask, but I can't think of anywhere else. Insights would be greatly appreciated, thank you!
> 
> Old versions of non-AUR packages can be found in the [archive](https://archive.archlinux.org/packages). For old versions of AUR packages, you should go to the package's git repository, select an older commit, and manually compile and install it. If you want to install an old version from the AUR, you'll need to manually modify the source code URL and checksums in the PKGBUILD file. I have a repository where I previously compiled an old version of [hyprland-git](https://github.com/Biaogo/neko-repository/blob/main/x86_64/hyprland-git-0.41.2.r13.4d6f96f7-1-x86_64.pkg.tar.zst), which you can temporarily use until the issue is fixed.
> 
> For local or remote installation packages, you only need to download `hyprland-git-0.41.2.r13.4d6f96f7-1-x86_64.pkg.tar.zst` and install it using either `pacman -U hyprland-git-0.41.2.r13.4d6f96f7-1-x86_64.pkg.tar.zst` for a local file, or `pacman -U https://github.com/Biaogo/neko-repository/blob/main/x86_64/hyprland-git-0.41.2.r13.4d6f96f7-1-x86_64.pkg.tar.zst` for the remote file.

Ohhh I see. Makes sense. Thank you so muuuuch :D

**Comment by end-4** [comment]
> Had the same issue just fixed it, the issue lies with the hyprland-git package, just make a backup for the config files before removing it `sudo pacman -Rns hyprland-git` after removing it i installed the hyprland package `sudo pacman -S hyprland` then ran `pacman -Qs hyprland` to check. So far its working fine no crashes are happening with the bar and its seems that everything is stable.

reinstalling hyprland doesn't mess with your config files, so no need to backup

**Comment by end-4** [comment]
I'm not going to upgrade Hyprland until it gets more stable and gets proper releases
Generally, I don't recommend updating Hyprland unless you specifically want a new feature/fix

**Comment by FrancescoCaracciolo** [comment]
> [hyprwm/Hyprland@daed752](https://github.com/hyprwm/Hyprland/commit/daed75219fa7b4ec345337ec99f816e94bda338c)

This totally fixed it

**Comment by Sakurapole** [comment]
> > [hyprwm/Hyprland@daed752](https://github.com/hyprwm/Hyprland/commit/daed75219fa7b4ec345337ec99f816e94bda338c)
> 
> This totally fixed it, on latest hyprland-git everything seems to be fine

yes, in latest hyprland-git, they fixed this problem, I have been using it all day.

**Comment by sametaor** [comment]
The issue's solved for me too, closing it.
Thank you to end-4 and everyone involved! Cheers :)
