### ISSUE TITLE
No window named 'bar' exists in config

### ISSUE THREAD

**Issue by abinlatheef** [end-4/dots-hyprland#71]
eww gives this error while starting

**Comment by abinlatheef** [comment]
Yes, I am on `m3ww`, sorry for not mentioning that.
![image](https://github.com/end-4/dots-hyprland/assets/63762448/a5ce5249-d398-44e7-8d61-58626b0be34e)
And yes I did comment out that line as said in the readme. This is my `status.yuck` file.

**Comment by abinlatheef** [comment]
Yes, I am on m3ww, sorry for not mentioning.
I commented out the 5th line as said in the readme. Attaching it for reference. I have installed every dependency said in the readme as well.
![image](https://github.com/end-4/dots-hyprland/assets/63762448/097c619d-19ce-46c3-be61-97456254b17f)

**Comment by end-4** [comment]
that looks alright
any other error? attach output of `eww logs`  please

**Comment by abinlatheef** [comment]
`eww logs`  just not prints anything. I decided to move on with systray. Though I believe there is an issue for people who are choosing to go without the systray. If you will guide me, I may be able to collect more details to find out more about the issue. But that said, it might possibly be because I am doing something stupid as well. Anyways, thank you so much for the help and your thing is so slick... Thanks a lot..
