### ISSUE TITLE
[Issue] Remove eww from the mix

### ISSUE THREAD

**Issue by mmahmoudian** [end-4/dots-hyprland#711]
At the moment the config does not use eww and yet eww is both in acknowledgment and the tags of the repo. I suggest updating those to reflect the current state of the repo.

**Comment by end-4** [comment]
it's used in the older styles. i tossed em into `archive` branch

**Comment by end-4** [comment]
but it's fair since i don't recommend anyone try my eww works anymore due to how broken they are now
i removed the 'eww' and 'osu' tag from the repo
