### ISSUE TITLE
[Issue] Cursor jumps to top left corner after opening any gnome application

### ISSUE THREAD

**Issue by LordOFTheOlympians** [end-4/dots-hyprland#716]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: EndeavourOS (Gnome)

---
## The issue
Cursor jumps to top left corner whenever i open any org.gnome application

It seems that whenever i open any gnome application, my cursor jumps to the top left corner. I don't think there's an installation issue as i have reinstalled the dotfiles twice on different instances. Any help would be appreciated.

P.S - This is my first github post(idk what to call it except post :)) and i would like to apologize in advance if I am irregular since I have a really busy schedule for the next week(s).

**Comment by end-4** [comment]
probably a hyprland problem since this only started happening to me after i updated hyprland

**Comment by LordOFTheOlympians** [comment]
Thanks for the update! Let's just hope it gets fixed in the future.

**Comment by bThiiago** [comment]
just remove focus_on_activate = true on hypr general.conf misc

**Comment by end-4** [comment]
thanks, that's a fine workaround
