### ISSUE TITLE
[Issue] fakefullscreen has been removed upstream

### ISSUE THREAD

**Issue by moetayuko** [end-4/dots-hyprland#719]
The `fakefullscreen` dispatcher has been removed from hyprland, and a new `fullscreenstate` has been added as an enhanced version

https://github.com/hyprwm/Hyprland/pull/7128

**Comment by Kalidude69** [comment]
what is the fix ?

**Comment by Kalidude69** [comment]
what's the fix??

**Comment by Utkarsh3212** [comment]
Just replace the fakefullscreen to fullscreenstate in ~/.config/hypr/hyprland/keybinds.conf

**Comment by Kalidude69** [comment]
> Just replace the fakefullscreen to fullscreenstate in ~/.config/hypr/hyprland/keybinds.conf

yes ik that.... i did the same but fake fulscreen doesnt work

**Comment by twist250** [comment]
@Kalidude69 try this `bind = Alt SHIFT, F, fullscreenstate, 0 3`

**Comment by Kalidude69** [comment]
> @Kalidude69 try this `bind = Alt SHIFT, F, fullscreenstate, 0 3`

Thanks!!! Works fine now
