### ISSUE TITLE
AGS break [Issue]

### ISSUE THREAD

**Issue by mahaveergurjar** [end-4/dots-hyprland#726]
AGS break after click on boder_clearTransparency this option at right side in tune option
![image](https://github.com/user-attachments/assets/5ccd8e65-10da-4139-bbe5-1a2fd5959603)

**Comment by DomsaVictor** [comment]
Same thing for me. Did you find a solution for this?

**Comment by mahaveergurjar** [comment]
Thanks

**Comment by end-4** [comment]
close the issue if that fixed it
thanks

**Comment by mahaveergurjar** [comment]
Ok
