### ISSUE TITLE
Workspace indicator doesn't work

### ISSUE THREAD

**Issue by nanashi-1** [end-4/dots-hyprland#73]
Variant: Hybrid

No matter what workspace I'm in, it just indicates that I'm in workspace number 1.

## Workspace 2
![image](https://github.com/end-4/dots-hyprland/assets/54083498/17483ea3-3572-43df-9062-1656a91fbf00)

## Workspace 3
![image](https://github.com/end-4/dots-hyprland/assets/54083498/93a2d29c-ce8c-46e0-a508-8f4c22b36e75)

## Workspace 4
![image](https://github.com/end-4/dots-hyprland/assets/54083498/b805c1d4-a7f6-43c2-a125-e17a767c736e)

**Comment by end-4** [comment]
please provide the output of `~/.config/eww/scripts/activews`

**Comment by nanashi-1** [comment]
> ~/.config/eww/scripts/activews

    2
    /home/nanashi/.config/eww/scripts/activews: line 13: socat: command not found

I then installed `socat`. The output after that is just `2`.

**Comment by nanashi-1** [comment]
Worked after `eww reload`
