### ISSUE TITLE
[Issue] Want full corner edges not rounded ones (both up and down)

### ISSUE THREAD

**Issue by Kalidude69** [end-4/dots-hyprland#732]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Cachy-os

---
## The issue
I believe the setting related to "corner_radius" or "screen corner rounding" _etc_ might be what I need to modify, but I’m not sure where to find it in the configuration. Could someone please guide me on how to disable screen rounding in all corners?

For hyprland windows the rounding is fine enough.... just need help about the actual screen rounding :)
**Thanks for help from the future**

**Comment by Tejas242** [comment]
You can find and edit configurations in `~/.config/ags/` folder.

**Comment by Kalidude69** [comment]
> You can find and edit configurations in `~/.config/ags/` folder.

bruh :/ iknow ags folder has the files i was asking for the specific file which has the contents for changing the stuff

**Comment by Tejas242** [comment]
To disable just comment the lines in config.js file

```
    forMonitors((id) => Corner(id, 'bottom left', userOptions.appearance.fakeScreenRounding !== 0)),
    forMonitors((id) => Corner(id, 'bottom right', userOptions.appearance.fakeScreenRounding !== 0)),
    forMonitors(BarCornerTopleft),
    forMonitors(BarCornerTopright),
```

**Comment by end-4** [comment]
change the `appearance.fakeScreenRounding` option 
0: None | 1: Always | 2: When not fullscreen

**Comment by Kalidude69** [comment]
thanks 🌟
