### ISSUE TITLE
[Issue] No signal on either monitor after logging in.

### ISSUE THREAD

**Issue by Xtobyte** [end-4/dots-hyprland#737]
Endeavour OS 
AMD GPU

After having it successfully installed and running for a few months, after a system upgrade a few weeks ago whenever I log into or start hyprland both of my monitors lose signal from the computer. I have tried multiple DMs and launching from tty, however since hyprland itself isn't crashing it is quite hard to get a log. I have read through the entire journalctl but didn't see anything too out of the ordinary, however I likely have missed something. The issue isn't with wayland as I can log into gnome wayland and plasma wayland fine. Any ideas as to what may be causing this or a way to get useful logs without it crashing would be helpful.

**Comment by end-4** [comment]
i don't use multiple monitors and without logs i'm clueless, so maybe ask this in the hyprland's discord or github issues

**Comment by Xtobyte** [comment]
I managed to resolve the issue by purging Hyprland and all its dependencies and reinstalling.
