### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by LumbaBalumba** [end-4/dots-hyprland#739]
## The issue

Is it possible to change default terminal emulator to kitty/alacritty? If yes, how do I do it?

**Comment by end-4** [comment]
change the keybind in `~/.config/hypr/hyprland/keybinds.conf` that launches `foot` so it launches to your preferred terminal instead

**Comment by end-4** [comment]
change `userOptions.apps.terminal` to your desired terminal
see `~/.config/ags/user_options.js`

**Comment by LumbaBalumba** [comment]
Is it possible to make terminal launch with zsh, not fish?

**Comment by end-4** [comment]
your terminal is configured by you. my dotfiles just provides foot config
for the quickscripts i don't think it matters much and there isn't a simple way to change it rn
