### ISSUE TITLE
[Issue] Install Failed

### ISSUE THREAD

**Issue by FrostLynn** [end-4/dots-hyprland#743]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Arch Linux also happen on CachyOS

---
My install always failed because of this issue down here

```plain
[./install.sh]: Command "yay -S --needed --noconfirm --asdeps adw-gtk3-git qt5ct qt5-wayland fontconfig ttf-readex-pro ttf-jetbrains-mono-nerd ttf-material-symbols-variable-git ttf-space-mono-nerd ttf-rubik-vf ttf-gabarito-git fish foot starship" finished.
==> Making package: illogical-impulse-fonts-themes 1.0-1 (Wed 14 Aug 2024 06:28:16 PM WIB)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: adw-gtk3-git
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> adw-gtk3-git
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
[./install.sh]: Command "makepkg -si --noconfirm" has failed.
```

</details>

**Comment by Tealers** [comment]
Having the same Issue here. Not sure if there's any alternative for adw-gtk3-git for this issue. Wiki shows error 404 on adw-gtk3-git page.

**Comment by JuanDavid006** [comment]
Yes. I'm also having this problem. Apparently the adw-gtk3-git AUR package stopped existing so that means that Yay can't satisfy all dependencies. All i did to fix the problem **for now** is just to remove the adw-gtk3 dependency from the PKGBUILD. Let's just wait what happens i guess...

**Comment by sasinhe** [comment]
It seems that the adw-gtk3-git package was merged into the [adw-gtk-theme-git](https://aur.archlinux.org/packages/adw-gtk-theme-git). I'm issuing a pull request to update the script, but changing to the new package name in the PKGBUILD should suffice.

**Comment by JuanDavid006** [comment]
I browsed for several minutes and i never saw that AUR package. Thanks for sharing it!
