### ISSUE TITLE
Powerview not working with multiple monitors

### ISSUE THREAD

**Issue by Clemorange22** [end-4/dots-hyprland#75]
- **I have read the instructions** and I have a problem with branch: m3ww
---
## The issue
![image](https://github.com/end-4/dots-hyprland/assets/62897760/3a9ced6a-9bec-4b82-993b-52db5042c34b)
It's working perfectly when i disconnect my external monitor

**Comment by end-4** [comment]
can you watch the output of `~/.config/eww/scripts/overview-wrapper1` when disconnecting your monitor?

**Comment by Clemorange22** [comment]
```
/home/clem/.config/eww/scripts/overview-wrapper1: line 3: scripts/overview: No such file or directory
/home/clem/.config/eww/scripts/overview-wrapper1: line 12: scripts/overview: No such file or directory
/home/clem/.config/eww/scripts/overview-wrapper1: line 12: scripts/overview: No such file or directory
/home/clem/.config/eww/scripts/overview-wrapper1: line 12: scripts/overview: No such file or directory
/home/clem/.config/eww/scripts/overview-wrapper1: line 12: scripts/overview: No such file or directory
/home/clem/.config/eww/scripts/overview-wrapper1: line 12: scripts/overview: No such file or directory
/home/clem/.config/eww/scripts/overview-wrapper1: line 12: scripts/overview: No such file or directory
/home/clem/.config/eww/scripts/overview-wrapper1: line 12: scripts/overview: No such file or directory

```
the error occurs each time i close the powerview

**Comment by end-4** [comment]
oops, forgot to mention that you need to run in eww dir
so that should be `cd .config/eww && scripts/overview-wrapper1`

**Comment by Clemorange22** [comment]
update : it does not work when i disconnect my monitor
it works only when i start hyprland with one monitor. If i connect the second it stops working

I got this output with the powerview working
```
[[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"1","workspace":{"id":1,"name":"1"}},{"address":"0x55c33a4e8eb0","at":[5,45],"class":"foot","icon":"/usr/share/icons/Win11-dark/apps/scalable/foot.svg","size":[1494,952],"title":"cd .config/eww && sc ~","workspace":{"id":1,"name":"1"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"2","workspace":{"id":2,"name":"2"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"3","workspace":{"id":3,"name":"3"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"4","workspace":{"id":4,"name":"4"}}],[{"address":"_none","at":[0,0],"class":"workspace","size":[1920,1080],"title":"5","workspace":{"id":5,"name":"5"}}]]
```

**Comment by Rakantor** [comment]
I had the same problem as OP and figured that these two lines are the problem in multi-monitor setups:

```
.config/eww/variables.yuck

(defpoll RES_WIDTH :initial 1920 :interval "69h" `xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1`)
(defpoll RES_HEIGHT :initial 1080 :interval "69h" `xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2`)
```
The shell commands output X lines for X connected monitors. As a result, the values for `RES_WIDTH` and `RES_HEIGHT`, which are used for styles in `.config/eww/windows/powerview.yuck`, will be invalid.
So change them to this:

```
(defpoll RES_WIDTH :initial 2560 :interval "69h" `xrandr --current | awk '/\*/ {split($1, arr, "x"); print arr[1]; exit}'`)
(defpoll RES_HEIGHT :initial 1440 :interval "69h" `xrandr --current | awk '/\*/ {split($1, arr, "x"); print arr[2]; exit}'`)
```

or simply replace them

```
(defvar RES_WIDTH 2560)
(defvar RES_HEIGHT 1440)
```

Now my powerview looks like this:

![20230930_13h33m17s_grim](https://github.com/end-4/dots-hyprland/assets/8210657/ecea2c7f-9269-4ff6-b520-dd57b32c1b88)

The layout is still garbled. I guess I'll need to adjust the styles in `.config/eww/windows/powerview.yuck` to get it looking right for my setup.

However, the active workspaces on my second monitor aren't displayed in powerview at all. I'm not sure if there's an easy solution to this.

**Comment by Clemorange22** [comment]
Thanks !

**Comment by end-4** [comment]
I'm closing this for now, since I switched from EWW to AGS and no longer able to support the former. The new widget system makes it **much** easier, with overview widget being more powerful, more performant, and should work better with multi-monitor (though I'm not exactly sure how well)
