### ISSUE TITLE
[Cant see all the soundcards name to choose the correct one in ags sound menu] 

### ISSUE THREAD

**Issue by andresparrab** [end-4/dots-hyprland#755]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: EndeavourOs

---
## The issue
![image](https://github.com/user-attachments/assets/683bf0b0-6bcc-427d-83d3-ecb007a88517)

When i open the right side ags panel and try to choose the sound card. 
I cant see the whole name of the sound cards and when i connect jabra and other sound card when have Team meeting is difficult to see witch is witch.

I send a screenshot, to the left is the gnome-settings that expand the box to show the full name of the soundcards 
On the right  side  is the ags menu would be nice to have like the gnome to be able to see the whold sound card or to give it a name  like:
 HDMI/ display port1 - spundcard name
Speakers - Canon... soundcard name
Jabra Analog - soundcar name

and so on..

<details>
<summary>Logs</summary>

```plain
Paste logs here
```

</details>

**Comment by end-4** [comment]
i don't like having an out of place looking popup
i wish i can make that text scroll... but i can't, so i decided to go with a tooltip that should show the full name

**Comment by andresparrab** [comment]
yes tooltip is great as well. is it already in the latest ags? or uppcomming? right now i dont have it right now. i have pulled the latest dotshyprlan and copy like always the ags folder to my ~/.config/
cp -rv dots-hyprland/.config/ags  ~/.config/

**Comment by end-4** [comment]
> right now i dont have it right now

update it
notice the commit above my reply? that's the one in which i added the tooltip

**Comment by andresparrab** [comment]
Hi!
yes I can see it now thank you.
