### ISSUE TITLE
Focus is not changing automatically while opening a new instance of an application

### ISSUE THREAD

**Issue by Acebasein** [end-4/dots-hyprland#757]
I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
I have made sure that both my config and system packages are up to date
Linux distro: Arch Linux

First of all, thank you very much for an awesome hyprland setup!!!

I believe it would be simpler to illustrate my issue using an example. Here’s one.

I use Sublime Text as my default text editor. Previously, when I opened Sublime Text and placed it in say, workspace-02, any new file I opened would automatically shift my focus to workspace-02. For example, if my File Manager was in workspace-05, opening a new file in Sublime Text (while I'm inside the File manager) would move my focus to workspace-02. However, after a recent update, this behavior has changed. Now, the focus remains in workspace-05 even after opening a file in the text editor. Any help would be appreciated.

**Comment by end-4** [comment]
Opening a GTK app makes the cursor jump to the topleft corner, which is annoying (see #716)
I disabled "focus on activate" as a workaround for that issue, so now newly opened apps no longer bring focus to them

**Comment by Acebasein** [comment]
> Opening a GTK app that tries to steal focus makes the cursor jump to the topleft corner, which is annoying (see #716) I disabled "focus on activate" as a workaround for that issue, so now newly opened apps no longer bring focus to them

Thank you, @end-4. I have updated the general.conf file to include focus_on_activate = true

**Comment by Acebasein** [comment]
Closed
