### ISSUE TITLE
Help needed with setting up hybrid branch

### ISSUE THREAD

**Issue by gabee12** [end-4/dots-hyprland#76]
- **I have read the instructions** and I have a problem with branch: hybrid
---
## The issue
I'm trying out the hybrid branch on my laptop and most things are working just fine, but I'm having trouble getting some things to work.

First, I'm having problems with the resolution. Most things are fine, but the top bar, bottom bar and side panels to fit on my screen (Resolution: 1366x768)

![WhatsApp Image 2023-09-09 at 20 12 29](https://github.com/end-4/dots-hyprland/assets/67608572/395d0d47-4fe7-4f7b-9579-4413ad7140a5)

Switching between modes also looks to be broken on my end:

![WhatsApp Image 2023-09-09 at 20 18 16](https://github.com/end-4/dots-hyprland/assets/67608572/f89b95a5-e41d-44e9-a00e-e0435e9ff9f5)

The bottom bar appears, but that's it, nothing else happens. Switching back to the default mode will cause the top bar to duplicate itself.

Another problem is that the background of terminals appears solid instead of translucent.

![WhatsApp Image 2023-09-09 at 20 21 56](https://github.com/end-4/dots-hyprland/assets/67608572/deb4003b-8928-439e-b1bd-d85f6a7bf1d4)

I would appreciate if you could help me solve these problems or at least point me in the right direction to fix them. I'm kinda new to this sort of thing so I have no idea what config files I should be editing to move these things around. I have tried changing the resolution in the eww variables file as pointed out in another issue, but that didn't help in my case.

**Comment by gabee12** [comment]
After messing around with the files for some more time I noticed that the guided install script wasn't copying all of the files in .config and .local. Copying them manually fixed most things

**Comment by end-4** [comment]
resolution problem can be solved but it will require a lot of modifications as stylesheets were hardcoded in px for 1920x1080 screen
consider using m3ww branch instead as it can be scaled easily
