### ISSUE TITLE
[Issue] dots-hyprland. Problem in colors.conf file.

### ISSUE THREAD

**Issue by kurisutinade** [end-4/dots-hyprland#761]
Hi guys. When I enable the transparency effect, hyprland crashes with an error in the colors.conf file on line 9

**Comment by kurisutinade** [comment]
config error in file /home/kurisu/.config/hypr/hyprland/colors.conf at line 9: rgba() expects lenght of 8 characters(4 bytes) or 4 comma separated values.
config error in file /home/kurisu/.config/hypr/hyprland.conf at line 9: config error in file /home/kurisu/.config/hypr/hyprland/colors.conf at line 9: rgba() expects lenght of 8 characters(4 bytes) or 4 comma separated values.

**Comment by Acebasein** [comment]
Did you modify the colors.conf file? May be it's expecting an 8 chars hex value  for the specific color in question. Please post a copy of your conf

**Comment by kurisutinade** [comment]
> Did you modify the colors.conf file? May be it's expecting an 8 chars hex value for the specific color in question. Please post a copy of your conf

Hi, no, i didn't change anything in colors.conf, I did a clean install of arch and automatically installed hyprland + end-4 theme according to the guide. Is it possible that the problem is because I'm testing all this on a virtual machine? In any case, I'll send you the config now
![Untitled](https://github.com/user-attachments/assets/faa936dd-7cda-41a4-b502-e1a9196370b4)

**Comment by end-4** [comment]
does picking a wallpaper again fix it

**Comment by pandalec** [comment]
I had a similar problem. Installation worked fine but switching the Dark/Light mode toggle resulted in the config shown above. Setting a wallpaper restored a functional colors.conf

**Comment by bilgineroral** [comment]
> does picking a wallpaper again fix it

setting a wallpaper broke it in my case (fresh install on Arch)

**Comment by kurisutinade** [comment]
> does picking a wallpaper again fix it

Indeed, after changing the wallpaper everything worked. Thanks for the answer!
