### ISSUE TITLE
[Feature]  Send an AI message via Enter key

### ISSUE THREAD

**Issue by yuneguy** [end-4/dots-hyprland#765]
**What would you like to be added?**

The ability to use the enter button in AI services as a send

**How will it help**

It is not very convenient to click on the button with the mouse, the enter button works as a line break.
is it possible to add this?

**Comment by end-4** [comment]
Shift+Enter should create newline and Enter should send though. No? probably a Hyprland problem. I don't remember encountering it recently... which Hyprland version are you on? Maybe update it?

**Comment by yuneguy** [comment]
latest version, I think most likely the problem is that I don't have a regular enter but a Kp_Enter

> Shift+Enter should create newline and Enter should send though. No? probably a Hyprland problem. I don't remember encountering it recently... which Hyprland version are you on? Maybe update it?

**Comment by end-4** [comment]
In `~/.config/ags/modules/sideleft/apiwidgets.js`, add the following after line 92:
```js
            print(event.get_keyval()[1]);
```
Then run ags in terminal with `pkill ags; ags`. Open the sidebar then press your enter key. Then send me the terminal output and I'll handle it for you

**Comment by yuneguy** [comment]
65421

**Comment by end-4** [comment]
thanks to ai i now know there's already a const for that key...
also i'm so sorry how long it took...
