### ISSUE TITLE
Nothing Shows Up For Music Bar in m3ww

### ISSUE THREAD

**Issue by TZProgrammer** [end-4/dots-hyprland#77]
When clicking Win+M, the eww widget pops up, but it is completely blank. I have tested Cava, and it does output when I play music, however nothing shows up in the widget. It is just a dark grey bar with nothing in it.

The widget when in the left bar works. It has the correct image, and the play button works. However absolutely nothing shows up in the bottom widget (other than a dark grey bar).

**Comment by end-4** [comment]
that fixed it for me. can you try again?

**Comment by end-4** [comment]
I'm just going to close this issue since I switched from EWW to AGS and no longer support EWW-powered configs.
