### ISSUE TITLE
[Issue] Keyboard layout icon in the tray does not change for some layouts

### ISSUE THREAD

**Issue by unknxnwxrld** [end-4/dots-hyprland#771]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: i use arch btw

---
## [Issue] Keyboard layout icon in the tray does not change

The keyboard layout icon in the tray does not change when using the Ukrainian and Slovak layouts. The icon of the previous “recognized” layout remains visible.
The bug remains at any order of layouts, does not depend on the used bind to change the layout.

**Comment by end-4** [comment]
It's not just "some". It's actually *most*. I know it sucks, but that's how dotfiles commonly are...
A layout is only recognized only when it's added to `~/.config/ags/modules/.commonwidgets/statusicons_languages.js`
I can add your languages if you can tell me precisely the layout abbreviation, layout name and flag

**Comment by unknxnwxrld** [comment]
nevermind, i just fixed it myself

**Comment by unknxnwxrld** [comment]
nevermind, i just fixed it myself

**Comment by kripikripi** [comment]
How did you fix it? I added `{
    layout: 'ua',
    name: 'Ukranian',
    flag: '🇺🇦'
  },` to the `~/.config/ags/modules/.commonwidgets/statusicons_languages.js` and it still only displays us
