### ISSUE TITLE
How to set fontsize

### ISSUE THREAD

**Issue by fecet** [end-4/dots-hyprland#78]
Sorry if it's a silly question. 
I found that scaleable widget is a highlight feature in readme but I don't find anywhere tell how to config it.

I read code in `eww`  config and set it by 
```
gsettings set org.gnome.desktop.interface font-name 'Noto Sans 18'
```
Is there any better way or it's the correct way?

**Comment by end-4** [comment]
i just use GNOME Tweaks
i'm a noob who doesn't have a deep understanding, uses gui apps and focuses on the fun stuff
![image](https://github.com/end-4/dots-hyprland/assets/97237370/66c242a9-a108-41e7-b420-fc4290413308)

**Comment by fecet** [comment]
Thanks! I also prefer gui, that's why I ask here :smile: but it doesn't exist in gnome setting manager that avaiable at eww widget.
