### ISSUE TITLE
Brown background and no panels

### ISSUE THREAD

**Issue by thememika** [end-4/dots-hyprland#780]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: glibc 2.39-based system, x86_64. Dbus 1.14.10, elogind from the 255.5, udevd from the same.  More information if needed.
---
## Brown background and nothing is shown

Hi!
My linux system is built by myself from sources, it's based around glibc. It is compatible to the standards we find in usual distros.

The previews of your Desktop look incredible. I wanted to try this as the first desktop environment on my system.
I have built and satisfied all 76 dependencies from `scriptdata/previous_dependencies.conf`, and all their sub-deps. I used mostly original upstream repositories. In every meson/cmake/configure/etc, I tried to satisfy as many optional features as possible - to be sure that things will work. It took few whole days to satisfy the dependencies, so I'm sad that the desktop doesn't work.
<br>I don't have system D, but I have elogind, pam, polkit, dbus, and all of these common things. (I have libsystemd.so.0 as a symlink to libelogind. It's a usual practice in distros w/o systemD.)

All the dependencies compiled without any errors! I had to adjust many things in my system, though. But it all built finally.

Then I went to `scriptdata/installers`.
I satisfied `AGS` with checkout to `05e0f23534fa30c1db2a142664ee8f71e38db260`, satisfied icons/fonts "Rubik", "Gabarito", "OneUI", "Bibata", then micro TeX to path. TeX works.

Finally after 4 days ,I put .config and .local to the home folder of unprivileged user, I run hypr land.

"Hyprland" started successfully on DRM device of nouveau.
I see a mouse cursor which looks like Hyprland icon. Input configured automatically with udev, it works. Many unneeded (for me) daemons start successfully: wpa_supplicant; upowerd; udisks2; geoclue; and even more. I plan to disable them later.

Yet the main thing, **there is nothing displayed on the screen, just brown background and mouse cursor**. 

This is how it looks:
![IMG_20240830_212348](https://github.com/user-attachments/assets/5b7219bd-6196-4772-8424-ed7b043f3e2c)
I press `Win + T`, and "foot" terminal opens! The 'fish' shell and the font looks beautiful! 
![IMG_20240830_212840](https://github.com/user-attachments/assets/9bea0e45-7c95-4000-a7ac-47c83ae3a522)
I think that the upper freespace above the terminal was intended for the AGS panel which did not start.
<br>I restart "AGS" as it is advised in your troubleshoot instruction
![Untitled66](https://github.com/user-attachments/assets/7a36e69c-88e0-4023-acce-ef78cf0581b3)
The user name is censored, see full log under Logs below. The error is not clear to me. Instructions were followed. Packages are satisfied. So I'm writing this issue.

I'm new to Wayland, hyprland and all the modern fancy things around these. My previous desktop was Xorg+twm for years. I know the kernel interfaces and internals (and used them with C), traditional daemons, also architecture internals; but still can't get used to Wayland-based desktop environments.

The modern shell and fonts are very nice. I'm excited to experience the whole desktop, hope I can - with your help.
Thanks in advance!
You can request more information if it is needed.
Sorry if something is put incorrectly in the Issue template.
<details>
<summary>Logs</summary>

```plain
Gjs-Console-Message: 23:06:29.080: [LOG] Styles loaded

(com.github.Aylur.ags:23982): Gjs-Console-WARNING **: 23:06:29.352: Error: can't assign "chromium-browser" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:25:14
newIcon@resource:///com/github/Aylur/ags/widgets/icon.js:8:12
ElementTile@file:///home/REPLACED/.config/ags/modules/cheatsheet/periodictable.js:26:32
default/mainBoard<.children</<.children<@file:///home/REPLACED/.config/ags/modules/cheatsheet/periodictable.js:62:58
default/mainBoard<.children<@file:///home/REPLACED/.config/ags/modules/cheatsheet/periodictable.js:62:27
default@file:///home/REPLACED/.config/ags/modules/cheatsheet/periodictable.js:60:33
SheetContent/sheetContents[id]<.children<@file:///home/REPLACED/.config/ags/modules/cheatsheet/main.js:82:48
SheetContent@file:///home/REPLACED/.config/ags/modules/cheatsheet/main.js:82:31
default@file:///home/REPLACED/.config/ags/modules/cheatsheet/main.js:91:32
forMonitors@file:///home/REPLACED/.config/ags/config.js:29:24
Windows@file:///home/REPLACED/.config/ags/config.js:47:5
@file:///home/REPLACED/.config/ags/config.js:75:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:23982): Gjs-Console-WARNING **: 23:06:30.125: Error: can't assign "network-wireless-disabled-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
SimpleNetworkIndicator/setup/<@file:///home/REPLACED/.config/ags/modules/.commonwidgets/statusicons.js:152:9
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:23982): Gjs-Console-WARNING **: 23:06:30.126: Error: can't assign "network-wireless-disabled-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
SimpleNetworkIndicator/setup/<@file:///home/REPLACED/.config/ags/modules/.commonwidgets/statusicons.js:152:9
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:23982): Gjs-CRITICAL **: 23:06:30.193: JS ERROR: TypeError: this._device is undefined
get access_points@resource:///com/github/Aylur/ags/service/network.js:135:9
updateNetworks@file:///home/REPLACED/.config/ags/modules/sideright/centermodules/wifinetworks.js:171:50
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:23982): Gjs-Console-WARNING **: 23:06:30.199: Error: can't assign "network-wireless-disabled-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
SimpleNetworkIndicator/setup/<@file:///home/REPLACED/.config/ags/modules/.commonwidgets/statusicons.js:152:9
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:23982): Gjs-Console-WARNING **: 23:06:30.200: Error: can't assign "network-wireless-disabled-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
SimpleNetworkIndicator/setup/<@file:///home/REPLACED/.config/ags/modules/.commonwidgets/statusicons.js:152:9
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

</details>

**Comment by end-4** [comment]
I greatly appreciate that you properly include details in your question (even a bit too much - inxi result is overkill)
Just a guess, but maybe install an icon pack? If you already have, try also installing Hicolor and Adwaita

**Comment by end-4** [comment]
> where can I see all the required icon packs to satisfy?

it's actually up to you. i have the installation install OneUI icons because I like it, but Adwaita is a good fallback to have. That's it

> Was it required to install them in /usr/local

Nope, `/usr` also works

**Comment by end-4** [comment]
okay, so there's this part of the logs that blended in with the icon warnings that i didn't notice:
```
(com.github.Aylur.ags:23982): Gjs-CRITICAL **: 23:06:30.193: JS ERROR: TypeError: this._device is undefined
get access_points@resource:///com/github/Aylur/ags/service/network.js:135:9
updateNetworks@file:///home/REPLACED/.config/ags/modules/sideright/centermodules/wifinetworks.js:171:50
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

it's the wifi selector on the right sidebar. i'm not sure what `this._device` is but it's probably AGS' internals. the part of my code that triggered this only attempts to get a list of wifi networks (`const accessPoints = Network.wifi?.access_points || [];`)

**Comment by end-4** [comment]
does the log say something else after that change?

**Comment by end-4** [comment]
run `~/.config/ags/scripts/color_generation/switchwall.sh` and show me the logs
