### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by user12xxxxxx** [end-4/dots-hyprland#783]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: endOS

---
## The issue
bluetooth is not working nor in hyperland neither in gnome-endOS

**Comment by Deivis44** [comment]
Wassup!

Use this commands for solving it, the problem it's that the service it's not waking up with the computer:

1. `sudo systemctl enable bluetooth`

Restart Bt service
2. `sudo systemctl restart bluetooth`

In my case those commands solved the issue, tried on 2 devices
![image](https://github.com/user-attachments/assets/32985676-fb0b-4d13-9717-902573ab04fa)
