### ISSUE TITLE
How is the clipboard managed, and where is located the history

### ISSUE THREAD

**Issue by Deivis44** [end-4/dots-hyprland#793]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Arch

---
## The issue
I wanna know how the clipboard is managed, and where is the file that stores that info, I copy some passwords that could be an important breach of security, anyway learning which tool is being used, at least cleaning the history could be a solution, anyway I just need the info about how to manage the tool for it.

Searching a long time I found that fuzzel with gnome opens a graphic view for those copies but the tool that manage the text is cliphist
Here is the repo: https://github.com/sentriz/cliphist

Using the command: `cliphist wipe` I can clear the history anyway, I don't find a place to know exactly where is being stored this info. 

Additionally, found other command: `cliphist list` after cleaning the history, the ID begins at the last one of my cleaned database

**e.g:** 
`cliphist list` 
```
1 some text
2 some text2
```

> I clean the entire database
`cliphist wipe` 

> I copy something on my computer
> If i look for the history again:

`cliphist list` 
```
3. some text3
```

The previous data now is erased but starts with the last ID registered, can I change it? not a problem for me but could be useful for a long term, imagine having a #90000 ID and have to watch that big number every time you wanna check your actual clipboard history

**Comment by end-4** [comment]
i think cliphust stores history somewhere in ~/.cache

**Comment by Deivis44** [comment]
> i think cliphist stores history somewhere in ~/.cache

Yeah, I found searching it deeper, also clearing just the: ~/.cache/cliphist/* you can reset the database and all the entries so I think it's fine
