### ISSUE TITLE
gtklock-runshell-module package does not exist in AUR or other repos

### ISSUE THREAD

**Issue by D3vil0p3r** [end-4/dots-hyprland#8]
Hey man! Wassupp?

I was reading the dependencies on the README and I noted that `gtklock-runshell-module` package does not exist in AUR. Furthermore, by looking the original GitHub repositories of the developer at https://github.com/jovanlanik?tab=repositories , this project does not exist.

**Comment by end-4** [comment]
hmm

As noted in the gtklock wiki, it's here: https://gitlab.com/wef/gtklock-runshell-module. But well it's kinda slow so I don't use it, just gonna remove that.

https://github.com/end-4/dots-hyprland/commit/9ebf40c8529e2af6270bdf1043b36a7e502c7d07

Thanks for reviewing the dependency list!
