### ISSUE TITLE
Calendar - Month cycle buttons don't work

### ISSUE THREAD

**Issue by OnlyCS** [end-4/dots-hyprland#80]
- **I have read the instructions** and I have a problem with branch: 
hybrid
## The issue
- +/- buttons next to calendar (i assumed for cycling months) do not work

**Comment by end-4** [comment]
I no longer use EWW and have switched to AGS, and I can no longer support the former. widget system, so I'm closing this issue. 
AGS makes things much easier: such simple action as changing a variable doesn't have to be done through an external script, so it's a lot less hacky and stuff are more likely to work. The calendar definitely does.
