### ISSUE TITLE
[Help] can any body tell me the name of the virtual keyboard which this project is using?

### ISSUE THREAD

**Issue by the-loan-wolf** [end-4/dots-hyprland#804]
I was searching the name of the virtual keyboard application in the scripts. I don't know which package was it! So can anybody tell me the project name/app name.

**Comment by Ninjdai1** [comment]
It's made in AGS, so it's not an external dependency, see https://github.com/end-4/dots-hyprland/blob/main/.config/ags/modules/onscreenkeyboard/onscreenkeyboard.js

**Comment by the-loan-wolf** [comment]
Oh thank you.

**Comment by the-loan-wolf** [comment]
Close the issue right now as complete
