### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by unjaks** [end-4/dots-hyprland#808]
- ✅ I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- ✅ I have made sure that both my config and system packages are up to date
- Linux distro: Arch Linux

---
## The issue
![image](https://github.com/user-attachments/assets/d8518f4a-aa30-466b-9b59-5e87a7d34ec2)
The installation was successful with no errors. After opening the customization button thingy and enabling transparency, the entire thing fell off and crumbled to pieces. Rebooting or refreshing did not help.
I have checked the related files, but it's not like I understand what "{{ $value }}" means. I know what it does tho, I just don't know if it is the right way, since it gives off an error, which I attached.
This exact line is pointed out in the error message btw
![image](https://github.com/user-attachments/assets/d7d8264b-3332-4c4a-9db4-f798ed92c7c7)

<details>
<summary>Logs</summary>
Useless
</details>

**Comment by end-4** [comment]
does selecting a wallpaper again fix it?
those {{ $funnyThingies }} are stuff in the template files that should be replaced with the actual values

**Comment by unjaks** [comment]
> does selecting a wallpaper again fix it? those {{ $funnyThingies }} are stuff in the template files that should be replaced with the actual values

I don't really understand how to change the wallpaper in that context, everything is too scuffed to navigate after what happened. Also I tried changing the background_color variable to rgba(0,0,0,0) and others, it didn't help

**Comment by torhaala** [comment]
> > does selecting a wallpaper again fix it? those {{ $funnyThingies }} are stuff in the template files that should be replaced with the actual values
> 
> I don't really understand how to change the wallpaper in that context, everything is too scuffed to navigate after what happened. Also I tried changing the background_color variable to rgba(0,0,0,0) and others, it didn't help

Try to run $HOME/.config/ags/scripts/color_generation/switchwall.sh

**Comment by unjaks** [comment]
> > > does selecting a wallpaper again fix it? those {{ $funnyThingies }} are stuff in the template files that should be replaced with the actual values
> > 
> > 
> > I don't really understand how to change the wallpaper in that context, everything is too scuffed to navigate after what happened. Also I tried changing the background_color variable to rgba(0,0,0,0) and others, it didn't help
> 
> Try to run `$HOME/.config/ags/scripts/color_generation/switchwall.sh`
> 
> or run `$HOME/.config/ags/scripts/color_generation/colorgen.sh path-to-some/wallpaper.jpeg --smart --apply`

Oh hell yeah now it works. My gratitude, u saved me there
