### ISSUE TITLE
Default Hyprland Wallpaper at Startup

### ISSUE THREAD

**Issue by TZProgrammer** [end-4/dots-hyprland#81]
I am using novelknock, and previously I was using w3mm, in both this issue was present. When I boot my system, fifty percent of the time, the default Hyprland wallpaper shows up, instead of the custom one set for swww. Recently, I have activated autologin, and stopped using a login manager to make the boot process faster, and now the custom wallpaper never shows up.

I have tried sending the output of "exec-once swww init", and "exec swww img ...", to some log files, however they are always empty, I am not sure if that is because the commands are not being ran, or if it is an issue with the logging process itself.

To start the wallpaper, now I have to run both swww init and swww img, implying that neither of them ran on boot.

Any help would be appreciated.

**Comment by clsty** [comment]
novelknock and w3mm are deprecated and we does not support it anymore.

The current active variant is "illogical impulse".
See [Wiki](https://end-4.github.io/dots-hyprland-wiki/en) for more.

Closing. 
Feel free to reopen this issue if you still encounter the same problem using the latest version of this repo.
