### ISSUE TITLE
[Issue] About screenshots(flameshot)

### ISSUE THREAD

**Issue by 1677883418** [end-4/dots-hyprland#811]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: 

---
## The issue

<details>
<summary>Logs</summary>

```plain
Paste logs here
```

</details>

In fact, I made it work at archlinuxt, and keybind works like this:

XDG_CURRENT_DESKTOP=sway flameshot gui | wl-copy

hyprland 0.43 work good,but have a question:

Usually I want to edit the image and copy it directly to the clipboard. But I need to manually select in fuzzel once, I want to know how to do it can use directly without manual selection, anyone know?

**Comment by end-4** [comment]
if you want to edit the screenshot before copying to clipboard, pipe your screenshooter to swappy
[see how i did this with grim and slurp](https://github.com/end-4/dots-hyprland/blob/88a0356a949bb2010456abe105ddffec443ea7bc/.config/hypr/hyprland/keybinds.conf#L27)

**Comment by 1677883418** [comment]
> if you want to edit the screenshot before copying to clipboard, pipe your screenshooter to swappy [see how i did this with grim and slurp](https://github.com/end-4/dots-hyprland/blob/88a0356a949bb2010456abe105ddffec443ea7bc/.config/hypr/hyprland/keybinds.conf#L27)

thanks for your reply
