### ISSUE TITLE
Shared Library Problem

### ISSUE THREAD

**Issue by 4st3risk** [end-4/dots-hyprland#82]
## issue about shared libraries.
`./allappnames: error while loading shared libraries: libboost_iostreams.so.1.81.0: cannot open shared object file: No such file or directory`

but it's not just allappnames program. other compiled cpp programs are same.
i think the problem is that the version of the shared library required by the program is different from the version of the shared library in user's environment.

so i had to recompile all the programs.
how about creating makefile or shell script to build from user's environment? if possible, you could also consider static build.

**Comment by end-4** [comment]
that `-static` flag should be sufficient right?

**Comment by 4st3risk** [comment]
> that `-static` flag should be sufficient right?

I think so.

**Comment by end-4** [comment]
EWW-powered configs are no longer supported. 
I have moved them to the `archive` branch and no longer provide binaries to keep the repo size small. 
This also means this issue is no longer relevant and therefore I'm closing it
