### ISSUE TITLE
[Issue] how to disabling the app theming

### ISSUE THREAD

**Issue by user12xxxxxx** [end-4/dots-hyprland#821]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: 

---
## The issue
although i like material you theming and appreciate  your work the theming isn't working out for 
is there a way to turn it off (expect for few certain application like foot)

**Comment by Pharmaracist** [comment]
u can by pressing Super+comma and from drop down menu set gradience to off

**Comment by user12xxxxxx** [comment]
thanks

**Comment by Sneethe** [comment]
@user12xxxxxx Here's how you actually disable terminal/foot theming. While retaining the nice GTK theming/gradience

1. `cd .cache/ags/user/generated/terminal`
2. `: > terminal`  Overwrites the file with zero bytes.
3. `sudo chattr +i sequences.txt` Sets the immutable flag, making it so the file can't be written to.

Honestly the automatic terminal theming is just dreadful. As often times the colors make all the terminal content, completely unreadable. In fact I went out of my way to not do any theme/wallpaper changes to avoid this. I do think how it affects all the other UI elements is fantastic though. 
And I can understand having automatic terminal theming for winning very important r*ddit karma (which you need to stockpile  for the next life). But I don't see how its suitable for regular usage. And I imagine a lot of people using a Tiling WM in the first place, already have a workflow that involves a lot of terminal usage. 

@clsty 
But it should probably be toggle-able via either the ags sideright  module or the ~/.config/ags/modules/indicators/colorscheme.js. The terminal theming is handled by the `apply_term` function in ~/.config/ags/scripts/color_generation/applycolor.sh which can easily be called as it own script. Or probably be better for it it be set like the gradience state (in ~/.local/state/ags/user/colormode.txt) handled by the apply_gtk function in the same applycolor.sh script

**Comment by clsty** [comment]
> [@clsty](https://github.com/clsty) But it should probably be toggle-able via either the ags sideright module or the ~/.config/ags/modules/indicators/colorscheme.js. The terminal theming is handled by the `apply_term` function in ~/.config/ags/scripts/color_generation/applycolor.sh which can easily be called as it own script. Or probably be better for it it be set like the gradience state (in ~/.local/state/ags/user/colormode.txt) handled by the apply_gtk function in the same applycolor.sh script

I'm not capable of doing anything for your suggestion. PR is welcomed, however end-4 is the one making decision about AGS related things.

**Comment by Pharmaracist** [comment]
to control further theming and stuff try missing with the color_generation scripts espicially applycolor.sh where you can comment the features u dont like

**Comment by end-4** [comment]
If you want to select what themes to be generated and applied, please use Pharmaracist's solution. It's simple enough and it saves me a lot of hassle for a feature I doubt would benefit many people
