### ISSUE TITLE
Powerview can`t show app icon

### ISSUE THREAD

**Issue by mahaveergurjar** [end-4/dots-hyprland#83]
- **I have read the instructions** and I have a problem with branch: 
---
## The issue
- (describe your problem here)
- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)

I installed
![230917_18h54m01s_screenshot](https://github.com/end-4/dots-hyprland/assets/57872034/dcef1d8e-91c8-4d19-ac09-19f07e224a49)
 eww and used your one widget Powerview but the widget is not working properly

**Comment by end-4** [comment]
try installing your icon pack to `/usr/share/icons` instead of somewhere in your home folder
man i still have to add that to the readme

**Comment by mahaveergurjar** [comment]
Already icons are in /usr/share/icons 
![230917_21h48m07s_screenshot](https://github.com/end-4/dots-hyprland/assets/57872034/ec66795f-c52a-44d0-b4aa-cd0b07f73fd7)

**Comment by end-4** [comment]
how's the result for the 2nd bullet point i wrote?

**Comment by TZProgrammer** [comment]
I have a similar problem, but slightly different, it might be related.

For me, the icons appear for a frame or two, before disappearing. The end result is just like the screenshot above. I am using novelknock.

**Comment by mahaveergurjar** [comment]
> how's the result for the 2nd bullet point i wrote?

![230918_20h17m27s_screenshot](https://github.com/end-4/dots-hyprland/assets/57872034/39a7f1db-657d-4778-8833-914cf8899165)
![230918_20h17m45s_screenshot](https://github.com/end-4/dots-hyprland/assets/57872034/10326f30-68f2-49f3-9a52-9b871a7f1c0e)

**Comment by end-4** [comment]
I have switched from EWW to AGS, which makes widget creation much easier and less hacky. It definitely does not have an icon problem like this.

I can no longer support EWW-powered configs, so I'm closing this issue.

**Comment by mahaveergurjar** [comment]
Ok
