### ISSUE TITLE
Thick Splash Screen Borders

### ISSUE THREAD

**Issue by whoslucifer** [end-4/dots-hyprland#833]
Anytime I run an app that displays a splash screen before the actual window shows up, a very thick outline shows up around the border....or rather as the border. However, this does not seem to affect anything JetBrains. It mostly affects floating windows like file pickers and splash screens

![image](https://github.com/user-attachments/assets/7698c95b-df9e-4fa7-97da-4c593dbf1993)

**Comment by s0mesh1t** [comment]
same problem

**Comment by whoslucifer** [comment]
> same problem

Hey.I dont think this is an issue with his dots. I have being working on my new setup on nixos from scratch and burpsuite still opens with those thick black borders on hyprland ... as usual. I think it MIGHT be a burpsuite problem because all JetBrains apps have a splash screen of almost the same size with burp but they are not affected by this at all

**Comment by sh1zicus** [comment]
> > same problem
> 
> Hey.I dont think this is an issue with his dots. I have being working on my new setup on nixos from scratch and burpsuite still opens with those thick black borders on hyprland ... as usual. I think it MIGHT be a burpsuite problem because all JetBrains apps have a splash screen of almost the same size as burp but they dont seem to be affected by this at all.
> 
> Besides burpsuite itself is written in Java with SwingUI and we all know how ugly Java UI can get

I have this problem on almost all windows that run on xwayland, I don’t use JetBrains
