### ISSUE TITLE
[bug] The fuzzel argument is outdated and needs to be replaced

### ISSUE THREAD

**Issue by yuneguy** [end-4/dots-hyprland#841]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: arch

---
## The report
The fuzzel argument is outdated and needs to be replaced
```--match-mode fzf``` instead of ```--no-fuzzy```. check https://github.com/end-4/dots-hyprland/issues/805

<details>
<summary>Logs</summary>

```plain
pkill fuzzel || ~/.local/bin/fuzzel-emoji
error: --no-fuzzy: invalid option

pkill fuzzel || cliphist list | fuzzel --no-fuzzy --dmenu | cliphist decode | wl-copy
error: --no-fuzzy: invalid option
extracting id: input not prefixed with id
```
</details>

**Comment by end-4** [comment]
fixed in #810
