### ISSUE TITLE
night light keep turning when i reboot or log out and log in

### ISSUE THREAD

**Issue by hdgetban** [end-4/dots-hyprland#849]
for some reason  night light  just keeps turning on i wanna disable it forever because it feels annoying disabling it everytime when i log out or reboot

**Comment by sadi-gg** [comment]
Facing the same problem. Got any solution?

**Comment by hdgetban** [comment]
The only solution I did was using another hyprland dotfiles and is honestly bit better

**Comment by sadi-gg** [comment]
Fount it. Just comment out 
exec-once = /usr/lib/geoclue-2.0/demos/agent & gammastep
this line from ~/.config/hypr/hyprland/execs.conf

**Comment by hdgetban** [comment]
O thanks

**Comment by end-4** [comment]
looks like this is solved? i'm closing, but feel free to reopen if you need further assistance with this
