### ISSUE TITLE
Issues in the winbar eww window (Windoes rice)

### ISSUE THREAD

**Issue by invincibleinventor** [end-4/dots-hyprland#85]
- **I have read the instructions** and I have a problem with branch: Windoes
---
## The issue
Hey! So I have 2 concerns with the windoes rice. So one is the icons hv not loaded. Some of the icons in the all apps section have been loaded. I have copied the icons folder to my `usr/share/icons` directory and have restarted several times but still the icons keep failing. All required dependencies and packages installed. I use arch btw (not so proud flex :P)

Secondly, let's say I have kitty open, and I open chrome. The winbar dosent show chrome in the app tray unless I do an `eww reload`. Same applies for closing. Until I reload eww after closing an app, it dosen't leave the active apps tray. Please look onto these issues. Thanks :D 

PS: Running `eww open winbar` through the `~/.config/hypr/execs.conf` file dosent show any active window icons in the tray at all and the volume/wifi/battery controls dont work. So I had to close winbar and reopen it in the` ~/.config/hypr/execs.conf `file. That somehow seems to fix it.

**Comment by invincibleinventor** [comment]
Nvm, i did a clean reinstall of my system and these dotfiles and seems to work. The nightlight dosent work tho, how do I fix it? The module dosent load. Just the text night light appears on the right side window (eww)

**Comment by invincibleinventor** [comment]
Nvm, After a clean reinstall of my machine, these dotfiles seem to work. But the nightlight dosent seem to work. The text night light appears on the right side quick settings eww window but the module dosent seem to load anything unlike the wifi, bluetooth modules.

**Comment by end-4** [comment]
hyprland is a bit messy with shaders.
does `hyprctl keyword decoration:screen_shader '~/.config/hypr/shaders/extradark.frag'` (make sure that shader file is there) work?

**Comment by end-4** [comment]
Turns out, to unset the shader path, we should set it to `[[EMPTY]]`. If you're still using the setup (I doubt you do, but just in case), make [anything that tries to set the keyword to a blank (`''`)] set that value instead.

I am closing this issue as I've switched from EWW to AGS, and I can no longer support the `windoes` branch.
