### ISSUE TITLE
[Issue] Hyprlock problems

### ISSUE THREAD

**Issue by VaiTheCatto** [end-4/dots-hyprland#852]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/ (funny cuz this page shows a 404 error but this one dosen't: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/)
- I have made sure that both my config and system packages are up to date ✅
- Linux distro: CachyOS (Arch) 🔥🔥🔥 

---
## The issue
My Hyprlock config resets everytime I change something in rules.conf or change my colourscheme

## What is supposed to happen:
After changing my desired config in rules.conf, 
Locking Hyprland using Super+L is supposed to keep my hyprlock config (cool catppuccin config I made)

## What's actually happening:
Resets back to the default config that the dotfiles come with for hyprlock (the ugly unconfigured black theme)

### Why I'm making this issue:
its making me annoyed that i have to change it back to (cool catppuccin config I made) everytime :(

**Comment by EvanSunde** [comment]
You need to edit this file not the one in hypr folder

```sh
~/.config/ags/scripts/templates/hypr/hyprlock.conf
```

**Comment by VaiTheCatto** [comment]
@EvanSunde thank you! that fixed my issue!
