### ISSUE TITLE
[Issue] download failure

### ISSUE THREAD

**Issue by CloseCoder** [end-4/dots-hyprland#859]
Command "yay -S --needed --noconfirm --asdeps adw-gtk-theme-git qt5ct qt5-wayland fontconfig ttf-readex-pro ttf-jetbrains-mono-nerd ttf-material-symbols-variable-git ttf-space-mono-nerd ttf-rubik-vf ttf-gabarito-git fish foot starship" has failed.
You may need to resolve the problem manually BEFORE repeating this command.

**Comment by CloseCoder** [comment]
RROR: Failure while downloading https://github.com/googlefonts/rubik/raw/e337a5f69a9bea30e58d05bd40184d79cc099628/fonts/variable/Rubik[wght].ttf
    Aborting...

**Comment by CloseCoder** [comment]
help me

**Comment by Singhzing-kid1** [comment]
[](https://aur.archlinux.org/packages/ttf-rubik-vf)

^^
you have to clone the repo off the AUR and edit the PKGBUILD

specific directions are at that link.
