### ISSUE TITLE
Change Sidebar Popup Position

### ISSUE THREAD

**Issue by whoslucifer** [end-4/dots-hyprland#861]
Earlier on , I used to be able to change the option of the left and right sidebars popping from the top and instead make them popup from the left and right sides respectively.

However I cant seem to find where the config file for this is located anymore.Where is it

**Comment by fruitsaladchan** [comment]
in $HOME/.config/hypr/hyprland/rules.conf

change these lines:

layerrule = animation slide top, sideleft.*
layerrule = animation slide top, sideright.*

to:

layerrule = animation slide left, sideleft.*
layerrule = animation slide right, sideright.*

**Comment by whoslucifer** [comment]
> slide top, sideleft.* layerrule = animation slide top, sideright.*

Thanks

**Comment by end-4** [comment]
thanks to this i had a second thought about the animation and decided to make the sidebars come from the sides again https://github.com/end-4/dots-hyprland/commit/7152dc12a0a9292eac43c55ea472291a6f250b9d

thank you i guess
