### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Neil-Tomar** [end-4/dots-hyprland#863]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Arch btw

---
## The issue
i just enabled tranceparency and BOOM!!! 
![zscreenshot](https://github.com/user-attachments/assets/36d8b36d-7c3c-4693-aebc-9b7f2691eedb)

and the error says ~/.conig/hypr/hyprlnad/colors.conf the rgba value is incoorect and when i fixed the value and replace with misc {
    background_color = rgba(1D1011FF)
}

it just fixed the error and eveything is same no icons no animations and nothing please fix it

<details>
<summary>Logs:-
pkill ags; ags

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.948: Theme parsing error: gtk.css:87:30: '' is not a valid color name

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:87:44: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:88:46: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:89:41: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:90:47: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:91:49: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:92:44: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:97:41: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:98:43: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:99:47: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:100:49: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:101:42: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:102:44: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:104:60: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:105:62: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:108:45: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:109:55: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:111:55: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:112:57: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:113:56: Expected a valid selector

(com.github.Aylur.ags:10013): Gtk-WARNING **: 14:34:05.949: Theme parsing error: gtk.css:114:58: Expected a valid selector
Another system tray is already running

(com.github.Aylur.ags:10013): Gjs-Console-CRITICAL **: 14:34:06.652: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/Neil/.cache/ags/user/generated/style.css

(com.github.Aylur.ags:10013): Gjs-Console-WARNING **: 14:34:06.746: Error: can't assign "chromium-browser" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:25:14
newIcon@resource:///com/github/Aylur/ags/widgets/icon.js:8:12
ElementTile@file:///home/Neil/.config/ags/modules/cheatsheet/periodictable.js:26:32
default/mainBoard<.children</<.children<@file:///home/Neil/.config/ags/modules/cheatsheet/periodictable.js:62:58
default/mainBoard<.children<@file:///home/Neil/.config/ags/modules/cheatsheet/periodictable.js:62:27
default@file:///home/Neil/.config/ags/modules/cheatsheet/periodictable.js:60:33
SheetContent/sheetContents[id]<.children<@file:///home/Neil/.config/ags/modules/cheatsheet/main.js:82:48
SheetContent@file:///home/Neil/.config/ags/modules/cheatsheet/main.js:82:31
default@file:///home/Neil/.config/ags/modules/cheatsheet/main.js:91:32
forMonitors@file:///home/Neil/.config/ags/config.js:29:24
Windows@file:///home/Neil/.config/ags/config.js:47:5
@file:///home/Neil/.config/ags/config.js:75:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class
</summary>

**Comment by Neil-Tomar** [comment]
oh just fixed it No worries

**Comment by rasjonell** [comment]
@Neil-Tomar how did you end up fixing it? getting the same issue rn :(

**Comment by Necora1** [comment]
Same issue here

**Comment by Neil-Tomar** [comment]
@rasjonell i just changed wallpaper with a keyboard shortcut and the issue was fixed immediately i don't remember what it was and i recently switched from this because the is a lot buggy and lacking the smoothness so i changed mine to Hyprdot you can check that out its grate

**Comment by rasjonell** [comment]
@Neil-Tomar @Necora1 
I noticed that some people were able to fix it by setting a wallpaper but it didn't work for me, apparently my issue was with the gradience-cli, had to re-compile it by changing some of the source files as it targeted a different python version than what i was using.
