### ISSUE TITLE
Wrong ags font

### ISSUE THREAD

**Issue by whoslucifer** [end-4/dots-hyprland#864]
I did a full wipe and reinstall yesterday and I now have some weird font on all of ags components. Which font was ags using

**Comment by Lenochxd** [comment]
Hey! The Rubik AUR package has been fixed this morning (2024-10-13 at 07:40 UTC). I contacted the maintainer yesterday, and the source URLs have been updated, so you shouldn’t need to manually edit it anymore.

**Comment by whoslucifer** [comment]
> Hey! The Rubik AUR package has been fixed this morning (2024-10-13 at 07:40 UTC). I contacted the maintainer yesterday, and the source URLs have been updated, so you shouldn’t need to manually edit it anymore.
> 
> I was able to fix the issue before the AUR package was updated by manually installing it from here: https://github.com/googlefonts/rubik/blob/main/fonts/variable/Rubik%5Bwght%5D.ttf

Okay. Thanks
