### ISSUE TITLE
[Issue] Black boxes around Nautilus menus

### ISSUE THREAD

**Issue by NotAF0e** [end-4/dots-hyprland#873]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Endeavour OS 

---
## The issue
Weird Black boxes around context menus in Nautilus. Probably a gtk theming issue with shadows but no clue how to fix

**Comment by NotAF0e** [comment]
![image](https://github.com/user-attachments/assets/a1edd8cf-e4a8-4289-b8c6-ec09e21395a8)

**Comment by end-4** [comment]
i don't get that
consider asking in hyprland's spaces

**Comment by end-4** [comment]
since i can't reproduce i can't help, sorry
feel free to reopen if you find info that shows it's something with my dotfiles
