### ISSUE TITLE
Not loading everything in time

### ISSUE THREAD

**Issue by tinytempmouse** [end-4/dots-hyprland#88]
when reboot into hyprland the wallpaper sometimes does not auto load and dunst does not load untill i pkill. Im also having issues with icons not loading.

![PXL_20231001_175841760 MP](https://github.com/end-4/dots-hyprland/assets/137355256/de8738a2-2205-416e-a758-8e87f4ed70bd)

**Comment by end-4** [comment]
you can try
- adding a delay to the relevant `exec-once`  line that executes `swww` in `.config/hypr/exec.conf`
- clearing swww cache
- updating swww and install Material Symbols again

I no longer support old EWW-powered setups. I've switched to using AGS, and I can no longer support `NovelKnock` branch, So I'm closing this issue
For the new AGS-powered one (now in main branch), there's an install script that does everything for you, including icon installation. So while I understand that it's unlikely, if you still want a config from me that works properly, you can check that out.
