### ISSUE TITLE
[Issue] blur issue

### ISSUE THREAD

**Issue by ll931217** [end-4/dots-hyprland#880]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Arch Linux

---
## The issue

I was able to get the blur effect to work with [linuxmobile's config](https://github.com/linuxmobile/hyprland-dots), but unable to with this config

`blur:special = true`
![image](https://github.com/user-attachments/assets/4c4f15a7-1efe-4ef1-b438-b3eba1b02eff)

`blur:special = false`
![image](https://github.com/user-attachments/assets/37665df9-8a0f-4070-a867-0f60e01e9ccf)

This screenshot is with blur enabled
`blur:enabled = true`
![image](https://github.com/user-attachments/assets/8fe13575-b40d-49ef-8b1e-809be83aab1d)

Here is my `$XDG_CONFIG_HOME/hypr/custom/general.conf`:

```config
general {
  border_size = 5
  col.active_border = rgba(e5b9c6ff) rgba(c293a3ff) 45deg
  col.inactive_border = 0xff382D2E
  no_border_on_floating = false # enable border on float window
}

cursor {
  no_hardware_cursors = true
}

decoration {
  active_opacity = 1.0
  inactive_opacity = 1.0
  # active_opacity = 0.8
  # inactive_opacity = 0.8

  blur {
    ignore_opacity = true
    special = true
  }

  shadow_offset = 1 2
}

misc {
  enable_swallow = true
}

dwindle {
	pseudotile = true
}
```

<details>
<summary>Logs</summary>

Not much information in the logs but here it is

```plain
[LOG] Instance Signature: 4520b30d498daca8079365bdb909a8dea38e8d55_1729298069_98651021
[LOG] Runtime directory: /run/user/1000/hypr/4520b30d498daca8079365bdb909a8dea38e8d55_1729298069_98651021
[LOG] Hyprland PID: 1297
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: BaoArch
[LOG] Release: 6.11.3-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000


[LOG] GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti GDDR6X] [10de:24c9] (rev a1) (prog-if 00 [VGA controller])
10:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c6) (prog-if 00 [VGA controller])


[WARN] Warning: you're using an NVIDIA GPU. Make sure you follow the instructions on the wiki if anything is amiss.

[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: "Hyper".replace("e", "")


[LOG] Old rlimit: soft -> 1024, hard -> 524288
[LOG] New rlimit: soft -> 524288, hard -> 524288
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 15.33µs. Estimated average calc time: 0.04µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 5.30µs. Estimated average calc time: 0.03µs.
[LOG] Using config: /home/ll931217/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
```

</details>

**Comment by D3ja-vu** [comment]
you need this on ur blur config 
ignore_opacity = true
new_optimizations = true

**Comment by ll931217** [comment]
> you need this on ur blur config 
> ignore_opacity = true
> new_optimizations = true

I have those options, the default `general.conf` contains `new_optimizations = true`, I have also tried including it in my own config but still no difference.

**Comment by D3ja-vu** [comment]
try remove the shadowing i have faced some prplems with it thats my config u can try it decoration {
    rounding = 6
    blur {
        enabled = true
        size = 12
        passes = 4
        new_optimizations = true
        ignore_opacity = true
    }
    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

**Comment by ll931217** [comment]
So using your exact options didn't have any effect. To make it easier, I added my Hyprland configs [here](https://github.com/ll931217/dotfiles/tree/master/.config/hypr)

**Comment by fruitsaladchan** [comment]
blur settings is already defined in ```~/.config/hypr/hyprland/general.conf ```

you need to comment out the line ```windowrule = noblur,.*``` in ```~/.config/hypr/hyprland/rules.conf```

and change term_alpha=100 in ```~/.config/ags/scripts/color_generation/applycolor.sh``` im using term_alpha=50
and this is what my terminal looks like
![image](https://github.com/user-attachments/assets/d43af34c-87fa-467b-adf9-cefb6ee6ffb1)

**Comment by ll931217** [comment]
> blur settings are already defined in `~/.config/hypr/hyprland/general.conf `
> 
> try to comment out the line `windowrule = noblur,.*` in `~/.config/hypr/hyprland/rules.conf`
> 
> and change term_alpha=100 in `~/.config/ags/scripts/color_generation/applycolor.sh` im using term_alpha=50 and this is what my terminal looks like ![image](https://private-user-images.githubusercontent.com/124645742/379526308-d43af34c-87fa-467b-adf9-cefb6ee6ffb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDUxMTgsIm5iZiI6MTcyOTc0NDgxOCwicGF0aCI6Ii8xMjQ2NDU3NDIvMzc5NTI2MzA4LWQ0M2FmMzRjLTg3ZmEtNDY3Yi1hZGY5LWNlZmI2ZWU2ZmZiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwNDQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWNlYjVjMTkwN2UxNmI3YjM0MDM4MDJlYThjN2ZmY2ZjZGE3ZjRjMmIwZGVmODdjNjE1YjZlNzk5MjI1NTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SRBi-QdQ3i9Ei1aYS61qzLDZKvIzkCnIbUNawR-ee88)

Thank you! Can't believe I didn't check that file, that fixed it for me thanks so much!

**Comment by greed-d** [comment]
hello sorry for necro bumping this issue, but I can't enable blur for other applications apart from foot. How can I accomplish that 
@fruitsaladchan

**Comment by fruitsaladchan** [comment]
uhhh did you try setting opacity rules for the other apps ? for example i use this rule for nautilus in rules.conf

```bash
windowrulev2 = opacity 0.79, class:^(org.gnome.Nautilus)(.*)$

```
