### ISSUE TITLE
[Issue] Bluetooth doesn't work

### ISSUE THREAD

**Issue by kripikripi** [end-4/dots-hyprland#882]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Arch Linux
---
## The issue

The built-in Bluetooth app shows that it's working but doesn't display any Bluetooth devices. The scan doesn't work in bluetoothctl either. I have bluez and bluez-utils installed, restarting bluetooth.service doesn't change anything too.
<details>
<summary> </summary>

```plain
sudo bluetoothctl
hci0 new_settings: powered bondable ssp br/edr le secure-conn wide-band-speech 
[bluetooth]# Agent registered
[bluetooth]# [CHG] Controller 34:CF:F6:B5:A6:39 Pairable: yes
[bluetooth]# scan on
[bluetooth]# SetDiscoveryFilter success
[bluetooth]# Failed to start discovery: org.bluez.Error.InProgress
[bluetooth]# scan off
[bluetooth]# Failed to stop discovery: org.bluez.Error.Failed
```

</details>

**Comment by monstaflame** [comment]
Hello, how did you fix this ? I've the same issue on hyprland 0.45 on arch
