### ISSUE TITLE
[Feature]  add a option to reduce round corners 

### ISSUE THREAD

**Issue by nx-smul** [end-4/dots-hyprland#885]
**What would you like to be added?**
add a option to increase decrease round corners

**How will it help**
I hate round corners

**Comment by alr86** [comment]
You hate rounded corners, yet you installed a Material-you configuration!?

**Comment by yashslakhtariya** [comment]
The option is there. Change value in hyprland configuration. Maybe general.conf in hyprland directory

**Comment by alr86** [comment]
https://github.com/end-4/dots-hyprland/issues/423#issuecomment-2063607478

**Comment by alr86** [comment]
> **What would you like to be added?** add a option to increase decrease round corners
> 
> **How will it help** I hate round corners

It's there: https://github.com/end-4/dots-hyprland/issues/423#issuecomment-2063607478

**Comment by nx-smul** [comment]
> > **What would you like to be added?** add a option to increase decrease round corners
> > **How will it help** I hate round corners
> 
> It's there: [#423 (comment)](https://github.com/end-4/dots-hyprland/issues/423#issuecomment-2063607478)

thanks man worked

**Comment by alr86** [comment]
> thanks man worked

You can close this issue if you don't have any other questions.
