### ISSUE TITLE
fcitx5 cannot float above ags component

### ISSUE THREAD

**Issue by gitttyyy** [end-4/dots-hyprland#894]
https://github.com/user-attachments/assets/d1eed075-45d4-4167-b2b5-0d8d1cd87bf0

like this, whether it's the search box or the sidebar

**Comment by end-4** [comment]
I can't remember why I had those components shown on `overlay` (on top of absolutely everything except pointer) layer...
I made them show on `top` layer, the way they should be. Does that fix it?

**Comment by gitttyyy** [comment]
> I can't remember why I had those components shown on `overlay` (on top of absolutely everything except pointer) layer... I made them show on `top` layer, the way they should be. Does that fix it?

 It's fixed. Thank you for your excellent work!!!
