### ISSUE TITLE
[Issue] Ags does not show icons, just text

### ISSUE THREAD

**Issue by Mimogu** [end-4/dots-hyprland#898]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: openSUSE Tumbleweed

---
## The issue
The bar does not show the icons, it just shows text.

<details>
<summary>Logs</summary>

┌─[mimogu@localhost] - [~] - [Sat Oct 26, 03:29]
└─[$] <> ags

(com.github.Aylur.ags:18369): Gjs-Console-WARNING **: 03:29:44.815: Error: can't assign "desktop-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:25:14
newIcon@resource:///com/github/Aylur/ags/widgets/icon.js:8:12
default/<.child<.children<@file:///home/mimogu/.config/ags/modules/sideleft/tools/quickscripts.js:76:21
default@file:///home/mimogu/.config/ags/modules/sideleft/tools/quickscripts.js:70:27
@file:///home/mimogu/.config/ags/modules/sideleft/toolbox.js:14:13
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

Gjs-Console-Message: 03:29:45.280: [LOG] Styles loaded

(com.github.Aylur.ags:18369): Gjs-Console-WARNING **: 03:29:45.421: Error: can't assign "chromium-browser" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:25:14
newIcon@resource:///com/github/Aylur/ags/widgets/icon.js:8:12
ElementTile@file:///home/mimogu/.config/ags/modules/cheatsheet/periodictable.js:26:32
default/mainBoard<.children</<.children<@file:///home/mimogu/.config/ags/modules/cheatsheet/periodictable.js:62:58
default/mainBoard<.children<@file:///home/mimogu/.config/ags/modules/cheatsheet/periodictable.js:62:27
default@file:///home/mimogu/.config/ags/modules/cheatsheet/periodictable.js:60:33
SheetContent/sheetContents[id]<.children<@file:///home/mimogu/.config/ags/modules/cheatsheet/main.js:82:48
SheetContent@file:///home/mimogu/.config/ags/modules/cheatsheet/main.js:82:31
default@file:///home/mimogu/.config/ags/modules/cheatsheet/main.js:91:32
forMonitors@file:///home/mimogu/.config/ags/config.js:29:24
Windows@file:///home/mimogu/.config/ags/config.js:47:5
@file:///home/mimogu/.config/ags/config.js:75:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

![image](https://github.com/user-attachments/assets/af9ea8cc-d669-4d67-b6dd-8f3b62643c6e)

</details>

**Comment by Mimogu** [comment]
Just found out the there was a similar issue made before and it was  asked to write this command

```sass -I ~/.local/state/ags/scss -I ~/.config/ags/scss/fallback ~/.config/ags/scss/main.scss ~/.cache/ags/user/generated/style.css```

for me it showed no errors

**Comment by Mimogu** [comment]
now I am getting this error when launching ags

```
(com.github.Aylur.ags:2147): Gtk-WARNING **: 20:18:54.312: Theme directory 256/applets of theme OneUI-dark has no size field


(com.github.Aylur.ags:2147): Gtk-WARNING **: 20:18:54.321: Theme directory 16@2x/emblems of theme OneUI-dark has no size field


(com.github.Aylur.ags:2147): Gtk-WARNING **: 20:18:54.323: Theme directory 22@2x/devices of theme OneUI-dark has no size field


(com.github.Aylur.ags:2147): Gtk-WARNING **: 20:18:54.324: Theme directory 22@2x/emblems of theme OneUI-dark has no size field


(com.github.Aylur.ags:2147): Gtk-WARNING **: 20:18:54.326: Theme directory 256@2x/applets of theme OneUI-dark has no size field


Gjs-Console-Message: 20:18:54.789: [LOG] Styles loaded
```

**Comment by Pharmaracist** [comment]
make sure that u downloaded material font

**Comment by Mimogu** [comment]
> make sure that u downloaded material font

I installed the font and still it did not do anything

**Comment by Mimogu** [comment]
I installed the font and still it did not do anything @Pharmaracist

**Comment by Pharmaracist** [comment]
install ttfs in /usr/share/fonts 
then fc-cache -fc
consider double checking lib-mixens.scss

**Comment by Mimogu** [comment]
After looking a bit more I basically had to download the Material Symbols Outlined, Material Symbols Rounded, and Material Symbols Sharp, and it works fine for me now. Thanks for helping.

**Comment by ZeyadMoustafaKamal** [comment]
close the issue
