### ISSUE TITLE
eww bar width change(and the workspaces are not showing up)

### ISSUE THREAD

**Issue by winder2412** [end-4/dots-hyprland#9]
hi i really like your eww config but i have a 1366x768 display and i wanted to change the width and hight a little bit 

and also the workspaces are not showing up (i'm using Hyprland on arch)

**Comment by end-4** [comment]
### Height/width
- There are variables for screen resolution in `.config/eww/modules/variables.yuck`. You should firstly go there and change the variables `RES_WIDTH` and `RES_HEIGHT`. Then you should go to `.config/eww/windows/osettings` `.config/eww/windows/onotify` and change some `:height` there if  those windows are too tall for you. 
- There surely are more things, and it's going to be quite a lot to modify, as sizes are coded in `px`. Some widgets try to adapt to the screen size after you manually set `RES_HEIGHT`/`RES_WIDTH` (like the overview) but not all.

### Workspaces
- Make sure you installed the dependencies (for workspaces, you'll need `gojq`, `rg`, `socat` (maybe more, idr)). Check the readme for a full list.
- If the workspaces from 1 to 10 aren't showing up, please manually run `.config/eww/scripts/workspaces` in the `.config/eww/` directory and see if it runs properly. Show me the output if it doesn't.
- If the active workspace indicator isn't showing up, do the same with `.config/eww/scripts/activews` in `.config/eww/`

**Comment by winder2412** [comment]
thank you so much 🙏🙏🙏🙏🙏🙏🙏🙏
