### ISSUE TITLE
Where is the resolution set?

### ISSUE THREAD

**Issue by Rersive** [end-4/dots-hyprland#90]
Where is the resolution of the taskbar and the desktop menu configured, since I am using it in 1600x900 and 1366x768 resolution. Also, the icons don't load correctly, solution? In windoes dotfiles

**Comment by end-4** [comment]
unfortunately i didn't use rem while for that setup so it can't be scaled
so either get a 1920*1080 screen or use the m3ww branch which supports scaling

**Comment by Rersive** [comment]
Isn't there a way to adjust the resolution? even if it is very difficult I want to learn

**Comment by end-4** [comment]
well there is a way
but it's going to be painful
you have to check every .scss file in `.config/eww/css/` and change every single size in there to make the elements smaller so that they fir your screen

**Comment by end-4** [comment]
and about icons, you should be more specific. which part doesn't show icons? and have you followed the icon cache generation process as mentioned in the instructions?

**Comment by Rersive** [comment]
The icons on the taskbar do not load, nor do they open when I open a program and thank you very much for the resolution

**Comment by Rersive** [comment]
I realize nothing fits, if one day you put it to quickly modify the resolution I will install it again

**Comment by end-4** [comment]
I've switched to AGS and will no longer support EWW-powered configs. So easy resolution modification for an old config is not coming, and I'm closing this issue. I hope you understand.
