### ISSUE TITLE
[Feature] Remove anime stuff

### ISSUE THREAD

**Issue by sh1zicus** [end-4/dots-hyprland#900]
### **What would you like to be added?**
Remove anime stuff

### **How will it help**
The most unnecessary thing that I've used just once to see what it is, I think many have done the same
I suggest cutting it out or making it possible to put it optionally for those who need it

### **Extra info**
 **I like anime UwU**

**Comment by NotAF0e** [comment]
good idea, when i first saw i was like huuuhhhh. i feel like this project should be treated more a DE. is there a discord in the event that a poll is created?

**Comment by s0mesh1t** [comment]
In https://github.com/end-4/dots-hyprland/pull/896 implemented the ability to disable this

**Comment by fruitsaladchan** [comment]
in ```~/.config/ags/modules/.configuration/user_options.js```  remove the ```waifu``` and ```booru```

from:
``` 
pages: {
      order: ["apis", "tools"],
      apis: {
        order: ["gemini", "gpt", "waifu", "booru"],
      },
    },
  },
```

**Comment by iceking-1912** [comment]
hey how to replace it /use it actual anime search

**Comment by end-4** [comment]
`@fruitsaladchan`'s solution above is the intended solution.
I'm not going to remove it entirely.

**Comment by hishemok** [comment]
+1

**Comment by end-4** [comment]
> +1

what are you doing here
the new quickshell version literally greets you with a welcome app that allows you to disable it right on the spot
