### ISSUE TITLE
problems witch DecorConfig

### ISSUE THREAD

**Issue by ensomnia1** [end-4/dots-hyprland#904]
![image](https://github.com/user-attachments/assets/719e965b-77de-4d63-af0a-7161202ef460)
Problem with col.shadow.
After changing it, errors occur; initially it was equal to $color12
![image](https://github.com/user-attachments/assets/617a335d-dbcb-4072-96ac-9124ea3dcbee)

**Comment by hjkbnm911** [comment]
show all UserDecorAnimation.conf

**Comment by ensomnia1** [comment]
> show all UserDecorAnimations.conf
![image](https://github.com/user-attachments/assets/513359c8-81a7-4ce1-ab52-470f8a3c0abc)
![image](https://github.com/user-attachments/assets/247b57b8-33f9-40d0-b203-3a42d8ab69d0)
![image](https://github.com/user-attachments/assets/a2351ae5-a6c7-4a42-bb49-8f6c2188f864)

**Comment by ensomnia1** [comment]
![image](https://github.com/user-attachments/assets/c777c518-6bc9-4f0b-b562-231a24832ba0)



> show all UserDecorAnimations.conf
