### ISSUE TITLE
Blur border around eww widgets

### ISSUE THREAD

**Issue by OnlyCS** [end-4/dots-hyprland#91]
- **I have read the instructions** and I have a problem with branch: 
--- novelknock
## The issue
- Weird blur-border around widgets of eww. How to remove?
(the 1 is there for a test, ignore it thanks!)
- (if it throws errors, **PLEASE**, attach logs and describe in detail if possible)
![image](https://github.com/end-4/dots-hyprland/assets/61358474/1438885f-70e2-4c39-af21-eed58acec948)

**Comment by OnlyCS** [comment]
this can be fixed by commenting out `layerrule = blur,gtk-layer-shell`, but that completely disables blur on eww widgets, and the dashboard looks weird.

**Comment by end-4** [comment]
`layerrule = ignorealpha 0.6,gtk-layer-shell`
get that 0.6 lower until that weird blur disappears while the widgets are still blurred

**Comment by OnlyCS** [comment]
0.5 was the magic value for me, thank you so much for your help!
