### ISSUE TITLE
Trying To Make This Work On Nixos

### ISSUE THREAD

**Issue by whoslucifer** [end-4/dots-hyprland#926]
Am trying to make your ags dots work on nixos and I have installed any dependencies I saw it required but I still get this error and ags doesnt show up. libnotify is installed and notify-send sends a notification as expected

ags

(com.github.Aylur.ags:5320): Gjs-WARNING **: 09:13:07.281: JS ERROR: Error: Requiring Notify, version none: Typelib file for namespace 'Notify' (any version) not found
@file:///home/asherah/.config/ags/services/messages.js:1:31
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by Makrennel** [comment]
Duplicate of #238 

I ended up giving up trying to get it working myself as I just simply couldn't get anything to display from ags, even though ags itself works and there wasn't really any useful error messages to go off for how to fix it.

**Comment by whoslucifer** [comment]
> Duplicate of #238
> 
> I ended up giving up trying to get it working myself as I just simply couldn't get anything to display from ags, even though ags itself works and there wasn't really any useful error messages to go off for how to fix it.

Hey Makrennel. I actually managed to get everything working literally yesterday. However I still need atleast a week to refine everything and remove bloat. 

Checkout my repo and see if it might be helpful

https://github.com/whoslucifer/ags-nix.git
