### ISSUE TITLE
eww top bar is being displayed over apps

### ISSUE THREAD

**Issue by Hcode00** [end-4/dots-hyprland#93]
## The issue

The top bar (the one that contains workspace, time, etc.) covers the content of other apps, and I have to make all windows float to resize them or go to full screen in an app to hide the bar.

I have followed the installation instructions and have all the required packages.

  I'm using:

- Arch Linux
- Kernel: 6.5.7-arch1-1
- Window Manager: Hyprland

**Comment by end-4** [comment]
I've switched to using AGS instead of EWW and won't be supporting configs using the latter. 
So only my newest config is supported, and it doesn't have this problem, so I'm closing this issue.
