### ISSUE TITLE
Notifications stop working after update ( illogical-impulse ).

### ISSUE THREAD

**Issue by VeilSilence** [end-4/dots-hyprland#94]
- **I have read the instructions** and I have a problem with branch: [illogical_impulse](https://github.com/end-4/dots-hyprland/tree/illogical-impulse)
---
## The issue
Title. After update, notifications stop working.
Log below.
[ags_debug.txt](https://github.com/end-4/dots-hyprland/files/13058339/ags_debug.txt)

**Comment by Bennnniiii** [comment]
This may be due to the notification close button not working currently. try deleting everything inside notifications.json in ~/.cache/ags/notifications ( echo "" > ~/.cache/ags/notifications/notifications.json). it could be that it has gotten too large without the ability to clean it up

**Comment by end-4** [comment]
jesus, that thing breaks a lot
also i did mention in the readme that you should use ags 1.3.0
i'll try to update and sort things out later, maybe tomorrow. If you really wanna try it right now, use git checkout and install ags 1.3.0 manually

**Comment by VeilSilence** [comment]
> jesus, that thing breaks a lot also i did mention in the readme that you should use ags 1.3.0 i'll try to update and sort things out later, maybe tomorrow. If you really wanna try it right now, use git checkout and install ags 1.3.0 manually
I builded ags from source. Downloaded 1.3 release, and compile manually.

**Comment by end-4** [comment]
added the button https://github.com/end-4/dots-hyprland/commit/216c39bc9cf202c61115e1eddf6b9ba61a7afc73
try again

**Comment by VeilSilence** [comment]
Clear notifications work now thank you.
Got another problem.
When i press `Super` nothing happens. Ags log when i press super bellow.
[ags.txt](https://github.com/end-4/dots-hyprland/files/13176651/ags.txt)

**Comment by end-4** [comment]
oh guess i forgot to push my hyprland config

**Comment by end-4** [comment]
hmm i did though
can you copy the hyprland config again? the `keybinds.conf` one

**Comment by VeilSilence** [comment]
Yea, works good now. Gonna look all hypr conf now to see if anything i'm missing in future.
One last thing. AGS throwing network errors. Wifi tray bugged for me also, didn't change status in tray. Always ? even when i connected. Tried to resolve my my side without luck.  Double checked all dependency. Maybe i should create separate issue? 
[ags.debug.txt](https://github.com/end-4/dots-hyprland/files/13178451/ags.debug.txt)

**Comment by end-4** [comment]
i'm closing this issue since the problem with notifications has been resolved
i suggest you try [aylur's config](https://github.com/Aylur/dotfiles) and see if the same error appears. if yes, ags issue. else, my issue (quite unlikely, as i copied most network/wifi backend from his setup)
