### ISSUE TITLE
No Icons

### ISSUE THREAD

**Issue by whoslucifer** [end-4/dots-hyprland#940]
I was using your nixos dots from the cirnos repo and decided to move to these because the old ones are really buggy.
All icons and text rendered just fine on the dots from cirnos. I copied the ags folder from this repo and installed ddcutil and sass .Both material-symbols and material-icons are already installed.

![image](https://github.com/user-attachments/assets/6ebdbd67-05fa-49b2-824d-014ca0cc9e05)

The photo above is when I use the dots from the cirnos repo and icons are shown correctly so missing fonts cant be the issue here

I saw this issue #174 and went through it. Did you change anything or what other dependencies do I need to install ?

This is how things look

![image](https://github.com/user-attachments/assets/7d6e8960-d123-4eae-9296-0c84ae4340fe)
![image](https://github.com/user-attachments/assets/9f0238f4-bfb6-4b99-82a2-ab781a9d92b3)
![image](https://github.com/user-attachments/assets/c9d4fc10-5b3f-4a81-a346-19076e1ef9c4)
![image](https://github.com/user-attachments/assets/1852bdf0-ed1f-4ab9-b209-0f34eca8368d)
![image](https://github.com/user-attachments/assets/5c03840a-b980-41d6-b141-5220493d305b)

This is the error am getting when I run ags

```
ags
  
  (com.github.Aylur.ags:124760): Gjs-Console-WARNING **: 21:43:47.263: Error: can't assign "desktop-symbolic" as icon, it is not a file nor a named icon
  set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
  _handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
  Icon@resource:///com/github/Aylur/ags/widgets/icon.js:25:14
  newIcon@resource:///com/github/Aylur/ags/widgets/icon.js:8:12
  default/<.child<.children<@file:///home/asherah/.config/ags/modules/sideleft/tools/quickscripts.js:76:21
  default@file:///home/asherah/.config/ags/modules/sideleft/tools/quickscripts.js:70:27
  @file:///home/asherah/.config/ags/modules/sideleft/toolbox.js:14:13
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
    
  
  No /dev/i2c devices exist.
  ddcutil requires module i2c-dev.
  
  (com.github.Aylur.ags:124760): Gjs-Console-CRITICAL **: 21:43:48.354: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/asherah/.cache/ags/user/generated/style.css
  Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class
  
  (com.github.Aylur.ags:124760): Gjs-CRITICAL **: 21:43:48.917: JS ERROR: TypeError: self.children[previousShownIndex] is undefined
  IconTabContainer/setup/<@file:///home/asherah/.config/ags/modules/.commonwidgets/tabcontainer.js:116:13
  hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
  
  (com.github.Aylur.ags:124760): Gtk-WARNING **: 21:43:48.917: Child name '0' not found in GtkStack

```

**Comment by adnansumi98** [comment]
I also faced the same issue. Use shortcut for color scheme Super/Windows + Comma key. Turn off this as shown below

![image](https://github.com/user-attachments/assets/47c0440d-4acd-461d-b66f-803f9fed474e)

**Comment by whoslucifer** [comment]
> I also faced the same issue. Use shortcut for color scheme Super/Windows + Comma key. Turn off this as shown below
> 
> ![image](https://private-user-images.githubusercontent.com/62370865/385486142-47c0440d-4acd-461d-b66f-803f9fed474e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzExMzAsIm5iZiI6MTczMTQ3MDgzMCwicGF0aCI6Ii82MjM3MDg2NS8zODU0ODYxNDItNDdjMDQ0MGQtNGFjZC00NjFkLWI2NmYtODAzZjlmZWQ0NzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA0MDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZTZmNWZkMmQ5YTFjYTM2M2VmNWQ3ZWMwNjM2YmU2YjU2ODkyYzM2MDEzNzRkNTFkMjAwMDE4NTk5NDdiZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.asazKlZxhk69nACoVPIBpwDmyXSmLl66z8OFwDfToaE)

Super + comma didnt work . What do you mean turn off this as shown below

**Comment by xyriku** [comment]
I've also faced this once i clicked the transparency button once, and this fixed issue https://github.com/end-4/dots-hyprland/issues/655 fixed it for me with the "set a wallpaper". I still have errors from that command showing, but for the most part, everything seems to be working now.

**Comment by whoslucifer** [comment]
> I've also faced this once i clicked the transparency button once, and this issue #655 fixed it for me with the "set a wallpaper". I still have errors from that command showing, but for the most part, everything seems to be working now.

That didnt work

**Comment by whoslucifer** [comment]
I replaced the scss files with the ones from the cirnos repo and it worked but I had to sacrifice color-generations when I switch the wallpaper. Ill have to remake all color generaions scripts to work on nixos with material_color_utilities instead of       materialyoucolor
