### ISSUE TITLE
[Issue] UI changed (Error)

### ISSUE THREAD

**Issue by Tamarindtype** [end-4/dots-hyprland#944]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date.
- Linux distro: Arch Linux (6.11.7.zen1-1zen)

---
## The issue
Messing around testing any features after installed the dotfiles just like a normal kid, but then the error occur when I clicked the blur in Tune live config  on the right sidebar.

<details>
<summary>Logs</summary>

![SHA_20241115_050629105_8 4 400](https://github.com/user-attachments/assets/40b63a97-1c95-41e4-b3b3-54887c339741)

```plain
Config error in file /home/<user>/.config/hypr/hyprland/colors.conf at line 9: rgba() expects length of 8 characters (4 bytes) or 4 comma separated values
Config error in file /home/<user>/.config/hypr/hyprland.conf at line 9.

# ~/.config/hypr/hyprland/colors.conf @ LINE 9
       background_color = rgba({{ #surface }}FF)

# ~/.config/hypr/hyprland.conf @ LINE 9
       source=~/.config/hypr/hyprlands/colors.conf
```
How to fix the error?

Thanks.
</details>

**Comment by DorianXVI** [comment]
In my case installing python-materialyoucolor-git solved it

**Comment by short-circuit** [comment]
set a wallpaper with `CTRL+SUPER/META+T` before messing with styling. You get a notification first thing when installing the dotfiles

**Comment by Tamarindtype** [comment]
> set a wallpaper with `CTRL+SUPER/META+T` before messing with styling. You get a notification first thing when installing the dotfiles

Ok thanks, maybe i'll try it later because it takes so much time to install this dotfiles lol.

i'll close this.
