### ISSUE TITLE
Brightness OSD non-functional 

### ISSUE THREAD

**Issue by Bennnniiii** [end-4/dots-hyprland#95]
- **I have read the instructions** and I have a problem with branch: Illogical-Impulse

the issue is simple, the brightness OSD doesn't update properly, it gets the value of the brightness at init (say 30) and then it doesnt reflect changes made to the brightness of the screen ( the key is pressed -> the brightness changes, the OSD pops out -> but the change in brightness is not reflected in the number in the OSD or the bar) audio OSD works just fine, except mute which doesnt seem to be indicated (just a missing feature i suspect and not a bug). down below are the logs, each of the single lines is printed every time i hit the brightness keys, and the big block up front is only printed once when the keys are pressed, and never again

(ags:96996): Gjs-WARNING **: 23:13:48.947: JS ERROR: Exception in method call: RunJs: TypeError: (intermediate value).Audio.speaker is undefined
speaker@file:///home/benjamin/.config/ags/modules/osd.js:28:23
speaker@file:///home/benjamin/.config/ags/modules/osd.js:70:43
anonymous@resource:///com/github/Aylur/ags/app.js line 176 > Function:3:11
RunJs@resource:///com/github/Aylur/ags/app.js:176:30
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

(ags:96996): GLib-GObject-CRITICAL **: 23:13:48.958: g_object_notify: object class 'Gjs_BrightnessService' has no property named 'screen-value'

(ags:96996): GLib-GObject-CRITICAL **: 23:13:52.373: g_object_notify: object class 'Gjs_BrightnessService' has no property named 'screen-value'

(ags:96996): GLib-GObject-CRITICAL **: 23:13:53.108: g_object_notify: object class 'Gjs_BrightnessService' has no property named 'screen-value'

(ags:96996): GLib-GObject-CRITICAL **: 23:13:56.901: g_object_notify: object class 'Gjs_BrightnessService' has no property named 'screen-value'

(ags:96996): GLib-GObject-CRITICAL **: 23:13:57.431: g_object_notify: object class 'Gjs_BrightnessService' has no property named 'screen-value'

**Comment by end-4** [comment]
clone again, i updated to make it work with ags 1.5.0

**Comment by Bennnniiii** [comment]
Works now, thank you !
