### ISSUE TITLE
[Issue] WTF is this EMOJI

### ISSUE THREAD

**Issue by ZeyadMoustafaKamal** [end-4/dots-hyprland#954]
So I found this https://github.com/end-4/dots-hyprland/blob/main/.local/bin/fuzzel-emoji#L1689. which makes me ask. where you got these emojis from ? BTW I don't care about your political point of view about this topic. But I don't think it's a good thing to have these in an OSS. I hope that you fix it.

**Comment by ZeyadMoustafaKamal** [comment]
Sorry my mistake

**Comment by Pharmaracist** [comment]
no its not and it should be fixed

**Comment by ZeyadMoustafaKamal** [comment]
It's just a reading mistake. I thought it's "terrorists" but it's "territories".

**Comment by Pharmaracist** [comment]
no both were written i double checked it its from fuzzel.ini "ksom israel"
