### ISSUE TITLE
[Feature] how do i get the old battery style from hyprland - hall of fame thing

### ISSUE THREAD

**Issue by Pharmaracist** [end-4/dots-hyprland#960]
i came across the old style of illogical-impulse and i wonder how can i bring this battery style back and couldn't figure out how 
![image](https://github.com/user-attachments/assets/b0f9504e-b14c-4c31-a215-2bccbb746b7a)
can you drop the old scss styling

**Comment by Blade04208** [comment]
perhaps try looking through https://github.com/end-4/dots-hyprland/tree/archive

if you cant see it, [check old commits](https://github.com/end-4/dots-hyprland/commits/main/) and see if you can find it

**Comment by Pharmaracist** [comment]
actually made it better i ended up editing all the dots 👉👈
