### ISSUE TITLE
Ags widgets are not starting

### ISSUE THREAD

**Issue by MdotAmaan** [end-4/dots-hyprland#98]
- **I have read the instructions** and I have a problem with branch:  illogical_impulse
---
## The issue
- Upon launching ags, it shows the following in the terminal
![image](https://github.com/end-4/dots-hyprland/assets/38326222/34d49b95-34ce-4ef0-af00-ec6d400537f6)
Also, the README says that I should use ags 1.5, but the newest version i see on the repo is 1.4. Was that a typo or is there a version 1.5 somewhere?

**Comment by end-4** [comment]
oh, just clone and compile
1.5.0 is what `ags --version` returns

**Comment by MdotAmaan** [comment]
Oh. Upon checking `ags --version`, for some reason I was stuck on 1.3 even after updating the -git package from the aur. Everything loads now.

**Comment by riloraspopo** [comment]
i can't get ags 1.5.0, clone new git and make, got 1.5.1 and i got error on running ags

(com.github.Aylur.ags:4815): Gjs-Console-WARNING **: 14:07:53.594: Calling Widget({ type }) is deprecated. Use Widget.subclass instead, or open up an issue/PR to include Gtk_DrawingArea on Widget

(com.github.Aylur.ags:4815): Gjs-CRITICAL **: 14:07:53.604: JS ERROR: Error: Expected an object of type GtkWidget for argument 'widget' but got type undefined
setup@file:///home/anonras/.config/ags/windows/desktopbackground/system.js:45:22
set setup@resource:///com/github/Aylur/ags/widgets/widget.js:77:18
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:10:12
AgsOverlay@resource:///com/github/Aylur/ags/widgets/overlay.js:15:31
createCtor/<@resource:///com/github/Aylur/ags/widget.js:22:26
ResourceValue@file:///home/anonras/.config/ags/windows/desktopbackground/system.js:32:9
@file:///home/anonras/.config/ags/windows/desktopbackground/system.js:56:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by riloraspopo** [comment]
clone latest git, got 1.5.1 version, and i still got error

**Comment by riloraspopo** [comment]
(com.github.Aylur.ags:9334): Gjs-Console-WARNING **: 14:27:19.280: Calling Widget({ type }) is deprecated. Use Widget.subclass instead, or open up an issue/PR to include Gtk_DrawingArea on Widget

(com.github.Aylur.ags:9334): Gjs-CRITICAL **: 14:27:19.290: JS ERROR: Error: Expected an object of type GtkWidget for argument 'widget' but got type undefined
setup@file:///home/anonras/.config/ags/windows/desktopbackground/system.js:45:22
set setup@resource:///com/github/Aylur/ags/widgets/widget.js:77:18
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
AgsWidget@resource:///com/github/Aylur/ags/widgets/widget.js:10:12
AgsOverlay@resource:///com/github/Aylur/ags/widgets/overlay.js:15:31
createCtor/<@resource:///com/github/Aylur/ags/widget.js:22:26
ResourceValue@file:///home/anonras/.config/ags/windows/desktopbackground/system.js:32:9
@file:///home/anonras/.config/ags/windows/desktopbackground/system.js:56:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

how to get 1.5.0 version.?
