### ISSUE TITLE
[QUESTION] What app is the Ai assistant app?

### ISSUE THREAD

**Issue by Euphonit** [end-4/dots-hyprland#983]
I really like the AI assistant app that comes with these dot files, but I prefer different dot files. I was wondering what app is the Ai assistant app or where can I get it or is it somewhere in the repo and can I get a version of it that run on my desktop without the rest of the dotfiles?

**Comment by SeeStarz** [comment]
I'm just an user so pardon me if I'm wrong, but you it may be of your interest to look up ags (aylur's gtk shell)

**Comment by Pharmaracist** [comment]
you can make ur own one with aylur ags to make simple api widget or you can clone this one it service and you make ur own interface
