### ISSUE TITLE
[Issue] colors.conf

### ISSUE THREAD

**Issue by HinaHyugaHime** [end-4/dots-hyprland#989]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: 
arch
---
## The issue

upon enabling transparent I get said logs and I cannot fix it or my taskbar now
<details>
<summary>Logs</summary>

```plain
Paste logs here
```
![image](https://github.com/user-attachments/assets/3eb8ae24-5dce-401a-9930-d97eae0d5b64)

</details>

**Comment by HinaHyugaHime** [comment]
secondary issue: how do I install weeb powers version?

**Comment by HinaHyugaHime** [comment]
Third issue: ags lagging(?) Or glitching out and not closing stuff

**Comment by krystlepalace** [comment]
I have the same issue, but even worse. 
All interface just broken.

**Comment by HinaHyugaHime** [comment]
> I have the same issue, but even worse. All interface just broken.

same thing happened to me, if I remember correctly, I changed background and it fixed itself?

**Comment by PlexILIghT** [comment]
Set the bamn background! It's looking for an image in the background for colors, trying to interpret nothing.

**Comment by HinaHyugaHime** [comment]
> Set the bamn background! It's looking for an image in the background for colors, trying to interpret nothing.

First, dont be rude, second, there was a background

**Comment by krystlepalace** [comment]
> > I have the same issue, but even worse. All interface just broken.
> 
> same thing happened to me, if I remember correctly, I changed background and it fixed itself?

I figured this out too. Just changed wallpaper
