### ISSUE TITLE
Not all EWW windows are opening (hybrid, novelknock, windoes, m3ww)

### ISSUE THREAD

**Issue by TheSunCat** [end-4/dots-hyprland#99]
- **I have read the instructions** and I have a problem with branch: 
windoes

## The issue
- Pressing the buttons in the bottom bar does not open any window (but the buttons look pressed)

Logs for opening the winbar and then clicking the Windows button:
[logs.txt](https://github.com/end-4/dots-hyprland/files/13176239/logs.txt)

**Comment by end-4** [comment]
the pinned apps on taskbar you mean? they're configured in `~/.config/eww/modules/taskbar.json`. make sure they have the correct path to whatever app you want
i am mighty amazed how you're still using it to this day btw

**Comment by end-4** [comment]
there is #100 which is quite similar
i wonder if this is some eww problem

**Comment by end-4** [comment]
okay what the hell
yesterday i was able to open everything normally, and now i'm only able to open the left sidebar
guess it's a recent update of something to blame

**Comment by TheSunCat** [comment]
Yeah I can indeed open the left sidebar fine, but not any other window/menu. Do you think this is an issue on the EWW side?

**Comment by end-4** [comment]
maybe gtk problem, as i'm sure i didn't update eww yesterday

**Comment by akshitgaur2005** [comment]
Hi, has this been resolved yet. Whatever I do, I cannot get it to work

**Comment by end-4** [comment]
Not fixed. And it isn't likely that I will fix it as Eww is no longer of my interest, now that AGS exists.

**Comment by akshitgaur2005** [comment]
There is a problem with illogical impulse too as it does not work correctly

**Comment by end-4** [comment]
> There is a problem with illogical impulse too as it does not work correctly

Make a new issue and describe in detail please

**Comment by andmydignity** [comment]
Idk about yall but just to let you know eww works fine for me in the hybrid branch.I installed eww-wayland ( version 0.4.0-5) from choatic-aur and that was all.Hope this helps someone.

**Comment by akshitgaur2005** [comment]
I have not checked chaotic-aur, but atleast eww-wayland, eww-git, eww(the tray one) fron aur do not seem to work correctly

**Comment by end-4** [comment]
Hmmmmm sidebars do work. The theme window doesn't open though

**Comment by akshitgaur2005** [comment]
Even in osu mode, I had to remove the animation to get any of the sidebars to work

**Comment by andmydignity** [comment]
Topbar and sidebars etc all work except for theme window.Idk why this is the case for me but i'm definitely not gonna complain.
________________________________
Kimden: end-4 ***@***.***>
Gönderildi: Pazartesi, Kasım 13, 2023 1:26:53 PM
Kime: end-4/dots-hyprland ***@***.***>
Bilgi: Semih Aslan ***@***.***>; Comment ***@***.***>
Konu: Re: [end-4/dots-hyprland] Not all EWW windows are opening (hybrid, novelknock, windoes, m3ww) (Issue #99)


Hmmmmm sidebars do work. The theme window doesn't open though

**Comment by akshitgaur2005** [comment]
Checked for chaotic-aur package, still doesn't make a change for me

**Comment by end-4** [comment]
I no longer use EWW and these configs are now very broken due to their hackiness. I now use AGS, and my new config doesn't have this problem since it doesn't rely on weird shell scripts.
I understand dropping such creations as these three is a great loss, and I seek your understanding that I can no longer support EWW-powered configs, so I will not be doing so.
Closing for now
