### ISSUE TITLE
[Issue]How do i add 12 hour time to the top bar?

### ISSUE THREAD

**Issue by woolium-dev** [end-4/dots-hyprland#991]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date: YES
- Linux distro: 
EndeavourOS Endeavour Neo
---
## The issue

I Need 12 hour time in the top bar. i can't figure out how to edit ags through the terminal. i can't read 24 hour time, but this is just a pet peeve i have.

English

No errors
<details>
<summary>Logs</summary>

Dont need any logs.
```plain
Paste logs here
```

</details>

**Comment by DarkOperation** [comment]
change line 137 in file `~/.config/ags/modules/.configuration/user_options.js` from `'format': "%H:%M"` to `'format': "%I:%M%P"`.

<sup>*Sorry for my english</sup>

**Comment by woolium-dev** [comment]
Thank you @DarkOperation !
