### ISSUE TITLE
[Issue]gtk

### ISSUE THREAD

**Issue by taoki123** [end-4/dots-hyprland#993]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: 

---![image](https://github.com/user-attachments/assets/5551c47a-0186-45a4-be9f-9102ac0a7615)![image](https://github.com/user-attachments/assets/51476915-068e-4f9f-9d47-00f7e4473c98)
## The issue

<details>
<summary>Logs</summary>

```plain
Paste logs here
```

</details>

**Comment by DarkOperation** [comment]
See #955
